### PR TITLE
pm2: add page

### PR DESCRIPTION
**Pull request by YangVincent**
[pm2](http://pm2.keymetrics.io) is a production process manager for Node.js

### CODE REVIEW

**Comment by agnivade** [comment]
@YangVincent - Please fix the travis errors. :)

**Comment by YangVincent** [comment]
Fixed!

**Comment by agnivade** [comment]
Can you also add `pm2 restart` ? Seems like an useful option to be there.

**Comment by YangVincent** [comment]
Done!

**Comment by agnivade** [comment]
@YangVincent - Made some changes to simplify the examples. Let me know what you think.

**Comment by YangVincent** [comment]
They look good!

**Pull request merged**
