### PR TITLE
subcommand-mention: add pt_PT translation

### PR DESCRIPTION
**Pull request by kant**
- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by marchersimon** [comment]
@kant could you please apply the suggestion above?

**Comment by kant** [comment]
> @kant could you please apply the suggestion above?

Yes, Sir!

**Comment by kant** [comment]
@waldyrious @marchersimon Done

**Review by marchersimon — APPROVED** [review]
Thanks @kant

**Pull request merged**
