### PR TITLE
CODEOWNERS: Remove @yutyo, since the user has been deleted

### PR DESCRIPTION
**Pull request by sebastiaanspeck**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Review by spageektti — APPROVED** [review]

**Comment by acuteenvy** [comment]
The account hasn't been deleted, it's just a username change.
https://github.com/tansiret
https://web.archive.org/web/20240428162619/https://github.com/yutyo

MAINTAINERS.md needs an update too, since there's now a dead link with the old username.

**Comment by kbdharun** [comment]
Agreed

---

Interestingly for username changes GitHub usually redirects to the new name, I am not sure why it isn't happening for this case with @tansiret.

**Comment by acuteenvy** [comment]
> GitHub usually redirects to the new name

It only creates redirects for repositories, until someone else creates an account with the old name.

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username#links-to-your-previous-profile-page

> After changing your username, links to your previous profile page, such as https://github.com/previoususername, will return a 404 error

**Comment by tansiret** [comment]
Oh I haven't realized the situation. Thanks guys!

**Pull request merged**
