### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by ghostslayer989**
/screenshot.png -- 83.75kb -> 50.57kb (39.62%)
Faster loading! Lol.

### CODE REVIEW

**Comment by ghostslayer989** [comment]
I signed it but it's pending. I rechecked 3 times.

**Comment by sbrl** [comment]
Hey, thanks for the PR!

While you may have signed, @CLAassistant is probably talking about the email address that your bot has used in the commit.

The GitHub account with the email address in the commit attached to it needs to sign the CLA :-)

**Comment by mebeim** [comment]
Hi, @ghostslayer989, could you please create a single commit done by **you** (not the bot) or change the author of this commit to yourself, so that the CLA check can pass and we can merge this? 

To change the author:

    git checkout imgbot
    git commit --amend --author="your-name <your-github-email>"
    git push -f

Otherwise, I see no alternative except closing this and doing it ourselves.

**Comment by mebeim** [comment]
Alright, I force pushed on your repo to update the commit author. I'm merging this now since it's already accepted.

**Pull request merged**
