### PR TITLE
tldr: include all platform options

### PR DESCRIPTION
**Pull request by CleanMachine1**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]

**Comment by bl-ue** [comment]
Could you please update the other translations?

**Comment by CleanMachine1** [comment]
They all have variations since they dont use the word OS, instead they all use Linux so I have to translate them to use specified OS.

I have done a few but they are probably wrong since they are all on google translate.

I don't think its worth anyones time.

**Comment by bl-ue** [comment]
Ah yes, I forgot about that :(

**Comment by CleanMachine1** [comment]
I made a little mistake here. I pushed a commit here instead of a different branch.

**Comment by CleanMachine1** [comment]
DONT MERGE THIS! Unexpected commits have been pushed!

**Comment by CleanMachine1** [comment]
Everything back to normal thanks to tldr git restore, then sourced it to a previous commit 8f85a31e632ddddb1f9630a254396af5777ca2d5

**Comment by CleanMachine1** [comment]
Right. All is done.

Although I lost about 15 minutes of work however whats happened has happened. Unless anyone can recover git-release.md

**Review by marchersimon — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
