### PR TITLE
Update glob requirement from 7.0.0 to 7.1.3

### PR DESCRIPTION
**Pull request by ghostslayer989**
Updates the requirements on [glob](https://github.com/isaacs/node-glob) to permit the latest version.
- [Release notes](https://github.com/isaacs/node-glob/releases)
- [Changelog](https://github.com/isaacs/node-glob/blob/master/changelog.md)
- [Commits](https://github.com/isaacs/node-glob/compare/v7.0.0...v7.1.3)

Signed-off-by: dependabot[bot] <support@dependabot.com>

### CODE REVIEW

**Comment by sbrl** [comment]
Hello!

While this PR is appreciated, it might be better to bundle this into a single PR that updates _all_ dependencies at once.

**Comment by ghostslayer989** [comment]
Sadly Dependabot doesn't do PRs like that.

**Comment by agnivade** [comment]
Well, you can always do it manually.

**Comment by sbrl** [comment]
Ah, I see @ghostslayer989. I wasn't aware that this was a bot making this PR.

**Comment by ghostslayer989** [comment]
Lol. In the text of the PR description, it says:

> Signed-off-by: dependabot[bot] support@dependabot.com

**Comment by sbrl** [comment]
@ghostslayer989 When you've got many PRs to review, you don't always read the description particularly carefully. 

@pxgamer @waldyrious

**Comment by mebeim** [comment]
Hi, @ghostslayer989, could you please create a single commit done by **you** (not the bot) to update both dependencies (`husky` and `glob`) at once, so that the CLA check can pass and we can merge this? Otherwise, I see no alternative except closing this and doing it ourselves.

**Comment by mebeim** [comment]
Closing this as per my previous comment.

**Pull request closed without merging**
