### PR TITLE
make banner in README transparent

### PR DESCRIPTION
**Pull request by marchersimon**
Since the current banner can be a pain to look at in dark mode, I made a transparent version and made the font slightly darker so it can be read in both dark and light mode. This is how the new one looks:

<table>
<tr><td></td><td></td></tr>
</table>

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by CleanMachine1** [comment]
```
  _________________________________
 |.--------_--_------------_--__--.|
 ||    /\ |_)|_)|   /\ | |(_ |_   ||
 ;;`,_/``\|__|__|__/``\|_| _)|__ ,:|
((_(-,-----------.-.----------.-.)`)
 \__ )        ,'     `.        \ _/
 :  :        |_________|       :  :
 |-'|       ,'-.-.--.-.`.      |`-|
 |_.|      (( (*  )(*  )))     |._|
 |  |       `.-`-'--`-'.'      |  |
 |-'|        | ,-.-.-. |       |._|
 |  |        |(|-|-|-|)|       |  |
 :,':        |_`-'-'-'_|       ;`.;
  \  \     ,'           `.    /._/
   \/ `._ /_______________\_,'  /
    \  / :   ___________   : \,'
     `.| |  |           |  |,'
       `.|  |           |  |
         |  |           |  |

```

**Review by CleanMachine1 — APPROVED** [review]

**Review by bl-ue — APPROVED** [review]
Fantastic!  Let's wait for @waldyrious's approval though.

**Comment by CleanMachine1** [comment]
and @sbrl

**Comment by waldyrious** [comment]
Thanks for doing this, @marchersimon! I'd actually go one step further, and replace `banner.png` and `banner-light.png` with a single, background-independent version, WDYT? Or at least retire the light version and leave just the transparent one.

**Review by sbrl — APPROVED** [review]
Looks great after @waldyrious' comments are addressed :D

**Comment by marchersimon** [comment]
Now, we just have one banner and it's SVG source file.

**Comment by marchersimon** [comment]
Can I also remove the background of [logo.png](https://github.com/tldr-pages/tldr/blob/main/images/logo.png)?

**Comment by sbrl** [comment]
Not sure about logo.png

**Comment by marchersimon** [comment]
I assume it's used somewhere external, but I can't think of any issue caused by removing the background of an image.

**Comment by bl-ue** [comment]
>Can I also remove the background of [logo.png](https://github.com/tldr-pages/tldr/blob/main/images/logo.png)? 

@marchersimon I don't think we should do that, at least not right now.  It has a specific color for the background (a dark blue) which can't be missed that easily, regardless of the color scheme.

**Comment by bl-ue** [comment]
@marchersimon the GitHub rich-diff displays the font as being removed in the new version — will you please verify?

Screen Shot 2021-06-09 at 11 20 55 AM

Also, the SVG is full of Inkscape-specific data.  Will you please save it as "Plain SVG" or even "Optimized SVG", rather that "Inkscape SVG"?

**Comment by marchersimon** [comment]
Plain and optimized 👍🏽 

I'm pretty sure that's a render error by GitHub, I'm also getting wrong results with rich diff. Mine is showing even different fonts. But if you have a look at https://github.com/marchersimon/tldr/blob/transparent-banner/README.md, you can see, that everything is correct.

**Review by sbrl — APPROVED** [review]
Time to merge, @bl-ue?

**Review by bl-ue — APPROVED** [review]
Yep 🚀

**Comment by marchersimon** [comment]
image

**Pull request merged**
