### PR TITLE
aptitude: remove purge

### PR DESCRIPTION
**Pull request by cameronjphillips**
----

~~- [ ] The page (if new), does not already exist in the repo.~~

~~- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

- [X] The page has 8 or fewer examples.

- [X] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines 

Remove the purge example as requested on #1521

### CODE REVIEW

**Comment by sbrl** [comment]
Does `aptitude` not have purge, @Darexon?

**Comment by Darexon** [comment]
@sbrl `aptitude` does have purge as well as `apt-get` but on the PR I mentioned @agnivade wanted purge removed from aptitude because it is an advanced option not needed by beginners.

**Comment by agnivade** [comment]
@sbrl - Please check #1521 for more context.

**Comment by cameronjphillips** [comment]
@sbrl I've signed the CLA on the linked PR and your link says I already signed the CLA.

**Comment by agnivade** [comment]
@cameronjphillips - Are your github email address and the address you have used to sign the CLA same ?

**Comment by cameronjphillips** [comment]
@agnivade I've added a new primary email address to my Github but the one I signed the CLA with is still on my account.

**Comment by agnivade** [comment]
@waldyrious - Can you do something about this ? I don't want to force merge.

**Comment by cameronjphillips** [comment]
@agnivade After clearing cookies and logging into GitHub I was able to sign the CLA again.

**Pull request merged**
