### PR TITLE
ssh: add command for using tar via pipes

### PR DESCRIPTION
**Pull request by jwilkins**
----

- [ ] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
Hi @jwilkins, thanks for the contribution.

However, I think this is an advanced usage of ssh. Our scope here is very limited, and we try to keep the examples from a beginner's perspective. If we mention all possible examples, this will become the man page itself. Keeping that in mind, I think this should not be added to the page.

Let me know your thoughts.

**Comment by sbrl** [comment]
I'm inclined to agree with @agnivade here, unfortunately - though I do believe that this command is rather cool - and while it's a shame to not include it, it does feel like an advanced usage.

However, we haven't yet got an example that executes a command on a remote host. To that end, perhaps this could be simplified to just `cat` a file from a remote host? Advanced users should be able to figure out that you can use `tar` etc. intead to send whole directories I think.

**Comment by agnivade** [comment]
> However, we haven't yet got an example that executes a command on a remote host. 

We do. It's the 4th example. :smile:

**Comment by agnivade** [comment]
Hey @jwilkins - Let me know if you agree with my suggestion to re-purpose this PR to update the remote command example to a concrete example.

**Pull request closed without merging**
