### PR TITLE
offlineimap: add page

### PR DESCRIPTION
**Pull request by jakevossen5**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Most of this program is defined by the config file, which doesn't really fit into TLDR but I tried to include some options that I frequently forget when using this program.

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Review by marchersimon — APPROVED** [review]
Thanks @jakevossen5

**Comment by CleanMachine1** [comment]
Why are you force pushing everything?

**Comment by bl-ue** [comment]
Force-pushing is fine, and in lots of places it's desirable, but in this repository we like to try to avoid it because it can make reviews (of these relatively small file) difficult. 🙂

**Review by CleanMachine1 — APPROVED** [review]

**Comment by CleanMachine1** [comment]
ah, should of waited another few hours..

**Comment by jakevossen5** [comment]
Sorry about the force push, I was just trying to limit the number of commits. I'll try to avoid them in the future!

**Comment by bl-ue** [comment]
Yeah, we auto-squash them together into one, so there's no need to push.  Thank you @jakevossen5!

**Pull request merged**
