### PR TITLE
awk: add /search/ example

### PR DESCRIPTION
**Pull request by solarsailer**
Searching for values in lines is a common operation with awk. I didn't specify that "something" is a regexp because it's not really useful at first.

### CODE REVIEW

**Comment by igorshubovych** [comment]
LGTM

**Comment by waldyrious** [comment]
I'd at least reorder the description sentence to match the order that the parts of the command appear. That helps in identifying what does what, especially since the // aren't mentioned explicitly.

**Comment by solarsailer** [comment]
I wanted to keep the same structure as the other examples. And I do refer to the value inside `//`, with "something" => "/{{something}}/". ;)

**Comment by waldyrious** [comment]
In the end, it's a judgment call. I don't think your choice is bad, I just think mine is more intuitive to beginners. That said, I won't oppose merging this as-is.

**Pull request merged**
