### PR TITLE
Add more Chinese translations

### PR DESCRIPTION
**Pull request by starccy**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by agnivade** [comment]
Thanks for the PR. Please also translate the text within the tokens.

/cc @HugueLiu

**Comment by starccy** [comment]
Do you mean I should translate the text between `{{}}` ? If yes, I am sorry for missing it. I will fix that.     
What's more, I note that someone would like translate by using automation scripts. Whether it means there is no need to translate manually any more?

**Comment by agnivade** [comment]
> Do you mean I should translate the text between `{{}}` ?

Correct.

> Whether it means there is no need to translate manually any more?

For now, that workflow is not applied yet. So you do not need to worry about that.

**Comment by sbrl** [comment]
I believe the automation scripts you refer to is a system by why translators can get notified about changes to the original versions of pages they have translated, but since that's still a work-in-progress, let's continue with the existing structure for now :-)

**Comment by starccy** [comment]
Ok, I learned that. Thanks.

**Comment by sbrl** [comment]
Are we ok to merge, @agnivade / @HugueLiu?

**Comment by agnivade** [comment]
I still see some tokens untranslated.

**Comment by starccy** [comment]
@agnivade I checked the files, Those untranslated tokens stand for filenames, I think it's unnecessary to translate them.

**Comment by agnivade** [comment]
I see tokens like foo and bash. I meant that these should be transliterated to Chinese characters, not translated to their Chinese equivalents.

**Comment by starccy** [comment]
I apologize for not replying you earlier, because I'm preparing for the exam. I would improve these stuff immediately.

**Pull request merged**
