### PR TITLE
fix zpool

### PR DESCRIPTION
**Pull request by lizhuoli1126**
zpool: fix for `one description one command`

### CODE REVIEW

**Comment by waldyrious** [comment]
Nice one, thanks! Before merging, I'd suggest splitting the "Import a zpool, optionally specifying a new name" example into two.

**Comment by lizhuoli1126** [comment]
@waldyrious I agree with you, but we can just use a bracket with `optionally specifying a new name` to show that it's an optional arg, I think it don't need one more separate line for this.

**Comment by waldyrious** [comment]
The problem is that the example uses two parameters, so the description should match. The tldr project exists precisely to remove the burden of reasoning over ambiguous documentation, and provide simple, straightforward examples. @igorshubovych or @rprieto what are your thoughts?

**Comment by rubenvereecken** [comment]
I'm quite sorry @lizhuoli1126 but this page has been the subject of quite some debate and I've recently merged a PR by @notpeter that affected this file in a way that just can't trivially be merged with your changes. I'm closing this commit for now because there's really nothing we can easily do - the best would be to reopen if things need changing.

**Pull request closed without merging**
