### PR TITLE
yarn-why: add page

### PR DESCRIPTION
**Pull request by pxgamer**
Looking at #2784 brought me to a Yarn equivalent of `npm-why`. Thanks @sbrl 

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by pxgamer** [comment]
Yarn lock files actually lock the dependencies (like Composer). Yarn also used to be much faster at installing, etc. before `npm v6`.

I've recently moved back from Yarn to npm to be honest though as the speed differences are barely noticeable I've found.

**Comment by agnivade** [comment]
After switching to yarn, life has brought me peace. I don't `rm -rf node_modules/` anymore !

**Comment by sbrl** [comment]
I see! `npm` does support locking dependencies via `package-lock.json` now though.

**Comment by pxgamer** [comment]
@sbrl, but unless you use `npm ci` the default doesn't really use the lock.

In Composer and Yarn, if you run an install, it will use the lock. In `npm install` it will update the lock.

**Comment by agnivade** [comment]
Yes, I think it was using package-lock.json from v 3 onwards. I have faced problems even with it.

**Comment by sbrl** [comment]
@pxgamer: TIL! Didn't know that.

**Pull request merged**
