### PR TITLE
Update vim.md

### PR DESCRIPTION
**Pull request by JeasineMa**

### CODE REVIEW

**Comment by felixonmars** [comment]
Actually I think "vimdiff" was used more widely than "vim -d". Any thoughts? @igorshubovych

**Comment by ostera** [comment]
:+1: to `vimdiff`

**Comment by igorshubovych** [comment]
I am noob in vi. I read only Volume 1 of Vi manual: How To Quit Vi

**Comment by ostera** [comment]
I ended up using vim because I couldn't exit it, now it's been 3 years. Stockholm Syndrome they say.

**Comment by igorshubovych** [comment]
I am not into vi, but I would agree with the tone of Felix comment. It should be a common case to be added. If it is not widely used, let's not bloat the pages just to reach goal 5-6 examples. Shorter is better. We are TLDR, you remember.

**Comment by igorshubovych** [comment]
I am not into vi, but I would agree with the tone of Felix comment. It should be a common case to be added. If it is not widely used, let's not bloat the pages just to reach goal 5-6 examples. Shorter is better. We are TLDR, you remember.

**Comment by waldyrious** [comment]
> I ended up using vim because I couldn't exit it, now it's been 3 years. Stockholm Syndrome they say.

I'm totally [tweeting that](https://twitter.com/waldyrious/status/681839033245380608).

**Comment by igorshubovych** [comment]
So what do we do here?

**Comment by 85pando** [comment]
As a long time via user I rather use `vimdiff` as well. If only because I did not know `vim -d`.  A vim user should know one of them, so why not include `vim -d` and create a vimdiff page as well?

**Comment by waldyrious** [comment]
:+1: @85pando

**Comment by igorshubovych** [comment]
@85pando 
there is a reason not to add `-d`: we need to keep it short.
There is another PR #465, adding more useful commands.

**Comment by 85pando** [comment]
That's a point…

**Comment by rubenvereecken** [comment]
I used vimdiff _a lot_ in my sad short years. Never used it as `vim -d`. Vim is at 4 examples so far and we shouldn't stretch it too hard. @JeasineMa what do you think of a separate `vimdiff` page? Would you be up for creating it?

**Comment by rubenvereecken** [comment]
I'm sorry, not merging. Still up for a separate `vimdiff` page though.'

Thanks for the effort @JeasineMa !

**Pull request closed without merging**
