### PR TITLE
rsync: add example with exclude file

### PR DESCRIPTION
**Pull request by akoenig**
Add an example where `excludes` are defined in a `exclude list`.

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the contribution! The page is starting to get a bit too long, though -- can you see any way to compact it? Maybe one or two of the existing examples could be removed? tl;dr is meant to only provide the 5-6 most common usages, not an exhaustive reference for each command.

**Comment by igorshubovych** [comment]
I do not think this example is quite common to be included. I have personally never used it personally. I think example with `--exclude` will be more common (the last one listed [here](https://en.wikipedia.org/wiki/Rsync#Examples)).

The page is already quite long: 6 examples and it will have 7 examples with your added.

**Comment by ostera** [comment]
I'm with @igorshubovych. :-1:

**Comment by igorshubovych** [comment]
As there are no feedback, I am closing this. Feel free to reopen if you think it should be there.

Thanks anyway! Keep going!

**Pull request closed without merging**
