### PR TITLE
bash: add page

### PR DESCRIPTION
**Pull request by Ethiraric**
The description may not be the best.
Feel free to suggest another one.

I'm actually surprised nobody has made this page already. Is there a particular reason ?
Looking through the Pull Request history, I couldn't find any one adding the page.

### CODE REVIEW

**Comment by Ethiraric** [comment]
I mostly wanted to differ from the manual page.

**Comment by waldyrious** [comment]
Looks nice :) One suggestion: maybe instead of "run", "start" could make it more explicit that the interpreter will be used interactively. The same kind of rephrasing could make the -x example description clearer as well.

**Comment by Ethiraric** [comment]
I've changed locally the run to start, but I don't seem to understand what you expect me to change for the -x example description. This option may be used in both interactive and non-interactive modes :/

**Comment by waldyrious** [comment]
Yeah, but the specific example (just bash -x) does start an interactive session, right? In that case I believe the description should match. Besides, a one-off usage of e.g. bash -c -x would be a bit artificial since the -x wouldn't be justified in most cases.

**Comment by Ethiraric** [comment]
Should I then make the -x example non-interactive ?

**Comment by waldyrious** [comment]
Looks great, thanks! :+1:

**Comment by igorshubovych** [comment]
Thank you!

**Pull request merged**
