### PR TITLE
mention lsb_release

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
Not sure if this is the best way to do it; we could split the page and add the note only in linux/uname.md, but that seems overkill considering that the current options have been [specifically selected to be the common denominator](https://github.com/tldr-pages/tldr/pull/285#issuecomment-119168870).

That said, the command *does* [differ across systems](https://en.wikipedia.org/wiki/Uname), so we could adapt it to make use of that -- but I can't think, off the top of my head, of any change that would be beneficial for the tldr audience.

**Comment by waldyrious** [comment]
Btw, I added the `lsb_release.md` page in #303

**Comment by waldyrious** [comment]
@rprieto please review :)

**Comment by rprieto** [comment]
Nice one :+1: Maybe in the conversation about a potential V2 format we can talk about a "related commands" section?

**Comment by waldyrious** [comment]
@rprieto sure. I believe you've mentioned stuff for v2 in several threads now, so if you like, please open a new issue with the main changes to discuss off the top of your head, and then we can add a reference to this PR there as well. As for this change, and in the context of v1, I'll take your :+1: as a license to merge :)

**Comment by waldyrious** [comment]
Hm, maybe #190 could host the v2 discussion? If so we should probably tweak the title to make this clear.

**Comment by waldyrious** [comment]
For future reference, this change [broke Travis](https://travis-ci.org/tldr-pages/tldr/builds/95266845) (which was set up after this PR was created), with the markdown lint error "MD028: Blank line inside blockquote". The fix was done in f3b5a63.

**Pull request merged**
