### PR TITLE
translated pages.es/linux to catalan in pages.ca_ES/linux + renamed systemctl.cmd to systemctl.md in pages.es/linux

### PR DESCRIPTION
**Pull request by Seifer23**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by Seifer23** [comment]
don't know how to verify Salvador Rodó Coll (it's me with git configured wrong), I will create another pull request with only my github account.

**Comment by navarroaxel** [comment]
@Seifer23 is there another type of Catalan outside Spain?

**Comment by Seifer23** [comment]
> @Seifer23 is there another type of Catalan outside Spain? I mean, `ca_ES`, `ca_AD`, `ca_IT` these are all different? We try to keep just one version: `pages.ca/` if it's possible.

You are right, it should be renamed to pages.ca/

**Comment by Seifer23** [comment]
> @Seifer23 is there another type of Catalan outside Spain? I mean, `ca_ES`, `ca_AD`, `ca_IT` these are all different? We try to keep just one version: `pages.ca/` if it's possible.

You're right, it should be replaced as pages.ca. I have changed it in my open pull-request ([#7736](https://github.com/tldr-pages/tldr/pull/7736))

**Pull request closed without merging**
