### PR TITLE
tar: Add brackets around letters of keywords and remove one example

### LINKED ISSUE #3876: Explain tar flags?
Just a thought from reading the README. The contributing guidelines say to allow people to understand the commands. The infamous tar flags can be easily explained by noting the common flags match their commands: (c)reate, e(x)tract, g(z)ip, (v)erbose, archive (f)ile, (a)uto-detect by extension. Perhaps these mnemonics should be added in each description.

### PR DESCRIPTION
**Pull request by sawshep**
- [x] The page has 8 or fewer examples.
~~^ There are 9 examples on tar~~
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

This fixes #3876, in order to better fit contributing guideline 3. This may get shot down by the bot due to the fact that some of the lines no longer start with capitals due to the letters in brackets.

### CODE REVIEW

**Comment by sawshep** [comment]
@einverne I would say to remove `tar xf --strip-components`. It's a pretty advanced use of tar and the example talks nothing about what `depth_to_strip` actually means.

**Comment by jxu** [comment]
Maybe amend the bot to allow a line starting with bracket

**Comment by sawshep** [comment]
I looked through [the bot's repo](https://github.com/tldr-pages/tldr-bot) and it seems like whatever script they use to check for capitals isn't in there.

**Comment by sbrl** [comment]
Hey there! We're currently in the middle of shuffling the CI checks around, so it's all over the place at the moment :P

The checks are done by GitHub actions, which calls the tldr-lint linter - which is ultimately generating the above error.

**Comment by zdroid** [comment]
It seems that `[C]reate` doesn't work either, so we'll need to amend tldr-lint.

**Comment by navarroaxel** [comment]
> It seems that `[C]reate` doesn't work either, so we'll need to amend tldr-lint.

Hey @sbrl, @einverne, @zdroid. I sent this https://github.com/tldr-pages/tldr-lint/pull/12 allowing to start an example description with `[` and checking if the first letter is in upper case.

I notice that code base is really outdated too.

**Comment by sawshep** [comment]
With the latest merge to the linter, hopefully the build will pass.

**Comment by navarroaxel** [comment]
> With the latest merge to the linter, hopefully the build will pass.

@sawshep Could you please merge with `master` and resolve the conflicts?

**Comment by sbrl** [comment]
Yeah, @navarroaxel - there's [a task to reimplement the linter in something more maintainable](https://github.com/tldr-pages/tldr/wiki/Coding-projects#convert-the-linter-from-clexyacc-to-a-more-popular-language).

_(Also, would it be possible if you could hang out in [our Gitter](https://gitter.im/tldr-pages/tldr) please @navarroaxel at all?)_

**Comment by owenvoke** [comment]
Working on the required `tldr-lint` release today. 😬 👍🏻

**Comment by owenvoke** [comment]
Sorry, that's my bad. We need to update the dependency in the npm lock (https://github.com/tldr-pages/tldr/pull/4415), and then rebase this I guess.

**Comment by navarroaxel** [comment]
@sawshep could you please merge with `master`?

**Comment by axmz** [comment]
What if we forgo the letter hint like [c]reate?

Here are my points:
1. so we'll keep the tool simple.
2. the users have to decide by themselves how they want to remember the commands. 
You just need to use the right words to describe the command: -c = Create...; instead of -c = New...
3. we will not have to deal with inconsistencies like tar -j which means: bzip (there is no j).
4. one short flag may represent multiple long flags ex: tar -Z, --compress, --uncompress.
5. no need to complicate the linter.
6. we'll avoid lot's of unknown risks.

What do you think?

**Comment by sbrl** [comment]
@axmz: I'd suggest opening an issue about that, as it's probably best discussed.

**Comment by bl-ue** [comment]
@sawshep are you still working on this?

**Comment by sawshep** [comment]
@bl-ue While it was never merged, `tldr tar` shows that brackets around the corresponding characters now exist, so yes.

**Comment by bl-ue** [comment]
@sawshep thank you for replying! it shows those because of my PR #5083 that was merged 4 hours ago! I sorry, I didn't know you would reply.

**Comment by sbrl** [comment]
> @bl-ue While it was never merged, `tldr tar` shows that brackets around the corresponding characters now exist, so yes.

The tldr linter was recently updated to add support for brackets at the beginning of an example, so that's why it was updated :-)

**Pull request closed without merging**
