### PR TITLE
open: add -n example, highlight arguments

### PR DESCRIPTION
**Pull request by corneliusroemer**
Improvement PR

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@EmilySeville7cfg could you possibly review? I think you were the last to edit this page :) Thanks!

**Review by EmilySeville7cfg — APPROVED** [review]
LGTM :)

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by navarroaxel — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
Too many reviewers were assigned. ;) They are dismissed now because PR is merged.

**Pull request merged**
