### PR TITLE
pages.zh_TW/*: fix wrong term

### PR DESCRIPTION
**Pull request by hms5232**
"文檔" is used in zh_CN, for zh_TW, that is "文件".

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by kbdharun** [comment]
Hi @hms5232, Welcome to tldr and thanks for your contribution. Please sign the CLA by clicking on the comment above.

**Comment by hms5232** [comment]
> Hi @hms5232, Welcome to tldr and thanks for your contribution. Please sign the CLA by clicking on the comment above fo this PR to go through.

OK, I just sign the CLA, cool :)

**Comment by kbdharun** [comment]
@LiLittleCat can you check this PR and give your insights regarding this change? Thanks in advance.

**Comment by LiLittleCat** [comment]
> @LiLittleCat can you check this PR and give your insights regarding this change? Thanks in advance.

Sure, it looks good to me, but I am not so familiar with traditional Chinese(Taiwan) aka zh_TW, so I suggest to ask some native speakers of zh_TW for their opinions.

**Comment by kbdharun** [comment]
> > @LiLittleCat can you check this PR and give your insights regarding this change? Thanks in advance.
> 
> Sure, it looks good to me, but I am not so familiar with traditional Chinese(Taiwan) aka zh_TW, so I suggest to ask some native speakers of zh_TW for their opinions.

Thanks, I had asked @blueskyson regarding it. I just wanted a second opinion as this change affects multiple pages.

**Review by blueskyson — APPROVED** [review]
I think both wordings are correct.

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
