### PR TITLE
curl: add --header example

### PR DESCRIPTION
**Pull request by jamescarlos**
Add curl header example.

### CODE REVIEW

**Comment by igorshubovych** [comment]
See #291

**Comment by felixonmars** [comment]
I would say +1 for this one, since `-H, --header` is a very useful (and often used, for me) option, and it's different from `--head` :)

However I would suggest to rephrase the description a bit. How about `include an extra header` or `include a custom header`?

**Comment by igorshubovych** [comment]
Agree with @felixonmars that it is good add yet one header to show the syntax in this case.

**Comment by jamescarlos** [comment]
Thanks all, I have changed the description to `include an extra header`

**Comment by igorshubovych** [comment]
@jamescarlos could you plz squash commits? don't worry about merge conflict, I will merge it. But plz squash commits.

**Comment by jamescarlos** [comment]
@igorshubovych commits have been squashed. thanks!

**Comment by igorshubovych** [comment]
Thanks!

**Pull request merged**
