### PR TITLE
adb-shell: add pt_BR translation

### PR DESCRIPTION
**Pull request by gfda**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks, @gfda :slightly_smiling_face:

**Comment by gfda** [comment]
Thanks for the review, I will take the time to translate more pages this week.

**Comment by sbrl** [comment]
That would be awesome, @gfda! Note that for translations you can submit multiple translations in a single PR - just have 1 commit per page :-)

**Comment by gfda** [comment]
Ok, thanks.

**Pull request merged**
