### PR TITLE
java command

### PR DESCRIPTION
**Pull request by Qtrain**

### CODE REVIEW

**Comment by igorshubovych** [comment]
Overall I like it but there is one thing you can improve in your commit.

Please remove index.json. You should not include index.json in commits. To avoid this issue in future you can run `make setup` against your repo, it will overwrite the your pre-commit hooks.

To fix the existing commit instead of creating new one, you can
```
git commit --amend
git push --force
```

**Comment by waldyrious** [comment]
There should only be one newline at the end of the file. Other than this, great contribution :)

**Comment by rubenvereecken** [comment]
Sorry for us being fickle and thanks for bearing with us :).

**Comment by Qtrain** [comment]
Hello @igorshubovych @waldyrious @rubenvereecken On the contrary, thanks for bearing with me :+1: 

I used the following to update but not sure if it went ok.

    git reset HEAD^ index.json (from inside the pages directory) 
    git commit --amend -m"git amend for index.json"
    git push --force

From my side it looked like it worked, but, I don't see a changed file in the amended commit for index.json.  Not sure, please advise.  Thanks!

**Comment by igorshubovych** [comment]
The results of your commits was good. But you had 2 commits. It is better not to pollute the history with commits, therefore I squashed your commits with rebasing.

Thanks for a contribution!

**Comment by Qtrain** [comment]
@igorshubovych Understood, thanks very much!  I will add a javac command shortly.

**Pull request closed without merging**
