### PR TITLE
common-arguments: update Russian translation

### PR DESCRIPTION
**Pull request by trolzen**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by navarroaxel — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
Please dismiss myself as a reviewer if PR is merged before I leave any review.

**Comment by trolzen** [comment]
> Please dismiss myself as a reviewer if PR is merged before I leave any review.

@EmilySeville7cfg Sorry, but whom do you address to, me or other reviewers?

**Comment by kbdharun** [comment]
> > Please dismiss myself as a reviewer if PR is merged before I leave any review.

Noted, Thanks 

> @EmilySeville7cfg Sorry, but whom do you address to, me or other reviewers?

It is addressed to us other reviewers.

**Comment by EmilySeville7cfg** [comment]
@trolzen, I've addressed to anyone. :)

**Pull request merged**
