### PR TITLE
logcat: update pt_BR translation

### PR DESCRIPTION
**Pull request by barbaraips**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by isaacvicente — APPROVED** [review]
Oi Bárbara! Muito obrigado por disponibilizar seu tempo e contribuir com nosso projeto :heart:. Seu PR segue nossas guidelines e está pronto para merge.

**Comment by kbdharun** [comment]
@isaacvicente Thanks for the review, When merging PRs can you cross-check if the merge commit title aligns with the PRs title? Since GitHub by default takes the title of the first commit made in the PR or it's initial title.

Regarding this PR, I will rebase and fix the commit title in main.

## Reference image

image

**Comment by isaacvicente** [comment]
> @isaacvicente Thanks for the review, When merging PRs can you cross-check if the merge commit title aligns with the PRs title? Since GitHub by default takes the title of the first commit made in the PR or it's initial title.
> 
> Regarding this PR, I will rebase and fix the commit title in main.
> 
> ## Reference image
> image

Yes, sorry for that. I never reviewed any PR before, next time I will pay more attention and/or ask for some help :)

**Pull request merged**
