### PR TITLE
package.json: update dependencies

### PR DESCRIPTION
**Pull request by pxgamer**
Note, this can probably be rebased and merged rather than squashing. 👍

-----

Due to the issues mentioned in PRs #2867 and #2868, I've created this new PR with the appropriate changes committed by Dependabot.

I was planning on updating [`markdownlint-cli`](https://npm.im/markdownlint-cli) to `v0.15.0` which is the latest, but it now actually enforces the tests (see the [Travis build failure](https://travis-ci.com/pxgamer/tldr/builds/109987111)) so it may be better to implement this with a future PR.

### CODE REVIEW

**Comment by mebeim** [comment]
Thanks @pxgamer. While we're at it, I'd also suggest bumping up `markdownlint-cli` to `0.15.0`.

**Comment by pxgamer** [comment]
@mebeim, yes. I had written a good description for this PR but accidentally didn't copy it from my work PC.

I'll update it tomorrow, but it basically explained why I didn't update that in this PR.

**Comment by mebeim** [comment]
@pxgamer alright, looking forward to that then :+1:

**Comment by pxgamer** [comment]
@mebeim, updated. I think I've lost a bit of what I wrote previously, but it's more or less fine now. 👍

**Comment by mebeim** [comment]
@pxgamer ok, I agree it's better to update that separately looking at it more closely. Thank you :)

**Pull request merged**
