### PR TITLE
README: add similar project

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** unknown

## Changes

- Add `learnxinyminutes` to README

### CODE REVIEW

**Comment by CleanMachine1** [comment]
This doesn't seem in line with the similar projects IMO.

The other mentioned projects are cheatsheet style repos which are very similar to tldr pages.

The similar projects we have all seem to a common goal of helping with the command-line whether than be remembering or a quick overview of a command. While this project seems to be entire tutorials and guides about learning an entire topic. I think it is a little out of scope.

Let's see what others think before rejecting it though.

 Interesting site regardless!

**Comment by kbdharun** [comment]
> This doesn't seem in line with the similar projects IMO.
> 
> The other mentioned projects are cheatsheet style repos which are very similar to tldr pages.
> 
> The similar projects we have all seem to a common goal of helping with the command-line whether than be remembering or a quick overview of a command. While this project seems to be entire tutorials and guides about learning an entire topic. I think it is a little out of scope.
> 
> Let's see what others think before rejecting it though.
> 
> Interesting site regardless!

Yeah, I agree with @CleanMachine1, even though this is an excellent website, Featuring it readme with other cheetshet resources doesn't fit well. Maybe we can add a section in Wiki like `Additional Resources` or `Recommended Projects` and add it under it.

**Comment by CleanMachine1** [comment]
I personally think after an another review, we should close this PR.

**Comment by marchersimon** [comment]
I too think we should only feature command-line-related projects.

**Pull request closed without merging**
