### PR TITLE
pages.*/*: replace `{{" "}}` with `"{{ }}"`

### PR DESCRIPTION
**Pull request by acuteenvy**
The latter notation is preferred by the style guide.

> It is suggested to enclose placeholders accepting strings as input within quotes. i.e. Use `"{{placeholder}}"` instead of `{{"placeholder"}}`.

### CODE REVIEW

**Review by renie — APPROVED** [review]
pt_BR and en LGTM

**Review by ikks — APPROVED** [review]
es: LGTM, thanks.

**Review by spageektti — APPROVED** [review]

**Review by blueskyson — APPROVED** [review]

**Review by kant — APPROVED** [review]
Spanish chapter: LGTM

**Review by noraj — APPROVED** [review]
French page LGTM

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
