### PR TITLE
ip: add page

### PR DESCRIPTION
**Pull request by haishanh**
iproute2(command name `ip`) is a great collection of utilities for working with networking.

It is considered the successor of `ifconfig`. It has many features designed for the complex modern network environment(especially in virtualization environment), like VXLAN tunneling, network namespace, ip rules, etc..

More and more Linux distro began to ship with iproute2.  On MacOS you can install using Homebrew:

```
brew install iproute2mac
``` 

See also introduction section [here](https://wiki.linuxfoundation.org/networking/iproute2)

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @haishanh - A page for `ip` already exists under 'linux/'. If you want to make some changes, please update that file :)

And FYI - we don't put a file directly under 'pages/', but we put it inside platform specific folders, or under 'common/' if its common for all platforms.

**Comment by haishanh** [comment]
Ah, I'm on a Mac and I forgot to check the directory `linux/`, sorry about that.  I'm closing this one.

FYI, I was intended to put the file in `pages/common`, don't know how I end up with it in `pages/`

**Comment by agnivade** [comment]
No worries. If you had intended to put it under common/, you can still do that in this PR itself. But we just need to verify that it works the same on both mac and linux.

**Comment by waldyrious** [comment]
@haishanh could you please confirm whether the examples in [the ip page under pages/linux/](https://github.com/tldr-pages/tldr/blob/master/pages/linux/ip.md) work for you as described there?

**Pull request closed without merging**
