### PR TITLE
<: add here strings and documents

### PR DESCRIPTION
**Pull request by Managor**
Closes https://github.com/tldr-pages/tldr/issues/12694
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by Managor** [comment]
There's also here documents, but tha syntax seems to require a multiline command. I have no idea how I could fit that in our specification. `command <<< end; text; text; end` did not work.

**Comment by Managor** [comment]
If anyone knows what the [n] in the documentation means, let me know

**Comment by Managor** [comment]
I see. The number is just the file descriptor the data gets sent to

**Comment by Managor** [comment]
I don't personally see the value in adding examples with the file descriptors as I see myself never using it. If someone proves me otherwise, we should rename the description to "Redirect data to a file descriptor."

**Comment by Managor** [comment]
I request opinions on this syntax. I remember seeing this in [tmux.md](https://github.com/tldr-pages/tldr/blob/main/pages/common/tmux.md)

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
