### PR TITLE
reboot: fix typo in example

### PR DESCRIPTION
**Pull request by AxiomaticAxolotl**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
This might not be approved. We currently have a PR for fixing loads of mistakes. Give me a minute and I'll find out.

**Comment by CleanMachine1** [comment]
Yes, just searched! Good find

**Review by navarroaxel — APPROVED** [review]

**Review by CleanMachine1 — APPROVED** [review]

**Comment by navarroaxel** [comment]
Thanks @AxiomaticAxolotl ! welcome to TLDR!

**Comment by CleanMachine1** [comment]
I got an approval after!

**Comment by CleanMachine1** [comment]
3 Minutes that PR was open!

**Comment by AxiomaticAxolotl** [comment]
Wow, you guys work fast

**Comment by bl-ue** [comment]
Sometimes. 😉 This was an easy and obviously correct PR, so there's nothing to comment on.  Most of the time PRs will take a couple days though, because we all have this or that we'd like to see corrected, etc.

**Comment by marchersimon** [comment]
Nice to see my contributions being used (and corrected) (https://github.com/tldr-pages/tldr/commit/9330e542b36c5dfccb3ed24bb2c8cc15ade3715f) 😄

**Pull request merged**
