### PR TITLE
pm: add page

### PR DESCRIPTION
**Pull request by marchersimon**
Part of #4934.

### CODE REVIEW

**Review by Yutyo — APPROVED** [review]
LGTM

**Comment by bl-ue** [comment]
Before merging, we need to move this page into either `pages/linux/pm.md` or `pages/android/pm.md`. #5462

**Review by sbrl — APPROVED** [review]
Thanks, @marchersimon!

**Comment by sbrl** [comment]
The first new page in the `android` platform!

**Comment by bl-ue** [comment]
https://github.com/tldr-pages/tldr/tree/d1f4342a740d7613cd4f881a1a571455dbe584ea/pages 🌟

**Pull request merged**
