### PR TITLE
common-arguments: fix Hindi translation

### PR DESCRIPTION
**Pull request by navarroaxel**
Fix `snake_case` is placeholder translation

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Review by marchersimon — APPROVED** [review]
LGTM, thanks
But let's wait for #9031 so we don't have yet another merge conflict there.

**Comment by kbdharun** [comment]
> LGTM, thanks
> But let's wait for #9031 so we don't have yet another merge conflict there.

Seems like we have 1 now 😅

**Comment by marchersimon** [comment]
Not anymore

**Comment by marchersimon** [comment]
Whenever you have a merge conflict, there is a button `Resolve conflict`, where you would normally merge the PR. [Here's](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) the GitHub docs on it.

**Comment by kbdharun** [comment]
> Whenever you have a merge conflict, there is a button `Resolve conflict`, where you would normally merge the PR. [Here's](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) the GitHub docs on it.

Thanks I will refer to this in future.

**Pull request merged**
