### PR TITLE
Fix linter errors for Brazilian Portuguese pages

### PR DESCRIPTION
**Pull request by mebeim**
Some of the `pt_BR` pages were malformed missing some tokens or trailing newlines. A quite trivial fix.

### CODE REVIEW

**Comment by andrik** [comment]
It looks like a rebase to me, what do you guys think?

**Comment by pxgamer** [comment]
@andrik, I'd say rebasing would be fine. :+1:

**Comment by mebeim** [comment]
Merged it myself since those are trivial changes. Thanks guys!

**Comment by schneiderl** [comment]
how did this passed the linter checks?

**Comment by pxgamer** [comment]
@schneiderl, the tldr-pages linter only checks English pages. This will have passed `markdownlint` however.

**Comment by schneiderl** [comment]
@pxgamer oh makes sense.

**Comment by mebeim** [comment]
Yep, same goes for #3493. I would fix the issue (#2756) myself, but it's not trivial and takes some time. A new script `scripts/test.js` should be written probably.

**Pull request merged**
