### PR TITLE
Page request/zplug

### PR DESCRIPTION
**Pull request by seanjpmccarron**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey - thanks for the new page @seanjpmccarron! Looks like you're having some issues with the linter. We've got the style we prefer documented over [here](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format), and a few good examples are the pages for `tar`, `eyeD3`, and `ln`. If you need any assistance, just ask :smiley_cat:

Also, it doesn't appear that you have signed the CLA. Could you click the link in the comment by @CLAassistant please? Your commits must also be authored by the email address(es) that you've got in your GitHub account settings.

**Comment by mebeim** [comment]
Hi @seanjpmccarron... is this a page request? I see your PR adds two empty pages. If you want to request a page you should [open an issue](https://github.com/tldr-pages/tldr/issues/new) instead!

**Comment by sbrl** [comment]
I'm not sure, @mebeim. @seanjpmccarron also closed #3313 just now too.

**Comment by mebeim** [comment]
@sbrl well, I'm even more confused now :\

**Pull request closed without merging**
