### PR TITLE
expose: add page

### PR DESCRIPTION
**Pull request by owenvoke**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by sbrl — APPROVED** [review]
Nice, @owenvoke! Looks ok to me :-)

Also, thanks for the review @Scaledi! Unfortunately it doesn't count towards the 2 reviews to memrge this until you get 5 separate PRs merged, but thanks for checking this PR!

If you're interested in reviewing for tldr pages, we'd love to have you! Simply submit 5 separate PRs which then get merged (and then perhaps remind us :P) :-)

**Comment by Scaledi** [comment]
> Nice, @owenvoke! Looks ok to me :-)
> 
> Also, thanks for the review @Scaledi! Unfortunately it doesn't count towards the 2 reviews to memrge this until you get 5 separate PRs merged, but thanks for checking this PR!
> 
> If you're interested in reviewing for tldr pages, we'd love to have you! Simply submit 5 separate PRs which then get merged (and then perhaps remind us :P) :-)

will do :) I knew it did not count, but just wanted to voice my support. as for the requirements, unfortunately, I don't have much to add, other than doing what I am doing right now :)

**Review by einverne — APPROVED** [review]
LGTM.

**Comment by sbrl** [comment]
@Scaledi Yep. So you could contribute 5 new pages in 5 different PRs. Once they are merged, you're eligible according to our [community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document. More hands to review are always welcome (_especially_ in October with hacktoberfest) :D

**Pull request merged**
