### PR TITLE
poweroff: update page

### PR DESCRIPTION
**Pull request by spageektti**

### CODE REVIEW

**Review by acuteenvy — COMMENTED** [review]
It seems like this depends on the version of systemd. I don't know when exactly this was changed though.

`man poweroff` in Debian 12 (systemd 252):
https://manned.org/man/debian-bookworm/poweroff
> `-f`, `--force`
> Force immediate halt, power-off, reboot. If specified, the command does not contact the init system. In most cases, filesystems are not properly unmounted before shutdown. For example, the command `reboot -f` is mostly equivalent to `systemctl reboot -ff`, instead of `systemctl reboot -f`.

`man poweroff` in Debian 11 (systemd 247):
https://manned.org/man/debian-bullseye/poweroff
> `-f`, `--force`
> Force immediate halt, power-off, or reboot. When specified once, this results in an immediate but clean shutdown by the system manager. When specified twice, this results in an immediate shutdown without contacting the system manager. See the description of `--force` in `systemctl(1)` for more details.

Other init systems probably also do this differently.

**Comment by spageektti** [comment]
I just thinked this is a typo because for me it works with one `--force` flag.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by Managor — APPROVED** [review]
Searching through the changelogs, I'm unable to find any documented changes with `--force` or `poweroff` keywords. https://github.com/systemd/systemd/blob/main/NEWS
We'll just have to go with what the manual says

**Pull request merged**
