### PR TITLE
Korean pages: fix (valid) tldr-lint errors

### PR DESCRIPTION
**Pull request by bl-ue**
**(valid)** because `TLDR015` and `TLDR104`, which are found a lot on the Korean pages, don't apply to any language but English.

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
When you look at the files view on PRs like this, the pages really look like a pile of garbage haha :smile:

**Review by sbrl — APPROVED** [review]
This looks ok, but note that Korean uses a completely different character set to Japanese.

**Comment by sbrl** [comment]
This PR has conflicting files, so those will need to be addressed before we can merge.

**Comment by bl-ue** [comment]
>This looks ok, but note that Korean uses a completely different character set to Japanese.

Oops! I forgot to updated my copy/pasted description

>This PR has conflicting files, so those will need to be addressed before we can merge.

I'll fix those and merge.

**Pull request merged**
