### PR TITLE
deluser: sync translations with PR #5245

### PR DESCRIPTION
**Pull request by bl-ue**
Syncs the Italian and Korean translations of `common/deluser.md` with the English translation, see PR #5245.

cc @TheLastGimbus

### CODE REVIEW

**Review by sbrl — COMMENTED** [review]
Ummm all I see are 2 deleted files? If the translations are updated, then there's really no need to delete these. In fact, [the translations dashboard](https://lukwebsforge.github.io/tldri18n/) should mark them ass outdated if the number of examples are different.

**Comment by bl-ue** [comment]
Yeah, `common/deluser.md` was moved to `linux/deluser.md`, but it had examples added.  I thought the best way to settle the situation was to just delete them, then if somebody tried to view the page in their language they'd see a not found and maybe submit a translation, rather than see an outdated page but think it's up to date, etc.. But instead I'll restore them, move them to `linux/`, and add what I can: the more information link :blush:

**Review by navarroaxel — APPROVED** [review]

**Review by sbrl — CHANGES_REQUESTED** [review]
Requesting changes to prevent accidental merge until @bl-ue applies changes.

**Review by navarroaxel — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
Thanks, @bl-ue!

**Pull request merged**
