### PR TITLE
update license year

### PR DESCRIPTION
**Pull request by frazjp65**

### CODE REVIEW

**Comment by agnivade** [comment]
I don't think this is meant to be updated. The year denotes when the license file was created.

@waldyrious

**Comment by waldyrious** [comment]
There are [various approaches](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/#the-date), the two most common being to use the creation year, and to use a range from the creation year to the current year. Although the argumentation for a range format (2014-2018) makes a lot of sense, I personally prefer using only the creation year, simply because it would take manual editing every year to keep the range from growing out-of-sync with the actual repo contents.

That said, I'd welcome an integration that automatically kept this up to date (similar to, say, what [greenkeeper](https://greenkeeper.io/) does for dependencies). Do you know of any such tools, @frazjp65?

**Comment by agnivade** [comment]
In all of the open source projects, I have always seen just the creation date. A tool is fine, but there is additional overhead to maintain the tool. I don't see a good ROI on using a tool just for this.

Just the creation date seems fine to me.

**Comment by waldyrious** [comment]
If it's a third-party integration that we'd just have to turn on, I don't see that as much of a burden. Of course, if it's something we'd have to manage more closely (running our own instance, managing login credentials, etc) then I agree the cost-benefit wouldn't look as good.

In any case, doing that or not would be orthogonal to this PR, so I guess we can close it. @frazjp65 let us know if you disagree -- we are open to reconsider, as always :)

**Pull request closed without merging**
