### PR TITLE
rm: add more information link

### PR DESCRIPTION
**Pull request by marchersimon**
For #5510

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Did my tool work? 🙂

**Comment by marchersimon** [comment]
@bl-ue absolutely, I love it. Would be cool if it would outomatically perform a `git add`.

**Comment by bl-ue** [comment]
I thought of that.  Would it be convenient for it to commit as well?

**Comment by marchersimon** [comment]
I don't think so. When I do it myself I can check if I'm on the right branch and write my own commit message. Also, I have to commit only once.

**Comment by bl-ue** [comment]
You can also use `git add .`, sounds like maybe you don't know that.

**Comment by marchersimon** [comment]
I have many untracked files (like scripts or todolists) and to make sure I don't add anything by mistake I try to avoid this.

**Comment by bl-ue** [comment]
Gotcha. Will do.

**Comment by bl-ue** [comment]
Done. 🎉

**Review by yutyo — APPROVED** [review]
LGTM

**Pull request merged**
