### PR TITLE
line: move page

### PR DESCRIPTION
**Pull request by lbonanomi**
Relocating line.md to under pages/linux

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

This PR closes https://github.com/tldr-pages/tldr/issues/3022

### CODE REVIEW

**Comment by sbrl** [comment]
So `line` is only available on Linux systems, and not on, say, macOS?

**Comment by lbonanomi** [comment]
@sbrl I take your point, and put myself in the hands of the org staff for an editorial decision.

I took a cue to home `line` under the Linux directory because it features in the util-linux tarball. `line` doesn't appear on my MacBook, but *does* appear on the (stock) Solaris and AIX hosts at my disposal.

**Comment by sbrl** [comment]
You have access to a solaris box? Awesome!

Yeah, the general rule of thumb is that if it's available on more than 1 platform, it belongs in `common/`.

This wasn't always the case though, but we changed our minds on it a while back (I think it was shortly after the new Windows platform was added).

**Comment by lbonanomi** [comment]
@sbrl I'm pretty sure I can find some pages in the linux directory that appear in at least one of the UNIX-compliant OSes. Do you think this is worth an audit? As I'm sure the org owners know I have time to spare. ;)

**Comment by sbrl** [comment]
Ah, that'd be great @lbonanomi if you've got some time! Any command that is supported more than 1 platform supported by tldr-pages (e.g. `linux` and `osx`) should be in `common/`.

**Comment by lbonanomi** [comment]
I'm filling in [a table of commands that common to Linux, Solaris and MacOS](https://gist.github.com/lbonanomi/49668c6108e8764305e23185ec46369f) as the obvious targets present themselves. 

I don't mean to drag this out, but I thought a public start would be a good

**Comment by sbrl** [comment]
Nice, @lbonanomi! I like your suggestions there to start with. Perhaps we can do all the _promote to `common`_ ones first in a single PR?

**Pull request merged**
