### PR TITLE
replace cn with zh; apt/aptitude/arch: add chinese translations

### LINKED ISSUE #2677: "cn" is not a valid ISO 639-1 code
Recently chinese pages were added in a folder `pages.cn`. It's awesome that different languages are being added but this comes with a problem. How do we choose languages?
So `ta` is a valid 2 letter ISO code (ISO 639-1) for Tamil. When this got added, I added the feature to my client so that the users language would be the default and a fallback to English. This works using ISO 639-1 language codes. 
The problem is that `cn` isn't a valid code. It's only a valid region code but we can't use that to define a language. For example Belgium has Dutch French and German.

The solution for this would be to change `cn` to `zh` which is the valid Chinese ISO 639-1 code.

I think we should add this to the contributing guidelines. It seems the best idea to structure the languages atm. So in the future when new languages get added the folder would look like this: `pages.<ISO 639-1 code>` for example for Dutch: `pages.nl`.

### PR DESCRIPTION
**Pull request by HugueLiu**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform folder (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

Closes #2677

### CODE REVIEW

**Comment by waldyrious** [comment]
@agnivade the diff of this PR doesn't look right to me. There's a bunch of untranslated pages added to the pages.cn directory, and I see no renaming. Do you get something different?

**Comment by agnivade** [comment]
@waldyrious - The first [commit](https://github.com/tldr-pages/tldr/pull/2679/commits/f003080a6949c716601f16edd5509723f5a4a3a2) actually deletes the files from .cn directory. And then the new files are added. I think somehow the combined view is not showing the deleted files. Or I maybe wrong.

**Comment by HugueLiu** [comment]
It's my fault, I am not  too good at git. Actually I commit twice, because firstly I just added the pages.zh, but I forgot to delete pages.cn, so that I committed again. I can close the PR and send again if necessary.

**Comment by principis** [comment]
Closes #2677 @HugueLiu thanks :)

**Comment by HugueLiu** [comment]
> Closes #2677 @HugueLiu thanks :)

Sorry, I have no permission to close an issue.

**Comment by principis** [comment]
> > Closes #2677 @HugueLiu thanks :)
> 
> Sorry, I have no permission to close an issue.

I know but the dev's will see it and close it. But it should close automatically if you reference it in your pull request iirc.

**Comment by pxgamer** [comment]
@principis, added it to the PR description so it will auto-close it 👍

**Comment by agnivade** [comment]
I am inclined to rebase and merge, since the commits are nicely lined up. And if the cn folders still remain, we can fix in a future commit. @waldyrious does that SGTY ?

**Comment by agnivade** [comment]
Ah .. I think it just made @waldyrious' job harder. This commit https://github.com/tldr-pages/tldr/pull/2679/commits/0b3ac5eec78fe2386145c499535928ee1fcdb2db seems to add some .cn pages which should not be there. And you have indeed combined the add and delete ones https://github.com/tldr-pages/tldr/pull/2679/commits/5782f31b843564c7fb29423b0bf40950650e7b7a to a rename commit.

@waldyrious - Since github has detected this to be a file rename change, its not showing additions and  deletions. The commits are a bit haphazard now. You can take a look and see what you want to do. If it's too much work, then just squash.

**Comment by HugueLiu** [comment]
I apologize for what I did,  becasue I make some trouble for you. And if there are somethings I can do ,please tell me.

**Comment by waldyrious** [comment]
>  You can take a look and see what you want to do. If it's too much work, then just squash.

_\*cracks knuckles\*_ Nah, that's just my kind of challenge ;) I'll try to work on it later today.

**Comment by waldyrious** [comment]
Argh, I messed up. I pushed our `master` branch to @HugueLiu's fork, rather than my rebasing of his master branch; now GitHub closed this PR since it detected that HugheLiu:master is even with tldr-pages:master, and with the PR closed I no longer have permissions to push to @HugueLiu's repo.

I will have to merge the rebased commit manually. Fortunately the authorship will be preserved. @HugueLiu, please run `git pull` on your fork to get the updates. (And from now on, please use a dedicated branch for PRs :smile:)

**Pull request closed without merging**
