### PR TITLE
Add php client

### PR DESCRIPTION
**Pull request by BrainMaestro**
This is a cool project. I looked around, and there was no php client, so I wrote one.

### CODE REVIEW

**Comment by agnivade** [comment]
Wow, php is being used as command line tools now ?! Who would have guessed ! :wink: 

@BrainMaestro - FYI we have a spec that all clients should aspire to adhere to - https://github.com/tldr-pages/tldr/issues/1065. You might want to take a look at that for your future work. I don't know how much of that you have done.

**Comment by BrainMaestro** [comment]
Well, I don't think php is anyone's first choice. But yeah you can. 

I actually looked around to see if there was some sort of guide but I didn't see one. Is adhering to the spec absolutely required? I didn't think mine needed a lot of the complex functionality of the node client given that it's unlikely to be used as much.

**Comment by agnivade** [comment]
>  Is adhering to the spec absolutely required?

Not really. We were having some discussions around trimming down the list of clients shown in the main page only to the ones that conform to the spec. Just to keep the behavior uniform. But nothing has been finalized yet.

**Comment by BrainMaestro** [comment]
Okay. I'll take a look at implementing the spec when it's completed

**Comment by BrainMaestro** [comment]
@sbrl hmm I didn't think about that use case, but you actually can. Most of the functionality resides in the `Page` class which you can import like any other. Let me know if it works out for you.

**Comment by sbrl** [comment]
@BrainMaestro Cool!

**Comment by waldyrious** [comment]
>  I didn't think mine needed a lot of the complex functionality of the node client

@BrainMaestro just to make sure, are you taking about features of the node client that are included in the spec, or just its list of features overall? In other words, are there parts of the proposals for the client spec in #1065 that you (as a client author) consider to be excessively onerous?

**Pull request merged**
