### PR TITLE
input: add page

### PR DESCRIPTION
**Pull request by marchersimon**
There isn't really any documentation for this command. There's only a list of keycodes [here](https://developer.android.com/reference/android/view/KeyEvent.html). What I used to get the infos was <https://stackoverflow.com/questions/7789826/adb-shell-input-events>.

For #4934

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]

**Comment by marchersimon** [comment]
Is <https://developer.android.com/reference/android/view/KeyEvent.html#constants_1> okay for the more information link. It doesn't provide anything on `input` itself, but it has a list of all event codes.

**Comment by navarroaxel** [comment]
@marchersimon 

> Is https://developer.android.com/reference/android/view/KeyEvent.html#constants_1 okay for the more information link? It doesn't provide anything on `input` itself, but it has a list of all event codes.

@marchersimon but this are the key constants not the command itself :thinking:.

**Comment by marchersimon** [comment]
That's all I could find. There was a thread about a documentation for the command [here](https://stackoverflow.com/questions/7789826/adb-shell-input-events), but they all just pointed to the link for the key constants.

**Comment by bl-ue** [comment]
To me, it seems fine.  I wish there was a good page for it but ¯\_(ツ)_/¯

**Review by bl-ue — APPROVED** [review]
To me, it seems fine.  I wish there was a good page for it but ¯\_(ツ)_/¯

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
