### PR TITLE
dnf: fix typo in Spanish translation

### PR DESCRIPTION
**Pull request by hsicilia**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by blueskyson — APPROVED** [review]

**Review by kant — CHANGES_REQUESTED** [review]
En este caso, no lleva tilde. Source: https://www.ejemplos.co/que-o-que/#:~:text=Qu%C3%A9%20lleva%20tilde%20y%20se,porque%20qu%C3%A9%20lleva%20tilde%20diacr%C3%ADtica.

**Comment by hsicilia** [comment]
> En este caso, no lleva tilde. Source: https://www.ejemplos.co/que-o-que/#:~:text=Qu%C3%A9%20lleva%20tilde%20y%20se,porque%20qu%C3%A9%20lleva%20tilde%20diacr%C3%ADtica.

Siento diferir, pero lleva tilde porque equivale a "cuál". Según la norma:

_1.1 Con acento

Se acentúa cuando equivale a cuál, vaya un, cuánto, cuán, qué buen, qué mal, qué cosa o motivo, lo que (aunque no siempre), nada que, algo para..._

Por si acaso he hecho la consulta a Fundeu RAE y me han contestado positivamente:

imagen

**Comment by kbdharun** [comment]
@navarroaxel What do you think about this change?

**Review by navarroaxel — APPROVED** [review]

**Comment by kant** [comment]
@hsicilia @kbdharun @blueskyson @navarroaxel Ok for me!

**Comment by kbdharun** [comment]
> @hsicilia @kbdharun @blueskyson @navarroaxel Ok for me!

Btw, you need to approve the PR for the merge checks to pass since you have requested changes. In future, I would suggest using the comment option instead of requesting changes.

**Review by kant — APPROVED** [review]
Done @kbdharun

**Pull request merged**
