### PR TITLE
flameshot: fix time unit in --delay example

### PR DESCRIPTION
**Pull request by MartinCura**
This is already correct in fr, de.

- **Version of the command being documented (if known):**  

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by marchersimon** [comment]
Thanks for your contribution. We should make sure that we also apply this change to the French and Chinese translation. (@Nico385412 @nicokosi @blueskyson @HugueLiu could you please maybe help out here?)

**Review by CleanMachine1 — APPROVED** [review]

**Comment by CleanMachine1** [comment]
@marchersimon the pages where never changed so while they are outdated, the command example there is still up-to-date

**Comment by CleanMachine1** [comment]
I am merging since this is minor.

**Comment by CleanMachine1** [comment]
Thanks for your contribution!

**Pull request merged**
