### PR TITLE
visudo and getent were added

### PR DESCRIPTION
**Pull request by slash3b**

### CODE REVIEW

**Comment by igorshubovych** [comment]
Please in future create one pull request per page.

**Comment by igorshubovych** [comment]
Also `getent` is not available under OSX.

**Comment by waldyrious** [comment]
@igorshubovych about the inclusion of sudo, please see the discussion at #756 (/cc @ostera). Let's keep in mind this tool should always strive to support CLI beginners.

**Comment by slash3b** [comment]
@igorshubovych thank you for the comments, I fixed what you mentioned and double checked the files. Next time only one commit!

@waldyrious thanks, indeed, in `visudo` case it makes sense to keep it prefixed with `sudo`.

**Comment by igorshubovych** [comment]
Thanks, LGTM!

**Comment by waldyrious** [comment]
LGTM too, thanks!

**Pull request merged**
