### PR TITLE
arch: create macOS page and add architecture flags

### PR DESCRIPTION
**Pull request by jakevossen5**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by jakevossen5** [comment]
`arch` on macOS is different than on other systems, and the `-x86_64` option is only on macOS.

**Comment by bl-ue** [comment]
Strange. Is the `-x86_64` only for M1 Macs or something?

**Review by bl-ue — APPROVED** [review]
Strange. Is the `-x86_64` only for M1 Macs or something?

**Comment by jakevossen5** [comment]
Yeah it is kinda weird, seems like Apple just hijacked `arch` to do a bunch of other stuff. Back when 32 bit was supported, you where able to add different flags to run it in 32 bit or 64 bit mode. You can also set environment variables and a whole bunch of other stuff if you look at the man pages, but I am pretty sure 99% of people typing `tldr arch` is going to be because they are on M1 and want to run something using x86_64

**Review by einverne — APPROVED** [review]
Looks good.

**Pull request merged**
