### PR TITLE
choco-upgrade: fix pt_BR argument translation

### PR DESCRIPTION
**Pull request by brunoeduardodev**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
@brunoeduardodev The PR is OK, but looks like you should clean up the history of your `master` for further PRs.

It's better if you use feature branch model when you submit PRs to avoid this situation. :grin:

**Comment by brunoeduardodev** [comment]
Yeah, i'll try to fix it 'cause now i'm seeing the files i added wasn't recognized to PR, i'm going to fix it now, sorry

**Comment by navarroaxel** [comment]
@brunoeduardodev `choco-install` and `choco-upgrade` are already merged in `tldr-pages:master`. Maybe that's why the PR has an empty diff.

**Comment by brunoeduardodev** [comment]
I've just created another pull request, now i think its right

**Pull request closed without merging**
