### PR TITLE
Create tr.md

### PR DESCRIPTION
**Pull request by Dahie**
tr is a small utility for translating characters in text documents

### CODE REVIEW

**Comment by waldyrious** [comment]
Could you include some of the examples given [on wikipedia](https://en.wikipedia.org/wiki/Tr_%28Unix%29)? They make some of the functionality of the command more evident (for example the 1-1 mapping of characters in the two sets, and some useful options.

**Comment by Dahie** [comment]
Thanks for the tip, I added the examples, reworded some descriptions and fixed formatting issues.

**Comment by waldyrious** [comment]
Looks nice :) Although "prints", "maps" and "compresses" should instead be "print", "map" and "compress" to match the tense of the other verbs.

**Comment by Dahie** [comment]
Done :)

**Comment by waldyrious** [comment]
:+1:

**Comment by rubenvereecken** [comment]
Thanks @waldyrious for the reviews.

I had a read and already I'm learning. Great page, thanks for the contribution!

**Pull request merged**
