### PR TITLE
add new guideline in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by yasharmaster**
Commands requiring 'sudo' should be mentioned directly in examples. It would be helpful to include it in the guidelines.

### CODE REVIEW

**Comment by waldyrious** [comment]
That's a great point, @yasharmaster, but I don't think this specific rule fits well with the other examples which are more generic. How about appending it to guideline no. 2 as an example? i.e.

> 2. When in doubt, keep new command-line users in mind. Err on the side of clarity rather than terseness. For example, commands that require `sudo` should include it directly in the examples.

(note also that I changed the '' to `` around `sudo`)

**Comment by yasharmaster** [comment]
@waldyrious Changed it.

**Comment by waldyrious** [comment]
Thanks @yasharmaster :) LGTM.

**Comment by ostera** [comment]
LGTM!

**Pull request merged**
