### PR TITLE
zdb - ZFS Debugger

### PR DESCRIPTION
**Pull request by notpeter**

### CODE REVIEW

**Comment by igorshubovych** [comment]
I like it. How come nobody commented? :)

**Comment by notpeter** [comment]
It's not too surprising, not very many zfs/solaris users and even fewer who have ever had to use the ZFS debugger. ;)

**Comment by waldyrious** [comment]
Despite not being a ZFS user, the page looks good to me and I'd OK merging it. Just one thing, you might want to add colons per the recently agreed formatting standard, @notpeter.

**Comment by notpeter** [comment]
np. done.

**Comment by igorshubovych** [comment]
Thanks for contribution!

**Pull request merged**
