### PR TITLE
pacman: update page

### PR DESCRIPTION
**Pull request by Lopkop**
`sudo pacman -S {{package}}` is actually not installation of a package, but synchronization. So its not only can install, but also update a package

### CODE REVIEW

**Review by spageektti — APPROVED** [review]
Thanks!

**Review by cyqsimon — CHANGES_REQUESTED** [review]
Sounds reasonable. But I think if we're telling people "this updates a package", the example should be changed to use `-Sy`. Otherwise beginner users can foreseeably run  into the situation where their local package repository cache is not up to date and they are left wondering why the update "is not working".

There is an argument to be made that `-S` without `-y` could be useful in some situations, but I think as a rule of thumb `-y` should always be used when possible.

**Comment by Lopkop** [comment]
@cyqsimon good point! Changed that

**Comment by acuteenvy** [comment]
> I think as a rule of thumb `-y` should always be used when possible.

This is not true. Using `-Sy` to install/update a single package causes a partial upgrade, and this might break some packages.

> Do not use: `pacman -Sy package`
> When refreshing the package database, always do a full upgrade with `pacman -Syu`.

https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported

**Comment by cyqsimon** [comment]
> > I think as a rule of thumb `-y` should always be used when possible.
> 
> This is not true. Using `-Sy` to install/update a single package causes a partial upgrade, and this might break some packages.
> 
> > Do not use: `pacman -Sy package`
> > When refreshing the package database, always do a full upgrade with `pacman -Syu`.
> 
> https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported

Hmm. Yeah you're right; I forgot about the matter with partial upgrades. My recommendation was not good.

And also, the original change (only changing the description; command stays unchanged) is not immune from this problem either. It is possible that the user's local package repository cache has been updated but the actually installed packages are lagging behind, for example if the user previously ran `sudo pacman -Syu` but then answered `n` to the confirmation.

In light of this, I actually believe the pre-change version is best. While it is technically correct that `-S` does perform an upgrade, I think it would be somewhat irresponsible from us to recommend a command that could potentially break a user's system in what is essentially a quick reference sheet.

Voting to close.

**Pull request closed without merging**
