### PR TITLE
chmod: add more info link and update French translation

### PR DESCRIPTION
**Pull request by patricedenis**

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Love changes like this ⚡

By the way, @patricedenis, you can see a nice overview of which translations need to be made (and which ones need updating) here: https://lukwebsforge.github.io/tldri18n/

**Comment by patricedenis** [comment]
yes, thanks ! I was on this page, that's why I committed here !

**Comment by bl-ue** [comment]
Just curious: how did you find that page? https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#translations, perhaps?

**Comment by patricedenis** [comment]
yes absolutely. I was reading the contributing page and I thought I could make some first easy contributions to translate some already done pages. I need to know more the syntax of markdown as well so it's a training session !  :-)

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
I'm asking because I was afraid that the place that I put that link was too hidden and people wouldn't notice it—thankfully that's not the case though!

**Pull request merged**
