### PR TITLE
write: add page

### PR DESCRIPTION
**Pull request by pollev**
----

- [OK] The page (if new), does not already exist in the repo.

- [OK] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [OK] The page has 8 or fewer examples.

- [OK] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [OK] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
Please give an '.md' extension to the page.

And also, we have maximum of 2 lines of the heading. So, please remove one line, choose whichever is the least important.

After that, we can get started with the review.

**Comment by pollev** [comment]
Updated page as requested

**Comment by agnivade** [comment]
Hi @pollev, I have made some simplifications which I think makes the page more succinct and clean. Let me know what you think.

**Comment by pollev** [comment]
Looks great!

**Comment by pollev** [comment]
Now that everything is approved, how do I actually merge?

**Comment by sbrl** [comment]
@pollev Once a maintainer has approved your PR, a second maintainer (such as myself!) will then come along and merge :smiley_cat:

**Comment by sbrl** [comment]
There you go :D

**Pull request merged**
