### PR TITLE
Update to use `actions/stale` instead of Stale Bot

### PR DESCRIPTION
**Pull request by owenvoke**
This updates tldr pages to use a GitHub Action for managing stale PRs. Under the hood it uses the [actions/stale](https://github.com/actions/stale) action.

Waiting on actions/stale#99 to be merged or worked on, so leaving this as draft. 👍 Once that functionality is added, we can remove [`.github/stale.yml`](https://github.com/tldr-pages/tldr/blob/208327d21a7373591f5024bf52dd1cb9ddee17f2/.github/stale.yml) and add the following property to the bottom of the GA workflow where I've commented.

```yml
close-pr-message: |
  Hi everyone.
  This thread is being closed as there was no response to the previous prompt.
  However, please leave a comment whenever you're ready to resume,
  so the thread can be reopened. Thanks again!
```

### CODE REVIEW

**Comment by zdroid** [comment]
In which ways is this better than the current approach?

**Comment by owenvoke** [comment]
More control, everything is centralised in the workflows, and also because Stale Bot is being deprecated at some point.
https://github.com/probot/stale/issues/248

**Comment by owenvoke** [comment]
@sbrl, yeah. :+1: I'll leave it as a draft, and get this set up when it's ready.

**Comment by owenvoke** [comment]
Now that this has been merged, I should be able to work on finishing this tomorrow. :+1:

**Comment by owenvoke** [comment]
That should be everything now. 👍

**Comment by zdroid** [comment]
Let's see how it works.

**Pull request merged**
