### PR TITLE
Adds -m syntax to python page

### PR DESCRIPTION
**Pull request by ostera**
I'm wondering if it'd make sense to include samples of the actual purposes for running the `-m` syntax, like running a webserver, or parsing json output in the terminal, with examples for those.

```md
* Parse JSON output
`cat raw.json | python -m json.tool`

* Serve the current directory at `localhost:8000`

`python -m SimpleHTTPServer`
```

Any ideas?

### CODE REVIEW

**Comment by igorshubovych** [comment]
While your examples are right and useful, they do not say what exactly -m does.

I like 2nd explanation from here:
http://stackoverflow.com/questions/7610001/what-is-the-m-switch-for-in-python

"-m mod : run library module as a script (terminates option list)"

**Comment by igorshubovych** [comment]
Here are also several good examples:
http://pythonwise.blogspot.com/2015/01/python-m.html

**Comment by ostera** [comment]
Yup, if you see in the original commit I added `-m` and not particular examples of it. It's now been reworded.

I feel that adding those examples might be useful, but I'm not sure where to add them. They're clearly not about how to use the `python` executable, but they are tightly related to it.

**Comment by igorshubovych** [comment]
This looks good. Let's give guys some time to review, and if there is no more suggestions, let's merge it in 1-2 days.

**Comment by igorshubovych** [comment]
> I feel that adding those examples might be useful, but I'm not sure where to add them. They're clearly not about how to use the python executable, but they are tightly related to it.

You probably often use something like
`python -m SimpleHTTPServer`

In this case you'd better create an alias. There are many useful modules on [this page](http://pythonwise.blogspot.com/2015/01/python-m.html), and we can't choose any of them to be the chosen one example.

**Comment by ostera** [comment]
I actually do have many aliases, and that one is among them: https://github.com/ostera/dotfiles/blob/master/system/.alias#L54

**Pull request merged**
