### PR TITLE
killall: add page

### PR DESCRIPTION
**Pull request by Raindeer44**

### CODE REVIEW

**Comment by Raindeer44** [comment]
Killall is a way to send termination signals to processes by using the process name rather than PID. It also sends the signal to all instances of the process rather than a singular PID (if applicable).

**Comment by jeeftor** [comment]
how does this differ from `pkill -f` ?

**Comment by Raindeer44** [comment]
`killall` and `pkill` are basically the same, but `killall` requires an exact match on the process name by default, which keeps users from accidentally killing a process with a similar name. In my opinion, this is the safer command to use, especially for newer users. I could add in wording saying the process name has to be exact.

**Comment by agnivade** [comment]
>  I could add in wording saying the process name has to be exact.

Yes, that would be helpful.

**Comment by Raindeer44** [comment]
I added some clarifying wording about the name matching.

**Comment by agnivade** [comment]
Hey @Raindeer44 - I think repeating "exact_process_name" multiple times is redundant. Mentioning it at the top should be enough. I also fixed one typo and simplified the last description. 

Let me know how you feel about the changes.

**Comment by Raindeer44** [comment]
I like the changes

**Pull request merged**
