### PR TITLE
SELinux page

### PR DESCRIPTION
**Pull request by clcollins**
Added an SELinux page with some basic useful commands.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
While I like the contents and I understand your motivation, people won't actually attempt `tldr selinux` because the tool is meant for single commands. 
I suggest you separate the contents into individual files named after the commands and either change this PR or create a new one. That should do.

**Comment by rprieto** [comment]
Thanks for the PR, but :+1: to Ruben's comment. `setenforce` and `chcon` could make good standalone pages. I'm not sure I'd add the `-Z` flag to the `ls` page though, given how specific it is.

**Comment by clcollins** [comment]
Thanks!  I'll work on a rewrite then.

**Comment by rubenvereecken** [comment]
Cool resubmit whenever I'll be waiting for it :).

**Pull request closed without merging**
