### PR TITLE
cut: use different separator characters

### PR DESCRIPTION
**Pull request by waldyrious**
to exemplify more possibilities

### CODE REVIEW

**Comment by ostera** [comment]
Maybe we could generalize this? `split out in the specified character`? To make it very clear that it's any character that goes.

**Comment by waldyrious** [comment]
Makes sense, I'll change.

**Comment by waldyrious** [comment]
On second thought, after reading the page again, I don't think that would match well with the style of the examples, which uses specific tokens rather than generalized ones. Since this tool does a narrow set of operations, I believe the various examples using different parameters give a better idea of how to use it than a smaller set of generic examples would, since the latter would require the reader to perform some "variable substitution" by head, which would only be justified if we were pressed for space. Does that make sense to you?

**Comment by ostera** [comment]
You're right, we're not pressed by space. We can revisit if/when more is added to the page. Merging! 👍

**Pull request merged**
