### PR TITLE
Fix description as discussed in #358

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by igorshubovych** [comment]
@rprieto, I have question regarding pull requests like this.

What is the best way of contributing?

- create a fork
- or create a branch in main repo?

**Comment by ostera** [comment]
I think a fork will always be the way to go. Github makes it far easier to do that by simply creating a fork under your back, and submitting the pull request directly.

**Comment by waldyrious** [comment]
I didn't think about a strategy, I just edited the file in the browser and the only two options I had was to commit to a separate branch and create a PR, or commit directly to master. I don't think we should go out of our way to use forks if github's interface makes that option less convenient (for repo collaborators at least -- for regular contributors, a fork is indeed the path of least effort).

**Comment by igorshubovych** [comment]
oh, ok. i did not think about it. sure, the simpler is collaboration is better

**Pull request merged**
