### PR TITLE
xzcat: add page

### PR DESCRIPTION
**Pull request by TerribleCodes**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **xz (XZ Utils) 5.2.2**

For [#8859 ](https://github.com/tldr-pages/tldr/issues/8859)

### CODE REVIEW

**Comment by navarroaxel** [comment]
Hi @TerribleCodes, welcome and thanks for your submission. Could you please sign the license to pass the CLA check?

**Comment by TerribleCodes** [comment]
> Hi @TerribleCodes, welcome and thanks for your submission. Could you please sign the license to pass the CLA check?

Hello. Can you tell me what happens here "pages/common/xzcat.md:1: TLDR010 Only Unix-style line endings allowed".

**Comment by navarroaxel** [comment]
@TerribleCodes I think you're using Windows, please read the isntructions in this proposal https://github.com/tldr-pages/tldr/pull/9010

**Comment by TerribleCodes** [comment]
> @TerribleCodes I think you're using Windows, please read the instructions in this proposal #9010

Thank You. It worked :D

**Comment by trolzen** [comment]
@TerribleCodes 
Since you solved your issue, could you tell what was the exact problem and how did you manage to resolve it?

What was your setup? Git-for-windows and some simple editor?

I'm asking because the #9010 which helped you is about a different issue, and with default git-for-windows setup after commit you should not have ended with replaced CRLF in the repository (not your working copy; CRLF in the working copy is OK).

**Comment by TerribleCodes** [comment]
> @TerribleCodes Since you solved your issue, could you tell what was the exact problem and how did you manage to resolve it?
> 
> What was your setup? Git-for-windows and some simple editor?
> 
> I'm asking because the #9010 which helped you is about a different issue, and with default git-for-windows setup after commit you should not have ended with replaced CRLF in the repository (not your working copy; CRLF in the working copy is OK).

@trolzen 
* To solve to issue I moved to my other PC which is running Kali OS. And I used `vim` as the editor. 
* I suggest you try `vim` that comes with `Git Bash`. Try performing all the Git operations using CLI. 
* For me, copy paste or editing inside the GitHub web-based editor didn't work. (Even in Kali OS I got the same error when using GitHub web-based editor; Don't know the reason)

**Comment by trolzen** [comment]
OK, thank you, so it was solved by editing under Linux.

> * For me, copy paste or editing inside the GitHub web-based editor didn't work. (Even in Kali OS I got the same error when using GitHub web-based editor; Don't know the reason)

This is really weird. :confused:

**Comment by TerribleCodes** [comment]
> OK, thank you, so it was solved by editing under Linux.
> 
> > * For me, copy paste or editing inside the GitHub web-based editor didn't work. (Even in Kali OS I got the same error when using GitHub web-based editor; Don't know the reason)
> 
> This is really weird. confused

Read this article.
<https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/>

**Pull request closed without merging**
