### PR TITLE
nmap: add full nse scan example

### PR DESCRIPTION
**Pull request by kawaiipantsu**
- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by sbrl — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Comment by sbrl** [comment]
Hey there, @kawaiipantsu! We're ready to  merge, but I notice you haven't signed the CLA yet. Could you sign it by clicking on the link in the comment above left by @CLAassistant please?

**Comment by kawaiipantsu** [comment]
> Hey there, @kawaiipantsu! We're ready to merge, but I notice you haven't signed the CLA yet. Could you sign it by clicking on the link in the comment above left by @CLAassistant please?

I just did, don't know if that's enough. Don't seem to register ?
Or is it just taking some time?

**Comment by sbrl** [comment]
Hrm, I see. Are you sure that the email address you committed with is registered in your GitHub account @kawaiipantsu?

**Comment by kawaiipantsu** [comment]
> Hrm, I see. Are you sure that the email address you committed with is registered in your GitHub account @kawaiipantsu?

I mean. must have used a wrong email then :-( No other way. But I have Github privacy enabled so it should always just changed my email to githubs own internal one. If I have to fix the email I would need to redo the fork, commit, push and pull request I guess ?

**Comment by kawaiipantsu** [comment]
> Hrm, I see. Are you sure that the email address you committed with is registered in your GitHub account @kawaiipantsu?

Just checked the git log, yes I used a wrong email I can't fix it by adding it - It's not in use anymore. But I have signed the CLA as kawaiipantsu.

**Comment by navarroaxel** [comment]
@kawaiipantsu just squash to 1 commit, reset the author, and rebase over `tldr-pages:master` because another `nmap` PR was merged.

**Comment by sbrl** [comment]
You should be able to force-push to the branch.

Given the messages here though, I think it's clear that you agree to the CLA, so I will merge this with my admin privileges :-)

Welcome to tldr-pages :smiley_cat:

**Comment by navarroaxel** [comment]
@sbrl now we have a page with 9 examples 🙀

**Comment by sbrl** [comment]
Oops! That was a mistake. We should correct this in another PR

**Comment by kawaiipantsu** [comment]
> @kawaiipantsu just squash to 1 commit, reset the author, and rebase over `tldr-pages:master` because another `nmap` PR was merged.

My git-fuu is not that strong, sorry I caused that much trouble heh ...

**Pull request merged**
