### PR TITLE
MAINTAINERS: add @CleanMachine1 to collaborators

### LINKED ISSUE #5961: Add collaborator: @CleanMachine1
Hi, @CleanMachine1! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#5950, #5948, #5947, #5935, #5923)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

### PR DESCRIPTION
**Pull request by CleanMachine1**
Adding my self to MAINTAINERS.md

Closes #5961

### CODE REVIEW

**Comment by CleanMachine1** [comment]
Couldn't figure it out, kept making mistakes!

**Comment by bl-ue** [comment]
>Couldn't figure it out, kept making mistakes!

Who cares? That's how you learn!

**Review by marchersimon — APPROVED** [review]
Welcome to tldr pages, @CleanMachine1

**Review by bl-ue — COMMENTED** [review]
🚀

**Review by bl-ue — APPROVED** [review]

**Comment by CleanMachine1** [comment]
May I merge?
when reviewed :rocket:

**Comment by bl-ue** [comment]
Sure! Let's wait for @navarroaxel's approval though.

**Comment by CleanMachine1** [comment]
Ok, don't see why since its not a tldr page, just adding to the maintainers but I am in no rush for it so, no problem.

**Comment by bl-ue** [comment]
As always @CleanMachine1 — don't merge PRs right away, because they've been open a while or have enough approvals.  You can ping them (although don't do that _too_ much because that'll clog others' inboxes), and you can approve them all you want, but only merge them after yours is the 3rd (or higher), because sometimes we intentionally don't merge for whatever reason.  Also, we generally leave PRs open 24-48 hours before merging it, so that other maintainers have a change to review ;)

**Comment by CleanMachine1** [comment]
Completely understand

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
Just in case you haven't read it @CleanMachine1: rebasing when the commits are clean and logical, and squash otherwise (so squash here).

**Comment by bl-ue** [comment]
Welcome aboard! :D 🎉

**Comment by navarroaxel** [comment]
@CleanMachine1 remember to clean up the commit message body when you `squash and merge`!

**Comment by CleanMachine1** [comment]
Ok, I did see the option to but ignored.
What would you have put, because I normally just use the title as the message

**Comment by navarroaxel** [comment]
@CleanMachine1  You should keep the subject but remove the body, the commit was this:
```
MAINTAINERS: add @CleanMachine1 to collaborators (#5963)
    
  * Update MAINTAINERS.md
    
  * Update MAINTAINERS.md
    
  * Update MAINTAINERS.md
  
  * Update MAINTAINERS.md
```
You should clean up the body to just keep this commit message instead:
```
```
MAINTAINERS: add @CleanMachine1 to collaborators (#5963)
```

**Comment by patricedenis** [comment]
Welcome !!!

**Comment by CleanMachine1** [comment]
Little late to the party :smile:

**Comment by patricedenis** [comment]
yes but I didn't congratulate you before so here I am ^^
:stuck_out_tongue_closed_eyes:

**Pull request merged**
