### PR TITLE
jps: add Chinese translation

### PR DESCRIPTION
**Pull request by BillLucky**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
@BillLucky these translations are really great — did you know that you can submit multiple translations in one large PR?  Make the title like this: `page1, page1, page3, page4: add Chinese translation`.  Keep up the great work! 😄

**Review by marchersimon — APPROVED** [review]

**Comment by BillLucky** [comment]
> @BillLucky these translations are really great — did you know that you can submit multiple translations in one large PR? Make the title like this: `page1, page1, page3, page4: add Chinese translation`. Keep up the great work! 😄

OK.

**Comment by bl-ue** [comment]
Let me clarify: if you'd rather not, it's perfectly fine to open mulitple small PRs :)

**Review by navarroaxel — APPROVED** [review]

**Comment by BillLucky** [comment]
> Let me clarify: if you'd rather not, it's perfectly fine to open mulitple small PRs :)

I got it, thanks @bl-ue

**Pull request merged**
