### PR TITLE
scripts/*.sh: set executable permission

### PR DESCRIPTION
**Pull request by bl-ue**
In most repos, executable shell scripts have the executable bit set.

### CODE REVIEW

**Comment by navarroaxel** [comment]
Why do you want to add the `x` permission if we lived all this time without it lol

**Comment by bl-ue** [comment]
Yeah, I know 😅 but **everyone** does it; I think it must have been just an oversight.

**Review by sbrl — APPROVED** [review]
Oops! I wonder how this has been working all this time :thinking: 

The shebang at the top of the files is actually useless without `chmod +x`, so great spot!

**Comment by MasterOdin** [comment]
> Oops! I wonder how this has been working all this time

They're explicitly called with `bash scripts/*.sh`, rendering the executable bit unnecessary.

**Review by marchersimon — APPROVED** [review]

**Pull request merged**
