### PR TITLE
flameshot: add French translation

### PR DESCRIPTION
**Pull request by jtm-lis**
There is no folder for uncommon pages for french. I tried finding, pages.fr but didn't see it created.

- [x] The page (if new), does not already exist in the repo.
### - [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
Page is not in the correct directory as no directory for French Pages--> linux exists 
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by jtm-lis** [comment]
### - [ ] The page is in the correct platform directory (common/, linux/, etc.)
Page is not in the correct directory as no directory for French Pages--> linux exists

@sbrl  well I am glad to hear that you are pacing yourself, with this workload, it is easy to burnout.  I

**Comment by owenvoke** [comment]
I hope you don't mind, I've moved the page to the Linux directory. 👍🏻

**Review by navarroaxel — APPROVED** [review]

**Review by owenvoke — APPROVED** [review]
This looks fine to me, but I don't speak French so can't really validate it. 😬

**Review by sbrl — APPROVED** [review]
Thanks, @jtm-lis!

Yeah, I find it easier to deal with lots of PRs in 1 go as opposed to lots of task switching.

**Pull request merged**
