### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by sbrl**
As part of #2986, we've now got a social preview and logo for tldr-pages.

I've set the social preview already, but GH doesn't have a native setting like GitLab does for logos - so you have to commit the file to your repository.

We should also consider adding the logo to the README.

### CODE REVIEW

**Comment by waldyrious** [comment]
Looks really great :)

Some screenshots below.

|Organization page|
|-----------------|
|Screenshot 2019-11-24 at 19 19 35|

|Profile of an org member|
|------------------------|
|Screenshot 2019-11-24 at 19 18 55|

|Tweet|
|-----|
|Screenshot 2019-11-24 at 19 30 39

All of the above worked nicely, as expected. However, when I attempted to make a Facebook post to test the larger image, it didn't seem to have been picked up:
Screenshot 2019-11-24 at 19 32 30

Did you set that too, @sbrl? Or just the logo?

**Comment by waldyrious** [comment]
Also, I'm wondering if we could change the `:books:` in the repository tagline with the actual Unicode character, 📚. That would probably improve the appearance of the tagline in the social preview cards, as shown above.

**Comment by sbrl** [comment]
Ah, I forgot about the org-level logo! No, that wasn't me.

I'll update the description now.

Hrm, not sure where FB is getting that image from. Is it cached or something?

**Comment by pxgamer** [comment]
Looks like the Facebook cache it their end. I've forced a refresh through the Developer panel, so all good now. :+1:

**Comment by waldyrious** [comment]
Great, I can attest that the new image is now shown when making a Facebook post:

Screenshot from 2019-11-24 23-39-06

As for the emoji, I suspect you're right @sbrl. I used the macOS emoji insertion widget (`Ctrl+Cmd+Space`) which sometimes enters custom codepoints rather than the Unicode standard emoji characters. I do mean the actual unicode character 📚 (`U+1F4DA`). Can you try it out in the repo description and see if it stops appearing as `:books:` in the social preview?

**Comment by pxgamer** [comment]
I've updated it to use the unicode character, seems to look good according to https://metatags.io, I'll refresh the Facebook developer dashboard again. 👍

**Comment by schneiderl** [comment]
Looks great. 😄

**Comment by sbrl** [comment]
Oh, no! Looks like GH automatically translate unicode chars into their emojis in the comments. That's why I got confused :P

**Pull request merged**
