### PR TITLE
Added the dirs command

### PR DESCRIPTION
**Pull request by sbrl**
Another simple tldr page.

### CODE REVIEW

**Comment by waldyrious** [comment]
Nice :) but the term "stack" should be defined somewhere, as it's not 100% intuitive what it means.

**Comment by sbrl** [comment]
@waldyrious Good point. I've added a definition, and fixed the errors in the build.

I'm also thinking that a 'see also' section would be really useful here to point readers at the page for `pushd` / `popd`. What's the protocol on that?

**Comment by waldyrious** [comment]
It's ok to mention them in the main description, as in, for example, [uname.md](../blob/master/pages/common/uname.md).

**Comment by sbrl** [comment]
@waldyrious Right. I've added another sentence to the description. Once this page is given the ok, I'll squash all my commits down.

**Comment by waldyrious** [comment]
LGTM :+1:

**Comment by sbrl** [comment]
@waldyrious Awesome, squashing now

**Comment by waldyrious** [comment]
@sbrl I'll let someone else merge the PR, so there's a second set of eyes looking at this, but if a few days go by without news, I'll merge.

**Comment by sbrl** [comment]
@waldyrious All squashed down into one nice neat package.

**Comment by felixonmars** [comment]
:100: Thanks!

**Pull request merged**
