### PR TITLE
Update screen.md

### PR DESCRIPTION
**Pull request by Dahie**
sessionname is also the session id, so have the same wording

### CODE REVIEW

**Comment by waldyrious** [comment]
Maybe the token should be called "session name" rather than just "name", which may be ambiguous. What do you think?

**Comment by Dahie** [comment]
I changed it accordingly. Thanks!

**Comment by waldyrious** [comment]
Please use snake_case for the token names, per the guidelines in CONTRIBUTING.md. Other than that, LGTM :)

**Comment by waldyrious** [comment]
@rubenvereecken should the linter detect non-snake-case tokens and react accordingly?

**Comment by Dahie** [comment]
Snake-Casified it. 8)

**Comment by waldyrious** [comment]
Awesome :) I'll merge directly since this PR has been open for over two weeks with no further comments. Thanks!

**Pull request merged**
