### PR TITLE
Markdown linting

### PR DESCRIPTION
**Pull request by rubenvereecken**
This pull request reflects part of the efforts for #278. 

- `make setup` now installs the gem 'markdownlint' in the `.gem` folder (@ostera is this rubyesque?). 
- `make lint` lints all markdown pages and reports on stderr. Takes some time.
- `make lint-changed` lints only those files added to git. Its primary use is as a pre-commit hook. If a file is about to be committed with linting errors they will be shown to the contributor and the git commit wil fail. As of yet there is no message "hey stuff failed" but the output is fairly self-descriptive. 

First `make lint-changed` was not only for added files but I figured its main purpose would be as a git pre-commit hook.

I'll leave this here for a bit until someone else can have a look at it. I have absolutely no explanation as to why the index is now apparently bigger. We still need to prettify that one so it's human-editable. In the meantime I'll look into Travis, make sure it fails when we want it to and points out the correct problems.

### CODE REVIEW

**Comment by rprieto** [comment]
Very nice work!
Implementation wise, I like the idea of doing it the idiomatic Ruby way, because it's less error prone and Ruby-savvy people would feel more at home. Not necessarily with a `Rakefile` for now (although why not in the future as it evolves), but at least for dependency management (`Gemfile`, `make install: bundle install`...).

**Comment by rubenvereecken** [comment]
Cool @rprieto, I think you're right that we should handle dependencies with a Gemfile. Can those specify install locations, or is that sort of thing generally not an issue?
Moreover, can a rubyist help me out?

**Comment by ostera** [comment]
@rubenvereecken it shouldn't be an issue, but it can vary greatly depending on how the rubygems are configured.

I sent you a pull request that takes care of this :smile:

**Comment by rubenvereecken** [comment]
I added @ostera's commits that took care of the Gemfile. Tested it all locally -- all we need to remember is that devs should now install `bundler` (I didn't have it). 
The pre-commit hook is still working nicely: If you have linting errors in a file you changed, the commit will fail. 

This looks ready to merge. We can migrate the old files bit by bit and they won't interfere with new commits. We do still need a Travis setup ideally.

**Comment by ostera** [comment]
Great news! :+1:

**Pull request merged**
