### PR TITLE
cal: various edits to make the page more useful

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by felixonmars** [comment]
The page is in `common`, but I don't have a `ncal` command :(

The `-w` switch works for my `cal` command, though. (util-linux 2.28)

**Comment by waldyrious** [comment]
Interesting, @felixonmars. Can you paste the manpage for your cal command so we can compare?

**Comment by felixonmars** [comment]
Here it is:

```
CAL(1)                                                                User Commands                                                               CAL(1)

NAME
       cal - display a calendar

SYNOPSIS
       cal [options] [[[day] month] year]

DESCRIPTION
       cal displays a simple calendar.  If no arguments are specified, the current month is displayed.

OPTIONS
       -1, --one
              Display single month output.  (This is the default.)

       -3, --three
              Display three months spanning the date.

       -n , --months number
              Display number of months, starting from the month containing the date.

       -S, --span
              Display months spanning the date.

       -s, --sunday
              Display Sunday as the first day of the week.

       -m, --monday
              Display Monday as the first day of the week.

       -j, --julian
              Display Julian dates (days one-based, numbered from January 1).

       -y, --year
              Display a calendar for the whole year.

       -Y, --twelve
              Display a calendar for the next twelve months.

       -w, --week[=number]
              Display week numbers in the calendar (US or ISO-8601).

       --color[=when]
              Colorize the output.  The optional argument when can be auto, never or always.  If the when argument is omitted, it defaults to auto.  The
              colors can be disabled; for the current built-in default see the --help output.  See also the COLORS section.

       -V, --version
              Display version information and exit.

       -h, --help
              Display help text and exit.

PARAMETERS
       A single parameter specifies the year to be displayed; note the year must be fully specified: cal 89 will not display a calendar for 1989.

       Two parameters denote the month (1 - 12) and year.

       Three parameters denote the day (1-31), month and year, and the day will be highlighted if the calendar is displayed on a terminal.  If no param‐
       eters are specified, the current month's calendar is displayed.

       A year starts on January 1.  The first day of the week is determined by the locale.

       The  week  numbering depends on the choice of the first day of the week.  If Sunday (the default) is used for the first day of the week, then the
       customary North American numbering will be used, i.e. the first Sunday of the year starts the first  week.   If  Monday  is  selected,  then  the
       ISO-8601 standard week numbering is used, where the first Thursday of the year is in week number 1.

COLORS
       Implicit coloring can be disabled as follows:

              touch /etc/terminal-colors.d/cal.disable

       See terminal-colors.d(5) for more details about colorization configuration.

BUGS
       The cal program uses the 3rd of September 1752 as the date of the Gregorian calendar reformation -- that is when it happened in Great Britain and
       its colonies (including what is now the USA).  Starting at that date, eleven days were eliminated by this reformation, so the calendar  for  that
       month is rather unusual.  The actual historical dates at which the calendar reform happened in all the different countries (locales) are ignored.

       Alternative calendars, such as the Umm al-Qura, the Solar Hijri, the Ge'ez, or the lunisolar Hindu, are not supported.

HISTORY
       A cal command appeared in Version 6 AT&T UNIX.

AVAILABILITY
       The cal command is part of the util-linux package and is available from ftp://ftp.kernel.org/pub/linux/utils/util-linux/.

util-linux                                                              June 2015                                                                 CAL(1)
```

**Comment by waldyrious** [comment]
Indeed, FreeBSD/OSX has a different version:

```
CAL(1)                    BSD General Commands Manual                   CAL(1)

NAME
     cal, ncal -- displays a calendar and the date of easter

SYNOPSIS
     cal [-jy] [[month] year]
     cal [-j] -m month [year]
     ncal [-jJpwy] [-s country_code] [[month] year]
     ncal [-Jeo] [year]

DESCRIPTION
     The cal utility displays a simple calendar in traditional format and ncal
     offers an alternative layout, more options and the date of easter.  The
     new format is a little cramped but it makes a year fit on a 25x80 termi-
     nal.  If arguments are not specified, the current month is displayed.

     The options are as follows:

     -J      Display Julian Calendar, if combined with the -e option, display
             date of easter according to the Julian Calendar.

     -e      Display date of easter (for western churches).

     -j      Display Julian days (days one-based, numbered from January 1).

     -m month
             Display the specified month.

     -o      Display date of orthodox easter (Greek and Russian Orthodox
             Churches).

     -p      Print the country codes and switching days from Julian to Grego-
             rian Calendar as they are assumed by ncal.  The country code as
             determined from the local environment is marked with an asterisk.

     -s country_code
             Assume the switch from Julian to Gregorian Calendar at the date
             associated with the country_code.  If not specified, ncal tries
             to guess the switch date from the local environment or falls back
             to September 2, 1752.  This was when Great Britain and her
             colonies switched to the Gregorian Calendar.

     -w      Print the number of the week below each week column.

     -y      Display a calendar for the specified year.

     A single parameter specifies the year (1 - 9999) to be displayed; note
     the year must be fully specified: ``cal 89'' will not display a calendar
     for 1989.  Two parameters denote the month and year; the month is either
     a number between 1 and 12, or a full or abbreviated name as specified by
     the current locale.  Month and year default to those of the current sys-
     tem clock and time zone (so ``cal -m 8'' will display a calendar for the
     month of August in the current year).

     A year starts on Jan 1.

SEE ALSO
     calendar(3), strftime(3)

HISTORY
     A cal command appeared in Version 5 AT&T UNIX.  The ncal command appeared
     in FreeBSD 2.2.6.

AUTHORS
     The ncal command and manual were written by Wolfgang Helbig
     <helbig@FreeBSD.org>.

BUGS
     The assignment of Julian--Gregorian switching dates to country codes is
     historically naive for many countries.

BSD                            November 23, 2004                           BSD
```

We ought to split this into two entries. Nice catch!

**Comment by jeeftor** [comment]
Whats going on with this PR?

**Comment by waldyrious** [comment]
@jeeftor good question, I can't recall why I added the "waiting" label. From what I can see re-reading the discussion above, it's up to me to actually split the cal page into a linux and osx version, and/or move the ncal command to a separate page. I'll add this to my personal todo list for when I'm done trimming the backlog I've let accumulate.

**Comment by waldyrious** [comment]
At last, I've cleared the backlog of other PRs, and finally took the time to properly edit this page. Turns out the original version which was in pages/common/ was an osx-specific version. I moved it to the proper place, and added a linux version. Ready for review! (ping @felixonmars)

**Pull request merged**
