### PR TITLE
pages.*: add standard translation

### PR DESCRIPTION
**Pull request by kbdharun**
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Automatically generated alias pages using the script at <https://github.com/tldr-pages/tldr/blob/main/scripts/set-alias-page.py> and added links to it using the script at <https://github.com/tldr-pages/tldr/blob/main/scripts/set-more-info-link.py>.

Closes #9601 (My previous PR)

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by kbdharun** [comment]
NOTE: Please hold off on the merge of this PR. I found some false positive deletions. I will fix it later today.

**Review by navarroaxel — APPROVED** [review]

**Review by blueskyson — APPROVED** [review]

**Comment by blueskyson** [comment]
How did the false positives happen? Is there a bug in set-alias-page.py?

**Comment by kbdharun** [comment]
> @kbdharun How did the false positives happen? Is there a bug in set-alias-page.py?

It didn't occur in `set-alias-page.py` but in the set more info script.

**Comment by kbdharun** [comment]
Can I merge this or should we wait for more reviews?

**Comment by EmilySeville7cfg** [comment]
You can. :)

**Pull request merged**
