### PR TITLE
del: add Arabic translation

### PR DESCRIPTION
**Pull request by hadeer-r**
- [x] The page(s) are in the correct platform directories: `windows`.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

### CODE REVIEW

**Comment by hadeer-r** [comment]
> * The page `pages.ar/windows/del.md` is outdated, based on the command contents itself.
> * The page `pages.ar/windows/del.md` has an outdated more info link.

I have reviewed the instructions using the original documentation and entered the true URL.

**Comment by hadeer-r** [comment]
> * The page `pages.ar/windows/del.md` is outdated, based on the command contents itself.
> * The page `pages.ar/windows/del.md` has an outdated more info link.

I have reviewed the instructions using the original documentation and entered the true URL.

**Comment by hadeer-r** [comment]
> To fix the link, you could run `scripts/set-more-info-link -S -l ar`

thank you, I have updated it

Is there a problem with the command?
should I edit first syntax to be: `{{file_pattern1}} file_pattern2}} ...`

**Review by kbdharun — APPROVED** [review]
LGTM, welcome to tldr and thanks for your contribution.

**Pull request merged**
