### PR TITLE
bspc: add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by renie**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Welcome to tldr and thanks for your contribution.

**Comment by renie** [comment]
Neat. Thanks @kbdharun and @sebastiaanspeck !

**Comment by renie** [comment]
Understood @sebastiaanspeck .

**Review by isaacvicente — APPROVED** [review]
Nice :)

Thanks for your contribution! :tada:

**Pull request merged**
