### PR TITLE
coreutils commands: move pages to common/ folder

### PR DESCRIPTION
**Pull request by felixonmars**
As suggested in #2196. The commands in coreutils are installable under
Mac and Windows, so let's move them to common/ folder.

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by agnivade** [comment]
Why is the sort file deleted ?

**Comment by felixonmars** [comment]
It includes one different example, but the rest are the same as the one in common/. If the example is important we should add it into the common/ one instead.

**Comment by agnivade** [comment]
Sure, let's do that. I wouldn't want to lose information. If we want to remove any example, we should do it in a separate PR. But since this PR is just about moving pages, I would like all examples to remain.

**Comment by felixonmars** [comment]
OK, updated.

**Comment by sbrl** [comment]
Thanks, @felixonmars :smiley_cat:

**Pull request merged**
