### PR TITLE
Update wget.md

### PR DESCRIPTION
**Pull request by Larry850806**

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks, but don't you mean "number of retries"? Also, what's the default if this option isn't specified -- zero, I suppose?

**Comment by Larry850806** [comment]
Yes, it doesn't retry in default. But `wget -t 0 {{url}}` means retry until finish download. Besides, I have modified the description to "number of retries".

**Comment by waldyrious** [comment]
I asked about the default so the description could be made clearer :) how about "Retry a given number of times if the download doesn't succeed at first"? I' saying this because "set maximum number of retries" may imply that there is an unlimited number of retires by default, and this option just limits them.

**Comment by Larry850806** [comment]
Oh, I see. Sorry for my poor English. I have modified the description.

**Comment by waldyrious** [comment]
LGTM :)

**Comment by felixonmars** [comment]
:+1:

**Pull request merged**
