### PR TITLE
moro: add page

### PR DESCRIPTION
**Pull request by omidfi**
Moro is a cli tool available on npm.org

### CODE REVIEW

**Comment by omidfi** [comment]
Hi @agnivade 

Thanks for the feedback. I hope it's ok now.

**Comment by agnivade** [comment]
Hi @omidfi - I took the liberty to simplify and shorten the descriptions. Basically wanted to make them look crisp. Please let me know if they look okay to you.

**Comment by omidfi** [comment]
@agnivade thanks. Looks great.

**Comment by agnivade** [comment]
@sbrl - Please review.

**Comment by sbrl** [comment]
Looks ok to me! :smiley_cat:

**Pull request merged**
