### PR TITLE
Add npm install --save-dev 🐖

### PR DESCRIPTION
**Pull request by livioso**
Am I the only one who always forgets if it's --saveDev or --save-dev? My suggestions add --save-dev too. 💩

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the contribution! May I suggest explaining in the command descriptions what's the use-case difference for `--save` vs. `--save-dev`? Happy to brainstorm possible phrasings.

**Comment by livioso** [comment]
For sure. 👍 How about this?

- Download a given dependency required for the application to run, and add it to the package.json:  
 `npm install module_name@version --save`

- Download a given dependency for development purpose, and add it to the package.json:  
`npm install module_name@version --save-dev`

↘️ Inspired by [this](http://stackoverflow.com/questions/22891211/what-is-difference-between-save-and-save-dev).

**Comment by waldyrious** [comment]
That works. I would only change "purpose" to "purposes", but other than that I'd OK that proposal 👍

**Comment by livioso** [comment]
@waldyrious 🐿 Changed the descriptions as discussed.

**Comment by waldyrious** [comment]
LGTM. @igorshubovych?

**Comment by igorshubovych** [comment]
Thanks!
redneckisland-redneck-island-season-5-episode-4-l4KhZIn63RpdUxFUQ

**Pull request merged**
