### PR TITLE
fc-pattern: add page

### PR DESCRIPTION
**Pull request by sethwoodworth**
A useful tool in linux for looking up extended information on a font.

### CODE REVIEW

**Comment by ostera** [comment]
@sethwoodworth please check the travis build logs :)

**Comment by sethwoodworth** [comment]
Fixed, rebased and now passing :)

**Comment by igorshubovych** [comment]
LGTM

**Comment by waldyrious** [comment]
Usually the tokens are provided in snake_case, but in this case I suppose it's better to illustrate what kind of strings one might pass to the command. LGTM :+1:

**Pull request merged**
