### PR TITLE
figlet: edit page

### PR DESCRIPTION
**Pull request by jeeftor**
Added additional info on how to get the list of available fonts.  

Also should this command be moved into common because you can run it on OS X??

### CODE REVIEW

**Comment by agnivade** [comment]
The command is `figlet`, but you have mentioned `showfigfonts`. Are both the same ?

**Comment by jeeftor** [comment]
Figlet when you install comes with a separate command called showfogfonts. So the question is How do you tie the. Together. It runs figlet with a string and prints out the text for each font. So it's important to be tied into figlet if you want to do other fonts but not sure the best way to do so. A separate command seems like you wouldn't find it

**Comment by agnivade** [comment]
Hmm, so linking 2 pages is possible. See the common/uname.md file. The node client will show a 'see also' section at the end of the command. You just have to add another line in the heading linking to `showfigfonts` command.

But if the user is probably never going to search for the `showfigfonts` as a standalone command, then for the sake of practicality, it makes sense to put them in a single page.

Thoughts ?

**Comment by jeeftor** [comment]
Thoughts are they are never going to search for showfigfonts separately from figlet.

**Pull request merged**
