### PR TITLE
ip*: add Turkish translation

### PR DESCRIPTION
**Pull request by ersen0**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

**Version of the command being documented (if known):**

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
@ersen0 could you please sign the license to pass the CLA check?

**Review by EmilySeville7cfg — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
Does anybody here knows turkish to review this PR better? 🤔

**Comment by navarroaxel** [comment]
> Does anybody here know turkish to review this PR better? thinking I can't rely completely on google translate.

@yutyo can

**Review by navarroaxel — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
Is there any way to tell GitHub assign reviewers based on language they can translate? For instance if PR title contains "Turkish" add @yutyo to reviewers.

**Comment by navarroaxel** [comment]
we can create groups in this section https://github.com/orgs/tldr-pages/teams

**Pull request merged**
