### PR TITLE
gource: tweak command descriptions

### PR DESCRIPTION
**Pull request by waldyrious**
Hopefully makes them clearer and more consistent.

### CODE REVIEW

**Comment by waldyrious** [comment]
I'm not really sure how `-c` and `-s` interact if used simultaneously. Any hints, @fuerbringer?

ps - I submitted these as a separate PR rather than request them in #1211 as that one had been nitpicked enough :)

**Comment by waldyrious** [comment]
Thanks for the clarifications @fuerbringer :)

**Comment by fuerbringer** [comment]
Looks great! I don't have anything to add. :+1:

**Comment by agnivade** [comment]
I think the "Set" prefix was shorter and concise. Repeating "Run gource" sounds awkward. Maybe we can mention "Run gource" at the start, and then start the rest of the descriptions with "Set".

**Comment by waldyrious** [comment]
I was aiming for consistency and maximum clarity (no parts of the description left implicit), but since you guys both seem to agree that starting with "Set" is sufficiently intuitive, I'll change.

**Pull request merged**
