### PR TITLE
Add page for vim

### PR DESCRIPTION
**Pull request by fluxw42**
Added initial page for vim with basic commands. Could be extended, but it's a start.

### CODE REVIEW

**Comment by igorshubovych** [comment]
I waited for this page for so long!!! :100:

Could you please also add the most important recipe for vim: how to exit from it?

See how it is done on the `less` page?
https://github.com/tldr-pages/tldr/blob/master/pages/common/less.md

**Comment by fluxw42** [comment]
Done. I also added vimtutor, which is the build in tutorial. This was useful for me since vim has a steep learning curve, so I guess it will help some other people as well.

**Comment by igorshubovych** [comment]
Well, you hurried up with vimtutor. It is a different command and should have its own page.

**Comment by fluxw42** [comment]
My bad. I thought they belonged together since they both point to the same tool. I've moved it from the vim page to it's own vimtutor page.

**Comment by igorshubovych** [comment]
Yay! Thank you for your pull request!

**Pull request merged**
