### PR TITLE
test: update condition example description

### PR DESCRIPTION
**Pull request by PackmanDude**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** (part of GNU coreutils) 9.1

### CODE REVIEW

**Comment by PackmanDude** [comment]
Assitance by anyone is very welcomed.

**Comment by navarroaxel** [comment]
@PackmanDude The pages for tldr should follow this format:

```markdown
- Example description (some clarification here):

`example command`
```

**Comment by PackmanDude** [comment]
A little bloated, but it may be as that to show how this is actually important.

**Review by blueskyson — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by mfrw — APPROVED** [review]
LGTM :)
Thank you @PackmanDude

**Pull request merged**
