### PR TITLE
aws codeartifact: add page; pt_BR translation

### PR DESCRIPTION
**Pull request by nkzren**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** `aws-cli/1.29.25 Python/3.11.5 Linux/6.1.59-1-lts botocore/1.31.25`

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

As mentioned by @sebastiaanspeck, I would suggest translating the application placeholders for domain, repository and subcommand.

**Comment by gutjuri** [comment]
Thanks for your contribution!

**Comment by kbdharun** [comment]
@gutjuri For PRs dealing with translations having code owners, it is suggested to wait for their reviews before merging it.

**Comment by gutjuri** [comment]
Good to know, thanks!

**Pull request merged**
