### PR TITLE
7z: fix example of -t option

### PR DESCRIPTION
**Pull request by augustgerro**

### CODE REVIEW

**Comment by agnivade** [comment]
Is this really a bug ? Does it not work without the space ?

**Comment by sbrl** [comment]
@agnivade I think so.

**Comment by waldyrious** [comment]
@augustgerro please sign the CLA so we can merge this PR. (Or let us know if you have any objections about that.)

**Comment by augustgerro** [comment]
@waldyrious Done! I have no any objections

**Pull request merged**
