### PR TITLE
md5sum: add page

### PR DESCRIPTION
**Pull request by beta1440**

### CODE REVIEW

**Comment by agnivade** [comment]
We already have a page for md5sum.md under linux. Please check the command's behavior under osx, and if they are the same, create another commit deleting the page under linux.

**Comment by Beta1440** [comment]
I wasn't aware of the md5sum.md page in linux. For some reason, the tldr website says there isn't a page for md5sum when i searched for it so that's why I submitted this pull request. 

Nevertheless, I'll verify whether this command is the same on osx.

**Comment by sbrl** [comment]
@beta1440 Hrm! You could have issues with the tldr client you're using. What OS are you on & what client are you using?

**Comment by agnivade** [comment]
He is using the web client. The web client doesn't look for common and platform specific pages combined.

**Comment by sbrl** [comment]
@agnivade Huh.... That's interesting. I thought it would have done. You learn something every day!

**Comment by beta1440** [comment]
I'm closing this pull request since I don't have anything else to add.

**Comment by waldyrious** [comment]
@beta1440, thanks for your contribution regardless. I'm sorry that the web client induced you in error and led you to work on creating a page that already existed. We really appreciate your time.

@ostera, any idea whether the web client could be adjusted to account for all pages regardless of platform?

**Pull request closed without merging**
