### PR TITLE
*: add Hungarian translation using DeepL

### PR DESCRIPTION
**Pull request by janoka**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by blueskyson** [comment]
Hi, your patience is very much appreciated. But we don't accept machine translation as we must ensure the readability of all pages. Furthermore, placeholders like `{{path/to/directory}}` should be translated as well.

**Comment by janoka** [comment]
Hi @blueskyson, 
Thank you for your prompt feedback!
Have you seen any other issue? I'm going to double-check the `{{something/to/translate}}` issues. 
But if you saw anything else those also would be warmly welcomed. Cheers!

> Hi, your work is very much appreciated. But we don't accept machine translation as we must ensure the readability of all pages. Furthermore, placeholders like `{{path/to/directory}}` should be translated as well.

**Review by kbdharun — COMMENTED** [review]
Welcome to tldr and thanks for your contribution. I have started a discussion regarding this PR in our chatroom, I will let you know the decision made after the conversation.

**Comment by SethFalco** [comment]
We'd had a few PRs like this before, we should probably clarify this in the guidelines.

As blueskyson says, we don't accept machine translations. (At least not without human-review.)
It's not that machine translations have no place in tldr; however, that would be client-behavior and should not live in this repository.

This repo is a source of truth for high-quality human reviewed pages. If you want to see machine translations, I'd encourage you to feature request it to your client of choice to delegate it to DeepL if the page is not found if you're language.

**Comment by janoka** [comment]
@blueskyson, @kbdharun, @SethFalco, and @EmilySeville7cfg thank you for the feedback!

Sorry, but I won't have the time and energy to review all the articles. But I understand your point and accept. 
I can make minor changes like correcting the previously mentioned `{{path/to/directory}}` translation issues, but without the chance to merge, I won't fix it.

So, I will close this PR.

**Pull request closed without merging**
