### PR TITLE
Added notify-send

### PR DESCRIPTION
**Pull request by rakeshdas1**

### CODE REVIEW

**Comment by igorshubovych** [comment]
Could you please lint it?

**Comment by rubenvereecken** [comment]
I just realized this is your third attempt (#559 and #606)? Poor man. I can merge this in some time when I've spare time, contributors please focus on content.

**Comment by waldyrious** [comment]
@rubenvereecken if you can, when you're dealing with this PR please also address the inline comments I left in #559.

**Comment by rakeshdas1** [comment]
I'm stumped... Travis is throwing me this error and I don't know what it is telling me to fix: `pages/linux/notify-send.md:1: TLDR101 Command description probably not properly annotated`

**Comment by rakeshdas1** [comment]
So now the build passes hmmm....

**Comment by rubenvereecken** [comment]
Bullocks to GitHub. I did this the clean way around but it won't acknowledge my efforts. This is merged but GitHub is being a dick. I did take the liberty of reworking some bits.

Cheers :tada:

**Pull request closed without merging**
