### PR TITLE
fuser: add page

### PR DESCRIPTION
**Pull request by mathieupouedras**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by mathieupouedras** [comment]
My bad dit not check tha fuser already existed in the repo. 
I did check only on https://tldr.sh/ with the search and fuser user was not listed.

**Comment by nicokosi** [comment]
> My bad i did not check that fuser already existed in the repo.
> I did check only on https://tldr.sh with the search and fuser was not listed.

:sob: 
Does the "search" widget only search `common` pages? Or it is outdated? :grey_question:

**Comment by CleanMachine1** [comment]
Yes, it does seem that only common is shown, anyway that can be fixed since a user might think we have a lack of pages if we only show them.

**Comment by marchersimon** [comment]
`tldr.sh` by default searches only through `common`, but you can search for `linux/fuser` to get the page. Defenetly not how it should be.

**Comment by nicokosi** [comment]
> Yes, it does seem that only common is shown, anyway that can be fixed since a user might think we have a lack of pages if we only show them.

Sorry, I don't understand after "anyway".

**Comment by nicokosi** [comment]
> `tldr.sh` by default searches only through `common`, but you can search for `linux/fuser` to get the page. Definitevely not how it should be.

OK, I think the code is here: https://github.com/tldr-pages/tldr.jsx-fork/blob/d1efe52eb77bde1b179f4eb0780f2060847ba199/src/Location.js#L29.
No idea on how to enhance (code or explanations?)...

**Comment by marchersimon** [comment]
I don't really know myself, but it's propably harder than just changing that line, since it has to look it every directory to see if that page exists there.

**Comment by nicokosi** [comment]
For information, I just opened a new PR: https://github.com/tldr-pages/tldr.jsx-fork/pull/3. 😅

**Pull request closed without merging**
