### PR TITLE
Translate 14 common pages in Italian.

### PR DESCRIPTION
**Pull request by mebeim**
Some more Italian common pages :smile: (now around 19.7% of total).

### CODE REVIEW

**Comment by schneiderl** [comment]
@mebeim anyone already involved in tldr besides you knows italian?

**Comment by mebeim** [comment]
@schneiderl Hmmm someone contributed some Italian pages some time ago, but other than that I don't know about anyone else unfortunately (i.e. repo collaborators or members of the org).

**Comment by sbrl** [comment]
Sorry, I only know English - I don't think various programming languages count here :P

**Comment by mebeim** [comment]
Alright, well there isn't really much more to do indeed.

**Pull request merged**
