### PR TITLE
ned: add page

### PR DESCRIPTION
**Pull request by nevdelap**
- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by nevdelap** [comment]
I have signed and if I click Details for license/cla it tells me that I've signed.

**Comment by nevdelap** [comment]
Hooray!

**Comment by nevdelap** [comment]
I have signed the agreement three times now. Hopefully this one will stick.
signed

**Comment by nevdelap** [comment]
I get it, my commit was with my work email. I've added it to my github and will verify it tomorrow.

**Comment by nevdelap** [comment]
I added my work email to my GitHub account and verified it. I made sure my GitHub profile would allow access to my email addresses. I repushed the commit using my personal email that has always been in GitHub. I logged out and back into the cla so that it asked again for access to my email addresses, and re-signed. Any advice on what's left to try?

**Comment by sbrl** [comment]
Hrm. Interesting issue, @nevdelap! You could try amending the commit you've made with the email address of your original GitHub email address in order to change the authorship information and the force-push:

```
git config user.name bill
git config user.email bob@bobsrockets.com
git commit --amend --no-edit
git push --force
```

The above should edit the username & email address locally tot he repository (without affecting your global config), edit the commit, and then push it to the remote branch.

Note that when making changes normally you don't need to squash & force-push - we've got a special button that does it for us when we merge :P

**Comment by nevdelap** [comment]
Hi @sbrl.

That's what I've done already. The original was pushed with my work address. The most recent patch is pushed with my personal address. My work address wasn't in my GitHub at the the time I created the pull request and originally signed. The latest is my address that has always been it GitHub.
```
09:51 ~/tldr> git show 61b8cd71df | head -n 3
commit 61b8cd71df78ae2f1e93e5b39d8a846453bb051a
Author: Nev Delap <ndelap@gmail.com>
Date:   Thu Feb 14 18:37:34 2019 +1000
```
I'm thinking it might be worth trying closing the pull request and creating a new one, so that it has a verified email address when it first sees it - which now would be either email address now - or maybe cla only considers the primary address. I think cla has gotten itself into a tizzy.

Cheers.

**Comment by sbrl** [comment]
Good idea! Sounds like a new PR should solve the issue.

Sorry for the additional bother!

**Pull request closed without merging**
