### PR TITLE
column: fix typo

### PR DESCRIPTION
**Pull request by mebeim**
"i.e." → "e.g."

### CODE REVIEW

**Comment by pxgamer** [comment]
Not sure what's happened to Travis here... 🤔

**Comment by sbrl** [comment]
Force-merging because this is a trivial change.

**Comment by mebeim** [comment]
@pxgamer oh I was wondering that too.. good to know it's now solved.

**Comment by sbrl** [comment]
@mebeim Yeah, if you're a repo admin you can force-merge - even if the checks aren't green.

**Pull request merged**
