### PR TITLE
git-init: update Italian translation

### PR DESCRIPTION
**Pull request by lucapollani**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution, can you add the translation of [`--object-format` example](https://github.com/tldr-pages/tldr/blob/main/pages/common/git-init.md) too here

**Comment by Luc9802** [comment]
@kbdharun I've not translated it intentionally since I don't think the original in english is 100% correct... `--object-format={{sha256}}` shouldn't be `--object-format={{format}}` and the description of the command more general?
Currently the example is specific for sha256 alghoritm.

**Review by mebeim — APPROVED** [review]

**Comment by mebeim** [comment]
@lucapollani I think the `--object-format` example is still good as is TBH. After all, we collect examples of commands, making an example with `SHA256` instead of a "generic" version that says `format` makes it a lot easier to understand what the command is about.

**Comment by lucapollani** [comment]
@mebeim I've updated the `--object-format` example as it's described in the english version.

**Review by mebeim — APPROVED** [review]
Awesome, thank you @lucapollani :)

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
