### PR TITLE
umount: make descriptions more explicit

### PR DESCRIPTION
**Pull request by waldyrious**
Note: the "dangerous" remark was not clear about what the danger is -- we can mention possible caveats, but it's better to be explicit.

### CODE REVIEW

**Comment by waldyrious** [comment]
Requesting review/merge from @sbrl and/or @rubenvereecken.

**Comment by sbrl** [comment]
(I'm on my phone, and Octodroid doesn't support reviews yet) 

Those improvements look good to me! Though the description (especially the first line) is misleading. It's true that it revokes access, but it unmounts the device too.

**Comment by waldyrious** [comment]
> Though the description (especially the first line) is misleading. It's true that it revokes access, but it unmounts the device too.

Sure we can change that line too. What would you suggest?

**Comment by sbrl** [comment]
@waldyrious Perhaps "Unmounts an entire filesystem...."? I'm not sure - that uses "unmount", which is almost in the command name.

**Comment by waldyrious** [comment]
Well, WIkipedia describes it [as follows](https://en.wikipedia.org/wiki/Mount_(Unix)):

> (...) `umount` instructs the operating system that the file system should be disassociated from its mount point, making it no longer accessible and may be removed from the computer.

Do you see anything we could use here for a compact description? Maybe "unlink a filesystem from its mount point"? Or perhaps something closer to "disassemble", since the filesystem ceases to exist as such when unmounted?

**Comment by sbrl** [comment]
@waldyrious Yeah, something like that! How about "Unlink a filesystem from its mount point, making it no longer accessible."?

**Pull request merged**
