### PR TITLE
git-cherry-pick: add examples to pick more commits

### PR DESCRIPTION
**Pull request by waldyrious**
See #1196 for context.

### CODE REVIEW

**Comment by agnivade** [comment]
LGTM

**Comment by waldyrious** [comment]
I'll wait for @alefir's input before merging :)

**Comment by alefir** [comment]
I'd suggest changing 'commit_hash' to just 'commit' in the first example, since the '_hash' bit isn't used in any of the other examples. Besides that, looks fine to me.

**Comment by waldyrious** [comment]
Good point, I'll change that. This is also consistent with the majority of our git pages, I believe.

**Pull request merged**
