### PR TITLE
pages.pt_BR/common/*: fix translation

### PR DESCRIPTION
**Pull request by renie**
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

### CODE REVIEW

**Comment by renie** [comment]
> > Hello! I've noticed something unusual when checking this PR:
> > 
> > * The page `pages.pt_BR/common/ffmpeg.md` is outdated, based on the command contents itself.
> > * The page `pages.pt_BR/common/ssh.md` is outdated, based on the command contents itself.
> > 
> > Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.
> 
> Can you fix these pages in this PR?

Sure, working on it

**Comment by renie** [comment]
All good now.

**Review by kbdharun — APPROVED** [review]

**Review by nelsonfigueroa — APPROVED** [review]
idk why my review was requested since i don't know Portuguese but this looks good to me lol

**Comment by nelsonfigueroa** [comment]
I'm going to merge this #yolo

**Pull request merged**
