### PR TITLE
generate_page.sh: add script for automatic page generation

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

## Notes

Does anybody know how to fix this problem with `wget`? Pages actually exist in manned.org but script treats them as missing.

image

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I've contacted maintainer of manned.org and we decided to allow `--user-agent tldr-fetcher` client` to permit extract manuals.

**Comment by EmilySeville7cfg** [comment]
Our [Bash framework](https://github.com/tldr-pages/tldr-bash-framework/blob/main/framework.sh) will be used here to create beautifully looking script.

**Comment by kbdharun** [comment]
> I've contacted maintainer of manned.org and we decided to allow `--user-agent tldr-fetcher` client to permit extract manuals:
> 
> > Eh, please don't impersonate actual browsers. Something simple like
> "tldr-fetcher" will do fine.
> 
> I guess we can try use another man page archive site where downloading pages is allowed by default. Why? Author can restrict access for tldr fetching again if we use such script too often (what is too often here is unclear for me).

I have a better solution why don't we create a mirror repository for https://code.blicky.net/yorhel/manned here on GitHub. So that we can perform actions right here inside of our organization. I kinda agree with why the author restricts it. Since it is a self hosted instance this can cause issues with his bandwidth. So I think this solution would be better since manned source code is available (i.e downloading or forking pages is available by default).

**Comment by waldyrious** [comment]
Intriguing idea. Thanks for the heads-up, @kbdharun. However, this PR is missing motivation, intended use, and example output. IMO reviews shouldn't be requested until that's in place.

**Comment by EmilySeville7cfg** [comment]
Script will not be finished. Sorry for inconvenience.

**Pull request closed without merging**
