### PR TITLE
fc-list: add page

### PR DESCRIPTION
**Pull request by mkoppmann**
Fixes issue #978. I know that the format is not the right one, but I wanted to use the same style as in fc-match and fc-pattern.

### CODE REVIEW

**Comment by waldyrious** [comment]
@mkoppmann thanks for the PR! the formatting is almost perfect, you just need to use {{snake_case}} for the token. Unless that is precisely what you meant by "the same style as in fc-match and fc-pattern"? Please confirm.

**Comment by mkoppmann** [comment]
@waldyrious Yes, that’s what I meant. [Here](https://github.com/tldr-pages/tldr/pull/811) is the closed PR for fc-pattern and you said “Usually the tokens are provided in snake_case, but in this case I suppose it's better to illustrate what kind of strings one might pass to the command.”

**Comment by waldyrious** [comment]
Thanks for the link, I didn't recall that :)

I wonder if we should provide a concrete example then, say "Times New Roman". That would make it clearer that the allowance was for the type of strings the command expects, rather than a possible overlook of the token syntax. What do you think

**Comment by mkoppmann** [comment]
You mean instead of {{Font name}}? So `fc-list | grep 'DejaVu Serif'`. I chose DejaVu Serif because on Linux it’s more likely to be installed. Should I change the examples in the other fc-*.md also?

**Comment by waldyrious** [comment]
Yeah, but keep the {{}} markers, since it's still a user-replaceable token -- it's just a specific rather than a generic one. And yes, if you could change the other fc-* pages, that'd be appreciated :)

**Comment by waldyrious** [comment]
Could you can change the other pages in this PR too?

**Comment by mkoppmann** [comment]
Hm? I changed fc-list, fc-match and fc-pattern. What other pages need to change? :)

**Comment by waldyrious** [comment]
The browser cache must have played a trick on me. Sorry about the confusion 😄 LGTM.

**Comment by agnivade** [comment]
:shipit:

**Pull request merged**
