### PR TITLE
*: always backquote `stdin`, `stdout` and `stderr`

### PR DESCRIPTION
**Pull request by pixelcmtd**
Kind of a "breakout issue" of #9578, because the kitchen sink approach only makes reviewing it take a lot longer. Also fixes file permissions, you're welcome.
By the way, if you are curious, I only needed to fix three things manually after doing this (every tool used except `-i` has a `tldr` page):

```sh
fd -t f . pages | xe -j100 -- -i {} sed 's/-std/---excapedsttd/g;s/`stdin`/stdin/g;s/`stdout`/stdout/g;s/`stderr`/stderr/g;s/stdout/`stdout`/g;s/stdin/`stdin`/g;s/stderr/`stderr`/g;s/---excapedsttd/-std/g'
```

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
I am a little bit confused by this command: `s/-std/---excapedsttd/g`. Why it is done?

**Comment by pixelcmtd** [comment]
> I am a little bit confused by this command: `s/-std/---excapedsttd/g`. Why it is done?

There are a lot of commands with flags like `--password-stdin`, `--stdin`, ... and I didn't feel like manually reverting 30 or so changes. `sttdin` is not matched by the regex `stdin`

**Review by EmilySeville7cfg — APPROVED** [review]

**Review by EmilySeville7cfg — APPROVED** [review]
- No issues found.
- Thanks for a contribution! ❤️ 🚀 😄

**Review by kbdharun — COMMENTED** [review]
I took a close look at it again, seems like the PR is GTG.

**Comment by EmilySeville7cfg** [comment]
> I took a close look at it again, seems like the PR is GTG. Can it be merged?

Yes, it can. If I encounter some conflicts I resolve them in my PR.

**Pull request merged**
