### PR TITLE
who: update deprecated command

### PR DESCRIPTION
**Pull request by vanvuvuong**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by acuteenvy — COMMENTED** [review]
`whoami` has its own separate page, because it's a different command. I think this example should be removed.

**Comment by spageektti** [comment]
We can note about `whoami` in a `See also` line.

**Review by spageektti — CHANGES_REQUESTED** [review]
Can you please make the changes @vanvuvuong ?

**Comment by vanvuvuong** [comment]
> Can you please make the changes @vanvuvuong ?

Sure, I just updated, please review those changes.
The other `See also` translations I copied from corresponding language page.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
