### PR TITLE
missing space between -p and {{password}}

### PR DESCRIPTION
**Pull request by vpilot**
Adding missing space between -p flag and {{password}}

### CODE REVIEW

**Comment by igorshubovych** [comment]
It is actually wrong according to documentation.
https://dev.mysql.com/doc/refman/5.5/en/mysql-command-options.html#option_mysql_password

I actually think it is good practice to use `--password`. And it is even better practice not to use passwords at all, because commands are stored in history.

**Comment by vpilot** [comment]
Well spotted. I 100% agree regarding --password.

**Comment by igorshubovych** [comment]
So I am closing this one.

Side note: please use feature branches for future.

**Comment by vpilot** [comment]
Hi Igor, I have merged changes that replaces -p with --password in both mysql.md and mysqldump.md in this ticket before it has been closed. I am quite new to Github pull request cycle, wasn't sure if it was the right way to address the issue. This is also relates to #434

**Comment by igorshubovych** [comment]
Sorry for that.

Could you please rebase your PR so it will have a single commit?
Also it is worth mentioning that password will be input from keyboard.

**Comment by igorshubovych** [comment]
Looks better now.

However you need to rebase and leave a single commit in PR. It is not good if we pollute the history.

Our current mysqldump page is not perfect. Your change is making it slightly better, but I would think about redoing it. Rule 4 of [Contributing Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) says that options should be introduced gradually.

So there can be
- backup example, no password
- restore example, no password
- restore example with password

Or something like that.

**Comment by vpilot** [comment]
Ok, taken on board. I am on it.
BTW option -p without a password also will prompt a user to enter one.

**Comment by igorshubovych** [comment]
Yes, so it can be '-p'.
My main argument against password was that it is a security bad practice to use passwords in commands.

**Comment by vpilot** [comment]
-p and --password are synonymous options and both will prompt a user to enter a password using keyboard, -p{{password}} would execute without prompt.

With mysqldump.md there is no much room for manoeuvre.  One addition I can make is to add a backup of multiple databases, using best practices as you mentioned.

What do you think?

**Comment by igorshubovych** [comment]
Let's squash the commits first. Can you please do it?

**Comment by vpilot** [comment]
I thought I have already sqashed my commits in ddf611f but it looks like it is not the case. I hope last commit fixes all commits. Please let me know if it is not what you wanted. It has been a bit of a learning curve, thanks for keeping up with me.

**Comment by igorshubovych** [comment]
Thank you! Congratulations with your first PR merged! Keep going!

**Pull request merged**
