### PR TITLE
echo, fdroid, fdroidcl, ffprobe, ffsend, fg, firefox, fortune, fuck, g++, gdb, gpg2, grep: Add german translation

### PR DESCRIPTION
**Pull request by marchersimon**

### CODE REVIEW

**Comment by navarroaxel** [comment]
:thinking: there are pages from #5286 here. if you need help cleaning the PR just say it.

**Comment by bl-ue** [comment]
That's because @marchersimon you created the `pr` branch while you were on the `master` branch, so the commits from `master` were copied over.  A quick and easy solution would be to close the PR, wait for #5286 to be merged, clean up your clone, and then make a new branch and a new version of this PR.  What do you think @marchersimon?

**Comment by marchersimon** [comment]
And once I thought I had done everything right... But alright, I'll close the PR

**Comment by bl-ue** [comment]
I'll send you instructions on how to cleanly open a new PR once we merge #5286.  By the way, nice job all of the translations! You're a machine! :smile:

**Comment by marchersimon** [comment]
Thank you. I just wanted to finally contribute to some projects and since I just know basic programming that's the only thing I'm left with.

**Comment by bl-ue** [comment]
@marchersimon did you ever get back to translating these pages?  There's a lot in there and it would be wonderful to have them.

**Comment by marchersimon** [comment]
@bl-ue I have not added anything new yet, but I'll make a PR with what I have now. 
Just out of interest: Are there many people using tldr pages in other languages than english? Because I'd think if you have to find out more about certain rare commands and are interested enough in Linux to find out about tldr, you'd have to deal with english anyway.

**Comment by bl-ue** [comment]
Of course, you're right.  I really don't know how many people use the other languages.  Clearly, not many, as shown at https://lukwebsforge.github.io/tldri18n/ 😄

**Comment by marchersimon** [comment]
That's a pretty nice table, I'd add that to CONTRIBUTING.md, since it gives a good overview, what still needs to be translated.
For myself, I'll probably focus more on creating new pages and improving existing ones.

**Comment by bl-ue** [comment]
>I'd add that to CONTRIBUTING.md, since it gives a good overview, what still needs to be translated.

Great idea! 🚀

**Pull request closed without merging**
