### PR TITLE
Added xinput command for Linux

### PR DESCRIPTION
**Pull request by jeanleonino**
The xinput utility is useful when you want to turn off a input device (laptop keyboard, for example).

### CODE REVIEW

**Comment by waldyrious** [comment]
"a utility to" is redundant and takes up valuable space :) I'd suggest removing it.

**Comment by igorshubovych** [comment]
Could you please squash the commits?

**Comment by jeanleonino** [comment]
@waldyrious well, other pages have that as well, so I put it because of that. 

@igorshubovych how?

**Comment by waldyrious** [comment]
@jeanleonino not all of them, IIRC, and those that do should eventually be cleaned up. In tldr land every character is precious :)

**Comment by ostera** [comment]
@jeanleonino: I concur with @waldyrious, also please rebase/squash and we can merge this

**Comment by igorshubovych** [comment]
@jeanleonino do you need help with squashing commits?

**Comment by igorshubovych** [comment]
Thank you for contribution!

**Pull request merged**
