### PR TITLE
git-stash: Add command to display changes in a stash

### PR DESCRIPTION
**Pull request by postrational**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by postrational** [comment]
Personally I use `tldr` to look for non-obvious command. I think that `stash show -p` is such a command, and I'd love to see it here.

How about combining `stash apply` and `stash pop` into one example? I added a commit with this approach.

**Comment by agnivade** [comment]
I think that is essentially trying to cram everything to fit the limit. It is indeed a challenge accomodating everyone's favorite option on a tldr page. That's why we only use the most common ones that someone will normally use in their day to day usage of the command.

A simple litmus test can be that among the 3 commands - stash apply, stash pop and stash show, which are the two you use most frequently. For me personally, it is only apply and pop. I don't need to actually see a stashed commit, because usually I know what is stashed by seeing the commit message.

**Review by einverne — COMMENTED** [review]
Thank you @postrational for this new patch. The command to show `changes in a stash` is useful. But I think the `git stash pop` command also important. It is hard to choose. I would like to keep the origin one.

**Comment by postrational** [comment]
Well, I never forget what `git stash apply` or `git stash pop` do, or how to use them. But I always forget the `-p` switch to `git show` and have to look it up. tldr seems like the perfect place to store this reminder.

**Review by agnivade — CHANGES_REQUESTED** [review]
> Well, I never forget what git stash apply or git stash pop do, or how to use them. But I always forget the -p switch to git show and have to look it up. tldr seems like the perfect place to store this reminder.

That's a fair point. But I think we are forgetting the viewpoint of beginners who have heard of "git stash" the first time and trying to understand what that command does. At a very basic level, tldr pages should contain the most used commands in day to day usage starting from the the simplest form to an advanced invocation. If there is still space left after that, we can accomodate other commands which aren't that easy to remember.

But from a priority viewpoint, `stash pop` is far more commonly used than `stash show -p`. Yes, it might be easy to remember, but that's only because you have learnt and used the command for so long that you don't have to think. But a tldr page is for all levels of people who might be trying to familiarize with the command for the first time. Thinking from that perspective, we should keep `stash pop` IMO.

Nevertheless, thank you for spending your time to send the change. Please do send PRs for any other page that you think needs improvement. :)

**Review by einverne — APPROVED** [review]
The new patch is the best solution, follow the guideline and introduce the new thing. Great thanks @postrational .

**Comment by postrational** [comment]
Is there any chance this PR will be merged?

**Comment by agnivade** [comment]
Hi @postrational - I have laid out my opinion about the PR above. However, it seems like others are in favor. So I think it should be good to merge.

**Comment by navarroaxel** [comment]
Yeah, it's a complex command but I think the changes are good. Looks like this is up to you @agnivade :grin:

**Comment by agnivade** [comment]
I still stand by my original opinion. It seems to go against the spirit of tldr pages to include a more complex command just because it's hard to remember, and exclude easy ones because they are simple.

**Pull request closed without merging**
