### PR TITLE
man: use long options in examples

### PR DESCRIPTION
**Pull request by nebulaa44**
- [ ] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by marchersimon** [comment]
@nebulaa44 I can't check right now, but I believe we kept the short options, because man on Windows doesn't support the long ones.

**Comment by EmilySeville7cfg** [comment]
@nebulaa44, please duplicate `man` tldr page to `linux/` and use long options. We already do like this.

**Comment by navarroaxel** [comment]
@marchersimon what do you think now?

**Review by EmilySeville7cfg — APPROVED** [review]

**Review by mfrw — APPROVED** [review]
LGTM :)
Thanks @nebulaa44

**Pull request merged**
