### PR TITLE
ollama: add page

### PR DESCRIPTION
**Pull request by Rolv-Apneseth**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** 0.1.10

Looking at the [GitHub page](https://github.com/jmorganca/ollama) this also runs on Mac, should I just clone the page into that folder or how do you handle these cases? It does not run on Windows yet.

I kept it to just five examples but can expand it to more if needed. For example, `ollama run {{model}}` is for running it in what I would call chat mode, but you can also just pass a single prompt with `ollama run {{model}} {{prompt}}`, should I include that?

### CODE REVIEW

**Comment by acuteenvy** [comment]
> Looking at the [GitHub page](https://github.com/jmorganca/ollama) this also runs on Mac, should I just clone the page into that folder or how do you handle these cases? It does not run on Windows yet.

The page should be in `common` if it works on more than one OS.

> I kept it to just five examples but can expand it to more if needed. For example, `ollama run {{model}}` is for running it in what I would call chat mode, but you can also just pass a single prompt with `ollama run {{model}} {{prompt}}`, should I include that?

Include whatever you think is the most useful. The limit is 8 examples per page.

**Comment by Rolv-Apneseth** [comment]
Ah apologies I assumed common was if it worked for all of them. I'll make those changes then.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by Rolv-Apneseth** [comment]
Thanks for maintaining this, it's very helpful.

**Review by Magrid0 — APPROVED** [review]
Looks good to me, thanks for your contribution!

**Review by gutjuri — APPROVED** [review]
Thanks for your contribution!

**Comment by Rolv-Apneseth** [comment]
It says there is a change requested but I already accepted the only change I saw from @sebastiaanspeck, am I missing something?

**Pull request merged**
