### PR TITLE
npm access: add page

### PR DESCRIPTION
**Pull request by bharateshwq**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by Magrid0 — COMMENTED** [review]
LGTM after the above suggestions

**Comment by bharateshwq** [comment]
Yeah sure I'm on it

**Comment by bharateshwq** [comment]
Hi @sebastiaanspeck ,
They have been fixed can you check them now

**Review by gutjuri — APPROVED** [review]
Thanks!

**Comment by bharateshwq** [comment]
Hey @gutjuri ,
do you guys have slack or any other discussion groups i had few suggestions to discuss on the implementation

**Review by nelsonfigueroa — APPROVED** [review]

**Review by acuteenvy — APPROVED** [review]

**Pull request merged**
