### PR TITLE
sed: adding remove trailing and leading whitespace commands

### PR DESCRIPTION
**Pull request by codydiehl**
Added removing leading and trailing whitespace [tabs, spaces] from end and beginning of lines.
useful for code cleanup.

----

- [ ] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by pxgamer** [comment]
Hi @codydiehl, thanks for the edits.

Personally I'd say these are already slightly covered by the other examples (find and replace in-place).

But I'll leave it for the others to decide. 👍

**Comment by agnivade** [comment]
Hey @codydiehl - thanks for the PR. This is just a specific case of the `-i` example already added. If we add this, we will be setting precedents for a lot of commands to have a generic example and then a specific example. Not sure if we want to do that.

**Comment by codydiehl** [comment]
Understood and reasonable. We can close this. 
I had mainly made the request to expand on some available regex type options available with sed. However that may not be fit for the sed tldr, and rather have better place in a regex specific entry.

**Comment by agnivade** [comment]
Thanks !

**Pull request closed without merging**
