### PR TITLE
rename pages.hbs to pages.sh

### PR DESCRIPTION
**Pull request by bl-ue**
See @vladimyr's message:
https://gitter.im/tldr-pages/tldr?at=60625b22cfd0b814ebac164d

### CODE REVIEW

**Comment by vladimyr** [comment]
Maybe we should symlink `hbs` to `sh` to stay on the safer side? 🤔

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
I don't think that's probably necessary:
1. There are only 10 pages being moved
2. In this projects symlinks are notorious (#787, https://github.com/tldr-pages/tldr/issues/5071#issuecomment-753565633)

**Comment by vladimyr** [comment]
Oh yeah, it is a cross-platform deal breaker. Obviously didn't give it enough thought. FWIW, I don't think anyone out there has their locale set to `hbs` so I guess we are fine.

BTW, thanks for picking it up I completely forgot to open an issue 🤦

**Comment by bl-ue** [comment]
Since we have the Gitter thread I didn't think an issue was necessary so I just PR'd it directly 👍🏻

**Comment by Lukasz-Pawski** [comment]
Unsubscribe

czw., 1 kwi 2021, 21:56 użytkownik Dario Vladović ***@***.***>
napisał:

**Comment by bl-ue** [comment]
@Lukasz-Pawski if you'd like to unsubscribe from all notifications in tldr-pages/tldr, you should [unwatch the repository](https://github.com/tldr-pages/tldr/watchers).

**Review by marchersimon — APPROVED** [review]

**Comment by marchersimon** [comment]
That should probably also updated in [set-more-info-link.py](https://github.com/tldr-pages/tldr/blob/master/scripts/set-more-info-link.py).

**Comment by bl-ue** [comment]
I totally remembered then I totally forgot! #5671

**Comment by sbrl** [comment]
For future reference, PRing directly from Gitter is fine for small changes. But for bigger ones, it's best to open a PR to discuss :slightly_smiling_face:

**Review by sbrl — APPROVED** [review]

**Comment by bl-ue** [comment]
~it's best to open a PR~ **it's best to open a issue**, right?

**Comment by bl-ue** [comment]
Now why did I open a separate PR for the `set-more-info-link.py` changes though this PR wasn't merged. 🤔

**Pull request merged**
