### PR TITLE
optipng: add page

### PR DESCRIPTION
**Pull request by oxguy3**
[OptiPNG](http://optipng.sourceforge.net/) is a popular PNG optimization tool.

I'm a bit curious what you guys think of the parenthetical notes for examples 2 and 3. They perhaps make the commands easier to understand, but they're also a bit clunky and I'm not entirely sure they're necessary. My hope is that someone is able to read those two examples, and easily deduce that there are also flags `-o1`, `-o2`, ... `-o6` for optimization in between the extremes of `-o0` and `-o7`.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
I recently merged `pigz` and fiddled a bit with it to my own liking:
```
  - Compress a file using the best compression method:
    pigz -9 filename

  - Compress a file using no compression and 4 processors:
    pigz -0 -p4 filename
```

I didn't put braces around the 0 and 9, but you could (or should). I don't require the parantheses describing how slower gets you better results, but I don't mind, either.

**Comment by oxguy3** [comment]
I like your "no compression" description -- that's pretty much what `-o0` does as well, so I'll change it to that. And if neither of us thinks the parentheses are necessary then I'm gonna drop 'em.

**Comment by rubenvereecken** [comment]
:+1: great :D

**Comment by igorshubovych** [comment]
LGTM! Thanks.

**Pull request merged**
