### PR TITLE
git-stash: add -p option

### PR DESCRIPTION
**Pull request by kalebo**
More people should know and use the patching mode for git commands

### CODE REVIEW

**Comment by kalebo** [comment]
I'm not sure why tldr-lint is throwing TLDR005 because both my commits have the description ending with a colon.

**Comment by waldyrious** [comment]
Hi, thanks for the PR! The linter can be cryptic at times, yeah. In this case I believe it's because there was a space after the colon. I took the liberty to fix it myself, to test the new PR collaboration features [announced by github recently](https://github.com/blog/2247-improving-collaboration-with-forks), hope you don't mind 😄

**Comment by waldyrious** [comment]
ps: great choice on the word to describe the -p option :)

**Comment by agnivade** [comment]
:+1:

**Pull request merged**
