### PR TITLE
cls: add Indonesian translation

### PR DESCRIPTION
**Pull request by mul14**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]
Remember that for translations you can send more than 1 translated page in 1 PR, just keep 1 commit per file and no more than 15 pages. This doesn't apply to the primary «English» pages.

**Review by sbrl — APPROVED** [review]
Thanks, @mul14!

Feel free to open 1 big PR if you're translating lots of pages, with 1 commit per page  :-)

**Comment by sbrl** [comment]
@navarroaxel: Not sure where the 15 page limit came from? I've seen PRs with 50+ and it's been fine...?

**Comment by navarroaxel** [comment]
@sbrl :joy: I can't mentally process so long PRs, the procrastination wins :disappointed:

**Comment by sbrl** [comment]
Ah, I see! I skim read them, and it usually turns out fine

Feel free to leave such PRs to other reviewers :-)

**Pull request merged**
