### PR TITLE
[numerous pages]: Fixed issue with clickable links in linux shells.

### PR DESCRIPTION
**Pull request by ScriptJunky**
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

This is what is being remediated;
Screenshot from 2023-10-02 10-20-33
Screenshot from 2023-10-02 10-32-35

- **Version of the command being documented (if known):**

Verified issue is present in zsh (w/ OMZ), and bash.

### CODE REVIEW

**Review by kbdharun — CHANGES_REQUESTED** [review]
@ScriptJunky Thanks for your contribution, unfortunately, this PR won't go through as this issue is client-specific and must be reported to the respective client you are using. Adding a period `.` behind links has been part of our style guide and client specification for a long time and any change to it would break pages in various clients.

**Comment by kbdharun** [comment]
> > Adding a period `.` behind links has been part of our style guide and client specification for a long time.
> 
> I tested 2 different shells. Same issue. I am more than happy to test more, and I believe it might be worth checking to see if others see the same, or somewhat similar behavior.

Can you let me know which client you are using?

I am an Oh my Zsh user myself and links in our clients work fine.

**Comment by ScriptJunky** [comment]
@kbdharun  I believe I found the issue. Are any of the folks in your team running KDE Plasma? `Konsole` captures the trailing dot, but `Gnome Terminal` does not (see screenshot);
Screenshot from 2023-10-02 11-18-29

**Comment by kbdharun** [comment]
> @kbdharun I believe I found the issue. Are any of the folks in your team running KDE Plasma? `Konsole` captures the trailing dot, but `Gnome Terminal` does not (see screenshot); Screenshot from 2023-10-02 11-18-29

I don't have Plasma but do have Konsole installed in Fedora, let me check if I can replicate the issue. Sorry for the delay, went for dinner.

**Pull request closed without merging**
