### PR TITLE
dunstctl: add page

### PR DESCRIPTION
**Pull request by ExperiBass**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by ExperiBass** [comment]
wait a sec whered all these come from? hold on a second...

**Comment by ExperiBass** [comment]
ok wait, i still quite havent figured out git, how do i fix this?

**Comment by navarroaxel** [comment]
> ok wait, i still quite havent figured out git, how do i fix this?

@ExperiBass  I think you should re-fork the repository, create a feature branch and then add your pages there.

**Comment by ExperiBass** [comment]
already did, was merged

**Pull request closed without merging**
