### PR TITLE
Add mdfind

### PR DESCRIPTION
**Pull request by greensn0w**

### CODE REVIEW

**Comment by waldyrious** [comment]
I think you need to use the `{{token}}` format (see CONTRIBUTING.md). Also, out of curiosity, what are the main differences between this tool and `find` or `locate`? If possible it would be good to at least hint at this difference in the description.

**Comment by lord63** [comment]
* why use `**`?
* also you may should update the index.json

**Comment by rprieto** [comment]
Other than the comments above, looks good :+1: `mdfind` seems to be an OSX-specific version of find (can find based on OSX attributes, etc).

**Comment by greensn0w** [comment]
@waldyrious: The main difference is, that it uses the spotlight index, so it's way faster than find.
@lord63: ** = bold

I will update index.json and mdfind.md in a few hours ;)
I'm currently at work.

**Comment by igorshubovych** [comment]
@greensn0w

I like your PR. Do you have any progress on it?
Just fix the md file, now there is no need to update index.json.

**Comment by greensn0w** [comment]
@igorshubovych Sorry for the long silence.
I updated `mdfind.md`. If there's anything more to fix, let me know.

**Comment by igorshubovych** [comment]
@greensn0w 

Thank you for a great contribution! Keep rocking!

**Pull request merged**
