### PR TITLE
Added example of overwriting an existing link

### PR DESCRIPTION
**Pull request by andreassimon**

### CODE REVIEW

**Comment by waldyrious** [comment]
@andreassimon can you clarify the usage of -T here? It seems to unnecessarily complicate the example (whose main purpose, if I understand correctly, is to demonstrate the use of -f). @rprieto I'd like to hear your opinion too.

**Comment by andreassimon** [comment]
without `-T`, the existing directory link is not overwritten, but a new link is created *inside* the linked directory.

**Comment by waldyrious** [comment]
Perhaps it would make sense to have first an example using a file, then one using a directory? Otherwise it may be confusing and unclear what -f and -T do. What do you think?

**Comment by andreassimon** [comment]
Feel free to submit it. :-)

**Comment by waldyrious** [comment]
sure, just wanted to know what you thought of it before :)

**Pull request merged**
