### PR TITLE
git diff: Add --staged option

### PR DESCRIPTION
**Pull request by eliotsykes**

### CODE REVIEW

**Comment by ostera** [comment]
:+1:

**Comment by igorshubovych** [comment]
What if we describe it a little bit more?
... staged (added to commit) files only

**Comment by eliotsykes** [comment]
How about something like:
```
- Show staged file changes. (Staged file changes are `git add`-ed but not yet committed).

`git diff --staged`
```

**Comment by igorshubovych** [comment]
Let's make it simple

~~~Markdown
- Show staged (added, but not committed) files changes only.

`git diff --staged`
~~~

**Comment by eliotsykes** [comment]
Is now a good time to squash + rebase?

**Comment by ostera** [comment]
Indeed it is @eliotsykes

**Comment by waldyrious** [comment]
Not just yet -- I suggest the following: "Show staged (added, but not **yet** committed) ~~files~~ changes only."

**Comment by eliotsykes** [comment]
Updated, squashed+rebased

**Comment by igorshubovych** [comment]
LGTM

**Pull request merged**
