### PR TITLE
package.json: update markdownlint-cli to v0.15.0

### PR DESCRIPTION
**Pull request by pxgamer**
As mentioned in #2960, this updates [`markdownlint-cli`](https://npm.im/markdownlint-cli) to `v0.15.0`.

The package now actually enforces the tests. The issue that arises from this is that there is a page [`pages/linux/whiptail.md:27`](https://github.com/pxgamer/tldr/blob/da2344c7a5e289b92aa3d767363bfba4afb67e67/pages/linux/whiptail.md) that has a line with **233** characters. Whereas we restrict pages to a max of **200** characters in our linting config.

This is mentioned in previous builds, but it won't be enforced when linting (the exit code is `0`). In the new versions, the exit code is `1`, so Travis CI fails to build.

To resolve this, we could cut down or remove the `Display a multiple-choice menu` example in `whiptail` (@sbrl?), or increase/remove the line length limit?

### CODE REVIEW

**Comment by pxgamer** [comment]
@sbrl, that seems like a nice tool. 👍 Just saying, the reason I mentioned you in the PR description was because you created the `whiptail` page that has the line limit. Any thoughts on the last paragraph?

**Comment by sbrl** [comment]
Ah, I didn't read the PR description properly and only looked at the dependency update :P

Erm unfortunately, `whiptail` is just a rather verbose command - and if we cut it down to under the 200 char limit we'd probably compromise readability.

Where did the 200 char limit come from, anyway? It seems kinda arbitrary.

**Comment by pxgamer** [comment]
Looks like it was added in 2016 ([`.markdownlintrc`](https://github.com/tldr-pages/tldr/blame/master/.markdownlintrc#L5)). But in the previous configs that it replaced, I can't find any references to a line limit other than [`markdown-style.rb`](https://github.com/tldr-pages/tldr/blob/5f6b09b04b4b3c871a0e5c49e1770b83d609f4f4/scripts/markdown-style.rb) which specifically excluded `MD013` completely.

**Comment by mebeim** [comment]
@pxgamer you know, I was taking a look at `markdownlint-cli` yesterday to try and figure out if it was actually configurable, and it's a shame that there's not an option to just print errors instead of returning `1`. I feel like PR should be made to `markdownlint-cli` to add such option. I would suggest appending a simple `|| true` in the lint command in the [`package.json`](https://github.com/tldr-pages/tldr/blob/master/package.json) to make it work like we'd like:

    "lint-markdown": "markdownlint pages/**/*.md || true",

**Comment by pxgamer** [comment]
I feel like that defeats the purpose of using the package, unless it was just used as a local command. :thinking: Perhaps it would be better to just set `MD013` to `false`. We do want to know if there are errors in markdown, so that we can update them when reviewing PRs. Otherwise the Travis build might succeed even if there are tabs or the wrong heading formatting (I'm not sure how much we check with `tldr-lint`).

**Comment by mebeim** [comment]
@pxgamer oh, I totally missed the fact that you could set a certain error to `false`. That's way better, I agree!

**Comment by pxgamer** [comment]
@agnivade, @waldyrious, @schneiderl and @sbrl.

What are your opinions on disabling the `MD013` (line-length) check?

**Comment by sbrl** [comment]
I'd agree that disabling it is probably the best option here.

**Comment by pxgamer** [comment]
Could anyone push a commit to disable that option for me? As I'm away from my PC this weekend. Or we can leave this until Monday when I'll be back. :+1:

**Comment by mebeim** [comment]
Done :+1: 

I also noticed only the english pages were being checked with the `test` or `lint-markdown` script and updated those two lines in the `package.json` as well.

**Comment by pxgamer** [comment]
Cheers @mebeim. I think this is ready to go. :thinking:

**Comment by agnivade** [comment]
Could we increase the limit to 250 ? I would feel safer if we had some limit instead of an unbounded line length.

**Comment by schneiderl** [comment]
> Could we increase the limit to 250 ? I would feel safer if we had some limit instead of an unbounded line length.

I personally think this is the best option here. So that if we face this same issue again in the future we discuss it deeply just to make sure it does make sense to have a page so big.

**Comment by mebeim** [comment]
Seems reasonable to me. I updated the linter config to 250 max length.

**Comment by waldyrious** [comment]
Sorry I couldn't comment earlier. Just for future reference, I personally feel it would be more to the spirit of tldr to keep limits (page size, line length, etc.) short, and find ways to work within them, even if that means compromising on accuracy. Even 200 characters feel excessive to me for a single line :(

**Comment by mebeim** [comment]
Well, I agree to some extent. I'd say limits are useful, but readability and usefulness of an example are to consider too. Most of the times an example can be rewritten to stay in the limits, or maybe even removed because it's too complicated, but I don't necessarily see exceptions like the one in `whiptail` as a problem.

**Pull request merged**
