### PR TITLE
git branch -a lists all branches

### PR DESCRIPTION
**Pull request by eliotsykes**

### CODE REVIEW

**Comment by igorshubovych** [comment]
I know about this command, but to me it is rather an edge case.

Do you really use it in action?

**Comment by eliotsykes** [comment]
> Do you really use it in action?

Yes, but less frequently than `git branch`.

I could remove `git branch -a` from the PR and leave the clarification about `git branch` listing local branches + highlights current branch.

**Comment by waldyrious** [comment]
I would prefer to merge this as-is; I think it's quite useful to clarify how to list both local and remote branches. Nice contribution @eliotsykes :+1:

**Comment by igorshubovych** [comment]
Agreed. LGTM

**Comment by felixonmars** [comment]
:+1:

**Comment by ostera** [comment]
:+1:

**Comment by igorshubovych** [comment]
LGTM as is

**Pull request merged**
