### PR TITLE
chsh: added list chells command

### PR DESCRIPTION
**Pull request by telmotrooper**
----

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by telmotrooper** [comment]
@slicer69 Could you paste what your `man chsh`outputs? On Arch Linux I can guarantee it works, but I haven't really tried it other distros.

For reference, my `man chsh` outputs:

```
CHSH(1)                                                           User Commands                                                           CHSH(1)

NAME
       chsh - change your login shell

SYNOPSIS
       chsh [-s shell] [-l] [-h] [-v] [username]

DESCRIPTION
       chsh is used to change your login shell.  If a shell is not given on the command line, chsh prompts for one.

       chsh supports non-local entries (kerberos, LDAP, etc.) if linked with libuser, otherwise use ypchsh, lchsh or any other implementation for
       non-local entries.

OPTIONS
       -s, --shell shell
              Specify your login shell.

       -l, --list-shells
              Print the list of shells listed in /etc/shells and exit.

       -h, --help
              Display help text and exit.

       -v, --version
              Display version information and exit.

VALID SHELLS
       chsh will accept the full pathname of any executable file on the system.  However, it will issue a warning if the shell is not  listed  in
       the  /etc/shells  file.  On the other hand, it can also be configured such that it will only accept shells listed in this file, unless you
       are root.

EXIT STATUS
       Returns 0 if operation was successful, 1 if operation failed or command syntax was not valid.

SEE ALSO
       login(1), login.defs(5), passwd(5), shells(5)

AUTHOR
       Salvatore Valente <svalente@mit.edu>

AVAILABILITY
       The chsh command is part of the util-linux package and is available from https://www.kernel.org/pub/linux/utils/util-linux/.

util-linux                                                          July 2014                                                             CHSH(1)

```

**Comment by agnivade** [comment]
Sorry, I had not tried the flag manually. Just tried in Ubuntu. The flag is not present.

**Comment by agnivade** [comment]
@telmotrooper - I have reverted the commit for now. If the flag is not present on Ubuntu, unfortunately we cannot add that in our linux folder too. If it is in osx though, we can add that in osx folder.

**Comment by telmotrooper** [comment]
@agnivade That's unfortunate, but I understand. I guess chsh, as part of util-linux, is not updated in Ubuntu, even though the man page was last updated in 2014...

**Pull request merged**
