### PR TITLE
tshark: add page

### PR DESCRIPTION
**Pull request by TerribleCodes**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented: TShark (Wireshark) 3.6.0**
#6863

### CODE REVIEW

**Comment by kbdharun** [comment]
@TerribleCodes Shouldn't the file name be tshark instead of wireshark?

**Review by kbdharun — COMMENTED** [review]
We have this page in tldr already. If you want to edit the [existing page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/tshark.md) feel free to do it in this PR.

**Comment by TerribleCodes** [comment]
> We have this page in tldr already. If you want to edit the [existing page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/tshark.md) feel free to do it in this PR.

@kbdharun 
Alright I'll try enhancing the existing file contents. Btw can you tick the Wireshark and Nmap in #6863 Because they already exist in tldr.

**Comment by kbdharun** [comment]
> > We have this page in tldr already. If you want to edit the [existing page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/tshark.md) feel free to do it in this PR.
> 
> @kbdharun Alright I'll try enhancing the existing file contents. Btw can you tick the Wireshark and Nmap in #6863 Because they already exist in tldr.

Done, Thanks for understanding

**Pull request closed without merging**
