### PR TITLE
COMMUNITY-ROLES: fix typo

### PR DESCRIPTION
**Pull request by marchersimon**
I fixed what I assume is a typo, since it doesn't really make sense otherwise.

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
"Past organization owners" is not a typo.  It was name the title of a section that was [removed](https://github.com/tldr-pages/tldr/pull/3006/files#diff-39da3bd6270d44ea37b6ed50bd42eeb9d93ac5e1639645871a69cbe08cbe29deL59) by @waldyrious in #3006.

In the past, all organization members _were_ owners.  There were no people who have climbed up to organization membership who did not stay long enough to become owners...

I suppose this is correct, but I'd like @waldyrious's opinion because he may have a better idea.

**Comment by marchersimon** [comment]
Oh, so the section title here (`Remove inactive orginazation members`) does not actually refer to members, but owners?

**Comment by bl-ue** [comment]
You know, it probably is for members, too, and that wasn't just updated.  I suppose it's fine to make this change.

**Review by bl-ue — APPROVED** [review]

**Review by nicokosi — APPROVED** [review]
👍

**Comment by waldyrious** [comment]
The removal process was not fully thought out at the time, actually. As @bl-ue said above, we had no instances of people who became inactive before becoming organization owners. I guess I should have drawn a full state transition diagram when writing these guidelines! 😄

If you guys don't mind, I'd ask you to hold off merging of this PR (and similar ones) for a couple weeks, when I'll be able to finally get to work on several other pending updates to the community roles guidelines documentation.

**Review by CleanMachine1 — APPROVED** [review]

**Review by patricedenis — APPROVED** [review]

**Comment by CleanMachine1** [comment]
@waldyrious just a little reminder.

**Review by nicokosi — APPROVED** [review]

**Review by owenvoke — APPROVED** [review]

**Comment by sbrl** [comment]
Ok, this has been sitting around since  May, so I'm going to merge it now. We can always redraft again in the future in a new PR.

**Pull request merged**
