### PR TITLE
docker-compose: run specifying a project name (#10596)

### PR DESCRIPTION
**Pull request by luisnquin**
Co-authored-by: Lucy Diniz <lucydiniz.rs@gmail.com>

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

I'll be happy to contribute more to this amazing project ^^

### CODE REVIEW

**Comment by luisnquin** [comment]
Sure, I'll merge my example with another

**Review by mfrw — APPROVED** [review]
LGTM :)
Thanks @luisnquin

**Comment by kbdharun** [comment]
@luisnquin Can you revert the change in other translations and only update the English page as we don't accept machine translations? 

> These pages can later be updated by respective native speakers.

**Comment by luisnquin** [comment]
@kbdharun it's fine if a just leave the **common** and **spanish** translations?

**Comment by kbdharun** [comment]
> @kbdharun it's fine if I leave the **common** and **spanish** translations?

Yep

**Comment by luisnquin** [comment]
It's done @kbdharun

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
