### PR TITLE
Update URL of Web Client

### PR DESCRIPTION
**Pull request by ostera**
Hey guys, I've rebuilt the web client in a nicer way, with nicer tools and a better design.

I've also hosted it elsewhere so it can use HTML5 PushState (now url's look like `tldr.ostera.io/linux/du` instead of the scrambled mess it was before).

Would be great to have it merged ASAP so I can get rid of the old one :)

### CODE REVIEW

**Comment by rubenvereecken** [comment]
Ooh pretty.

**Comment by rubenvereecken** [comment]
Was going to comment on Alfred Work flow change but seems you just moved it. Looks goodgood!

**Comment by waldyrious** [comment]
Btw, slightly off-topic: @rubenvereecken, @ostera and I have been having some issues with fixing stuff every now and then because we're not members of the tldr org. Think you could take care of that?

**Comment by waldyrious** [comment]
For future reference, after a brief discussion in Gitter (full disclosure: not in the public channel, although we've since decided to hold all project-related discussions in the project's public channel), @ostera and I have been made organization members on the same day (3 July).

**Pull request merged**
