### PR TITLE
sinfo: add link and improve examples

### PR DESCRIPTION
**Pull request by sbrl**
Behold! I now have access to my University's resident HPC (or, as I like to call it, supercomputer :D). It uses Slurm - so naturally I wrote a page on it. Checking though, it looks like we already have one - but since it uses the short-form options I thought I could do slightly better.

My University uses Slurm 15.08.8 for reference.

### CODE REVIEW

**Comment by ivanhercaz** [comment]
This is the first time I merged a PR in this repository and I would like to know if I did it fine and if it is totally agree with the maintainer's guide. I decided to make a "squash and merge" because it is a just one commit, but if this PR would have been several commits for the same command I should apply the same action, no? But if this PR would have been several commits, each one for a different page, I should apply "rebase and merge". Am I right?

**Comment by zdroid** [comment]
Yes, you did it all correctly. Rebase and merge cases are very rare, so if you are in doubt you can just squash and merge. They're supposed to be used with PRs labelled as `mass changes`.

**Comment by ivanhercaz** [comment]
Nice! So I understood it fine. Thank you @zdroid!

**Comment by agnivade** [comment]
Merge is disabled.

And for the other two, glad you asked, because we have it well documented- https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md#ii-handling-prs :)

Please go through all of the documentation and familiarize yourself. And feel free to ask for help in our gitter chat. Great to have you on the team !

**Pull request merged**
