### PR TITLE
Correct english in ssh page

### PR DESCRIPTION
**Pull request by sbrl**
I thought that the english on the SSH tldr page could be improved, so I'm making this pull request.

### CODE REVIEW

**Comment by felixonmars** [comment]
:+1: Thanks!

**Comment by waldyrious** [comment]
@rubenvereecken any chance the linter can look for verbs in the gerund (-ing) and present (-s) tense in the examples? They should all be in the infinitive tense.

**Comment by rubenvereecken** [comment]
While that would be possible, it would be naive and therefore never complete. A quick search got me `ping` and `ioping`. Every ping example has the verb `ping` in it. So unless we're doing a full language analysis, I wouldn't opt for this route.

**Comment by waldyrious** [comment]
I meant only in the first word of the line, and only of example descriptions. Wouldn't that be less error-prone?

**Comment by rubenvereecken** [comment]
Well it still fails with the `ping` example.

**Comment by waldyrious** [comment]
Anything else? We could only trigger if the word has more than one letter before -ing. We'll never have a perfect system anyway, as real data is messy, but if we can approximate it to an acceptable degree without too much complexity, it could be worth considering:

```
~/tldr$ ag "^\- [A-Z][a-z]{2,}ing " .
pages/common/alias.md
6:- Creating a generic alias:
18:- Turning rm an interative command:
22:- Overriding la as ls -a:

pages/common/gifsicle.md
5:- Making a GIF animation with gifsicle:
9:- Extracting frames from an animation:

pages/common/mysqldump.md
9:- Restoring a backup, user will be prompted for a password:

pages/common/ssh.md
6:- Connecting to a remote server:
10:- Connecting to a remote server with a specific identity (private key):
14:- Connecting to a remote server with specific port:

pages/common/sshfs.md
5:- Mounting remote directory:
9:- Unmounting remote directory:
13:- Mounting remote directory from server with specific port:

pages/common/sudo.md
5:- Listing of an unreadable directory:

pages/common/vim.md
17:- Exiting vim:

pages/common/vimtutor.md
9:- Exiting the tutor:

pages/linux/dd.md
13:- Generating a file of 100 random bytes by using kernel random driver:

pages/linux/xargs.md
9:- Handling whitespace in arguments:

pages/osx/dd.md
13:- Generating a file of 100 random bytes by using kernel random driver:
```

**Comment by waldyrious** [comment]
Also:

```
~/tldr$ ag "^\- [A-Z][a-z]+es " .
pages/common/mkdir.md
5:- Creates a directory in current folder or given path:
9:- Creates directories recursively (useful for creating nested dirs):

pages/common/redis-cli.md
18:- Executes Redis command:

pages/common/rmdir.md
5:- Removes directory, provided it is empty. Use `rm` to remove not empty directories:
9:- Removes directories recursively (useful for nested dirs):

pages/common/srm.md
6:- Removes a file after overwriting (single pass, 7 pass, 35 pass):

pages/osx/ditto.md
5:- Overwrites contents of destination folder with contents of source folder:
```

**Comment by rubenvereecken** [comment]
Alright I'm willing to give it a go. Thanks for convincing me with examples. Mostly it's because I see this pop up way too often lately. It'd actually be great to have a little section in `CONTRIBUTING.md` on English form. *hint hint*

**Comment by waldyrious** [comment]
Yes, I've been wanting to include them, but last time I proposed them nobody cared :'(

**Comment by rubenvereecken** [comment]
We're starting to feel the need.

**Comment by waldyrious** [comment]
I'll take care of it soon :+1:

**Comment by rubenvereecken** [comment]
Thanks for letting us hijack your PR @sbrl, you da man.

**Comment by sbrl** [comment]
@rubenvereecken No problem :wink:

**Pull request merged**
