### PR TITLE
lpr: add page-ranges example

### PR DESCRIPTION
**Pull request by aaaawwWWWwwwwWWW**
- [ ] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — CHANGES_REQUESTED** [review]
Hi @aaaawwWWWwwwwWWW, welcome and thanks for your submission. But our rule is up to 8 examples per page and this has 9 examples.

Which example do you think we can remove?

**Comment by aaaawwWWWwwwwWWW** [comment]
hi. it's hard to tell because i personally only use the first 2 examples in the page and the 2 examples i committed. The rest seems useful also; but the having 2 examples for printing in double sides seems unnecessary mostly taking into consideration their commands in the example are the same. So i think turning that into a single example?

**Comment by aaaawwWWWwwwwWWW** [comment]
or i actually could transform my example in a single example too as in

Print either a single page (2) or a range of pages (2-16):
`lpr -o page-ranges={{2|2-16}} {{path/to/file}}`

**Review by navarroaxel — APPROVED** [review]

**Comment by aaaawwWWWwwwwWWW** [comment]
oh i didn't saw you approved the changes and  made 2 other changes. that double-sided example was wrong so i fixed it and also turned it into a single example so another can be added in the future.

**Comment by navarroaxel** [comment]
@aaaawwWWWwwwwWWW Don't worry. I reviewed the new changes and I think your changes are good, I made the mistake to not re-count the example count.

**Review by sbrl — APPROVED** [review]
Thanks, @aaaawwWWWwwwwWWW!

**Pull request merged**
