### PR TITLE
*: fix typos

### PR DESCRIPTION
**Pull request by bl-ue**
Fixes typos.

### CODE REVIEW

**Review by sbrl — COMMENTED** [review]
Wow, that's a lot of typos - thanks so much @bl-ue!

Gosh, there's a typo in the title of the `thunderbird` page? How did we miss that one haha :joy: 

Any particular reason for closing this? I'd love to merge this.

**Comment by bl-ue** [comment]
Hi @sbrl, I closed it because I was working on a different PR but I've changed my mind since then.

I used [codespell](https://github.com/codespell-project/codespell) to find them.  That tool makes it very easy to find and correct common typos.

**Review by navarroaxel — APPROVED** [review]

**Review by Sosthene-Guedon — APPROVED** [review]

**Comment by bl-ue** [comment]
Thank you for the approval @Sosthene-Guedon! :)

**Comment by bl-ue** [comment]
cc @sbrl

**Review by sbrl — APPROVED** [review]
Thanks, @bl-ue!

Maybe you could write a page for codespell too? :P

**Comment by bl-ue** [comment]
@sbrl Great idea!!!  I can't believe there isn't already one!

**Pull request merged**
