### PR TITLE
fix: remove a typo in osx sed page

### PR DESCRIPTION
**Pull request by VEBERArnaud**
## Description

Remove in typo in the osx sed page

### CODE REVIEW

**Comment by waldyrious** [comment]
That's not a typo :) see #829 for references.

**Comment by VEBERArnaud** [comment]
Thanks for the references but it's not working for me

```sed -i 's/is/are/g' example.md``` ✅ is working
```sed -i'' 's/is/are/g' example.md``` ✅ is working
but
```sed -i '' 's/is/are/g' example.md``` ❌ is not working (The tldr osx sed page version)


```
❯ sed -i '' 's/is/are/g' example.md
sed: can't read s/is/are/g: No such file or directory
```

**Comment by ostera** [comment]
Hi @VEBERArnaud, are you using GNU sed or BSD sed?

BSD sed comes by default with OS X, and requires `-i ''`. But if you brew your coreutils, then you are using GNU sed, and thus don't require it.

**Comment by VEBERArnaud** [comment]
My bad, I'm using GNU sed 
If BSD sed is the default with OS X, then the actual sed page is fine for me 😌

**Comment by waldyrious** [comment]
If `i''` works in both BSD and GNU sed, maybe we can use that and merge the two examples back into the common directory :) @VEBERArnaud can you test that?

**Comment by VEBERArnaud** [comment]
```/usr/local/bin/sed``` <- GNU
```/usr/bin/sed``` <- BSD

```
❯ /usr/local/bin/sed -i'' 's/is/are/g' example.md

❯ /usr/bin/sed -i'' 's/is/are/g' example.md
sed: 1: "example.md": invalid command code e
```

Nope the ```i''``` is not working with BSD

**Comment by waldyrious** [comment]
Too bad. Thanks for confirming.

**Pull request closed without merging**
