### PR TITLE
Add Crystal client

### PR DESCRIPTION
**Pull request by porras**
Hi!

I learnt about TLDR a couple of days ago and I love it!

I built a simple client with Crystal, in case someone wants to give it a try. Find it here: https://github.com/porras/tlcr

### CODE REVIEW

**Comment by ostera** [comment]
Thanks! We'll try it out and get back to you :)

**Comment by igorshubovych** [comment]
Please write instructions for installation.
That's what I got trying install shards in brew:

```
Last 15 lines from /Users/igor/Library/Logs/Homebrew/shards/01.crystal:

    parse(ARGV) { |parser| yield parser }
    ^~~~~

in ./src/cli.cr:23: instantiating 'OptionParser:Class#parse!()'

    OptionParser.parse! do |opts|
                 ^~~~~~

in ./src/cli.cr:24: undefined method 'working_directory' for Dir:Class

      path = Dir.working_directory
                 ^~~~~~~~~~~~~~~~~



READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/manastech/crystal/issues
```

**Comment by rubenvereecken** [comment]
I guess I had my own issues, posted it at porras/tlcr#1

Other than that, I'm all for adding this one to the list. If you're serious about it, I'd also suggest adding options like the [node client](https://github.com/tldr-pages/tldr-node-client#usage) has, like rendering a local page. Good for devs.

**Comment by porras** [comment]
Hi and thanks for testing! I'm seeing building from source is trickier than I expected, or more sensitive to the environment. I'll close this PR and reopen it when I can provide a simpler installation method with binaries with brew and/or apt-get (I'm working on it but I'm a Crystal newbie and I've never done that before).

@rubenvereecken thanks for the suggestions, I'm planning to add that, and also the ability to download all the pages at once, instead of on demand (from the node client too).

And finally, also thanks for reporting the issues in my repo!

**Pull request closed without merging**
