### PR TITLE
clear: add Spanish translation

### PR DESCRIPTION
**Pull request by ivanhercaz**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

This PR translated `clear` page but from the updated version proposed in #3684.

### CODE REVIEW

**Comment by ivanhercaz** [comment]
Ups! Excuse me, I need to rework this PR due an error working with branches I used.

**Comment by zdroid** [comment]
You need to revert the first commit, since it'll make merge conflicts with #3684. I'd also wait with reviewing this until the other PR is resolved.

**Comment by ivanhercaz** [comment]
> You need to revert the first commit, since it'll make merge conflicts with #3684. I'd also wait with reviewing this until the other PR is resolved.

I have reverted the changes and just commit the Spanish translation. I will check your review in #3684 as soon as possible.

**Comment by sbrl** [comment]
I think it might be worth merging your other PR that adds the English improvements to the `clear` page before we merge this one.

**Comment by ivanhercaz** [comment]
> I think it might be worth merging your other PR that adds the English improvements to the `clear` page before we merge this one.

Of course! Because this one depends totally of #3684, due we are discussing the main content that I translated in this one. I am not hurry up so when the first one was solved, I will update this PR.

**Comment by ivanhercaz** [comment]
> Update the descriptions to agree with #3684.

I was doing it at the moment in which you send this message! What a coincidence! I updated the descriptions with 29b0d56 to agree with the current English version.

**Pull request merged**
