### PR TITLE
iconv: Convert Multiple Files

### PR DESCRIPTION
**Pull request by mehdi-farsi**
- [x] add an example to iconv section.

### CODE REVIEW

**Comment by igorshubovych** [comment]
What does this command really do?
Convert several input files into a single target file? How?

**Comment by mehdi-farsi** [comment]
Sorry for my lack of accuracy !

It permits to convert several input files into a single target file.

```shell
?> echo "lél" > lol && echo "cat" > cat
?> iconv -t ISO-8859-1 lol cat > lolcat
?> cat lolcat
l?lcat
?>
```

**Comment by igorshubovych** [comment]
The first rule of Contributing Guidelines says:

- Focus on the 5 or 6 **most common** usages

Being honest it is the first time I see `iconv` is used for concatenating files. Are you sure it is widely used? I am not totally against that, just curious.

It seems like this command can be simply exchanged by `iconv` and then `cat`, or vice-versa `cat` and then `iconv`

**Comment by mehdi-farsi** [comment]
You are right !

I had to use it in a particular case.

The files had to be converted in a specific format and then I concatenated the result in an output file.

But it's not a common use case ! :)

**Comment by igorshubovych** [comment]
I have closed it. It is good that we agreed on that.

Anyway thank you for your contributions and keep up the good work.

**Pull request closed without merging**
