### PR TITLE
Complete maintainers' guide

### LINKED ISSUE #1209: Write a maintainer's guide
We need to have a well-defined (public) procedure for handling PRs, since there's a chronic issue of a PR backlog we can't seem to get rid of entirely. It could be something like:

- PRs will be merged once they (1) pass the automated tests (Travis CI and CLA signing) without issues, (2) have the review comments addressed (3) get the thumbs-up of two maintainers -- the second one can do the merging immediately after accepting.
- If a week goes by after (1) and (2) are satisfied, but no second maintainer has manifested their approval, the first maintainer can merge.
- If a month goes by without reaction from the submitter (e.g. to fix lint errors or review comments), the PR should be taken over by a maintainer who should ensure that at least the page conforms to the contribution guidelines and passes Travis CI before merging.
  - Here, "taking over" means making any necessary changes, including rebase, reword of commit messages, and change of content, while preserving the authorship metadata (e.g. by amending commits rather than copy-pasting the content)

This should ensure we remain responsive to contributions, and that contributors have a clear notion of what to expect (and when to call out maintainers if they fail to adhere :P)

Any thoughts? Did I miss something?

### PR DESCRIPTION
**Pull request by waldyrious**
This PR completes the work initiated in #1839, and closes #1209. /cc @agnivade, @sbrl. I'd also love to get feedback from @jsonbruce and @pxgamer, who are our newest collaborators since #1885 :)

Note: I've split the commits into a logical progression, to make the changes easier to review.

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the reviews. Please don't merge yet, I will add the template messages as discussed in #1878.

**Comment by waldyrious** [comment]
**Update:** I started adding the template messages in `maintainers-guide.md`, but it ended up getting too long. I decided to take a different approach:
- reduced the scope of `GOVERNANCE.md` to cover only the community interaction guidelines;
- combined the second section of `GOVERNANCE.md` (about the _criteria_ for role transitions), the entire contents of `MAINTAINERS.md` (about the _performers_ of role transitions), and the new content including the template messages (about _procedures_ for role transitions) into a single file, `COMMUNITY-ROLES.md`.

This hopefully makes `GOVERNANCE.md` more compact and readable, and reduces fragmentation of the information about community roles, which was going to be split across 3 files.

In addition, I also removed the ambiguity regarding in the term "maintainer", which was used to mean both "repository collaborator with commit access" and "organization owner". It now means only the former.

Again, please review the commits individually to ensure each change makes sense in context.

**Comment by sbrl** [comment]
Looks ok to me! 👍  Curious as to why the contents of `MAINTAINERS.md` has been moved to the bottom of `COMMUNITY-ROLES.md`, though.

**Comment by waldyrious** [comment]
> Curious as to why the contents of MAINTAINERS.md has been moved to the bottom of COMMUNITY-ROLES.md, though.

No particular reason, I just thought it made sense to present the sequence in the "when --> how --> who" order.

But now that I think of it, I also like the fact that this order gives more prominence to the processes and guidelines, than to the people. I think that's important if we want a community that's encourages collaboration and is as self-managing as possible.

Besides, the part of the list that is useful for, say, third parties reaching out to the tldr-pages organization, is both linkable via its section header anchor, and equivalent to the listing at https://github.com/orgs/tldr-pages/people, which is public and easily accessible. So I don't see any downsides of that list being at the bottom of the file. Do let me know if you disagree with any of this, though.

**Comment by agnivade** [comment]
LGTM

**Comment by jsonbruce** [comment]
It's really a great job. Thanks~ @waldyrious

**Comment by waldyrious** [comment]
Great, thanks for the reviews guys :+1: I'll go ahead and merge this now, given the multiple approvals (and no objections).

Later on I will submit small changes as a separate PR, which are needed to account for the limitations I found while performing role changes at the organization level. More details in [this comment](https://github.com/tldr-pages/tldr/issues/1878#issuecomment-358610454).

**Pull request merged**
