### PR TITLE
zip: explain how to specify the compression level

### PR DESCRIPTION
**Pull request by andromedarabbit**
Title explains...

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @andromedarabbit - thanks for the PR ! We usually keep our first examples short and clean. In that vein, can you add the `-9` option to the 3rd example instead of the 1st ?

**Comment by andromedarabbit** [comment]
@agnivade Thanks for your guidance. I have made my changes as you suggest.

**Comment by agnivade** [comment]
@jeeftor - pls take a look. Btw I have also sent you an invite [link](https://github.com/tldr-pages/tldr/settings/collaboration) to get write privileges.

**Comment by andromedarabbit** [comment]
Any further news?

**Comment by agnivade** [comment]
Hey @andromedarabbit - sorry for the delay. I am actually waiting for @waldyrious' / @jeeftor's  approval on this.

**Comment by jeeftor** [comment]
And I took the day off yesterday from all technology

**Comment by andromedarabbit** [comment]
it was a pleasant experience.

**Pull request merged**
