### PR TITLE
z: reword descriptions for clarity

### PR DESCRIPTION
**Pull request by waldyrious**
I'm still unsure about the "foo" then "bar" example. Can you clarify how that works, @ranyitz?

Also, I think we should include at least one (specific) regex example. And what about wildcards such as `*`? Do those work, or is `*` always interpreted in the regex sense?

----

- [_] The page (if new), does not already exist in the repo.

- [_] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
> I'm still unsure about the "foo" then "bar" example. Can you clarify how that works, @ranyitz?

I think it will go to a path which contains "foo" before "bar". 

> Also, I think we should include at least one (specific) regex example.

Yes, agree.

**Comment by waldyrious** [comment]
>> I'm still unsure about the "foo" then "bar" example. Can you clarify how that works, @ranyitz?

> I think it will go to a path which contains "foo" before "bar".

So for example `path/to/foo/something-bar` would work, or would it have to be `path/to/foo/something/bar`, or something else?

**Comment by sbrl** [comment]
The order they are generally used is foo -> bar -> baz as far as I know

**Comment by sbrl** [comment]
Ping @agnivade. Are we ok to merge this, or are further changes required?

**Pull request merged**
