### PR TITLE
Update nmap.md

### PR DESCRIPTION
**Pull request by d33tah**
Actually I started writing and then found that there's already an Nmap page, but I think that my version is already some improvement. Blessed by Daniel Miller, the Nmap maintainer:

http://seclists.org/nmap-dev/2015/q4/294

### CODE REVIEW

**Comment by ostera** [comment]
@d33tah please rebase with latest master so we can merge this in :+1:

**Comment by d33tah** [comment]
@ostera: looks like it's done

**Comment by ostera** [comment]
@d33tah cool, let's wait till the check is completed and get it merged.

**Comment by waldyrious** [comment]
Note that there's already #435 so these two PRs should be coordinated

**Comment by d33tah** [comment]
@waldyrious: I suggest you discard this PR - `-F` is not a common option and for speeding up scanning, `-T4` will be more effective.

**Comment by d33tah** [comment]
@waldyrious: I merged master again, basically overwriting the file. I do not believe -F is a feature more important than the ones I listed and I understand that the six-option limit should not be exceeded.

**Comment by waldyrious** [comment]
@d33tah I'm sure we can sort it all out. Please excuse the issues we've been having, it's due to an inordinate amount of attention and contributions in a short time span. I'll let others who've actually used the command comment on the merits of which options to keep.

**Comment by d33tah** [comment]
Sure, thanks.

**Comment by prankymat** [comment]
@d33tah ```-T4``` is seemingly not as fast as ```-F``` since it still scans for all ports from ```1-65535``` vs only scanning the common ports with ```-F```.

**Comment by d33tah** [comment]
@prankymat: `-T4` does not change the list of ports scanned and by default Nmap scans 1000 ports. Try yourself:

```
$ nmap -T4 scanme.nmap.org

Starting Nmap 6.40 ( http://nmap.org ) at 2015-12-29 18:36 WAKT
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.035s latency).
Not shown: 992 closed ports
PORT      STATE    SERVICE
22/tcp    open     ssh
25/tcp    filtered smtp
80/tcp    open     http
135/tcp   filtered msrpc
139/tcp   filtered netbios-ssn
445/tcp   filtered microsoft-ds
9929/tcp  open     nping-echo
31337/tcp open     Elite

Nmap done: 1 IP address (1 host up) scanned in 3.79 seconds
```

You can see that "992 closed ports" ports means that in addition to the 8 ports listed, only 992 were scanned. That's not 65k.

**Comment by prankymat** [comment]
@d33tah thanks for clarifying that -T4 scans for 1000 ports instead of 65k ports! However I still believe ```-F``` is a faster mode for nmap.

Quoted from ```man nmap```
```
-F: Fast mode - Scan fewer ports than the default scan
```

```-F``` scans for around 100 ports which is significantly reduces the time when scanning a subnet.

**Comment by d33tah** [comment]
@prankymat: -T4 assumes a fast network connection - if it's not there, Nmap's congestion control system gets lost and actually ends up doing more work. With ubiquitous access to broadband Internet, I don't think that happens very often. Try this script on various shell servers:

```
#!/usr/bin/env python

import subprocess
import time
import sys

addarg = ' '.join(sys.argv[1:])
for arg in ['', '-T4', '-F']:
    t = 0
    for n in range(10):
        sys.stdout.write(".")
        sys.stdout.flush()
        cmd = "nmap %s %s" % (addarg, arg)
        started = time.time()
        subprocess.call("%s >/dev/null 2>&1" % cmd, shell=True)
        t += time.time() - started
    print("\r%0.2f\t%s" % (t/10.0, cmd))
```

Here are some example results - 100MBit internet connection, where -F is sometimes even slower:

```
(virtualenv)[ACL][13:37:50][/tmp]$ python timenmap.py scanme.nmap.org --unprivileged
5.20....nmap scanme.nmap.org --unprivileged 
5.12....nmap scanme.nmap.org --unprivileged -T4
5.79....nmap scanme.nmap.org --unprivileged -F
(virtualenv)[ACL][13:20:12][/tmp]$ python timenmap.py scanme.nmap.org --unprivileged
4.96....nmap scanme.nmap.org --unprivileged 
4.61....nmap scanme.nmap.org --unprivileged -T4
5.44....nmap scanme.nmap.org --unprivileged -F
(virtualenv)[ACL][13:23:53][/tmp]$ sudo python timenmap.py scanme.nmap.org --privileged
7.24....nmap scanme.nmap.org --privileged 
6.66....nmap scanme.nmap.org --privileged -T4
4.49....nmap scanme.nmap.org --privileged -F
(virtualenv)[ACL][13:33:58][/tmp]$ sudo python timenmap.py scanme.nmap.org --privileged
7.17....nmap scanme.nmap.org --privileged 
6.63....nmap scanme.nmap.org --privileged -T4
4.06....nmap scanme.nmap.org --privileged -F
```

Linode (this is the network scanme.nmap.org is in):

```
[10:53:48][~/workspace/nmap]$ sudo python /tmp/timenmap.py scanme.nmap.org --unprivileged
1.98....nmap scanme.nmap.org --unprivileged 
1.94....nmap scanme.nmap.org --unprivileged -T4
1.83....nmap scanme.nmap.org --unprivileged -F
[10:54:48][~/workspace/nmap]$ sudo python /tmp/timenmap.py scanme.nmap.org --unprivileged
1.99....nmap scanme.nmap.org --unprivileged 
1.94....nmap scanme.nmap.org --unprivileged -T4
1.80....nmap scanme.nmap.org --unprivileged -F
[10:55:49][~/workspace/nmap]$ sudo python /tmp/timenmap.py scanme.nmap.org --privileged  
2.18....nmap scanme.nmap.org --privileged 
2.11....nmap scanme.nmap.org --privileged -T4
1.94....nmap scanme.nmap.org --privileged -F
[10:57:51][~/workspace/nmap]$ sudo python /tmp/timenmap.py scanme.nmap.org --privileged
2.19....nmap scanme.nmap.org --privileged 
2.09....nmap scanme.nmap.org --privileged -T4
1.98....nmap scanme.nmap.org --privileged -F
```

Slow ADSL (not over wireless):

```
(virtualenv)[11:59:42][~]$[SUDO] python timenmap.py scanme.nmap.org --privileged  
5.25....nmap scanme.nmap.org --privileged 
4.35....nmap scanme.nmap.org --privileged -T4
1.98....nmap scanme.nmap.org --privileged -F
(virtualenv)[11:33:47][~]$[SUDO] python timenmap.py scanme.nmap.org --privileged
7.51....nmap scanme.nmap.org --privileged 
5.88....nmap scanme.nmap.org --privileged -T4
2.20....nmap scanme.nmap.org --privileged -F
(virtualenv)[11:36:29][~]$[SUDO] python timenmap.py scanme.nmap.org --unprivileged
15.61...nmap scanme.nmap.org --unprivileged 
12.45...nmap scanme.nmap.org --unprivileged -T4
2.79....nmap scanme.nmap.org --unprivileged -F
(virtualenv)[11:44:05][~]$[SUDO] python timenmap.py scanme.nmap.org --unprivileged
15.57...nmap scanme.nmap.org --unprivileged 
12.44...nmap scanme.nmap.org --unprivileged -T4
2.15....nmap scanme.nmap.org --unprivileged -F
```

It would be perfect if I didn't hammer scanme.nmap.org from multiple accounts at a time, but I was feeling a bit impatient. 

Keep in mind that -F gives 10x as little information, so I would expect a 10x speedup to justify using that. This is one of the reasons that believe that users should be taught -T4 instead of -F.

**Comment by dmiller-nmap** [comment]
I think `-T4` should be given here, because the goal is a tl;dr of Nmap's options, not "here's how to get the fastest scans." The `-F` option can be considered a special case of `-p`, which is already mentioned. Other than `-T4`, no other timing options are mentioned.

I would like to see `-sn` reinstated if it can be done within the constraints of the format.

Note that `-A` also enables NSE script scanning.

Minor grammar gripe: "Some features only activate when Nmap is **run** with privileges."

**Comment by d33tah** [comment]
@waldyrious: is it okay if I also add -sn or would I have to remove something to add it? If I have to, which option would you remove @dmiller-nmap?

**Comment by waldyrious** [comment]
@d33tah 6 examples (if I'm counting right) is quite acceptable. I just noted that there's a note at the end of the file, though -- could that be added to the main description, or even better, placed inline in the specific commands where it's needed?

**Comment by d33tah** [comment]
@waldyrious: better now?

**Comment by prankymat** [comment]
@d33tah :+1:  for the detailed explanation!!! Agreed with @dmiller-nmap mentioning the purpose of tldr. Big :+1: for the awesome community of tldr.

**Comment by waldyrious** [comment]
Looks great on my side, you guys are the experts :) I'll let another maintainer thumbs-up this and merge (@ostera?)

**Comment by igorshubovych** [comment]
Please squash the commits

**Comment by d33tah** [comment]
@igorshubovych done

**Pull request merged**
