### PR TITLE
Update docker description

### PR DESCRIPTION
**Pull request by lukeyeager**
That period just doesn't belong.
```
$ tldr docker
# docker                                                                                              
                                                                                                      
  Docker allows you to package an application with all of its.                                        
  Dependencies into a standardized unit for software development.
```

### CODE REVIEW

**Comment by igorshubovych** [comment]
I actually don't like this description at all. I mean I don't like both variants. IMO we should not try to explain what Docker is in this short description. Because it impossible, or possible but useless.

In my opinion it is better to say something like

```md
> Command line interface for managing Docker containers 
```

Or something like this.

**Comment by lukeyeager** [comment]
Sounds good to me. Updated.

**Comment by igorshubovych** [comment]
Put period (.) at the end.

Also Google suggests it should be "command-line" with dash, not "command line".

**Comment by waldyrious** [comment]
Thanks @lukeyeager for the attention to detail! But I'm afraid Igor's suggestion goes to the other extreme, to be redundant and not informative at all. How about something in the middle? Here's a suggestion:

> **docker**
> Command line interface for managing the deployment of applications inside standardized software containers

**Comment by waldyrious** [comment]
By the way, pinging @rubenvereecken because the awkward formatting was due to [#633](https://github.com/tldr-pages/tldr/pull/633/files#diff-35)

**Comment by igorshubovych** [comment]
@waldyrious 
I am briefly familiar with Docker, so please correct me if I am wrong.
Docker is a format of containers. There are other packagers/containers: Rocket (rkt), Odin and [others](https://en.wikipedia.org/wiki/Operating-system-level_virtualization). And `docker` is just a CLI to manage only Docker containers. Hence it is incorrect to say "applications inside standardized software containers". It is only about Docker containers.

https://en.wikipedia.org/wiki/Docker_(software)

**Comment by lukeyeager** [comment]
I'm happy to update the PR with whatever y'all decide. Also happy to let you close this PR and fix it in your own way if you like.

**Comment by waldyrious** [comment]
@igorshubovych good point. The Docker format is a standardized one, but it's better to be explicit to avoid ambiguity. I'd propose then changing "standardized" to "Docker":

> **docker**
> Command line interface for managing the deployment of applications inside Docker software containers

**Comment by igorshubovych** [comment]
I checked that `docker`’s help is even shorter:

> A self-sufficient runtime for containers.

So it would be weird if tldr’s version is longer than official help :)

To me, it should be something like

> Manage Docker containers and images

or just

> Manage Docker containers

**Comment by waldyrious** [comment]
I like "Manage Docker containers and images" :+1:

**Comment by lukeyeager** [comment]
> I like "Manage Docker containers and images"

Updated to this.

**Comment by igorshubovych** [comment]
Thanks!

**Pull request merged**
