### PR TITLE
couchdb: add page

### LINKED ISSUE #1175: page request: couchdb
This is the command that runs the server

https://linux.die.net/man/1/couchdb

### PR DESCRIPTION
**Pull request by lamar-frankie**
----

- [ x] The page (if new), does not already exist in the repo.

- [x ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ x] The page has 8 or fewer examples.

- [ x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines 

Closes #1175

### CODE REVIEW

**Comment by agnivade** [comment]
Some general comments before we dive in further.

- Start with the simplest invocation first. Just `couchdb`.
- The page seems too long. We should trim it down a bit, maybe up to 6 examples would be good.
- There should be a natural flow to the examples. Regarding the killing of background process, start with the `-b` option, which spawns a background process, then move on to `-k` which kills it, and then `-d`, which shuts it down.

In general, think about which options are not necessary, and which options are required for a beginner to get started. Accordingly update the page.

**Comment by lamar-frankie** [comment]
I simplified the page. I think all the commands that remain are pertinent.
Start couchdb
Launch shell
Start in the background
Kill
Shutdown

**Comment by agnivade** [comment]
@lamar-frankie - made a minor change. Let me know if this looks good to you.

**Comment by sbrl** [comment]
Looks good to me! Thanks, @lamar-frankie 😺

**Pull request merged**
