### PR TITLE
dotnet-restore: add Russian translation

### PR DESCRIPTION
**Pull request by Ryzhehvost**

### CODE REVIEW

**Review by Abrynos — APPROVED** [review]
I don't understand the language, but the format looks good

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
Welcome :wave: you can translate more than 1 page in the same PR.

**Review by sbrl — APPROVED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

Feel free to open 1 big PR if you're translating lots of pages, with 1 commit per page  :-)

**Comment by sbrl** [comment]
Thanks for the approval, @Abrynos! Once you have 5 non-trivial PRs merged, you're eligible to become a contributor according to our [community roles document](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) :-)

**Pull request merged**
