### PR TITLE
cups*: use OpenPrinting CUPS docs instead of Apple CUPS

### LINKED ISSUE #11845: OpenPrinting CUPS vs. Apple CUPS
According to the Apple CUPS GitHub repo:

> Note: Apple CUPS is the version of CUPS that is shipped with macOS and iOS. For the current version of CUPS that is used on other operating systems, see https://openprinting.github.io/cups for details.

Considering that CUPS is in the common directory, I think we should use the OpenPrinting documentation as a reference instead of Apple CUPS one and replace the links accordingly, using https://openprinting.github.io/cups/ instead of cups.org.

### PR DESCRIPTION
**Pull request by vitorhcl**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Fixes #11845.

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by isaacvicente — APPROVED** [review]
LGTM!

**Comment by isaacvicente** [comment]
@kbdharun Our pipeline checks for broken links? If not, this would be really great when updating links.

**Comment by kbdharun** [comment]
> @kbdharun Our pipeline checks for broken links? If not, this would be really great when updating links.

We do document a way to check for dead links in our Wiki. But we don't have it here as part of CI to not send multiple automated requests to smaller sites. So for PRs like this I would suggest manually checking the links.

**Pull request merged**
