### PR TITLE
print() is a function in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
----

- [ ] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, thanks for the PR @cclauss! Why did you close this? I don't see any issues with the PR itself.

If you need any assistance, please just ask :smiley_cat:

**Comment by agnivade** [comment]
OP also needs to change .travis.yml as this would fail if run under python2. I am not 100% sure though about travis python versions.

**Comment by cclauss** [comment]
Why would it break Python 2?

**Comment by sbrl** [comment]
Yep, it does! I'd approve this, but @cclauss closed it.

**Pull request closed without merging**
