### PR TITLE
rainbowstream: add page

### PR DESCRIPTION
**Pull request by jitakirin**
Ref #1162

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
Thanks for the contribution @jitakirin. The language and explanations need to be improved a bit. 

I haven't looked in-depth. But here are a couple of points which you might want to look at - 
1. The main heading seems to have been copied verbatim from the documentation page. Perhaps we can summarize that in a more clear fashion. We can also get rid of the ellipsis (...). It's an informal language use which we tend to avoid.
2. Please start the page with the normal command invocation `rainbowstream` and explain what it does.
3. Then move to explaining how to get into the interactive mode and the different commands in that mode.

Once these are taken care of, we can move to a more in-depth review.

**Comment by jitakirin** [comment]
Hi @agnivade, I based this on the page for [rtv](https://github.com/tldr-pages/tldr/blob/master/pages/common/rtv.md), you wouldn't have a better example (especially for an interactive app) so I can get a better idea of preferred language and style?

I'll get the points addressed anyway, thanks for the review 😃

**Comment by agnivade** [comment]
Yes, rtv seems to be as close to this I can find.

**Comment by sbrl** [comment]
The `alpine` and `ansible` pages might be worth a little look if you want more of an idea of the kind of style we go for :-)

**Comment by agnivade** [comment]
Yes, `alpine` works.

**Comment by jitakirin** [comment]
I tried to address all the points, please let me know if there are further improvements I can make.

**Comment by agnivade** [comment]
Sorry for the delay on this @jitakirin. I made some small changes. Its ready now.

**Comment by sbrl** [comment]
Thanks, @jitakirin! :smiley_cat: 

Just 2 more commands left in #1162 to go!

**Pull request merged**
