### PR TITLE
rolldice: add pt_BR translation

### PR DESCRIPTION
**Pull request by vappolinario**
- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by bl-ue** [comment]
Looks like you have unrelated commits from your previous PR @vappolinario.  Here's how to clean them up:
```
git remote add upstream https://github.com/tldr-pages/tldr.git
git fetch upstream master
git rebase upstream/master
git push --force
```

**Comment by marchersimon** [comment]
> just run the last 2 commands right before you create a new branch based off of `master`.

@bl-ue do you mean the 2nd and 3rd?

**Review by marchersimon — APPROVED** [review]

**Review by yutyo — APPROVED** [review]
LGTM

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
>@bl-ue do you mean the 2nd and 3rd?

No, I actually made a typo.  I meant the last 3 commands.

**Review by bl-ue — APPROVED** [review]

**Pull request merged**
