### PR TITLE
nano: started tldr for nano

### PR DESCRIPTION
**Pull request by jlems**
Starting up tldr for nano.

### CODE REVIEW

**Comment by ostera** [comment]
:+1:

**Comment by igorshubovych** [comment]
Finally an editor for humans.

But actually Ctrl+o writes it to disk: http://take.ms/0IHDU

Frankly speaking I don't think we should include key bindings on this page. Vi and Emacs pages need them, because there is no visual helper. Nano has it, so they are visible. I would rather add some command line options.

**Comment by jlems** [comment]
@igorshubovych 
That's a good point. I can update it with some command line options. 

Thanks!

**Comment by waldyrious** [comment]
I'd say we should still mention that the common commands are at the bottom of the screen. Btw if you want a CLI editor for *real* human beings, try [dit](https://github.com/hishamhm/dit), [sanos](http://www.jbox.dk/sanos/editor.htm) or [slap](https://github.com/slap-editor/slap) :smile:

**Comment by igorshubovych** [comment]
so what is the resolution here?

**Comment by waldyrious** [comment]
I propose mentioning in the main description that the commands commands are listed at the bottom of the screen.

**Comment by notpeter** [comment]
I don't think we should be mentioning any keys used in nano, nor that there's help at the bottom of the screen.  Nano devotes two whole lines of your display in-app to that at all times. I vote for keeping it short and sweet.

**Comment by 85pando** [comment]
Acttually @notpeter I thought so too, so i recommended nano to my non-cli accustomed friend for work on the server and he was not even able to save the file because he could not understand the message about which line endings to use (which i never consciously noticed).

So if someone looks for info I'd rather say there should be a comment here about this…

@waldyrious What about vim (yes, vim is usable and is therefore for _real humans_, some even say emacs is an editor…).

**Comment by waldyrious** [comment]
@85pando vim is only usable once you learn the basics (how to enter insert mode, how to exit). Before that it's [terrible UX](https://twitter.com/waldyrious/status/681839033245380608) IMO. Nano does way better than it, as do the editors I suggested above, except for more advanced stuff, obviously.

**Comment by rubenvereecken** [comment]
@85pando raises a valid point for a newbie that might `tldr nano` to figure out how to save files. But then again.. it's a text editor. Everyone should have _a_ text editor they can at least open and save files in (nano was my first). It's not quite up to us to teach someone how to approach whatever text editor. Just tldr.

**Comment by waldyrious** [comment]
Something simple like "Common commands are displayed in the bottom" seems mostly harmless IMO.

**Comment by ostera** [comment]
I think this is good as is. If we still feel we have to add common commands, we can revisit. Merging now.

**Comment by waldyrious** [comment]
Just for the record, I'm against cutting discussions off like this without consensus. No big deal, especially since the project does gain a new page which could remain in bikeshedding for a while, but I don't like the way this was resolved either. At least we could have agreed to disagree before a final decision was made.

**Comment by igorshubovych** [comment]
I agree with @waldyrious, let's in future wait till we have no disagreement.

**Pull request merged**
