### PR TITLE
Use markdown for salt, salt-run and zbarimg

### PR DESCRIPTION
**Pull request by lord63**

### CODE REVIEW

**Comment by waldyrious** [comment]
What's the motivation for the index.json change? Can you add it to the commit description above so that it's preserved in the commit log?

**Comment by lord63** [comment]
> What's the motivation for the index.json change?

Rebuild the index. Since those three file were not markdown files, they were not included before. This line said that:

    Dir["#{ENV["TLDRHOME"]}/pages/**/*.md"].each do |file|

> Can you add it to the commit description above so that it's preserved in the commit log?

Do you mean that add the reason why I change the `index.json`?

**Comment by waldyrious** [comment]
> Do you mean that add the reason why I change the index.json?

Yes, if it's relevant. I was particularly thrown off by the sorting change.

**Comment by lord63** [comment]
@waldyrious  I got this result by running `make index`. Actually, I'm also feeling a little puzzled.
ping @rprieto : need review. I'd like to send a PR to modify the ruby script if you think that we should sort the json by alphabetical.

**Comment by rprieto** [comment]
Thanks, the PR looks good to me!

We probably have to get used to `index.json` being updated, since it's a pre-commit hook. But big :+1: to making it stable if we can, alphabetical order sounds great!

**Comment by lord63** [comment]
@rprieto Hi, just creat a PR #296 to sort the json file. Please review.
You can merge that PR if it looks good to you, I'll update the index.json in this PR after PR 296 is merged.

**Comment by lord63** [comment]
ping @rprieto. Any concerns that not merge this PR? Let me know and I'll update it.

**Comment by rprieto** [comment]
Looks great, let's merge this when #296 is merged

**Comment by lord63** [comment]
The conflict has been fixed, should be good to go now.

**Comment by rprieto** [comment]
Looks great, thanks for all the work and patience :)

**Pull request merged**
