### PR TITLE
arp-scan: move to common platform

### PR DESCRIPTION
**Pull request by Fivro**
copied arp-scan command tldr file from  linux one written by Stig124

### CODE REVIEW

**Review by blueskyson — APPROVED** [review]
It looks good to me. Thanks for your contribution. Please sign the [https://cla-assistant.io/tldr-pages/tldr](https://cla-assistant.io/tldr-pages/tldr) to proceed CI.

**Comment by marchersimon** [comment]
If we have a command which is available on more than one platform, we put it into `common`. So we shouldn't create `osx/arp-scan`, but move `linux/arp-scan` to `common/arp-scan`.

**Comment by marchersimon** [comment]
> If we have a command which is available on more than one platform, we put it into `common`. So we shouldn't create `osx/arp-scan`, but move `linux/arp-scan` to `common/arp-scan`.

@Fivro would you like to do that? You could either do it in this PR or open a new one.

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
@Fivro Thanks for find this issue! I'll merge this.

**Pull request merged**
