### PR TITLE
groups: move to common

### PR DESCRIPTION
**Pull request by jonlabelle**
groups command is available in BSD flavors, not just Linux.

```
GROUPS(1)               FreeBSD General Commands Manual              GROUPS(1)

NAME
     groups - show group memberships

SYNOPSIS
     groups [user]

DESCRIPTION
     The groups utility has been obsoleted by the id(1) utility, and is
     equivalent to "id -Gn [user]".  The command "id -p" is suggested for
     normal interactive use.

     The groups utility displays the groups to which you (or the optionally
     specified user) belong.

EXIT STATUS
     The groups utility exits 0 on success, and >0 if an error occurs.

SEE ALSO
     id(1)

FreeBSD 11.2-RELEASE-p4          June 6, 1993          FreeBSD 11.2-RELEASE-p4
```

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by pxgamer** [comment]
Linux also covers Windows. I'm not sure `groups` works correctly in Windows (even in LSFW?) but I'll have a look.

**Comment by jonlabelle** [comment]
hmmm.... you mentioned *Linux also covers Windows*... but why is there a [windows](https://github.com/tldr-pages/tldr/tree/master/pages/windows) and [linux](https://github.com/tldr-pages/tldr/tree/master/pages/linux) category?

**Comment by pxgamer** [comment]
Sorry, I meant to say that `common` covers Windows. 🤦‍♂️ Long night. I've updated my comment.

**Comment by jonlabelle** [comment]
@pxgamer To answer your question if `groups` if available in the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), it indeed is...

wsl_groups_screenshot

**Comment by sbrl** [comment]
Perhaps we could move ncat in #2415?

**Pull request merged**
