### PR TITLE
shopt: add page

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by agnivade** [comment]
LGTM. :+1:

**Comment by waldyrious** [comment]
Thanks for the review @agnivade. We can't merge this yet, however, or we'll have the same problem as when #1030 was merged... We *could* edit the [linter](https://github.com/tldr-pages/tldr-lint), but I'm not sure I understand the syntax it uses. I [made a small change](https://github.com/tldr-pages/tldr-lint/pull/6/files) attempting to fix #1030, but it may not be correct.

**Comment by agnivade** [comment]
Got it. /cc @rubenvereecken.

**Comment by waldyrious** [comment]
@agnivade I've tried to understand [the code in the linter that's producing the error](https://github.com/tldr-pages/tldr-lint/blob/master/tldr.l#L92-L95), but I'm still puzzled. Can you make sense of it? The non-alphanumeric and non-space characters in the main description are:

    :(`$`).
    (`$`)``.

respectively.

/ping @rubenvereecken

**Comment by agnivade** [comment]
The error says descriptions should end in a period. But L4 **does** end in a period. Is this a bug in the linter side or in the page ?

**Comment by waldyrious** [comment]
I'm pretty sure it's a bug in the linter, but I can't understand the code well enough to pinpoint it :(

**Comment by agnivade** [comment]
Found the issue ! Your second line has trailing spaces. :) I am planning to do some work in the linter to give better error messages.

**Comment by waldyrious** [comment]
Ok, given your previous LGTM, I'll approve as well and merge. 👍

**Comment by waldyrious** [comment]
I was puzzled for a moment there with the Travis failure in the "push" test. Turns out it's #1030 saying hi. I'll rebase the branch, that should fix it.

**Comment by waldyrious** [comment]
All right! we're set to go :)

**Pull request merged**
