### PR TITLE
Add cordova

### PR DESCRIPTION
**Pull request by lagelalegal**

### CODE REVIEW

**Comment by igorshubovych** [comment]
Please remove index.json.

Also please read [Contributing Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md). The page you created does not follow them.

**Comment by lagelalegal** [comment]
OK, I will improve it.

**Comment by rprieto** [comment]
Thanks a lot for contributing! I think the 3 main things that need improvements are:
- have 1 command per description
- keep only the most-used commands (e.g .how common is `--link-to`?)
- we avoid catch-alls like `[--device|--emulator|--target=Foo]` to focus on actual working examples, like only specifying `--device` or `--emulator`

**Comment by lagelalegal** [comment]
@rprieto  Thank you very much, I got it.

**Comment by waldyrious** [comment]
Those are waaay to many examples! Much appreciated, but not really in the spirit of tldr :)

Can you reduce them to the 5-6 most common uses of the command?

**Comment by lagelalegal** [comment]
@waldyrious I'm sorry, I want to create a detailed command description. Just like you said, I will be reduced to some common cases.

**Comment by igorshubovych** [comment]
@lagelalegal thank for your contribution! Keep going!
Please next time - squash the commits!

**Comment by lagelalegal** [comment]
@igorshubovych thank for your suggestion.

**Pull request merged**
