### PR TITLE
pages.th/*: fix more information label

### PR DESCRIPTION
**Pull request by kbdharun**
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Reference PR's: #8568 , #8580.

## Changes:

- Updated `More information:` keywords across all `pages.th` to a single uniform keyword `ข้อมูลเพิ่มเติม:`. 
- Note: This PR only updates the `More information:` keyword and not the pages contents.

### CODE REVIEW

**Comment by kbdharun** [comment]
@Leomotors @MasterIceZ ; Can you check the changes?

**Review by Leomotors — APPROVED** [review]
👍

**Review by MasterIceZ — APPROVED** [review]
LGTM! 👍🏻

**Review by MasterIceZ — APPROVED** [review]
👍🏻

**Comment by kbdharun** [comment]
Thanks for the reviews

**Review by blueskyson — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
