### PR TITLE
Translate git commands to Italian - part 2 (revived)

### PR DESCRIPTION
**Pull request by mebeim**
Just a copy of #3339, with my suggested changes applied. Unfortunately I was not able to apply changes on the PR itself, and since it's been sitting there for quite some time, I closed it to open this one. All commits also have @glenacota as author.

Just count my "auto-approve" on this since the PR is basically not mine.

### CODE REVIEW

**Comment by ivanhercaz** [comment]
I labeled this PR as `page edit` because there are commits with changes in pages that already exist. I think the `mass changes` label i self-explanatory.

**Comment by zdroid** [comment]
Grazie mille @mebeim

**Comment by mebeim** [comment]
@ivanhercaz we use the mass changes label when the PR edits a significant number of pages, this is not the case though. I know an addition of several translation is technically speaking is a mass change, but it's not necessary to label it as such.

**Comment by zdroid** [comment]
Judging by the past use of the label, it seems we use it for both purposes.

**Comment by mebeim** [comment]
@zdroid there are some PRs in which this is applied for the same reason I explained above, which is the translation of multiple pages, but I would really try to avoid it. Labels are meant to make searching easier, this only confuses things as translations are not a "mass change" of existing content.

**Comment by waldyrious** [comment]
@mebeim just to be clear, mass-change PRs are not intended for any regular page edits that happen to be done all at once — for those, we'd prefer separate PRs. The typical use case is for edits that apply across multiple pages but are closely related to each other, such as a typo fix or a formatting change, but also adding multiple pages from the same source (#702 comes to mind). In that regard, touching multiple pages as part of a translation round sounds like a valid use case for the label.

Perhaps the word "mass" is too loaded for the actual meaning of the tag; maybe "bulk changes" would work better? Or is your concern about the "change" as opposed to "addition"? In that case, we could go for the more explicit "multiple pages". Let me know what you think!

/cc @ivanhercaz, due to [this comment](https://github.com/tldr-pages/tldr/pull/3727#issuecomment-573467508).

**Pull request merged**
