### PR TITLE
gh-formatting: add page

### PR DESCRIPTION
**Pull request by navarroaxel**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by marchersimon** [comment]
What about `--json`, `-jq` or `--template`?

**Comment by navarroaxel** [comment]
> What about `--json`, `-jq` or `--template`?

@marchersimon what are you suggesting? :thinking:

**Comment by marchersimon** [comment]
```
- List all available JSON fields

`gh formatting --json`
```
For `--jq`, I'd just use some query syntax, but I don't know what that is and I don't know what this command does.
Same for `--template`. I don't understand the command well enough to document it.
But a page with one example is better than no page, so you don't have to add anything.

**Comment by navarroaxel** [comment]
@marchersimon But `--jq` and `--json` should be used in the target command, not in this subcommand. `gh formatting` is only a help page.

You can use:
```
gh pr view 6290 --json
gh pr view 6290 --jq
```
etc

**Comment by marchersimon** [comment]
Hm, the GitHub docs for this command are a little confusing.

**Review by marchersimon — APPROVED** [review]
Thanks 👍🏽

**Review by CleanMachine1 — APPROVED** [review]
Mobile GH is annoying!

**Pull request merged**
