### PR TITLE
tldr: update link

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by Waples** [comment]
I don't see any reason for this change, care to explain @sebastiaanspeck ?
Also pulling in @navarroaxel @bl-ue

**Comment by acuteenvy** [comment]
Since this page documents command-line usage of clients, I thought linking to the client spec would be better.

**Comment by kbdharun** [comment]
@Waples I would like to request you to see the changes to the style guide/client specification, etc before commenting as you haven't been active for a while and a lot has been going on (are you still using the same Gitter ID if so I would be happy to give you updates in our chatroom).

We have changed the suggestion from linking to the authors site to the command line reference or the man page in our style guide and this change reflects it. And also navarooaxel and bl-ue aren't active anymore.

While navarroaxel is still present, he isn't aware of the change.

**Comment by Waples** [comment]
@kbdharun ahaa I missed that change indeed.. I also didn't know Blue and Navo weren't involved anymore due to my absence.

**Pull request merged**
