### PR TITLE
vlc: use official wiki as link

### LINKED ISSUE #6569: vlc: link to more useful information
Currently, the tldr page for `vlc` links to its [homepage](https://www.videolan.org/vlc/), which does not provide much useful information for someone wanting to learn more about the command. The homepage only advertises its features and links to downloads.

I suggest that we instead link to `vlc`'s [documentation homepage](https://wiki.videolan.org/Documentation:Documentation/) or its [documentation page for the CLI](https://wiki.videolan.org/Documentation:Command_line/).

### PR DESCRIPTION
**Pull request by tactlessfish**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

This PR improves the vlc link, as discussed in #6569.

Close #6569

### CODE REVIEW

**Comment by tactlessfish** [comment]
Ah, sorry I forgot about the preferred commit message format. Is there a way to redo the commit message?

**Comment by navarroaxel** [comment]
> Ah, sorry I forgot about the preferred commit message format. Is there a way to redo the commit message?

@tactlessfish it's ok, we normalize that when we merge.

**Review by nicokosi — APPROVED** [review]
👌

**Review by pixelcmtd — APPROVED** [review]
I can see that.

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
