### PR TITLE
chkdsk, cls, dir, del: add Italian translation

### PR DESCRIPTION
**Pull request by Magrid0**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution, seems like you are creating new branches in your fork keeping your existing branch as the base, in the future I would suggest using `tldr-pages:main` as the base branch. I have closed your other recursive PRs. Upon, merge we will rebase and merge this PR to keep your 4 commits intact.

**Comment by Magrid0** [comment]
> Thanks for your contribution, seems like you are creating new branches in your fork keeping your existing branch as the base, in the future I would suggest using `tldr-pages:main` as the base branch. 

hi, thanks for your suggestions, I'm brand new to git so I don't fully understand everything, I'm using the main branch of my fork, shouldn't I do it?

**Comment by kbdharun** [comment]
> > Thanks for your contribution, seems like you are creating new branches in your fork keeping your existing branch as the base, in the future I would suggest using `tldr-pages:main` as the base branch. 
> 
> hi, thanks for your suggestions, I'm brand new to git so I don't fully understand everything, I'm using the main branch of my fork, shouldn't I do it?

Yes, when creating a new branch you need to select the source repository's  primary branch (main here). The later that you now use will be useful for some repositories for testing changes or working on top of a branch.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by blueskyson — APPROVED** [review]

**Pull request merged**
