### PR TITLE
Moved scripts from linux/osx into common

### PR DESCRIPTION
**Pull request by Parth-Mehrotra**

### CODE REVIEW

**Comment by Parth-Mehrotra** [comment]
Moved
+ dd.md
+ head.md

**Comment by igorshubovych** [comment]
`top` has different options on OSX and Linux.
`base64` has different options on OSX and Linux.
`netstat` has different options on OSX and Linux.
`wall ` has different options on OSX and Linux.

Cannot be merged.

**Comment by Parth-Mehrotra** [comment]
Okay, will remove those, keeping `dd` and `head`, what about:
+ `du`? It seems to match

**Comment by Parth-Mehrotra** [comment]
Okay @igorshubovych, removed those that are different and kept `dd` and `head`

Moved
+ dd.md
+ head.md
+ ~~wall.md~~
+ ~~top.md~~
+ ~~base64.md~~
+ ~~netstat.md~~

**Comment by igorshubovych** [comment]
`head` has different options in OSX and Linux. There are 2 different pages in OSX and Linux folders.
`dd` has slight differences.

@Parth-Mehrotra 
Do you test commands before doing anything?
What was the purpose of this PR?

Also check what your PR is actually doing. It removes `top`, `dd` and `netstat` commands.

**Comment by Parth-Mehrotra** [comment]
I'm going to start a fresh pull request, and correct a bunch of my mistakes @igorshubovych

**Pull request closed without merging**
