### PR TITLE
zoxide: add zi command usage

### PR DESCRIPTION
**Pull request by abuturabofficial**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by vitorhcl — CHANGES_REQUESTED** [review]
Hi, thanks for bringing up this command and this example!

Each page documents a single command, so could please create a new page for `zi`? We can still recommend it in this page using a "See also" after the description and before the "More information" link:
```md
> See also: `zi` for a interactive selection menu.
```

**Comment by abuturabofficial** [comment]
> Hi, thanks for bringing up this command and this example!
> 
> Each page documents a single command, so could please create a new page for `zi`? We can still recommend it in this page using a "See also" after the description and before the "More information" link:
> 
> ```
> > See also: `zi` for a interactive selection menu.
> ```

I will do it tomorrow morning.

**Comment by abuturabofficial** [comment]
> > Hi, thanks for bringing up this command and this example!
> > Each page documents a single command, so could please create a new page for `zi`? We can still recommend it in this page using a "See also" after the description and before the "More information" link:
> > ```
> > > See also: `zi` for a interactive selection menu.
> > ```
> 
> I can do it, but does it make sense to separate as it's literally just the single command other than usual ones!

Don't consider this separate command from usual `z`, and there is no other functionality of the zoxide related `zi`. I'm new to the PR thingy, so don't know how hard the requirements are for project.

But literally this is the only thing, missing in `zoxide page`, so I'm requesting a review again. If the maintainers insist I'll create a separate page for it.

**Comment by vitorhcl** [comment]
> > I can do it, but does it make sense to separate as it's literally just the single command other than usual ones!
> 
> Don't consider this separate command from usual `z`, and there is no other functionality of the zoxide related `zi`.

I see some pros and cons for each approach.

## Approach 1: Separate pages for each command
The style of the tldr pages, for consistency and no controversy, is each page documenting a single command (or even a specific subcommand).

This, combined with the "See also" suggestion, gives us some benefits:
- It is easy to notice the "See also" at the start of the page, specially when it has a description, so we don't need to worry about the user not discovering the command.
- A separate description for each command (I know they are very similar, but `zi`, at least by default, shows an interactive menu, but `z` doesn't). This brings for the page description: 
    - Preciseness (documents exactly what the command does, and not what "another" command does)
    - Conciseness (focuses on what a single command does)
    - As a result of the above, a much clearer, less confusing description, particularly for those who don't know the command(s) usage.
- When you use a client, you probably want either to know the usage of one command or another; in this case, you either run `tldr z` or `tldr zi`. However, the user will still see that the other command exist by seeing the "See also"
- We can have tailored examples for each command. As a theoric example, we could have:
    - Both basic usages for `zi` and examples with some sort of program that modifies the `fzf` menu
    - Both basic `z` usages and advanced usages with integrations with programs that benefit from simple output, like `grep`
- We have a hard limit of 8 examples for each page, which forces us to write the best examples. In this case:
    - Moving `zi` to another page, we have one more space for a `z` page, specially if `z` gains more option

## Approach 2: Single page for 2 commands

I know the options of `z` and `zi` are the same, but IMO the only advantage of keeping them in the same page is having both `z` and `zi` examples in the same page.

Actually, it's less probable the user will see `zi` if it is at the end of the page.

## Conclusion and different opinions

In my opinion, after this analysis it's much better to always document a single command per page.

@kbdharun @sebastiaanspeck any opinions?

After all, our guidelines aren't strict rules, if you can think of any advantages of a single pages that outweight the advantages of spliting the pages, we will be glad to hear you, @abuturabofficial :)

If we think your points make sense, we are completely open to open an exception in our guidelines.

**Comment by abuturabofficial** [comment]
> I see some pros and cons for each approach.
> 
> ## Approach 1: Separate pages for each command
> The style of the tldr pages, for consistency and no controversy, is each page documenting a single command (or even a specific subcommand).
> 
> This, combined with the "See also" suggestion, gives us some benefits:
> 
> * Easy to notice: It is easy to notice the "See also" at the start of the page, specially when it has a description, so we don't need to worry about the user not discovering the command.
> * Better page descriptions: A separate description for each command (I know they are very similar, but `zi`, at least by default, shows an interactive menu, but `z` doesn't). This brings for the page description:
>   
>   * Preciseness (documents exactly what the command does, and not what "another" command does)
>   * Conciseness (focuses on what a single command does)
>   * As a result of the above, a much clearer, less confusing description, particularly for those who don't know the command(s) usage.
> * Better client experience: When you use a client, you probably want either to know the usage of one command or another; in this case, you either run `tldr z` or `tldr zi`. However, the user will still see that the other command exist by seeing the "See also"
> * Specific examples: We can have tailored examples for each command. As a theoric example, we could have:
>   
>   * Both basic usages for `zi` and examples with some sort of program that modifies the `fzf` menu
>   * Both basic `z` usages and advanced usages with integrations with programs that benefit from simple output, like `grep`
> * Example limit: We have a hard limit of 8 examples for each page, which forces us to write the best examples. In this case:
>   
>   * Moving `zi` to another page, we have one more space for a `z` page, specially if `z` gains more option
> 
> ## Approach 2: Single page for 2 commands
> I know the options of `z` and `zi` are the same, but IMO the only advantage of keeping them in the same page is having both `z` and `zi` examples in the same page.
> 
> Actually, it's less probable the user will see `zi` if it is at the end of the page.
> 
> ## Conclusion and different opinions
> In my opinion, after this analysis it's much better to always document a single command per page.
> 
> @kbdharun @sebastiaanspeck any opinions?
> 
> After all, our guidelines aren't strict rules, if you can think of any advantages of a single pages that outweight the advantages of spliting the pages, we will be glad to hear you, @abuturabofficial :)
> 
> If we think your points make sense, we are completely open to open an exception in our guidelines.

Makes sense, I'll create a new page for `zi` then.

**Comment by abuturabofficial** [comment]
I just realized something. `Zoxide` is rust rewrite of the original `z` project, and both are not even command to command compatible. Most of the options for `z` have no use in `zoxide`.

Original: <https://github.com/rupa/z>
Rust rewrite (More popular): <https://github.com/ajeetdsouza/zoxide>

The page for `zoxide` do exist, but it seems to be not updated as the commands have been more simplified now. So, I might open a new PR for `zoxide` to first simplify the listing.

But it will be definitely more confusing as now both support simple usage of `z` command, and till now I didn't even know about the original project, and it's tl;dr page with name `zoxide` instead of `z`.

So need advice on that please @vitorhcl @sebastiaanspeck.

**(I'm keeping this PR open till hear something back on how to simplify things for everyone moving forward, though this PR is practically stale, due to feature incompatibility)**

**Pull request closed without merging**
