### PR TITLE
git-cherry-pick: add page

### LINKED ISSUE #1155: Add git cherry-pick command

### PR DESCRIPTION
**Pull request by alefir**
Added page for git cherry-pick

EDIT: Fixes #1155

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks! Would it make sense to add another example, say, to cherry pick into a branch that isn't the current one?

**Comment by alefir** [comment]
I don't believe you can do that with cherry-pick. I think you need to checkout the branch you want to cherry-pick into.

Should I add something about that to it?

**Comment by waldyrious** [comment]
Yeah, the "to the current branch" should probably be mentioned in the main description, if that's always the case. Perhaps adapting one or two of the examples from https://git-scm.com/docs/git-cherry-pick#_examples would be a better, then. But it's just a suggestion to improve the page, nothing that would block merging :)

**Comment by alefir** [comment]
I've updated it to specify the current branch in the main description

**Comment by agnivade** [comment]
:+1:

**Comment by waldyrious** [comment]
@alefir unfortunately the latest change doesn't conform to the the current [page format guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format). @agnivade any idea why the linter isn't detecting that?

**Comment by alefir** [comment]
@waldyrious Would you prefer removing that line, moving it to the description, or something else?

**Comment by agnivade** [comment]
@waldyrious - oops, it actually fails but somehow the exit code is 0. Is it due to the tee or the error redirection ? https://travis-ci.org/tldr-pages/tldr/builds/184122860. Wonder how it did not get caught in our tests.

**Comment by waldyrious** [comment]
Hopefully Travis will now report errors correctly. One of them, I believe, should be that the main description lines should end with a period :)

**Comment by waldyrious** [comment]
LGTM. Given @agnivade's thumbs-up above, I'd say we're ready to merge. Coincidentally, yesterday I needed to cherry-pick two commits into a branch, so I might edit the page to add that example afterwards. Thanks @alefir!

**Pull request merged**
