### PR TITLE
pages*: fix placeholder highlight

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by reinhart1010** [comment]
Any rationale for this?

**Comment by kbdharun** [comment]
> Any rationale for this?

This PR seems to be similar to #13030, I believe Sebastian is trying to move the `--` symbols inside the placeholder so that they don't have a different color/style. I too am not sure if this is necessary (we enclose the symbols inside the placeholder if we are showing both long and short options).

**Comment by vitorhcl** [comment]
Hmm I don't know, I have mixed feels about this.

This style is more consistent with {{-short-option|--long-option}}.

In the other hand, the coloring indicates the only value that can be changed for this placeholder, to properly follow this example, is the actual word(s).

Also, maybe it can clutter a bit the example if, for example, a considerable number of long options is in the same placeholder?

**Comment by acuteenvy** [comment]
> In the other hand, the coloring indicates the only value that can be changed for this placeholder, to properly follow this example, is the actual word(s).

Which is why, in my opinion, the two correct ways to write it are `--{{a|b}}` and `{{--a|--b}}`.
I personally like the first one better.

**Comment by vitorhcl** [comment]
It would be good to document this in the style guide

**Pull request closed without merging**
