### PR TITLE
reg: add page

### PR DESCRIPTION
**Pull request by pxgamer**
Part of #1579

This command will be split across pages for the following commands:

- reg query (#1909)
- reg add (#1910)
- reg delete (#1911)
- reg copy (#1912)
- reg save (#1913)
- reg restore (#1914)
- reg load (#1915)
- reg unload (#1916)
- reg compare (#1923)
- reg export
- reg import
- reg flags

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by pxgamer** [comment]
Yes. `reg /?`

**Comment by pxgamer** [comment]
Yes. `reg /?`

**Comment by sbrl** [comment]
Ah, perhaps we could reword it then

**Comment by pxgamer** [comment]
I will reword it now 👍

**Pull request merged**
