### PR TITLE
MAINTAINERS: add @SethFalco to collaborators

### LINKED ISSUE #5993: Add collaborator: @SethFalco
Hi, @SethFalco! You seem to be enjoying contributing to the tldr-pages project.
You now have had seven distinct pull requests merged (#5864, #5876, #5921, #5922, #5936, #5985, #5991)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

### PR DESCRIPTION
**Pull request by SethFalco**
Closes #5993

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Review by CleanMachine1 — APPROVED** [review]
Doesn't break the file, :+1:

**Comment by CleanMachine1** [comment]
Welcome to the maintainer team!

**Review by bl-ue — APPROVED** [review]
Welcome with ❤️! 🎆

**Comment by bl-ue** [comment]
Go ahead and merge this PR yourself when @marchersimon approves, @SethFalco.  We always squash, except when someone adds an explicit note to rebase.

**Comment by bl-ue** [comment]
It's actually not necessary at all — I use my own fork still, just because I like to ;)

**Review by marchersimon — COMMENTED** [review]
image

It's never too late to approve 😄

**Comment by CleanMachine1** [comment]
Amazing

**Comment by CleanMachine1** [comment]
Have you accepted the invite @SethFalco it doesn't appear above your name. If you have then you need to make your membership public

**Comment by marchersimon** [comment]
I can see the `collaborator` badge. 🤔 
image

**Comment by CleanMachine1** [comment]
Yes of course. I am an idiot. I realised my mistake 20 seconds ago.... got confused with Waples

**Comment by bl-ue** [comment]
Wow @marchersimon that's green for you?  Just how did you do it?  I've never been able to.

**Comment by bl-ue** [comment]
This is what it looks like for me

Screen Shot 2021-05-19 at 4 15 14 PM

But maybe I'm misunderstanding...?

**Comment by CleanMachine1** [comment]
Yes
its a picture

**Comment by marchersimon** [comment]
> Oh wait, it's a joke — you're faking an approval @marchersimon?

It's not the most official approval, but it's still as valid 😄

**Pull request merged**
