### PR TITLE
send-to-bot: enrich the comment to update the comment later

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
https://github.com/tldr-pages/tldr-bot/pull/14

### CODE REVIEW

**Comment by sbrl** [comment]
Heya! Looks good to me.

However, it looks like you're using a different HTTP API endpoint.

I'm the one who hosts tldr-bot, do I need to pull or anything?

For future reference, anyone is free to poke me in any way they like to do maintenance on tldr-bot. There haven't been any updates to tldr-bot's code for a while, so I haven't done anything with it except keep it running.

**Comment by kbdharun** [comment]
> Heya! Looks good to me.
> 
> However, it looks like you're using a different HTTP API endpoint.
> 
> I'm the one who hosts tldr-bot, do I need to pull or anything?
> 
> For future reference, anyone is free to poke me in any way they like to do maintenance on tldr-bot. There haven't been any updates to tldr-bot's code for a while, so I haven't done anything with it except keep it running.

Hi @sbrl, I have tested the changes made to the tldr-bot along with @sebastiaanspeck in my fork (setting the URL to my personal server) and can confirm it works as intended (i.e. https://github.com/kbdkorg/tldr/pull/12).

The migration would be pretty seamless you can pull the latest commit from tldr-bot and set a new environment variable with `BOT_USERNAME=tldr-bot` then redeploy with the same steps in https://github.com/tldr-pages/tldr-bot.

> Yes, I introduced a new endpoint to retain old behaviour and make explicit we want to recreate a previous comment. It would be great if you could update the tldr-bot with the latest Git repository. Is it maybe an idea that more than one org owner has access to hosting the tldr-bot?

Agreed, if one or two more people have access to the VPS it would allow us to address any issues that arise proactively (i.e. changes in GitHub API).

----

Additionally, I think since previous bot comments are deleted we can output the errors in the workflow too so that for deleted comments we can quickly glance at the error without needing to navigate the logs (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions).

**Review by kbdharun — APPROVED** [review]

**Comment by kbdharun** [comment]
> > Additionally, I think since previous bot comments are deleted we can output the errors in the workflow too so that for deleted comments we can quickly glance at the error without needing to navigate the logs (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions).
> 
> Do we want to address this in this PR or in a new one?

I think we can do it in a new one post this PRs merge since it only needs minor modifications in CI.

**Comment by sbrl** [comment]
Heya!

> Agreed, if one or two more people have access to the VPS it would allow us to address any issues that arise proactively (i.e. changes in GitHub API).

I can absolutely provide credentials to login to the server. If you are an org owner/member, please DM me on matrix and I'll take a look at adding you.  I will need an SSH public key from you. My server has password login disabled.

I can even add a `sudo` rule to allow you to restart the bot.

> The migration would be pretty seamless you can pull the latest commit from the [tldr-bot](https://github.com/tldr-pages/tldr-bot) repository and set a new environment variable with BOT_USERNAME=tldr-bot then redeploy with the same steps in https://github.com/tldr-pages/tldr-bot#run-as-a-service (and at last merge the current PR).

Got you. Is that before or after this PR is merged?

**Comment by sbrl** [comment]
I can also provide alternative emergency communication mechanisms that generate notifications etc via DM as appropriate.

Has the tldr-bot been spamming...? I'm confused.

**Review by sbrl — APPROVED** [review]

**Comment by sbrl** [comment]
Cool, everything is looking good from my end.

I'm seeing these requests:

```
Oct 01 21:30:21 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 15/15] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:30:21 2024] GET /status => generated 2 bytes in 1 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
Oct 01 21:31:01 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 16/16] 2600:1f18:179:f900:4696:7729:7bb3:f52f () {46 vars in 767 bytes} [Tue Oct  1 21:31:01 2024] HEAD /status => generated 0 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
Oct 01 21:35:25 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 17/17] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:35:25 2024] GET /status => generated 2 bytes in 1 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
Oct 01 21:38:52 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 18/18] 63.143.42.252 () {46 vars in 755 bytes} [Tue Oct  1 21:38:52 2024] HEAD /status => generated 0 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
Oct 01 21:40:29 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 19/19] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:40:29 2024] GET /status => generated 2 bytes in 3 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
Oct 01 21:45:34 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 20/20] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:45:34 2024] GET /status => generated 2 bytes in 5 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
Oct 01 21:46:06 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 21/21] 2600:1f16:775:3a00:37bf:6026:e54a:f03a () {46 vars in 767 bytes} [Tue Oct  1 21:46:06 2024] HEAD /status => generated 0 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
Oct 01 21:50:38 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 22/22] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:50:38 2024] GET /status => generated 2 bytes in 3 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
Oct 01 21:53:52 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 23/23] 63.143.42.252 () {46 vars in 755 bytes} [Tue Oct  1 21:53:52 2024] HEAD /status => generated 0 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 0)
Oct 01 21:55:42 starbeamrainbowlabs.com uwsgi[329891]: [pid: 329891|app: 0|req: 24/24] 2001:41d0:e:74b::1 () {34 vars in 521 bytes} [Tue Oct  1 21:55:42 2024] GET /status => generated 2 bytes in 1 msecs (HTTP/2.0 200) 2 headers in 78 bytes (1 switches on core 0)
```

**Pull request merged**
