### PR TITLE
read: add example using 'while'

### PR DESCRIPTION
**Pull request by orestisfl**
Copied from `while`

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by orestisfl** [comment]
Hah, I didn't count. Let me know if you would like to replace an example with this one. I think it's more intuitive to recall the syntax of a while read loop through the `read` page instead of the `while` page.

**Comment by bl-ue** [comment]
In my opinion, @orestisfl, the 3rd example (`Enable backspace and GNU readline hotkeys when entering input with read`) doesn't seem particularly useful, whereas your example does.  How about you remove the 3rd example? (but keep your example at the bottom to maintain visual consistency as all of the other examples start with `read`)

**Comment by bl-ue** [comment]
Also @orestisfl please sign the CLA to pass the `license/cla` check.

**Comment by orestisfl** [comment]
@bl-ue up :)

**Review by bl-ue — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
This seems fine to me. That readline example looks neat, but I can see how your new example would be more immediately useful in the terminal. For example, I recently cooked up this to rename a sequence of PNG images into a format that ffmpeg can understand:

```bash
i=1; while read -r filename; do mv "${filename}" "${i}.png"; i=$((i+1)); done < <(find . -iname '*.png' | sort);
```

**Pull request merged**
