### PR TITLE
Bringing back tldr bot again

### PR DESCRIPTION
**Pull request by agnivade**
- Removed all the permissions of the bot, so that github won't remove
the token.

### CODE REVIEW

**Comment by agnivade** [comment]
@waldyrious - can you approve this ?

**Comment by ostera** [comment]
👍

**Comment by ostera** [comment]
Even if the bot didn't have permissions, having the token exposed allows anyone to use it and have us rate-limited.

I like having the bot not have any permissions, but I'd rather not expose the token at all and keep using travis encrypted env variables.

**Comment by agnivade** [comment]
You have a point. Its just that there's some weird github logic where travis encrypted variables are not available for PRs from foreign repos. Now, I am not sure after removing all permissions, this still applies or not. There's no way to test it out anyway without merging it first. Let me update it.

**Comment by ostera** [comment]
Ah that would make sense. Otherwise anyone could fork a project, submit a
PR, and steal the secrets as they er unencrypted inside of the CI process.
sön 29 jan. 2017 kl. 15:51 skrev Agniva De Sarker <notifications@github.com

**Pull request merged**
