### PR TITLE
pt_br/axel: add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by waldyrious**
This is a re-submission of #3187. Unfortunately that PR can't be recovered, because the forked repository from which it originated was deleted.

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by schneiderl** [comment]
Thank you @waldyrious for re-submiting this PR.

**Comment by sbrl** [comment]
I'll let someone who knows the language merge this :P

**Comment by mebeim** [comment]
Ping @schneiderl ready to merge?

**Comment by schneiderl** [comment]
Hi @mebeim 
All good from my side and all the comments from the previous PR(#3187) have been addressed already. 
That being said, I think it is ready to merge.

**Comment by mebeim** [comment]
Merging then.

**Pull request merged**
