### PR TITLE
set-more-info-link.py, pages.hi/*: fix punctuation in Hindi translation

### PR DESCRIPTION
**Pull request by marchersimon**
I noticed that Hindi uses a `।` as period. We didn't consider this in `set-more-info-link.py`, so this PR will fix this.
Waiting for #6537

### CODE REVIEW

**Comment by sbrl** [comment]
Can this be merged now?

**Comment by marchersimon** [comment]
Now it can

**Review by sbrl — APPROVED** [review]

**Comment by 2KAbhishek** [comment]
I have added a few new pages in Hindi, I'll update those to use '।'

**Comment by marchersimon** [comment]
Thanks! Am I actually using the right symbol in this PR? (since there are two different ones)

**Review by navarroaxel — APPROVED** [review]

**Comment by 2KAbhishek** [comment]
> Thanks! Am I actually using the right symbol in this PR? (since there are two different ones)

Yup 😁

**Pull request merged**
