### PR TITLE
set-more-information.py: add sync option

### PR DESCRIPTION
**Pull request by blueskyson**
## Usage

Issue [#6385](https://github.com/tldr-pages/tldr/issues/6385). Synchronize each translation's more information link (if exists) with that of English page.

```
export TLDR_ROOT=path/to/tldr
cd path/to/tldr
python scripts/set-more-info-link.py --sync
# or python scripts/set-more-info-link.py -S
```

The `sync` option can be used with `stage` option; Ignored if it's used with `page` option. 

```
python scripts/set-more-info-link.py -S -s
# sync with stage option
```

```
python scripts/set-more-info-link.py -p common/git https://example.com -S
# this will ignore sync
```

## Screenshots

These pictures are taken from other test branch.

螢幕擷取畫面 2021-08-23 210400

螢幕擷取畫面 2021-08-23 211459

## Other Changes

- Add `ro` (Romanian) into `labels` dict.
- Avoid to put a space after every full-width colon in Chinese page.

### CODE REVIEW

**Comment by marchersimon** [comment]
Thanks! Didn't think this would be finished so soon.

**Review by marchersimon — APPROVED** [review]

**Comment by marchersimon** [comment]
@MasterOdin do you think this can be merged?

**Review by MasterOdin — APPROVED** [review]

**Comment by blueskyson** [comment]
@marchersimon Now you can execute a massive sync. 🎉

**Comment by marchersimon** [comment]
Sure, I'll open a PR. Thanks.

**Pull request merged**
