### PR TITLE
yay: add more information link

### PR DESCRIPTION
**Pull request by navarroaxel**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Looks good! I noticed you got the French space correct 👍🏻

**Comment by navarroaxel** [comment]
> Looks good! I noticed you got the French space correct 👍🏻

I copy-pasted the sentence from `pacman`. lol

**Comment by bl-ue** [comment]
Did you do it from the GH UI or locally?

**Comment by navarroaxel** [comment]
> Did you do it from the GH UI or locally?

locally with `Atom`.

**Comment by bl-ue** [comment]
Ah, I see.  I wondered if you might have done it via the UI, and figured out a way to prevent GH from substituting the French space with a normal space. 👍🏻

**Review by sbrl — APPROVED** [review]
Thanks, @navarroaxel!

**Pull request merged**
