### PR TITLE
mplayer: add page

### PR DESCRIPTION
**Pull request by burned42**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 1.4

### CODE REVIEW

**Comment by burned42** [comment]
@navarroaxel thanks for your review comments, I adjusted the changeset in dc2ec2700cab232ec3dedf3cfe0172d1df1b8366

**Comment by burned42** [comment]
@navarroaxel thanks for the quick review :) I think I applied all your suggestions and it also shows that you marked all discussions as resolved, however it still says that there's `1 change requested` but it doesn't display any requested changes.

Do you still have any changes in mind, or is github just broken (maybe due to the force pushes)?

**Comment by navarroaxel** [comment]
@burned42 GitHub keep the `changes requested` status until I approve the PR itself. Also please don't `push --force`, it's harder to us to track the suggestions and changes. I don't have more suggestions at the moment, I will wait for another reviewer.

**Comment by burned42** [comment]
@navarroaxel oh ok, sorry. I thought I was expected to keep it at one commit with the commit message as mentioned in the contribution guides, so I adjusted the commit and force pushed. I totally understand your explanation however and won't force push next time :+1:

**Pull request merged**
