### PR TITLE
ani-cli: add Malayalam translation

### PR DESCRIPTION
**Pull request by sanbabyfrancis**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by mfrw — CHANGES_REQUESTED** [review]
Can we please change the base branch to `main` instead of master :)
We do not have any-checks for master branch and we do not use it.

**Comment by kbdharun** [comment]
> Can we please change the base branch to `main` instead of master :)
> We do not have any-checks for master branch and we do not use it.

This explains my issue. Thanks

**Comment by sanbabyfrancis** [comment]
Oh, my mistake. What should I do next? Should I close this make another PR from main branch?

**Comment by kbdharun** [comment]
> Oh, my mistake. What should I do next? Should I close this make another PR from main branch?

I would suggest you delete your `main` branch in your fork and rename `master` to `main` and you can change it above too I guess.

> Would it work @mfrw?

**Comment by kbdharun** [comment]
@mfrw this PR seems to be automatically merged by github-actions, How to fix it?

**Comment by mfrw** [comment]
I think we have an easier solution, there is an edit button on the PR, where we can change base.
Let me try that.

@kbdharun not really sure if it would work, let me try it and see.
My hunch, no probably not

**Comment by kbdharun** [comment]
Can we edit the branch for merged PRs too?

**Comment by mfrw** [comment]
Okay, after some experiments, what we can do.
lets use the `main` branch to fork off from the repository.
```bash
git checkout main
git checkout -b topic-branch
do the change
git push origin topic-branch
```
The reason, I am being so explicit, it seems the original PR was from `master` which is not a good idea :)

- We should refrain from directly pushing to the default branch (master/main)
- We should fork off a topic branch from the default branch 

> Can we edit the branch for merged PRs too?

Nope, i wanted to experiment and seems we can not :) -- @kbdharun

**Comment by sanbabyfrancis** [comment]
Reading through the conversation I think I've done something seriously wrong. Sorry to put you in this trouble 😢 @kbdharun @mfrw

**Comment by mfrw** [comment]
> Reading through the conversation I think I've done something seriously wrong. Sorry to put you in this trouble 😢 @kbdharun @mfrw 

Nooo not at all :)
You did not do anything wrong :)
We are all learning and we are bound to fumble.

**Pull request merged**
