### PR TITLE
vgcreate: improvements to descriptions

### PR DESCRIPTION
**Pull request by waldyrious**
Follow-up of #1269.

### CODE REVIEW

**Comment by waldyrious** [comment]
@agnivade any clue as to why @mention-bot didn't comment in this thread? I was expecting it to ping @rgcr.

**Comment by agnivade** [comment]
Hmm .. no idea :confused:

**Comment by waldyrious** [comment]
let's give him a few days to provide feedback.

**Comment by rgcr** [comment]
I think it's a good improvement 👍

**Pull request merged**
