### PR TITLE
git-diff: use English names for natural language dates in Spanish translation

### PR DESCRIPTION
**Pull request by bl-ue**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

They were translated into Spanish, which is great, but they don't actually work, which might be an unpleasant surprise to the user.

### CODE REVIEW

**Review by sbrl — APPROVED** [review]
Great spot!

**Review by navarroaxel — APPROVED** [review]

**Comment by sbrl** [comment]
Merging because this is a fairly trivial change.

**Comment by bl-ue** [comment]
@navarroaxel: I see you made a change—thank you!  A quick [search](https://github.com/tldr-pages/tldr/search?q=ruta%2Fdel) reveals several such occurences...should they be also be changes like what you've done here?

**Comment by navarroaxel** [comment]
> @navarroaxel: I see you made a change—thank you! A quick [search](https://github.com/tldr-pages/tldr/search?q=ruta%2Fdel) reveals several such occurences...should they be also be changes like what you've done here?

Yep, I had that in mind, Open #5440

**Pull request merged**
