### PR TITLE
false: add Korean translation

### PR DESCRIPTION
**Pull request by teddygood**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by teddygood** [comment]
Sorry to keep closing PR. PR is awkward. If there is anything that needs to be fixed, please give me feedback.

**Comment by teddygood** [comment]
thanks. If I use the PR Suggestion, I think it push the main branch. Is it okay?

**Comment by navarroaxel** [comment]
> thanks. If I use the PR Suggestion, I think it push the main branch. Is it okay?

@teddygood yeah, that's the most easy way for this repository.

**Comment by teddygood** [comment]
@navarroaxel good. thank you for helping me.

**Pull request merged**
