### PR TITLE
shuf: add Spanish translation

### PR DESCRIPTION
**Pull request by kant**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Review by 4G3NT — CHANGES_REQUESTED** [review]
Fix typo

**Comment by 4G3NT** [comment]
There is a typo on line 20.

Line 20 should be shuf --input-range={{1-10}}

not shuf --input-range={1-10}}

Using tldr -f to render the page before submitting a pr is a good idea too.

**Comment by kbdharun** [comment]
Fixed, thanks for the suggestion @4G3NT

**Comment by kant** [comment]
[Codespell](https://github.com/tldr-pages/tldr/actions/workflows/codespell.yml)

**Review by blueskyson — APPROVED** [review]

**Pull request merged**
