### PR TITLE
stat: add page

### LINKED ISSUE #1487: page request: stat
`stat` is useful for showing octal permissions:
https://askubuntu.com/questions/152001/how-can-i-get-octal-file-permissions-from-command-line

### PR DESCRIPTION
**Pull request by juan88**
Fixes #1487 

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
I believe this should go to the linux folder, not common.

**Comment by juan88** [comment]
I'm not a mac user but from searching in google it says it is available.

I might check it later at work from a macs friend if needed.

2017-10-05 0:58 GMT-03:00 Agniva De Sarker <notifications@github.com>:

**Comment by agnivade** [comment]
Common includes mac, windows and linux. I was talking about windows. I'm afraid you have to do the same thing you did with popd.

**Comment by juan88** [comment]
Thanks for your feedback. I'll make the necessary changes to make it right!

2017-10-05 12:25 GMT-03:00 Agniva De Sarker <notifications@github.com>:

**Comment by agnivade** [comment]
> I'm not a mac user but from searching in google it says it is available.

Yes, it seems to exist - http://www.unix.com/man-page/FreeBSD/1/stat/. Do you plan to add the page later ?

**Comment by juan88** [comment]
Could not test it on a mac yet. I try today at work if my collegue comes to
the office and I'll add it.

2017-10-09 9:09 GMT-03:00 Agniva De Sarker <notifications@github.com>:

**Comment by agnivade** [comment]
Thanks for your work @juan88 . I made some simplifications of my own. Please have a look and let me know if everything looks good.

**Comment by juan88** [comment]
> Thanks for your work @juan88 . I made some simplifications of my own. Please have a look and let me know if everything looks good.

Looks great! thank you for your patience and guidance throughout the process.

**Comment by sbrl** [comment]
Looks good to me! Thanks, @juan88 :smiley_cat:

**Pull request merged**
