### PR TITLE
Split STYLEGUIDE out from CONTRIBUTING.md

### LINKED ISSUE #1508: split CONTRIBUTING.md into main guidelines and auxiliary docs
This has been discussed in a couple PRs now -- most recently in #1495 (/cc @vivekkrish).

#1018 is the only issue specifically related to additions to the CONTRIBUTING.md file that I could find in a quick search (I'm pretty sure there have been discussions to that effect in a few other threads). Such tasks should be included/considered when performing the split.

Links to other discussions where this topic has been discussed would be appreciated. I hope to be able to work on this when I get some time on my hands, but in the meantime, any contribution is welcome :)

### PR DESCRIPTION
**Pull request by iamam34**
- Fixes #1508 (I kept every bullet point, just reordered and moved across files)
- Includes additional point "do not use token syntax in descriptions" as noted in #1495
- Does NOT address "how to explain origin of option names" #1018

Comments, edits, suggestions and questions welcome! Specifically, do we want to move some of STYLEGUIDE.md back into the main CONTRIBUTING.md document?

I've been inspired to contribute as part of [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/).

### CODE REVIEW

**Comment by agnivade** [comment]
This is a non-trivial PR. I think the primary idea was to have an addendum sort of thing apart from the CONTRIBUTING.md. So that, normal users can read CONTRIBUTING.md and just be fine with it, and hardcore users can read the extra document. 

You have taken out the formatting part and made it into a separate doc. Ideally I wouldn't want anything removed from CONTRIBUTING.md and just a link to the auxiliary page with the extra added guidelines.

Please wait for @waldyrious to take a look and comment on this.

**Comment by sbrl** [comment]
Thanks for the PR! This is a rather interesting issue, as we'd like to keep at least something in `CONTRIBUTING.md`. Perhaps we can put a summary in CONTRIBUTING, and link to the style guide for more information? I certainly agree that a style guide would be useful though.

@waldyrious - what do you think?

**Comment by iamam34** [comment]
Thanks for your quick response. What do you mean by "auxiliary" guidelines? Are there any parts of the current CONTRIBUTING.md that could be considered auxiliary?

**Comment by agnivade** [comment]
> What do you mean by "auxiliary" guidelines?

That was the whole point of #1508. There are several guidelines which are not explicitly written down anywhere. Just something we have been using. Like not using tokens in the description, not referring to a person directly with "you".

You wouldn't know these until you have been a member of the org for several years. Hence, my suggestion to wait until @waldyrious takes a look at it.

**Comment by iamam34** [comment]
@agnivade I understand that I don't know any of the community's unspoken guidelines, but my intent with this PR was to create a space for y'all to add to as time goes on.

**Comment by waldyrious** [comment]
Please accept my deepest apologies for the delay, @iamam34. Your contribution is very much appreciated :)

After discussing with the other maintainers on Gitter (transcript available [here](https://gitter.im/tldr-pages/tldr?at=5a1976ab71ad3f87362b1fca)), we decided to preserve some of the content in CONTRIBUTING.md, in preparation for further reorganization of these documents. I took the liberty to rebase this branch to include these changes so that we can merge the PR sooner rather than later.

You'll get pinged to comment on the upcoming PR, but in the meantime, if you have any comments about this PR, feel free to comment below :)

**Comment by waldyrious** [comment]
Ah, crap. It looks like editing fork branches on PRs doesn't work very well when the branch is the primary one of the fork, as was the case here. Sorry about that. I'll open a new PR, but the commits should remain attributed to @iamam34.

**Comment by waldyrious** [comment]
Notes for future reference:
- the new PR (resubmission of this one) was #1594.
- cross-referencing issue #131, which was closed when the page format guidelines were first added as part of the CONTRIBUTING.md file, in [8d6fa52](https://github.com/tldr-pages/tldr/commit/8d6fa5235c7d78e0a8da99543b1bb8fc45077101#diff-6a3371457528722a734f3c51d9238c13).

**Pull request closed without merging**
