### PR TITLE
Lint fix

### PR DESCRIPTION
**Pull request by lord63**
Thanks to vim, remove all the warnings is not a hard thing. By the way, the warning number is not 249, many of them are duplicated. 

Now, please review the PR :tada:  Let me if there are something need to be modefied before merge it.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
Nice! And I should learn that vim trick then, all I have running is syntactic. 
I'm on my mobile at the moment so I can't properly review right now, but would you mind squashing those identically named commits? Makes it a bit less bloaty.

**Comment by lord63** [comment]
@rubenvereecken  Sure. Too many changes in a commit is not a good thing in my opinion, I prefer small commits. Maybe the commit message is not good enough.
So, after reviewed this PR and before merge this one, just ping me and I'll be happy to squash them =)

**Comment by rubenvereecken** [comment]
Checked it out, all good to go :+1:. 

I usually prefer small commits myself, but this is just a batch of style changes, all void of semantics. Throw 'em all together, it's fine.

**Comment by lord63** [comment]
@rubenvereecken  Squashed :fireworks:

**Comment by rubenvereecken** [comment]
Awesome, thanks! Finally that debt cleared up.

**Comment by lord63** [comment]
Close #278 ?

**Comment by rprieto** [comment]
Thanks a lot for going through this, it's awesome to have all pages nice & clean now! :fireworks: 
Agreed we can close #278 ! Objections?

**Pull request merged**
