### PR TITLE
Fixed up cat.md

### PR DESCRIPTION
**Pull request by rselwyn**
I fixed it to conform with the file bracketing (using {{ }}) requirement.  I also added appending.

### CODE REVIEW

**Comment by ostera** [comment]
This was just fine as it was. Adding `.ext` makes no difference.

**Comment by rselwyn** [comment]
I can remove the .ext and just stick with the append @ostera

**Comment by ostera** [comment]
:+1:

**Comment by waldyrious** [comment]
As we discussed recently (/cc @rprieto, @igorshubovych), the `>` and `>>` are not strictly `cat` features, but they are quite closely related to it, so I suppose we can open an exception as we did with `ls` and the wildcards (I don't have the PR reference handy, sorry). So my verdict is tentative merge :+1:

**Comment by rprieto** [comment]
Looks great! Agreed with what @waldyrious said, so :+1: from me.

**Pull request merged**
