### PR TITLE
find: Delete files older than 'x' days

### PR DESCRIPTION
**Pull request by rajivrnair**
A simple way to find and delete files older than a certain number of days.
This is something I use frequently to clean up old log files (sometimes setup as a cron).

### CODE REVIEW

**Comment by waldyrious** [comment]
Perhaps simplify the example to remove the `-name`? That's demonstrated in another example already. Otherwise, I'd suggest including that in the example description, for completeness.

**Comment by rajivrnair** [comment]
Included the name bit in the example description.

**Comment by waldyrious** [comment]
Thanks for the quick reaction, LGTM.

**Comment by igorshubovych** [comment]
Thanks for contribution. Keep up the good work!

**Pull request merged**
