### PR TITLE
updated strace.md with starting a program

### PR DESCRIPTION
**Pull request by Nekel-Seyew**

### CODE REVIEW

**Comment by agnivade** [comment]
Hi there, 

Please run `npm test` before submitting a PR to ensure that all tests have passed. And also format your git commit title as mentioned in [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message). Thanks !

**Comment by waldyrious** [comment]
> Please run `npm test` before submitting a PR to ensure that all tests have passed. And also format your git commit title as mentioned in [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message). Thanks !

Alternatively (and more conveniently), take a look at the output of the Travis CI build (click the "details" link), which tells you exactly what's wrong:
> pages/linux/strace.md:21: TLDR005 Example descriptions should end in a colon

**Comment by Nekel-Seyew** [comment]
ok, I want to look at the travis build, but every time I do, I get a blank page.

**Comment by agnivade** [comment]
That is strange, I get the proper logs.

Here is your error-
```
Error: Parse error on line 22:
...am by executing it: `strace {{program}
----------------------^
Expecting 'NEWLINE', 'BACKTICK', got 'TEXT'
```

**Comment by agnivade** [comment]
Thanks. Before others start to review the PR, I would request you to change the commit title to something like -
`strace: Added option to start an executable`

**Comment by agnivade** [comment]
@waldyrious , @ostera, @igorshubovych - Comments ?

**Comment by ostera** [comment]
I'd say is good to squash. We can change the commit ourselves then.

**Comment by waldyrious** [comment]
Agree w/ @ostera

**Comment by ostera** [comment]
Used `strace.md: Added option to start an executable` as most of our commit's seem to follow that `{name}.md: {what}` convention.

**Pull request merged**
