### PR TITLE
Add collaborator: @ivanhercaz

### LINKED ISSUE #3690: Add collaborator: @ivanhercaz
Hi, @ivanhercaz! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#3669, #3682, #3670, #3675, #3680)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

### PR DESCRIPTION
**Pull request by zdroid**
Closes #3690

### CODE REVIEW

**Comment by sbrl** [comment]
Erm this is a bit presumptuous, @zdroid. I recommend waiting until they accept the invitation, and _then_ open the PR to add them. What happens if they say no?

**Comment by zdroid** [comment]
@sbrl I took [this comment](https://github.com/tldr-pages/tldr/pull/3670#issuecomment-568121468) as a 'yes'.

**Comment by ivanhercaz** [comment]
Wow! That's really awesome. Thank you very much for this proposal.

> Erm this is a bit presumptuous, @zdroid. I recommend waiting until they accept the invitation, and then open the PR to add them. What happens if they say no?

Don't worry @sbrl. I am really happy with this invitation and I see this as an opportunity to contribute a bit more in a different way to this project. I didn't reply the invitation [until now](https://github.com/tldr-pages/tldr/issues/3690#issuecomment-568924840) but...

> @sbrl I took [this comment](https://github.com/tldr-pages/tldr/pull/3670#issuecomment-568121468) as a "yes".

... this is true hehe. I understand the comment isn't valid as an official acceptance, but please keep calm about it because I really like atmosphere of this project and how all of you collaborate to make it better.

Really awesome! Again, thank you very much!

**Comment by waldyrious** [comment]
> @sbrl I took [this comment](https://github.com/tldr-pages/tldr/pull/3670#issuecomment-568121468) as a "yes".

That's fair, @zdroid, but because not everyone is able to keep track of all conversations, it would have been nice to mention that comment either in the opening message of this PR, or in the corresponding issue (#3690). Otherwise it would become quite difficult to track down the conversation sequence a few months or years down the road (and we do need to dig up old conversations every now and then, so let's make our own lives easier when we can! 😄)

**Comment by andrik** [comment]
Welcome aboard @ivanhercaz 

It's really nice to see more people getting involved with tldr

**Comment by waldyrious** [comment]
> It's really nice to see more people getting involved with tldr

Agreed — and especially so for someone with experience in the Wikimedia world, whose community has managed to build a very permissive collaboration culture, similar to what we're trying to implement in tldr-pages (case in point!).

Welcome @ivanhercaz! Make sure to get acquainted with the [project governance](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md) guidelines and the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md)! 😉

**Comment by sbrl** [comment]
Hey, awesome @ivanhercaz! Invite sent :D

You've got experience with the Wikimedia world? Nice!

**Comment by ivanhercaz** [comment]
> Welcome aboard @ivanhercaz
> 
> It's really nice to see more people getting involved with tldr

Thank you very much! It is a pleasure to be in this ship @andrik :heart: 

> > It's really nice to see more people getting involved with tldr
> 
> Agreed — and especially so for someone with experience in the Wikimedia world, whose community has managed to build a very permissive collaboration culture, similar to what we're trying to implement in tldr-pages (case in point!).
> 
> Welcome @ivanhercaz! Make sure to get acquainted with the [project governance](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md) guidelines and the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md)!

Thank you for your words and the welcome, @waldyrious. I hope to contribute as much as I can within my possibilities. Before to perform any maintenance task I will read carefully the project governance and the maintainer's guide documents.

> Hey, awesome @ivanhercaz! Invite sent :D
> 
> You've got experience with the Wikimedia world? Nice!

Thank you, @sbrl! Yes, I am Wikimedia since some years. If sometimes I can help you with something, ask me! I will do everything in my hands.

> Let's merge this when @ivanhercaz accepts the invite.

Accepted!

Again, thank you very much to everyone and specially to @zdroid for being attentive to my activity and propose me as collaborator :heart:.

**Comment by zdroid** [comment]
Welcome aboard! :ship: :it:

**Pull request merged**
