### PR TITLE
tldr as container image

### PR DESCRIPTION
**Pull request by nutellinoit**
Added the ability to use `tldr` by running a container. This is my first pull request i hope i'm not going against contributions guide!

### CODE REVIEW

**Comment by sbrl** [comment]
So this runs a tldr client in a docker container?

**Comment by agnivade** [comment]
Yes.

**Comment by pxgamer** [comment]
Is this ok to close as it hasn't had any activity for 25 days. @agnivade, @sbrl does this seem alright?

@nutellinoit, I can see you've made a repo for this but it's empty at the moment. I'd be happy to do some testing once it's set up. :smile: :confetti:

**Comment by agnivade** [comment]
Yep.

**Comment by nutellinoit** [comment]
After a lot of time I managed to create the project. The link is https://github.com/nutellinoit/tldr-docker

I set jenkins so that every hour goes to check the repository and download the submodules, then will trigger the new docker build and push on docker hub

😊

**Comment by agnivade** [comment]
Sure, I don't see a reason not to. We should create a separate section "Docker images".

**Pull request closed without merging**
