### PR TITLE
feat: add more information links

### PR DESCRIPTION
**Pull request by owenvoke**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by owenvoke** [comment]
This basically just prepares the repository for when we release the next version of `tldr-lint`.

**Review by navarroaxel — APPROVED** [review]

**Comment by owenvoke** [comment]
I'm going to leave this as is, so it's ready to merge whenever, and then we can apply the required changes for `TLDR019` (as listed in #5046) in a separate PR. 👍🏻

**Comment by waldyrious** [comment]
@owenvoke any reason you added new links in this PR, in addition to fixing the existing ones? I would prefer the additions to be in a separate PR.

I'd be happy to split them out myself, keeping your commit authorship, if you'd like.

**Comment by owenvoke** [comment]
Ah, I just started this off as a PR for adding new ones. And then noticed there were broken ones too. I'm happy for it to be split into another PR. 👍🏻

**Comment by waldyrious** [comment]
Ok! I've split the syntax fix changes into #5050.

**Review by waldyrious — APPROVED** [review]
A straightforward improvement. Thanks!

**Pull request merged**
