### PR TITLE
Add Discord Slash Command Bot

### PR DESCRIPTION
**Pull request by Epictek**

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Wow, cool!! 🚀

**Review by sbrl — APPROVED** [review]
Awesome work!

Holding off on a merge just for a moment or two because @Epictek is going to update the README of the repository of the bot

Disclaimer: I know @Epictek IRL.

**Review by navarroaxel — APPROVED** [review]

**Review by marchersimon — APPROVED** [review]

**Comment by Epictek** [comment]
Updated readme, ready to merge if all okay. :)

**Comment by marchersimon** [comment]
The Readme looks good, however we usually wait a day or two before merging any non-trivial PRs to give anyone a chance to comment.

**Comment by bl-ue** [comment]
Welcome to tldr-pages, @Epictek, and thank you for the excellent new client!

**Pull request merged**
