### PR TITLE
README: update Homebrew client to Rust client `tlrc`

### PR DESCRIPTION
**Pull request by kbdharun**
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

## Changes

- Update the Homebrew client from the C client to the Rust client (`tlrc`).
- Minor fixes to the Installation section.

I have already updated [the Wiki](https://github.com/tldr-pages/tldr/wiki) for the same.

### CODE REVIEW

**Review by gutjuri — APPROVED** [review]
Thanks, but why change the C client for the Rust client? :D

**Comment by kbdharun** [comment]
> Thanks, but why change the C client for the Rust client? :D

_Good question, The reason isn't properly documented in a specific place but we have the same response when it is brought up in any issue or discussion._ 

The C client has long been undermaintained as the previous maintainers have become inactive or have other priorities. It lacks crucial features like Language support, etc which has been a requirement in the client specification since 2019 (v1.2) (before even I joined `tldr` 😅 ). If you check out the commit history, you will notice that most of them are PR merges done by me or Seth Falco (both of us aren't that proficient with C) closing open issues and no new major features were added.

C Client is widely used by Mac and Linux users via Homebrew and Nix and it is one of the popular clients behind node client, python client and tealdeer. So most first-time users of `tldr` are exposed to the project with this client. Its lack of features has led to an increasing amount of bug reports and issues in the past few years. 

The C client is packaged in various GNU/Linux distributions too. We have held multiple discussions to either replace it with the Python client or a better one for a while. One of the comments we make in PRs to authors is to ask if they are interested in maintaining the client and ask them to drop by the chatroom (and let us know if they are). Till now we haven't received a single message from someone expressing interest in maintaining it actively and updating it to comply with the client specification.

A few months ago, @acuteenvy created a new Rust-based client and added it to the Wiki (right around the time she was invited as a collaborator by pixelcmtd). A few days ago, she expressed her interest in making `tlrc` an official client in the [chatroom](https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$CU7_y11ArchT-ospvq10mEBYLNEOzO3DlJGLsLnK8cA?via=gitter.im&via=matrix.org&via=one.ems.host) [1]. We quickly checked out the client's features and accept it as it addressed all the missing features of our other official clients and was fast too.

I made this message last week in [chatroom](https://matrix.to/#/!zXiOpjSkFTvtMpsenJ:gitter.im/$kP7-49_3LSGQjKEdpaamgBGoebiw6kcOefn7It66YUg?via=gitter.im&via=matrix.org&via=one.ems.host) [2] asking if we should replace the C clients Homebrew package with `tlrc`. And masterodin suggested making a separate manifest instead and it is what we did.

The C client is still officially supported and we will eventually implement features of the recent Client specification but it wouldn't be widely suggested as it is now.

Btw @gutjuri, if you are interested in the C client. Feel free to drop by to checkout the open PRs and implement any missing features.

----

## Messages

### 1 (acuteenvy's initial message)

> Hi, could I move a client to the tldr-pages org?
> All the current official clients do not implement some optional parts of the spec (e.g. showing that there are other pages with the same name in a different directory or downloading individual archives) and even some required parts (the Python client doesn't show pages from the android directory, the Node client still uses --os instead of --platform etc.). I wrote [a client](https://github.com/acuteenvy/tlrc) that does all that and has more configuration options than the current official clients.

### 2 (my message inquiring about changing the Homebrew client)

> Hi guys, I have been thinking since the C client has been undermaintained and lacks features suggested in the Client specification. How about replacing it with [tlrc](https://github.com/tldr-pages/tlrc) in [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/t/tldr.rb)?
> 
> If you notice the [statistics of the package](https://formulae.brew.sh/formula/tldr#default) it is annually used by more than 20k users. So exposing these users to a client which lacks feature parity with other official clients might leave a bad impression about the project.
> 
> (Note. This message isn't about discontinuing the client but rather switching the homebrew package with tlrc)

**Review by acuteenvy — APPROVED** [review]
Now we just need to add support for BSDs and Android in the Python and Node clients.

**Comment by kbdharun** [comment]
> Now we just need to add support for BSDs and Android in the Python and Node clients.

Already did it for Node (checkout my open PR). 

Feel free to create one for the Python client (if possible, can you review the open PR for implementing caching support in it?).

**Comment by acuteenvy** [comment]
> implementing caching support

The Python client doesn't have caching?

**Comment by kbdharun** [comment]
> > implementing caching support
> 
> The Python client doesn't have caching?

Seems like me edit didn't go through GitHub mobile app. I meant caching support for the new translation archives instead of the whole zip.

**Comment by acuteenvy** [comment]
Can I merge this or are we waiting for something?

**Comment by kbdharun** [comment]
> Can I merge this or are we waiting for something?

Sure, it is GTG.

**Pull request merged**
