### PR TITLE
pdfinfo: add page

### PR DESCRIPTION
**Pull request by sahilister**
- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]
Hey @sahilister, thanks for all your contributions :heart: 

I can see more options like `-box` or `-meta` to display more metadata, are these useful?
Also. do you know about `-js print all JavaScript in the PDF`? Looks useful before to open a PDF with code inside

**Review by einverne — APPROVED** [review]
Thank you for your new page @sahilister . It looks good to me, but I'm confused about the difference between the user password and owner password?

**Comment by navarroaxel** [comment]
> Thank you for your new page @sahilister . It looks good to me, but I'm confused about the difference between the user password and owner password?

@einverne I didn't know about the 2 levels of security in the PDF files too https://www.isumsoft.com/pdf/pdf-user-password-and-owner-password-secure-pdf-document.html :open_mouth:

**Comment by sahilister** [comment]
@navarroaxel 
> I can see more options like `-box` or `-meta` to display more metadata, are these useful?

`-box` is an advance usage of `pdfinfo` command and in my initial usage, information it provides doesn't seem handy for new/casual users. 

As in case of `-meta`, document level metadata or in other words, data from document catalog isn't been actively filled with information by PDF makers/providers. Almost all the PDFs I checked, only one displayed any result using `-meta`, so I believe it can be skipped.

**Comment by sahilister** [comment]
@navarroaxel 
> Also. do you know about `-js print all JavaScript in the PDF?` Looks useful before to open a PDF with code inside

Initially I was adding `-js` command as rightly stated by you about the usage. But in the latest version, 4.02 (referenced in more information section), `-js` option has been dropped. As downstream repos get in distributions get updated, `-js` would stop working. 

So had to skip adding that option.

**Comment by navarroaxel** [comment]
Cool, I want the review from @sbrl to check the grammar.

**Review by owenvoke — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
Thanks, @sahilister! Nice one.

Also great point about the extra arguments there - sometimes minimalism is best.

**Pull request merged**
