### PR TITLE
at: add notify-send example

### PR DESCRIPTION
**Pull request by zdroid**
Closes #3862.

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by zdroid** [comment]
There was. You can re-read the previous discussion at #3862. I understood that I should make a new PR to avoid CLA conflicts.

**Comment by sbrl** [comment]
Ah, I see @zdroid - thanks!

That still leaves the  issue of `reboot` though and the duplicated functionality.

**Comment by zdroid** [comment]
@sbrl what is so problematic with it though? It's a use case many could need.

**Comment by sbrl** [comment]
To summarise my earlier comments, I see 2 issues:

1. The `shutdown` command already allows a reboot to be scheduled.
2. The `reboot` command as an example requires `sudo`, so the command as-is wouldn't work unless you are root (e.g. you `sudo` the `at`).

**Comment by zdroid** [comment]
Do you have any commands to replace it in mind? For example, it could be `notify-send` in Linux.

**Comment by sbrl** [comment]
Yeah, `notify-send` could work - especially since this page is in the `linux` folder.

Other candidates could include a gzip, or something similar.

**Comment by zdroid** [comment]
@sbrl Is it good now?

**Pull request merged**
