### PR TITLE
ssh reverse tunneling added

### PR DESCRIPTION
**Pull request by abshammeri**
I've added an example to do a reverse tunneling through ssh. Reverse tunneling used to access a personal machine from a remote server. It common to use this feature to bypass corporate firewalls so the user can access its machine from remote server. This example will complete the tunneling options list:
* -L
* -D
* -R (the added item)

Thanks,

### CODE REVIEW

**Comment by waldyrious** [comment]
Many thanks for your contribution, but this page is already quite long, and adding more commands makes it longer still. In the spirit of tl;dr, what changes do you think could make sense to *shorten* the page, even if we add -R? Maybe combine two examples, or remove one that's less common?

**Comment by rubenvereecken** [comment]
Pretty cool example. There are some formatting issues (besides syntax) but there's a bigger problem here: We restrict our pages to have about 6 examples. We're even removing the "about" part of that statement and this page was already slightly beyond its limit. The example you propose is one too many. If examples are absolutely necessary, we replace an old one. I don't see which one we could drop.

I'd refuse this PR with a sore heart, but I'll have other contributors get their say in first. I'm sorry @abshammeri.

**Comment by abshammeri** [comment]
It's fine guys, and sorry for the failed test, I did not notice that there is CI here, if you might add the automated testing step to the contribution page.

**Comment by rubenvereecken** [comment]
Yeah, we should do that somewhere. I've been meaning to add that. Cheers @abshammeri

**Pull request closed without merging**
