### PR TITLE
New command: calc

### PR DESCRIPTION
**Pull request by sbrl**
There's a ton more you can do with this one, but I personally haven't learnt the full capabilities of this one :P

If you're on a debian-derivative, install it with `sudo apt install apcalc`.

### CODE REVIEW

**Comment by waldyrious** [comment]
Hey @agnivade, reading the comment above, I got a few ideas of how simple tweaks that could make the message more friendly. How about something like:

>The [build](https://travis-ci.org/tldr-pages/tldr/builds/233382895) for this PR has failed with the following errors:
>```
>pages/linux/calc.md, line 10: Command example is missing its closing backtick
>```
>Please fix the error(s) and push again.

**Comment by agnivade** [comment]
Sure

**Comment by waldyrious** [comment]
Actually, it would be even nicer if the offending line was printed along with the error, something like this:

    On pages/linux/calc.md, line 10:
        `calc -p '{{85 * (36 / 4)}}'
    Error: Command example is missing its closing backtick.

(by the way, the line number seems [off by one](https://en.wikipedia.org/wiki/Off-by-one_error) -- it should be [line 11](https://github.com/tldr-pages/tldr/pull/1380/commits/d8d15a514cf70b3218663e36d6979a526867ffab))

**Comment by sbrl** [comment]
The avatar looks a bit weird I think

**Comment by agnivade** [comment]
You are most welcome to re-design it :)

**Comment by waldyrious** [comment]
To avoid off-topic discussion on this thread, I created issues for both tldr-bot related comments above.

**Pull request merged**
