### PR TITLE
Add new page about xargs command

### PR DESCRIPTION
**Pull request by jrziviani**
- xargs is a command that uses the standard input to create parameters
   for a command to execute.

Signed-off-by: Jose Ricardo Ziviani <jrziviani@gmail.com>

### CODE REVIEW

**Comment by igorshubovych** [comment]
It is one of the most complicated page. I thought already some time ago on how to make this page without breaking the rules. I do not know how to do it.

@rprieto do you have idea on how to make it follow the spirit of the project?

**Comment by waldyrious** [comment]
Perhaps using only echo commands to generate input would better exemplify xargs without polluting the page too much with other commands? Dunno, it's an idea.

**Comment by ostera** [comment]
may I suggest we use `ls -1` to generate input? It's available everywhere, everyone is very likely to know how it works.

**Comment by igorshubovych** [comment]
Well I actually found out today we have a page for it, but in Linux folder only

**Comment by ostera** [comment]
There's another pull request to move the linux page to common here: https://github.com/tldr-pages/tldr/pull/450

**Comment by rprieto** [comment]
I like the idea of using `echo` to introduce the concept with a simple example, and moving to `ls` for the more complex ones (involving multiple lines, etc...). Also still :+1: from me if we want to use `ls` the whole way, this this command is about piping from other commands :)

**Comment by igorshubovych** [comment]
I like ls more than deborphans. It is even available on Windows in powershell.

**Comment by jrziviani** [comment]
Oh, I didn't see the xargs page in the linux folder. I think it's better to go to https://github.com/tldr-pages/tldr/pull/450 and close this pull request.

**Comment by igorshubovych** [comment]
Agree. Thanks for contribution anyway.

**Comment by igorshubovych** [comment]
Feel free to close it.

**Pull request closed without merging**
