### PR TITLE
scp with ssh key

### PR DESCRIPTION
**Pull request by xidui**

### CODE REVIEW

**Comment by igorshubovych** [comment]
I like it. It is quite a common case.
But there are too much examples on this page already.
@rprieto, @rubenvereecken, @waldyrious,

Maybe we should remove "specify port on host" or "copy a file from one host to another", they seems to be less common.

**Comment by xidui** [comment]
To keep less examples, I think it may be better to merge several examples together.
such as 
1. we can make `upload` and `download` together to be `copy`
2. -r, -P and -i parameters can be used together in a single command. I think users can understand what they mean and choose the parameters which they need

**Comment by igorshubovych** [comment]
@xidui,

I doubt that we should go this way. Both upload and download are very important use cases. They cover 90% of scp usage.

IMO we should eliminate either copy or port examples, because in my practice they are used less. Frankly speaking I've never used them.

Let's wait for other opinions.

**Comment by waldyrious** [comment]
I agree that the port option could be removed, but the copying from one remote host to another is important IMO to drive the point home that the left argument is the source and the right one the destination, regardless of the location being local or remote. In any case, by removing the port example and adding the one on this PR, we'd have a page with 6 entries, which seems within reasonable limits.

**Comment by igorshubovych** [comment]
Anyway. This Pull Request is good to go.

**Pull request merged**
