### PR TITLE
http: add page

### PR DESCRIPTION
**Pull request by jkbrzt**
https://github.com/jkbrzt/httpie

### CODE REVIEW

**Comment by igorshubovych** [comment]
9 examples are too much. Plz think what can be omitted.

**Comment by jkbrzt** [comment]
Seven — better?

**Comment by igorshubovych** [comment]
Better, but I will probably omit the last one too. The recommended amount of commands is 5-6.

**Comment by jkbrzt** [comment]
Okay, I've deleted the last one.

**Comment by ostera** [comment]
Honestly this 7 examples are 99.9% of the use cases ever needed. I'd perhaps remove the first one, since it might be obvious from the output what to do with it (maybe `http url > file`?).

Maybe the authentication and extra headers can be merged? After all, you can authenticate via headers.

**Comment by ostera** [comment]
Nooo, the last one was the most useful one haha (imo, since it shows you can actually use this in a `|` chain)

**Comment by jkbrzt** [comment]
That's the thing :smile:  The original nine examples covered everything important and removing any of them is a compromise. As for `http url > file` vs. `http -d url`: they are actually different and `-d` is more interesting for everyday use.

**Comment by jkbrzt** [comment]
I leave it up to you guys. Feel free to remove/include what you deem important. I might be biased.

**Comment by igorshubovych** [comment]
After reading the thread I agreed with @ostera. Let's have 7 commands. So i merged it manually with all 7 commands.

Thank you for contribution!

**Comment by ostera** [comment]
Yays!

**Comment by jkbrzt** [comment]
👍👍👍

**Pull request merged**
