### PR TITLE
case: update description

### PR DESCRIPTION
**Pull request by Managor**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by Managor** [comment]
Someone probably needs to use `help` and methodically go through all of the builtin commands and constructs that bash has.

Furthermore I have to ask if bash builtins should be in `common` or `linux` folder

**Review by mfrw — APPROVED** [review]
LGTM.
Thanks @Managor

**Comment by mfrw** [comment]
> Someone probably needs to use `help` and methodically go through all of the builtin commands and constructs that bash has.
Sure, lets create an issue and maybe swarm it ... [also we might as well add the tag `help-wanted`]

> Furthermore I have to ask if bash builtins should be in `common` or `linux` folder
My opinion, they should be in `*nix` instead of common. Alas, we dont have a distinction for `*nix` and `Windows`.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
