### PR TITLE
7z: add space after option -p and -o

### PR DESCRIPTION
**Pull request by andrik**
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by andrik** [comment]
It's not mandatory using space, but as suggested by @schneiderl on the pt_br version I think it looks better using it.

**Comment by waldyrious** [comment]
@andrik is there a long-form of the `-o` option that we could use? Perhaps that would accept a space or an equal sign, making the command more readable. (Though that's not a big deal, it can be confusing to have a space after `-p` and no space after `-o`).

**Comment by sbrl** [comment]
I don't think there is.

Also, the official 7z manual page does not include a space, I've realised. I think I would vote for reverting this change.

**Comment by andrik** [comment]
Yeah, it's better to follow the manual. I'll change it.

**Pull request merged**
