### PR TITLE
Add curl example for printing response headers

### PR DESCRIPTION
**Pull request by jeremyruppel**
This is probably the most useful curl command I can never remember. Thanks for the great project!

### CODE REVIEW

**Comment by waldyrious** [comment]
I'm afraid this page is starting to become too long for a "tldr". Do you think any of the current examples could be removed or merged to another?

**Comment by igorshubovych** [comment]
Yes. There are 7 examples. I think it is still acceptable, however it would be good if a more experienced contributor suggest.

I noticed that DELETE example has similar idea to POST example

`curl -X {{DELETE}} {{http://localhost/item/123}}`

`curl -X POST -H "Content-Type: application/json" -d {{'{"name":"bob"}'}} {{http://localhost/login}}`

So maybe DELETE example can be just removed.

**Comment by felixonmars** [comment]
@jeremyruppel Why not just use `--head` as described in the previous example? If you are afraid if the server returns different headers for HEAD requests (although it's the server's fault in this case), you can still combine with `-X GET` or whichever method you want and curl will still print the headers only.

**Comment by jeremyruppel** [comment]
@felixonmars wow, I didn't realize you could mix `--head` and `-X`. The curl man entry for `--head` doesn't read like that to me, anyways. Thanks for the tip!

**Pull request closed without merging**
