### PR TITLE
Ssh keygen filepath

### PR DESCRIPTION
**Pull request by jedahan**
i always forget its lowercase -f

### CODE REVIEW

**Comment by ostera** [comment]
Could you make sure not to include other commits in your PR?

**Comment by jedahan** [comment]
whoops, fixed

**Comment by waldyrious** [comment]
A couple comments:

- it would be nice to use the term "file" or "filename" in the example description, to make the meaning of -f even more obvious.
- if we're going to use "location" (i.e. a path, as I see it) rather than just "filename", the "~/.ssh/" should be part of the token.

Ideally we'd choose one of the two options above. I'm more inclined towards the first, even if the second is technically correct, considering that tldr aims to be beginner-friendly.

**Comment by jedahan** [comment]
great feedback @waldyrious - I am definitely having trouble figuring out a concise wording that also fits with that real-world example that is also easy to parse TT

**Comment by jedahan** [comment]
ssh prompt is
```
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/jedahan/.ssh/id_rsa):
``

**Comment by waldyrious** [comment]
Sounds good @jedahan

**Comment by jedahan** [comment]
OK, try number 2

**Comment by ostera** [comment]
Thanks!

**Pull request merged**
