### PR TITLE
docker-compose: add Indonesian translation

### PR DESCRIPTION
**Pull request by fadharpra**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by fadharpra** [comment]
Hi @kbdharun and @reinhart1010, kindly review my request

**Review by reinhart1010 — CHANGES_REQUESTED** [review]
Thanks for your contribution, here are some reviews from mine.

**Review by reinhart1010 — APPROVED** [review]
Thanks, but we need another maintainer to approve this before finally merge this PR.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
