### PR TITLE
mockgen: add page

### PR DESCRIPTION
**Pull request by anirudhts**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, @anirudhts! Thanks for the PR.

Looks like there's a page edit here as well as the addition of a page for a new command. Could this be separate pull requests please? It makes it much easier and less confusing to review.

Also, it looks like you're having some trouble with @CLAassistant. All the email addresses on the commits in your PR need to be registered on your GitHub account in order for it to register you signing the CLA.

**Comment by anirudhts** [comment]
@sbrl Is it sufficient of one of the emails r valid? And I will remove the changes in the other page as well so that this pull is focused on one single change

**Comment by agnivade** [comment]
It seems like you have sent the PR from 3 different mail addresses. I would request you to just send a single PR with one email from which you have signed the CLA.

**Comment by sbrl** [comment]
Unfortunately not, @anirudhts. All the email addresses used to commit in a PR have to be registered against a GitHub account that has signed the CLA for it to register.

You could try and interactive rebase to fix it if you're feeling adventurous, or you could close this PR and open a new one with a single commit instead.

**Comment by zdroid** [comment]
I suggest closing this, as it proposes 2 distinct changes at once.

**Comment by ivanhercaz** [comment]
I am agree with @zdroid. I think the better will be to close this PR and open one with the commits just by users/emails that can sign the CLA.

**Comment by zdroid** [comment]
Closing this as there has been no response from @anirudhts for 2 months. If you ever revisit this PR, you are supposed to split the changes into two distinct PRs and commit only with your account that has CLA signed.

**Pull request closed without merging**
