### PR TITLE
Add `make backticks` task

### PR DESCRIPTION
**Pull request by hollingberry**
See https://github.com/tldr-pages/tldr/pull/255.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
The backticks script is looking good, I'll experiment a bit with it because I'm thinking of additing it to a git pre-commit hook. That way we can have it error _only_ when a contributor has forgotten some backticks and shut up otherwise. What do you think about that? It would mean though that it wouldn't be meant for explicit activation because it would output nothing if everything succeeds. This could be mended by using stdout and stderr though and having the Makefile redirect one. Would love to hear your thoughts.

I suggest you move your changes to `make_index.rb` though. A little cherry-pick of the commit onto another branch should do, then send another PR for that one. That way @ostera can have a look at that in particular. For example, I see you removed the need for the `TLDR_HOME` environmental variable. It does allow calling the script without having the variable, but not from everywhere. The other little Ruby improvements look good though.

**Comment by ostera** [comment]
@hollingberry, great work! I'd have something more generic for the Makefile (think `make lint-pages`) where we could call a bunch of linting scripts, like your backticks one. Plus it's more expressive – it's harder to tell what exactly `make backticks` is doing until you actually run it, versus `make lint-pages`. Just a thought.

@rubenvereecken I'm good with the changes to `make_index.rb` that make it more idiomatic (using `.values` for instance, that was a good catch by @hollingberry that I wasn't aware of). I'd like to keep `TLDR_HOME` thou, the cost of supporting a path prefix for the tools to work on is very small and it offers far more flexibility at this point in time. I'd rather re-export `TLDR_HOME` than get into the code to change something. Path of least resistance – no pun intended.

**Comment by rubenvereecken** [comment]
@ostera fair call.

@hollingberry do you feel like adding `TLDR_HOME` back in? Other than that the index script has changed for the best. Concerning the `make backticks`, I hadn't even thought of the actual make target name until ostera brought it up. I think we should go for something obvious like `make check`, `make test` or `make lint`.

Now, concerning its use as a pre-commit. One way we could go about it is like this: Show warnings/errors on `stderr` and other informative messages on `stdout`. That way its useful as an independent target but the git pre-commit hook can do something like `make test 1> /dev/null` which would only show the errors. Just thinking aloud, any input is welcome.

**Comment by ostera** [comment]
:+1:

**Comment by ostera** [comment]
I think this can be closed?

**Comment by rubenvereecken** [comment]
We don't have a script to repair backticks anymore but it should be obsolete with linting. Note that a double missing backtick will pass linting perfectly, so contributors should still keep a watchful eye.

I won't merge this but this PR has fixed the attention on the need for linting and urged us to incorporate a linter together with git hooks. So thanks for that @hollingberry :).

If we ever do need the backticks, we know where to look now.

**Pull request closed without merging**
