### PR TITLE
git-svn: add fetch subcommand

### PR DESCRIPTION
**Pull request by agnivade**
Closes #950

### CODE REVIEW

**Comment by waldyrious** [comment]
Nice work @agnivade. I've reattributed the commits following the name and email currently present in @rcorrie's profile, so that cla-assistant can deal with them. For reference, here's the command I used:

```
git filter-branch --env-filter '
OLD_NAME="rcorrie"
OLD_EMAIL="rcorrie@adt.com"
NEW_NAME="Ricardo Corrie"
NEW_EMAIL="rc@rcorrie.com"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$NEW_NAME"
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$NEW_NAME"
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' master..svn
```

Note: I just learned about [git-filter-branch](https://git-scm.com/docs/git-filter-branch) the other day -- seems daunting at first but it is quite understandable. Look for the part where it says "The `--env-filter` option can be used to modify committer and/or author identity." For filtering only the `svn`branch, I referred to the [git rev-list docs](https://git-scm.com/docs/git-rev-list).

**Comment by agnivade** [comment]
I see, very nifty indeed !

**Comment by waldyrious** [comment]
LGTM 👍

**Comment by agnivade** [comment]
LGTM

**Pull request merged**
