### PR TITLE
nethogs: add

### PR DESCRIPTION
**Pull request by fuerbringer**

### CODE REVIEW

**Comment by waldyrious** [comment]
This is an awesome tool, thanks for adding it! But don't you need `sudo` for it to work?

**Comment by fuerbringer** [comment]
Correct. You need to be root to use nethogs (su or sudo). The user will be notified when he tries to run the program without root access.

**Comment by waldyrious** [comment]
Then please include that, since most people don't usually run as root.

**Comment by fuerbringer** [comment]
Ok. I've included sudo.

**Comment by waldyrious** [comment]
Thanks, LGTM :+1:

**Comment by felixonmars** [comment]
Please squash the commits, thanks ;)

**Comment by fuerbringer** [comment]
Squashed my commits.

**Comment by felixonmars** [comment]
:+1: Thanks!

**Pull request merged**
