### PR TITLE
cat: remove examples with the option "-u"

### PR DESCRIPTION
**Pull request by tricantivu**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** 9.3

As mentioned in the comments of #11821, the GNU implementation of the command [`cat` does ignores the option `-u`](https://github.com/coreutils/coreutils/blob/master/src/cat.c#L18).  

~~By the way, I noticed some of the placeholders and backticks were a little bit off. Should I do anything about them?~~

### CODE REVIEW

**Review by vitorhcl — APPROVED** [review]

**Comment by vitorhcl** [comment]
> By the way, I noticed some of the placeholders and backticks were a little bit off. Should I do anything about them?

I can't see them, could you show me please?

**Comment by vitorhcl** [comment]
> 
> Hello! I've noticed something unusual when checking this PR:
> 
> - The page `pages.hi/linux/cat.md` already exists under the `common` platform.
> - The page `pages.ml/linux/cat.md` already exists under the `common` platform.
> - The page `pages.pt_BR/linux/cat.md` already exists under the `common` platform.
> - The page `pages/linux/cat.md` already exists under the `common` platform.
> 
> Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.
> 

@sebastiaanspeck hmm, so these are the type of false positives that will be fixed by #11980, right?

**Comment by tricantivu** [comment]
> > By the way, I noticed some of the placeholders and backticks were a little bit off. Should I do anything about them?
> 
> I can't see them, could you show me please?
> 
> 

Sorry, I made a mistake. Most likely my editor is misconfigured and/or outdated (e.g. some characters were shown with an escape sequence).

**Review by cyqsimon — APPROVED** [review]
Good catch!

**Comment by tricantivu** [comment]
> Good catch!

@gutjuri and @sebastiaanspeck  were the ones who originally noticed this. I just peeked the source code (e.g. `git log --follow src/cat.c`) of the *coreutils* project and edited the files.

**Comment by tricantivu** [comment]
Should I create another pull request your suggested changes @vitorhcl?

**Comment by vitorhcl** [comment]
> Should I create another pull request your suggested changes @vitorhcl?

Sorry, I'm not sure what you're talking about

**Pull request merged**
