### PR TITLE
xclip: update

### PR DESCRIPTION
**Pull request by roxchgt**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

[xlip man page](https://man.cx/xclip)

### CODE REVIEW

**Comment by navarroaxel** [comment]
Hey @roxchgt. You should fix your commit's author to fix the `license/cla` check. First, squash the commits usings:

```bash
git reset HEAD~1 --soft
git commit --amend --no-edit
```
Then, fix the author with:

```bash
git commit --amend --author 'Your name <user@example.com>'
git push --force
```

And the name and email must match your GitHub account.

**Comment by roxchgt** [comment]
> Hey @roxchgt. You should fix your commit's author to fix the `license/cla` check. First, squash the commits usings:
> 
> ```shell
> git reset HEAD~1 --soft
> git commit --amend --no-edit
> ```
> 
> Then, fix the author with:
> 
> ```shell
> git commit --amend --author 'Your name <user@example.com>'
> git push --force
> ```
> 
> And the name and email must match your GitHub account.

Oh sorry, I had forgot to set the local repo config. The global was probably taken which is not related to my github

**Comment by sbrl** [comment]
Hey there, @roxchgt! Is there any reason why you closed this PR? Anything we can help with?

**Comment by roxchgt** [comment]
@sbrl I messed it up with this author thing (see above)… I resetted my repo back, set my local config `user.name` & `user.email`, commit `--amend` (unfortunately w/p `--author`, since i though my config is set now correctly, which didn't fix the problem) and it appeared as 2 users, also the checks couldn't proceed because of forced push... so I decided to close this and open a new req (4985)

**Comment by sbrl** [comment]
No worries! Thanks for clarifying :-)

**Pull request closed without merging**
