### PR TITLE
aria2c: Add Indonesian translation

### PR DESCRIPTION
**Pull request by frostg-012**
- [x] The page(s) are in the correct platform directories: `common`.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by reinhart1010** [comment]
LGTM to me, even though the `{{url}}` part could be replaced into something like `{{http://contoh.com}}`, just like what we did in `curl` and `wget`.

**Review by reinhart1010 — APPROVED** [review]
Oh, I see that the English version also uses `url` by default.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by kbdharun** [comment]
The translation LGTM.

@reinhart1010 Your suggestion is good, Also the main page refers to both URI and URL. I am confused because 
> URI (Uniform Resource Identifiers) can represent both the URL and the URN of a resource, simultaneously, while URL can only specify the address of the resource on the internet. 

Let me ask somebody else for a review of the original page.

**Review by blueskyson — APPROVED** [review]

**Pull request merged**
