### PR TITLE
MAINTAINERS.MD: Add @schneiderl as contributor

### PR DESCRIPTION
**Pull request by schneiderl**
Just added myself as collaborator on Maintainers.md

Closes #2899

### CODE REVIEW

**Comment by mebeim** [comment]
I'd rather say "Add @schneiderl as contributor" since it's an addition rather than an a role change. Also you lost a newline there, let's keep the formatting consistent, shall we? Oh, and by the way: welcome aboard! :smile: :tada:

**Comment by schneiderl** [comment]
@mebeim made the necessary changes :)

**Comment by waldyrious** [comment]
@schneiderl please keep the double lines before level-2 headings :blush:

**Comment by mebeim** [comment]
@waldyrious they are kept. GitHub displays the diff in a weird way, but there still are two lines before the next heading.

By the way @schneiderl with my previous comment I was talking more about the commit message than the title of the PR :sweat_smile:, that's what is going to be in the history. I'm approving anyway since it can be changed when merging so that's not really a big problem.

**Comment by waldyrious** [comment]
> @waldyrious they are kept. GitHub displays the diff in a weird way, but there still are two lines before the next heading.

Right, my bad. It's what I get for reviewing PRs late at night! 😄

**Pull request merged**
