### PR TITLE
[: add Swedish translation

### PR DESCRIPTION
**Pull request by jzlpr**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]
Awesome @jzlpr.

**Comment by CleanMachine1** [comment]
Any reason you have closed?

**Comment by navarroaxel** [comment]
@CleanMachine1 I think Robert open this PR from `main` in their fork and now he'll try to open the same PR from a feature branch in the fork.

Let us know if you need any help @jzlpr! We're here to help.

**Comment by jzlpr** [comment]
Hi

Its my first PR. Go easy on me :)
Accidentally mixed up my repo with the main. Tried to resolve the issue,
but ended up making it worse, so I deleted the PR.

I will try again at a later time.

**Comment by CleanMachine1** [comment]
Should be pretty simple for you to do.

I assume you are using git on the command-line.

go to your cloned fork.
```git branch sv/[
git checkout sv/[```

make the file and add, then commit.

Sorry if this is patronizing.

**Comment by jzlpr** [comment]
Hi
No worries. I have added the file to my forked then pushed.
New PR.

Sorry for late answer and duplicating PR

:)

**Pull request closed without merging**
