### PR TITLE
MAINTAINERS.md: Add @andrik & @Aracki as repos collaborators

### LINKED ISSUE #2988: Add @andrik and @Aracki as contributors
Hi, @andrik and @Aracki! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#2895, #2854, #2860, #2866, #2924, .... | #2478, #2503, #2582, #2616, #2617, .......)!
That qualifies you to become collaborators in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As collaborators, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as collaborators?

Either way, thanks for all your work so far!

### PR DESCRIPTION
**Pull request by Aracki**
I have added @andrik & @Aracki as repository collaborators.

Closes #2988.

### CODE REVIEW

**Comment by waldyrious** [comment]
Before merging, let's wait for confirmation from both @Andrik and @Aracki that they've accepted the invitation at #2988.

**Comment by pxgamer** [comment]
@waldyrious, I assumed that https://github.com/tldr-pages/tldr/issues/2988#issuecomment-490493462 and https://github.com/tldr-pages/tldr/issues/2988#issuecomment-490585158 were the confirmations. 🤔

**Comment by Aracki** [comment]
I accepted it.

**Comment by waldyrious** [comment]
The invites are only sent once the contributor(s) agrees with the proposal, as @sbrl's comments attest. What I meant was public confirmations that the invites have been accepted, as @Aracki did above. That's not a big deal, of course, but it helps us make sure that the closing of the issue only happens once all the steps are completed (the last one being the merge of this PR).

**Comment by andrik** [comment]
I accepted it

**Comment by waldyrious** [comment]
Thanks guys!

**Pull request merged**
