### PR TITLE
Add trailing newline to Korean pages

### PR DESCRIPTION
**Pull request by mebeim**
All common Korean pages were missing a trailing newline.

### CODE REVIEW

**Comment by Proscream** [comment]
@mebeim I'm sorry, but I don't know what's changed. If you let me know, I think it will be helpful to translate in the future!

**Comment by mebeim** [comment]
@Proscream I only added a newline (`\n`) at the end of each page since it was missing.

**Comment by Proscream** [comment]
Thank you for your comments.

**Comment by einverne** [comment]
Oh, did not notice the tailing line missing when review. I will be careful in the future.

**Comment by mebeim** [comment]
@einverne that's hard to notice! The only real way is cloning the fork and running `markdownlint` on it 😅

**Comment by mebeim** [comment]
If only our build script correctly identified the issue... that's another thing I'm currently investigating.

**Pull request merged**
