### PR TITLE
vim, nvim: add ZZ in save and exit example 

### PR DESCRIPTION
**Pull request by Managor**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by renie — APPROVED** [review]
LGTM. Even more because you've changed my life with this :exploding_head:

**Review by acuteenvy — COMMENTED** [review]
`ZZ` only writes if the file has been modified - it's equivalent to `:x`.
`:wq` writes to the file regardless of whether it's been changed or not.

**Comment by Managor** [comment]
What is the practical difference of those operations? Just the fact that the file timestamp gets modified?

**Comment by acuteenvy** [comment]
> What is the practical difference of those operations? Just the fact that the file timestamp gets modified?

On an unmodified file, yes. Otherwise there's no difference.

**Comment by Managor** [comment]
For the purposes of this example I don't see it as any issue. The `:wq` portion is to let the new users know this is the command that everyone tells you to use on the internet and the `ZZ` portion is to let the user know that you can also use this.

**Review by acuteenvy — APPROVED** [review]

**Pull request merged**
