### PR TITLE
pages.pt_BR: add and update several pages

### PR DESCRIPTION
**Pull request by vitorhcl**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by vitorhcl** [comment]
> > Hello! I've noticed something unusual when checking this PR:
> > 
> > * The page `pages.pt_BR/common/units.md` is outdated, based on the command contents itself.
> > 
> > Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.
> 
> Could you maybe fix this? :happy:

I already fixed it in [b85a275](https://github.com/tldr-pages/tldr/pull/11829/commits/b85a27511d8934d5f5f41ab9072593b8dc30f85e) 😅

**Comment by vitorhcl** [comment]
> > > 
> > > 
> > > Could you maybe fix this? :happy:
> > 
> > 
> > I already fixed it in [b85a275](https://github.com/tldr-pages/tldr/pull/11829/commits/b85a27511d8934d5f5f41ab9072593b8dc30f85e) 😅
> 
> Sorry, thank you for adding the example that was missing, but I (and tldr-bot too), still found a mismatch with the English page: [English](https://github.com/tldr-pages/tldr/blob/d8fb25727700b594c02ac48df555049c65d4e4d8/pages/common/units.md?plain=1#L20) vs [translated page](https://github.com/vitorhcl/tldr/blob/dc36a8d43d2f47f8dce087824ecdf1a2b6dadb0e/pages.pt_BR/common/units.md?plain=1#L20). The translated page is missing double-quotes around the first argument. I saw that the file itself is not very consistent with double-quotes so I understand that you missed this one.

I'm sorry, I fixed it now

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by isaacvicente — APPROVED** [review]
LGTM :tada:

**Pull request merged**
