### PR TITLE
awk: add operators match 

### PR DESCRIPTION
**Pull request by tcarecolin**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — CHANGES_REQUESTED** [review]
Hi @tcarecolin, thanks for your submission. But the pages can't have more than 8 examples. Do you think we should edit or remove some?

**Comment by tcarecolin** [comment]
Hi @navarroaxel , yes i think we should remove some, because the use of () and operators is a verry common and useful usecase for awk

**Comment by sbrl** [comment]
@tcarecolin which other examples do you think are the least useful?

**Comment by tcarecolin** [comment]
i would certainly remove 
```
`awk '{s+=$1; print $1} END {print "--------"; print s}' {{nom_de_fichier}}`
```
which is very repetitive according to the previous one

**Comment by navarroaxel** [comment]
@tcarecolin I agree, please send a commit removing it.

**Review by navarroaxel — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Review by sbrl — APPROVED** [review]

**Pull request merged**
