### PR TITLE
vladimyr: add page

### PR DESCRIPTION
**Pull request by bl-ue**
cc @vladimyr

### CODE REVIEW

**Review by sbrl — APPROVED** [review]
Every command documented increases coverage, I suppose!

**Comment by sbrl** [comment]
(also, @bl-ue I suggest avoiding requesting review unless you really need someone's specific opinion on an issue, because otherwise it generates lots of notification noise for people.)

**Comment by vladimyr** [comment]
> Every command documented increases coverage, I suppose!

And increases distribution aka `tldr.zip` size. As much as I can't say no to being _famous_ let's think a bit about bandwidth costs here.

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
Well @vladimyr image someone install the command for some reason, maybe he wants to experiment with it (I do that a lot) and then forgets about it.  Sometime later, when he's forgotten about it, he checks `tldr vladimyr` and then he remembers what it is.  For example, a user might with a script globally install a lot of packages that have `"bin":` in their `package.json`s and he runs `for command in ... ; do tldr $command >> commands.txt; done` or something to that effect.

**Pull request merged**
