### PR TITLE
Update jq page with correct command format

### PR DESCRIPTION
**Pull request by chuanjin**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by agnivade** [comment]
It works fine without the quotes here. Did you mean to add it to prevent them from being shell-escaped due to some reason ?

**Comment by chuanjin** [comment]
It works in Bash, but not other shell e.g. zsh, I have to put the quotes to make it work for both.  @agnivade

**Comment by chuanjin** [comment]
I have signed the Contributor License Agreement, not sure why is still showing "not signed yet".

**Comment by agnivade** [comment]
That is because the email you have used in your commit and your github email does not match.

**Comment by chuanjin** [comment]
I will fix it, thanks @agnivade

**Pull request merged**
