### PR TITLE
timew: tweaks to descriptions

### PR DESCRIPTION
**Pull request by waldyrious**
Just a couple tweaks I feel make the descriptions slightly more natural. Follow-up of #1343.

### CODE REVIEW

**Comment by waldyrious** [comment]
Why doesn't @mention-bot like my PRs? :( /cc @abactel

**Comment by abactel** [comment]
This looks good to me

**Comment by sbrl** [comment]
Shall I merge?

**Comment by waldyrious** [comment]
@sbrl since this PR was proposed by a maintainer, which we normally count that as one of the two required approvals, technically it's fine to merge. Socially, it is good to also wait for previous contributors to the page to have their say, especially if they have been pinged. Given that both conditions are fulfilled here, sure, go ahead :)

**Comment by sbrl** [comment]
Merge complete! Delete the branch at your leisure :D

**Pull request merged**
