### PR TITLE
deps: upgrade husky to v7.0.1

### PR DESCRIPTION
**Pull request by navarroaxel**
- [`glob`](https://www.npmjs.com/package/glob) — `7.1.6` → `7.1.7`
- [`husky`](https://www.npmjs.com/package/husky) — `6.0.0` → `7.0.1`

The `.husky/.gitignore` is now unnecessary https://github.com/typicode/husky/releases/tag/v7.0.0

### CODE REVIEW

**Review by marchersimon — APPROVED** [review]

**Comment by marchersimon** [comment]
I didn't ever notice that directory before. Why does it do?

**Review by owenvoke — APPROVED** [review]

**Review by mfrw — APPROVED** [review]
LGTM

**Comment by navarroaxel** [comment]
> I didn't ever notice that directory before. Why does it do?

@marchersimon It's just the hooks scripts and some generated stuff from Husky to inject the bash script.

**Comment by CleanMachine1** [comment]
Nevermind, I couldn't see that the file had been deleted

**Pull request merged**
