### PR TITLE
Revert "pacman: update install instructions"

### PR DESCRIPTION
**Pull request by agnivade**
This reverts commit 37ff096332183e7bc87635e9aaea70f5e25b9936.

See discussion at https://github.com/tldr-pages/tldr/pull/1562#issuecomment-346997167

### CODE REVIEW

**Comment by agnivade** [comment]
ping @Foxboron

**Comment by Foxboron** [comment]
Looks great, thanks!

**Comment by agnivade** [comment]
@sbrl - I am going ahead and merging this since its a revert of an already submitted PR. You can follow the link to the discussion above for more context.

**Comment by sbrl** [comment]
@agnivade Thanks! Just read it through. Looks like this revert should go ahead.

**Pull request merged**
