### PR TITLE
README: add link to Techno-Disaster repo and Google Play app

### PR DESCRIPTION
**Pull request by Techno-Disaster**
New android client. App is in review on the store, the link should be operational soon

### CODE REVIEW

**Comment by bl-ue** [comment]
Reall cool @Techno-Disaster.  However, I'm slightly concerned about the name `tldr`, because that almost makes it seem like that's the root project rather than just a client.  @sbrl, @owenvoke, @mebeim - do you have any opinions?

**Comment by Techno-Disaster** [comment]
> Really cool @Techno-Disaster.  However, I'm slightly concerned about the name `tldr`, because that almost makes it seem like that's the root project rather than just a client.  @sbrl, @owenvoke, @mebeim - do you have any opinions?

The play store listing is going to say ``` tldr man-pages``` and I could change the repo name anyday. Open to any other suggestions.

**Comment by bl-ue** [comment]
What about changing the repo name to something like `tldr-android`?

**Comment by Techno-Disaster** [comment]
> What about changing the repo name to something like `tldr-android`?

sure it's in flutter so I'll do ```tldr-flutter``` . What about the name on the playstore?

**Comment by bl-ue** [comment]
I don't think that needs to be changes.  `tldr man-pages` sounds good to me 👍🏻

**Review by sbrl — APPROVED** [review]
Looks ok to me! Thanks, @Techno-Disaster :D

Let's wait until the link is operational before we merge this PR.

**Comment by Techno-Disaster** [comment]
> Looks ok to me! Thanks, @Techno-Disaster :D
> 
> Let's wait until the link is operational before we merge this PR.

Sounds good. I actually released it to closed testing for some testing but will update it on the production track on playstore soon after that, so this might take a few weeks considering google's review times

**Review by owenvoke — APPROVED** [review]
LGTM once the repo has been renamed. 👍🏻 I agree that `tldr-flutter` might be better.

**Review by bl-ue — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Comment by Techno-Disaster** [comment]
Hey @bl-ue small update, the update is live [here](https://play.google.com/store/apps/details?id=wtf.technodisaster.tldr)  and I changed the repo name to ```tldr-flutter```. Can we merge this now?

**Comment by owenvoke** [comment]
@Techno-Disaster, merged! Thank you. 👏🏻

**Pull request merged**
