### PR TITLE
ansible-pull: add German translation

### PR DESCRIPTION
**Pull request by 1H0**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
Welcome to tldr, Translate command arguments inside `{{}}`.

**Comment by navarroaxel** [comment]
@1H0 could you please translate the placeholders?

**Comment by 1H0** [comment]
Yes, you're right I forgot `hosts_file` there and just fixed it. The other parameters like `branch`, `playbook` or `repository_url` are not really translatable into German in my opinion. If we talk about Ansible playbooks in German, we use the English term because it's a technical term and usually don't translate it to "Spielbuch" for example.

**Review by navarroaxel — APPROVED** [review]
It's repository and branch isn't translated in German Git pages

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
