### PR TITLE
lsb_release: add Spanish translation

### PR DESCRIPTION
**Pull request by ivanhercaz**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by ivanhercaz** [comment]
You're welcome, @sbrl! I hope to see a Spanish-speaker reviewing the translations I done. The translations are better when they are reviewed by more than one user. I will try to encourage some mate to join this awesome project.

**Comment by zdroid** [comment]
@ivanhercaz If you get 5 own PRs merged, you'll be able to review the PRs of others yourself (see [Community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md)). :smile:

**Comment by ivanhercaz** [comment]
> @ivanhercaz If you get 5 own PRs merged, you'll be able to review the PRs of others yourself (see [Community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md)).

Yes! I read it after to contribute with both PRs. It would be a pleasure to help in this project.

**Comment by zdroid** [comment]
For some reason CLA bot doesn't work here. :o

**Comment by ivanhercaz** [comment]
> For some reason CLA bot doesn't work here. :o

It is something very strange. I sign #3669 without problems but in this case I didn't receive a message by CLA bot nor seem to be auto-signed. I thought it would sign automatically due I sign the another PR.

**Comment by zdroid** [comment]
The trick worked. :tada:

**Comment by sbrl** [comment]
Currently we don't have the detection process automated, so once you've got 5 PRs merged you may need to poke us on Gitter: https://gitter.im/tldr-pages/tldr :P

**Comment by zdroid** [comment]
@sbrl You're a bit late to the party. #3690 #3691

**Comment by sbrl** [comment]
I work through my notifications in chronological order, @zdroid.

**Pull request merged**
