### PR TITLE
Add `du -m`

### PR DESCRIPTION
**Pull request by steelywing**

### CODE REVIEW

**Comment by igorshubovych** [comment]
I would split it into 2 examples.

**Comment by steelywing** [comment]
:smiley: Updated

**Comment by waldyrious** [comment]
:+1: very useful. But maybe the tokens should say "file_or_directory" for extra clarity. If you don't pay attention you might miss that "file" isn't part of a path.

**Comment by igorshubovych** [comment]
@waldyrious it is rare that you do `du` for file

**Comment by igorshubovych** [comment]
oh, now i see what you mean.
{{file/directory}} should be fixed.

**Comment by igorshubovych** [comment]
@steelywing do you need help for finishing it?

**Comment by rubenvereecken** [comment]
Cheers! :+1:

**Pull request merged**
