### PR TITLE
espanso: add page

### PR DESCRIPTION
**Pull request by nicokosi**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by bl-ue** [comment]
@ nicokosi if you can, please avoid force-pushing.  It's not necessary as we automatically squash commits before merging and it can make reviewing a bit difficult 🙂

**Comment by nicokosi** [comment]
> @nicokosi if you can, please avoid force-pushing. It's not necessary as we automatically squash commits before merging and it can make reviewing a bit difficult 🙂

Sorry, I thought it was OK since the PR is a work in progress (draft). 😇
Now stopping force-pushing. 🙂

**Comment by bl-ue** [comment]
Oh, then yeah it doesn't matter if it's a draft (sorry about that, not too observant on my part :).

**Review by bl-ue — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Comment by bl-ue** [comment]
Welcome to tldr-pages, @nicokosi! ⚡

**Pull request merged**
