### PR TITLE
pages.{ar,fa}: remove translated placeholders

### PR DESCRIPTION
**Pull request by kbdharun**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

This PR convert all translated placeholders in Arabic and Farsi pages to English to avoid flipping text in the web client and CLI. See https://github.com/tldr-pages/tldr/pull/11992#discussion_r1441553065 for additional information.

@MrMw3 Feel free to checkout the changes for Farsi pages.

> [!NOTE]
> I left the message as it is in `echo` as it isn't a generic placeholder; for `rmdir` page in Arabic I used Google translate to get the recent translation as there were differences in the placeholders.

### CODE REVIEW

**Comment by MrMw3** [comment]
you do great @kbdharun, i see the changes and there is only one problem. in `pages.ar/common/rmdir.md` you translated texts to Persian (Farsi) instead of Arabic.

**Comment by MrMw3** [comment]
> > Hello! I've noticed something unusual when checking this PR:
> > 
> > * The page `pages.fa/common/7z.md` is outdated, based on number of commands.
> > * The page `pages.fa/common/7za.md` is outdated, based on number of commands.
> > * The page `pages.fa/common/7zr.md` is outdated, based on number of commands.
> > 
> > Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.
> 
> @MrMw3 could you update these pages to reflect the English pages?

Yes, i'll going to do it.

**Comment by kbdharun** [comment]
> you do great @kbdharun, i see the changes and there is only one problem. in `pages.ar/common/rmdir.md` you translated texts to Persian (Farsi) instead of Arabic.

Nice catch, will fix it.

**Review by gutjuri — APPROVED** [review]

**Comment by kbdharun** [comment]
> pages.ar/common/rmdir.md was issued as malformed [more info](https://github.com/tldr-pages/tldr/blob/11ada1bc2471b6cab31280bd03f19ec66dc626c1/pages.ar/common/rmdir.md?plain=1#L5). Is the More Information-translation in the [script](https://github.com/tldr-pages/tldr/blob/11ada1bc2471b6cab31280bd03f19ec66dc626c1/scripts/set-more-info-link.py#L52) incorrect?

Will fix it.

**Pull request merged**
