### PR TITLE
mvn: add more examples

### PR DESCRIPTION
**Pull request by anirudhts**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by agnivade** [comment]
What @einverne said. The mvn page was written after careful analysis from real world usage on the most commonly used options. I don't think we can leave out any of those options already present.

**Comment by agnivade** [comment]
You cannot add anything else. There are already 8 examples.

**Comment by sbrl** [comment]
....unless there are some existing examples that could be improved?

**Comment by agnivade** [comment]
@sbrl - Perhaps, but I'm not sure. See my [comment](https://github.com/tldr-pages/tldr/pull/3451#issuecomment-544792622) above. I personally asked several of my friends who use mvn about what are the top commands they use every day and then compiled this list. I doubt we can remove something from here.

**Pull request closed without merging**
