### PR TITLE
Add netstat to OSX, made small changes

### PR DESCRIPTION
**Pull request by cdminigun**
Added netstat.md file to OSX. (Wasn't sure if sunos had netstat, if it does, netstat should be moved to common)

Added some changes for common use cases for netstat. 

Added the -t (TCP) and -c (Continuous) options.

### CODE REVIEW

**Comment by igorshubovych** [comment]
1. Please squash 6 commits
2. Please avoid using | grep. See rule 6 from [Contributing Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md).

**Comment by cdminigun** [comment]
1. Squashed commits. 

2. Followed your advice and removed the last two entries. (They were duplicates without grep)

**Comment by igorshubovych** [comment]
Right, but check out also last example on osx page:
`netstat -ap | grep ':80'`

1. It is not correct (it says "netstat: option requires an argument -- p" on my Mac).
2. We try to avoid using other commands in examples.

**Comment by cdminigun** [comment]
Ah, I missed that portion of it during rebase. That was a portion intended to be deleted. 

Fixed the -p option as well. On OSX it requires a protocol attached to it. As such, OSX does need it's own netstat.md 

Tested all current commands to make sure they worked in both OSX and linux.  Let me know if there are any other changes that you think should be made.

**Comment by igorshubovych** [comment]
Great! Thanks, @cdminigun!
Well done!

**Pull request merged**
