### PR TITLE
tput: add two examples

### PR DESCRIPTION
**Pull request by jeeftor**
* Added `word wrap` examples
So I kind of pushed us to 7 examples here - however - i feel like if you have an enable word wrap command you need to also know how to disable it.

### CODE REVIEW

**Comment by agnivade** [comment]
Ah thats a good point @waldyrious. Lets do that @jeeftor

**Comment by jeeftor** [comment]
@waldyrious - I made the changes you requested.  Will you re-review?

**Comment by agnivade** [comment]
@waldyrious - ping :)

**Comment by jeeftor** [comment]
@waldyrious ping again ...

**Comment by waldyrious** [comment]
So sorry guys for the delay!

**Pull request merged**
