### PR TITLE
Nautilus

### PR DESCRIPTION
**Pull request by thomas-m-d**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Added a page for the terminal command to Gnome's default file explorer, Nautilus (also known as Gnome Files).

### CODE REVIEW

**Comment by thomas-m-d** [comment]
i forgot to add periods at the end of the command descriptions, so i'm closing this pr and opening a new one with the fixes committed.

**Comment by marchersimon** [comment]
@thomas-m-d you can always push commits to the branch you opened the PR with. No need to close and open a new one.

**Comment by thomas-m-d** [comment]
> @thomas-m-d you can always push commits to the branch you opened the PR with. No need to close and open a new one.

thanks. i'm still getting used to how github handles everything :/

**Comment by marchersimon** [comment]
No problem, it can be quite overwhelming at the beginning. Feel free to ask if you have any questions.

**Pull request closed without merging**
