### PR TITLE
obabel: fix typo

### PR DESCRIPTION
**Pull request by Acetylsalicylsaeure**
insert forgotten "

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by spageektti — APPROVED** [review]

**Comment by spageektti** [comment]
@Acetylsalicylsaeure you need to create another branch in your fork to submit another PR for the new page

**Comment by Acetylsalicylsaeure** [comment]
> Do you want to add mopac in the same PR or is that done by mistake?

my bad, forgot to branch

removed the page for mopac

**Comment by spageektti** [comment]
For future I suggest not using main branch to avoid mistakes.

**Review by spageektti — APPROVED** [review]
Thanks for your contribution!

**Review by kbdharun — APPROVED** [review]

**Comment by kbdharun** [comment]
Nice catch, thanks for the fix.

**Pull request merged**
