### PR TITLE
a2disconf, a2enconf: add pt_PT translation

### PR DESCRIPTION
**Pull request by tcarrondo**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Review by waldyrious — CHANGES_REQUESTED** [review]
Great contribution! The only remarks I'd make are the same ones I left in #7177: Using ~~the infinitive tense,~~ the new orthography, and "em" instead of "nas" in the page descriptions.

**Comment by waldyrious** [comment]
I've removed the request to use the infinitive tense following the discussion at #7159, but the other suggestions remain. Let me know what you think, @tcarrondo!

**Comment by tcarrondo** [comment]
@waldyrious done. thanks, you rock!

**Review by waldyrious — APPROVED** [review]
Nice! Thanks for bearing with the clunky review :) we're still working out the multilingual content guidelines.

**Pull request merged**
