### PR TITLE
grep: remove 2 examples

### LINKED ISSUE #1695: Grep page has 10 examples
This might be overly pedantic, but the contribution guidelines specify no more than 8 examples. Grep has 10.

### PR DESCRIPTION
**Pull request by agnivade**
Make the page conform to our maximum limit of 8 examples

Fixes #1695

----

~- [ ] The page (if new), does not already exist in the repo.~

~- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
I have removed the 2 examples which I feel are least used amongst all of the others. Feel free to comment if you think some other option needs to be removed.

**Comment by sbrl** [comment]
I agree about the count one, but perhaps we could merge the line numbers and filename ones to get us under the limit? I find the filenames one to be rather useful when grepping multiple files myself (i.e. with a glob).

**Comment by agnivade** [comment]
Noted. @waldyrious - Do you have any thoughts ?

**Comment by gnebehay** [comment]
If we keep the filename example, could we change it from `-l` to `-H`? The problem with `-l` is that it suppresses all other output, while `-H` just adds the filename in the beginning of the line, which is what I imagine is more useful.

**Comment by agnivade** [comment]
Done

**Pull request merged**
