### PR TITLE
stale.yml: Change time for issues to be stale

### PR DESCRIPTION
**Pull request by CleanMachine1**
Some issues are being marked as stale, when they shouldn't be such as page request

I suggest that we either: 

Do what is done here, increasing the time for issues to be marked as stale and be closed

OR

make stalebot ignore the help wanted labelled issues

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
I suggest to close PRs just when:
- no opened issue linked to PR **and**
- no activity happened in them for a long time **and**
- no `help wanted` label present in PR or it's issue

**Review by owenvoke — APPROVED** [review]
LGTM! We could perhaps add `help wanted` to the `exempt-pr-labels` list as well, as mentioned by @EmilySeville7cfg 👍🏻 Regarding linked issues, we could probably PR support for that to the `actions/stale` action. 🤷🏻

**Comment by CleanMachine1** [comment]
https://github.com/tldr-pages/tldr/pull/8114/commits/ca6cfc740822ebcb77f112b21cd327bf8004fb40 From what I can tell, this is the correct syntax what what I found [here](https://github.com/actions/stale#exempt-issue-labels)

**Review by EmilySeville7cfg — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
Should I merge it now or wait another reviewers?

**Comment by owenvoke** [comment]
I think 2 reviewers is enough 👍🏻

**Pull request merged**
