### PR TITLE
hostname: add page

### PR DESCRIPTION
**Pull request by igorshubovych**

### CODE REVIEW

**Comment by waldyrious** [comment]
lgtm :+1:

**Comment by rubenvereecken** [comment]
Hehe it's Java cased (NewHostname). Looks good though :+1:

**Comment by igorshubovych** [comment]
@rubenvereecken what do you think it should be?

{{new.host.name}} to highlight the fact that it is a host name? Or {{new hostname}}, or what?

**Comment by rprieto** [comment]
I don't mind either, but if we with the second one someone recommended we use `new_hostname` to avoid confusion when colours are turned on (otherwise it might look like two arguments).

**Comment by igorshubovych** [comment]
ok. i will redo camelCase to snake_case.

@rprieto, could you plz also reply to my email?

**Comment by igorshubovych** [comment]
i fixed from {{NewHostname}} to {{new_hostname}}.

BTW, it turned to be that {{new.host.name}} looks also good in `tldr-node-client`. Anyway this variant should be acceptable.

**Comment by rprieto** [comment]
Ah I didn't mind camel case, it was in reply to the suggestion of `{{new hostname}}`.

**Comment by waldyrious** [comment]
I think we should have a standard format for arguments, for consistency's sake. Separating words with either underscore or period seems good to me.

**Comment by rubenvereecken** [comment]
I like rprieto's last example best. If absolutely need be I could suffer undercases. But yes, consistency would be welcome. Sorry to have this on your thread, Igor!

**Comment by igorshubovych** [comment]
Then I changed it to {{new.host.name}}. Looks much better, and the idea also resembles {{path/to/directory}} used on other pages.

**Comment by rubenvereecken** [comment]
The objection I would have that I just thought of when I saw the `java` page pass by without actually looking at it:

`java -jar {{executable.thing.jar}}`
vs
`java -jar {{executable_thing.jar}}`

The latter, underscores, is useful if you want to hint at file extension and the like.

**Comment by rprieto** [comment]
I would definitely not use `.` as a word separator in the general case, underscores or camel case feel more natural to me. I thought is was being proposed here because that's what hostnames look like.

**Comment by rubenvereecken** [comment]
Ah fair point, I now take Igor's meaning. Sleepy me was only thinking of the discussion on consistency. 

Great, I like this one.

**Comment by waldyrious** [comment]
Good points about the file extensions. I retract my support for periods as word separators and support onlynunderscores instead. CamelCase for some reason doesn't seem to fit well to my eyes in the command line, but that's probably just a stylistic choice.

**Comment by igorshubovych** [comment]
Ok. I redid that with snake_case.

We broke too many spears arguing about this tiny issue. Probably we need to add rule in Contributing Guidelines about tokens.

**Comment by waldyrious** [comment]
> Probably we need to add rule in Contributing Guidelines about tokens.

Exactly, my goal with this discussion was not to nitpick on this particular PR, but to take the opportunity (since the issue arised here naturally) to settle the matter in a definitive way, which we could then add to CONTRIBUTING.md :)

In that sense, would you guys say there is a consensus?

**Pull request merged**
