### PR TITLE
cmd, hyperfine, neofetch: add Italian translation 

### PR DESCRIPTION
**Pull request by gsobell**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
@gsobell Please create a new branch in your fork and add `zathura` there. If you need help with Git just ask for help.

**Review by sbrl — APPROVED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

**Comment by navarroaxel** [comment]
Thanks @gsobell, try to not send PRs from the `main` branch in your fork and keep it in sync with the `tldr-pages:main`, otherwise you can branch from your `main` to create PRs because the branch is dirty.

**Comment by gsobell** [comment]
Noted, will do.

**Pull request merged**
