### PR TITLE
create_ap: add page

### PR DESCRIPTION
**Pull request by 7vikpeculiar**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey - thanks for the new page, @7vikpeculiar! Looks like you're having some issues with the linter. We've got the style we prefer documented over [here](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format), and a few good examples are the pages for `tar`, `eyeD3`, and `ln`. If you need any assistance, just ask :smiley_cat:

**Comment by sbrl** [comment]
Hey, @7vikpeculiar you appear to have closed this PR. Is there anything I can help you with at all?

**Comment by bl-ue** [comment]
@7vikpeculiar if you reopen this PR, I'll help you fix the errors.  They're easy ones.

**Comment by bl-ue** [comment]
Never mind! I see you opened a new one #2884.

**Pull request closed without merging**
