### PR TITLE
amass*: update translations

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by vitorhcl — APPROVED** [review]
Portuguese and Spanish translations LGTM

**Review by isaacvicente — APPROVED** [review]

**Review by noraj — COMMENTED** [review]
LGTM for french part

**Review by Nico385412 — APPROVED** [review]
LGTM for the french part too

**Review by leonvsc — APPROVED** [review]
Dutch part looks good to me!

**Review by blueskyson — APPROVED** [review]

**Pull request merged**
