### PR TITLE
jwt: add space in algorithm list in description

### PR DESCRIPTION
**Pull request by bl-ue**
https://github.com/tldr-pages/tldr/issues/5111#issuecomment-758038458

### CODE REVIEW

**Review by waldyrious — APPROVED** [review]
Thanks! Merging straight away, as a trivial fix.

**Review by MasterOdin — APPROVED** [review]

**Review by owenvoke — APPROVED** [review]

**Comment by bl-ue** [comment]
@waldyrious I know! I about to do the same thing once but I was stopped too! 😆

**Comment by navarroaxel** [comment]
> Thanks! ~Merging straight away, as a trivial fix.~ Actually, only org members (or owners?) can bypass PR merge rules, in this case the "two approvals" rule. 

@waldyrious Only org owners.

**Comment by bl-ue** [comment]
@waldyrious why not become an org owner again? :)

**Comment by waldyrious** [comment]
> @waldyrious Only org owners.

Thanks for the confirmation @navarroaxel! We may need to update the maintainer's guide to clarify this, expecially in the [Handling PRs](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md#ii-handling-prs) section. @bl-ue would you like to tackle that?

In addition, maybe we should also expand the description org owners's abilities in [MAINTAINERS.md](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md#organization-owners), in the same vein as #5123 (although that would likely mean adding lot more information... 🤔 maybe a link to the [documentation](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/permission-levels-for-an-organization) would be helpful there as well.)

**Comment by waldyrious** [comment]
> @waldyrious why not become an org owner again? :)

I actually find it quite useful to be able to see things from the perspective of someone with limited permissions, as we often tend to forget how things aren't as easy for other people when the path is made easier for us (e.g. I've seen people closing issues on GitHub and asking the reporter to reopen if they're not satisfied, but they actually cannot do that — which ends up making that closing action a lot more aggressive than what may have been intended).

Additionally, I do want this inconvenience to remain in place, sort of as a constant reminder to make sure I get around to amending our policies to make the role transitions into a monotonic (forward-only) path, as I [recently suggested](https://gitter.im/tldr-pages/tldr?at=5fe7512793af5216fc6474d3) — for example, by introducing a "maintainer emeritus" role.

**Comment by bl-ue** [comment]
Okay, sounds good.  That does seem useful.

You're full of interesting thoughts! :)

**Comment by bl-ue** [comment]
>Thanks for the confirmation @navarroaxel! We may need to update the maintainer's guide to clarify this, expecially in the Handling PRs section. @bl-ue would you like to tackle that?

Sure! I'll take care of it.

**Comment by bl-ue** [comment]
Hey @waldyrious — your [maintainer emeritus / forward-only](https://github.com/tldr-pages/tldr/pull/5135#issuecomment-758247180) is cool stuff — I'd love to see it implemented :)

**Pull request merged**
