### PR TITLE
rsync: modify one example with more useful flags

### PR DESCRIPTION
**Pull request by Khord**
----

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, @agnivade! The CLA Assistant seems broken. What should we do here?

**Comment by agnivade** [comment]
@Khord - Could you click on this [link](https://cla-assistant.io/tldr-pages/tldr?pullRequest=2477) again ?

**Comment by sbrl** [comment]
All fixed :D

**Comment by agnivade** [comment]
FWIW, the `--progress` flag is already there in a later example. So I don't think it is necessary. We don't clobber all the flags in a single command, rather introduce each flag one by one and let the user build up complex examples.

**Pull request merged**
