### PR TITLE
docker: add German translation

### PR DESCRIPTION
**Pull request by Abrynos**

### CODE REVIEW

**Review by navarroaxel — CHANGES_REQUESTED** [review]
Hey @Abrynos, thanks for your submission.

Can you translate the variables like `{{container_name}}` and `{{image}}` for make this easier for non-English speakers?

Remember that for translations you can send more than 1 translated page in 1 PR, just keep 1 commit per file and no more than 10 pages. This doesn't apply to the primary «English» pages.

**Comment by Abrynos** [comment]
Well... "name" is also the german word for "name" and we use the words "container" and "image" in german as well.

If we translated "image" verbatim we would end up with "Bild", which may be a correct translation for the word, but is completely wrong in the context of docker, as it has the meaning of "picture" and is not associated with being a template for something else. Same problem occurs if we verbatim-translate "container". I've never heard a university professor use any form of german translation. (Also the word "container" is already part of the german language used to describe containers on ships).

**Review by navarroaxel — APPROVED** [review]
Thanks for the clarification @Abrynos, I don't know the language but the format looks good.

**Review by sbrl — APPROVED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

**Pull request merged**
