### PR TITLE
history: remove examples

### PR DESCRIPTION
**Pull request by marchersimon**
[Ref](https://github.com/tldr-pages/tldr/pull/5455#issuecomment-800191933)

### CODE REVIEW

**Review by navarroaxel — CHANGES_REQUESTED** [review]
I don't see why we delete these 2 examples, because these are valid ones.
Oh, you want to add `!!` here? :upside_down_face: sounds strange.

**Comment by marchersimon** [comment]
That was the idea of @bl-ue [here](https://github.com/tldr-pages/tldr/pull/5455#issuecomment-800191933). 
But actually I could refer to the new `!!` page in the description.

**Comment by bl-ue** [comment]
Only do this if you plan to fill this page up to 8—@marchersimon is that you're plan?  Otherwise, there's no need to remove the examples because they have _some_ use.

**Comment by marchersimon** [comment]
Okay, that was a misunderstanding on my part, I'll leave them in.

**Pull request closed without merging**
