### PR TITLE
docker: update docker commands to conform to Docker 1.13

### PR DESCRIPTION
**Pull request by djung460**
----

~~- [ ] The page (if new), does not already exist in the repo.~~

~~- [ ] The page (if new), has been added to the correct platform folder: 
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
ping @jeeftor

**Comment by sbrl** [comment]
Ah, cool! Thanks for the update. So there's now a `container` action in docker? Does that mean there are now other actions it can perform?

**Comment by djung460** [comment]
Same actions, just renamed. It's nice because it adds more structure to commands in the form of`docker <logical object> <command>`. Also since Docker might stop supporting the older commands I figured it would be good to prepare for that and update these. :)

**Comment by sbrl** [comment]
Thanks for the PR, @djung460!

**Comment by djung460** [comment]
No problemo, happy to contribute!

**Pull request merged**
