### PR TITLE
add bashmarks.sh https://github.com/huyng/bashmarks

### PR DESCRIPTION
**Pull request by MattMcFarland**

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for your contribution! Just a small nitpick: please use the infinitive tense (Goes-->Go, Saves-->Save, etc.) in the example descriptions.

**Comment by MattMcFarland** [comment]
Thanks! I've updated the descriptions per your request.

**Comment by igorshubovych** [comment]
Please squash commits

**Comment by MattMcFarland** [comment]
I'm sorry, but I don't know how.  Can you elaborate?

**Comment by plessbd** [comment]
@MattMcFarland: https://davidwalsh.name/squash-commits-git

**Comment by MattMcFarland** [comment]
I'm sorry I followed the instructions there but I get noop when I try to use rebase.  I'm lost and not sure how to squish them.   

```
noop

# Rebase 268a6fe..268a6fe onto 268a6fe (1 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```

I cant do anything with `noop`

I then do `:q` to quit

I get this response:
`Successfully rebased and updated refs/heads/bashmarks.`

then I try `git status`

I get this:
```
git status
On branch bashmarks
nothing to commit, working directory clean
```

I even tried `git push -f`


It's not working. sorry wish I could contribute to this project but its starting to take too much of my time.  I have too many things going on right now, I'll see if I can try again later some time, maybe I can just restart from scratch, might be faster.

Thanks anyway and thanks for making an awesome command line app

**Comment by igorshubovych** [comment]
@MattMcFarland 
Nevermind. In simple cases we can do exceptions.

Just FYI, we are insisting on squashing commits, because every pull request gots a lot of feedback, and so there are many commits related to one PR. If we don't do it, our history will soon got unreadable.

Check this video tutorial: https://www.youtube.com/watch?v=qh9KtjfjzCU

**Comment by igorshubovych** [comment]
LGTM

**Comment by MattMcFarland** [comment]
Thank you!! bookmarking the vid now.

**Pull request merged**
