### PR TITLE
Create ISSUE_TEMPLATE

### LINKED ISSUE #1069: Define and Setup Issue Template
As per https://github.com/tldr-pages/tldr/issues/980

### PR DESCRIPTION
**Pull request by agnivade**
----

~- [ ] The page (if new), does not already exist in the repo.~

~- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~

~- [ ] The page has 8 or fewer examples.~

~- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited~

~- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines~

Closes #1069

### CODE REVIEW

**Comment by sbrl** [comment]
Not sure that "add page" is correct for this PR :P

**Comment by agnivade** [comment]
Any better suggestions ? :P

**Comment by sbrl** [comment]
Maybe "ISSUE_TEMPLATE: Create initial template"? It's tough one :P

To be honest I think `Create ISSUE_TEMPLATE` or `Create issue template` would be fine. Maybe even `ISSUE_TEMPLATE: Create issue template`?

**Comment by agnivade** [comment]
ping @waldyrious

**Comment by waldyrious** [comment]
I think entry 2 should be removed, for the following reasons:

> 2. You can file an issue if you want a command added, or a page modified.

This doesn't say anything new, especially not for someone already opening an issue.

> Issues regarding overall repo architecture are also fine.

I don't think it would be clear what this means, and in any case, such issues are rare enough that including this extra bit of text provides little benefit for the extra length it adds to the template.

In addition, entry 3 (suggesting the Gitter chat room) should probably be shortened and integrated directly into the opening sentence. I don't think we have enough issues of this type (i.e, where a permanent record of the Q&A wouldn't be useful to others) to justify having this as a separate rule. Take issue #1503, for instance: it might seem like a minor issue (a non-issue, even), but the thread provides permanent, searchable documentation for that information, which will spare others the research work, should the question ever arise for someone else.

I would therefore drop the numbered list and reduce this template to two paragraphs. The longer we make this template, the less likely people are to read it.

If you agree, I'm happy to help work out alternative wordings.

**Comment by agnivade** [comment]
Yes, please go ahead.

**Comment by agnivade** [comment]
@waldyrious - Do you have some time to look at it ?

**Comment by waldyrious** [comment]
Apologies for the extended delay. Here's what I would propose:

> \

How does it look?

**Comment by agnivade** [comment]
LGTM ! Updated

**Comment by agnivade** [comment]
ping @sbrl

**Pull request merged**
