### PR TITLE
platformio: add more information link

### PR DESCRIPTION
**Pull request by Gitleptune**
Official homepage, unsure if it's needed because it's an alias.

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by navarroaxel** [comment]
The alias pages shouldn't have a link.

**Comment by Gitleptune** [comment]
Oh I thought it should because it was in #6062 
image

**Comment by navarroaxel** [comment]
> Oh I thought it should because it was in #6062

@Gitleptune Maybe an autogenerated list.
@marchersimon Could you help here?

**Comment by marchersimon** [comment]
Yep, I autogenerated that list and didn't think about aliases. But I don't see a reason not to add it. Especially when we someday implement a system which requires every page to have a more information link, we would have to differentiate between normal pages and alias pages.

**Review by sbrl — APPROVED** [review]

**Review by marchersimon — APPROVED** [review]
Thanks @Gitleptune

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
