### PR TITLE
podman: examples parity with docker

### PR DESCRIPTION
**Pull request by gjbianco**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known): N/A (applies to most/all versions)**

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by kbdharun** [comment]
@navarroaxel Should we merge this PR or wait until the other PR is merged?

**Comment by navarroaxel** [comment]
I prefer this version of podman page, the another has subcommand pages

**Comment by kbdharun** [comment]
> I prefer this version of podman page, the another has subcommand pages

I guess we can merge this PR and update the other one.

**Comment by FearTheBadger** [comment]
go for this merge, I will pull the base podman.md from my commit.

**Comment by kbdharun** [comment]
> go for this merge, I will pull the base podman.md from my commit.

Done thanks, please pull this file from base @FearTheBadger

**Pull request merged**
