### PR TITLE
Add several mkfs tools

### PR DESCRIPTION
**Pull request by 85pando**
Tools to create files systems from the command line.

Im not sure with `mke2fs.md` because thats actually the tool, but you normally use the explicit versions like `mkfs.ext2` to actually create a filesystem (much like `git-commit`). Some feedback here would be welcome. The alternative would be to split it up into three single files with each virtually the same description.

### CODE REVIEW

**Comment by sbrl** [comment]
Suggestion: mkfs.vfat

**Comment by 85pando** [comment]
(I will merge the changes when I get the go for this merge)

**Comment by 85pando** [comment]
Add colons instead of full stops to make `lint` happy.

Now `lint` is unhappy, because of full stops in title. The thing is that the tools do have full stops in their name/command.

**Comment by igorshubovych** [comment]
@85pando we will work on this.

**Comment by igorshubovych** [comment]
Linter is currently unhappy because we did not realize that name of command can contain dots.

**Comment by 85pando** [comment]
Yeah, probably a corner case, as not many tools will have this…

**Comment by rubenvereecken** [comment]
Thanks for the heads up, will be incorporated very soon. I constricted the original case because more often than not something containg a period ends in one, you'd get titles like `Git.`

**Comment by rubenvereecken** [comment]
Fixed in current master. Additionally, tldr will now use tldr-lint's master branch for Travis.

**Pull request merged**
