### PR TITLE
apt-get: add purge

### PR DESCRIPTION
**Pull request by Darexon**
----

~~- [ ] The page (if new), does not already exist in the repo.~~

~~- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

- [x] The page has 8 or fewer examples.

- [X] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [X] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines 

Added an `apt-get purge` description to the apt-get page.

### CODE REVIEW

**Comment by agnivade** [comment]
Thanks for the PR.

I am however reluctant to merge this. The `--purge` is an advanced option which is not needed by a beginner. Please keep in mind that tldr pages are not a replacement for man pages. We intentionally have a limit of 8 examples max so that we can keep the page short and contain the most useful examples. It's tldr for a reason. :wink: 

In this case, we are 7 which is cutting it pretty close without any strong reason to do so. Hence, my reluctance.

**Comment by Darexon** [comment]
Purge is included in the Aptitude page which is why I feel it should be included in the apt-get page as well.

**Comment by agnivade** [comment]
I would want it removed from aptitude page also then. We try hard to keep all pages consistent, but with so many commands and its variants across platforms, its not possible to do that always.

Overall, the central theme should be to keep it limited and tight. And mention only practical examples.

**Comment by agnivade** [comment]
Appreciate your understanding on this @Darexon. I hope this does not deter you from sending more PRs in the future. Feel free to send a PR to update the aptitude page.

**Pull request closed without merging**
