### PR TITLE
mullvad: move to common platform

### PR DESCRIPTION
**Pull request by gitsoft**
CONTRIBUTING.md read and applied to the best of my abilities.

Adding terminal commands for Mullvad VPN terminal cli.

### CODE REVIEW

**Review by navarroaxel — CHANGES_REQUESTED** [review]
Hi @gitsoft, welcome and thanks for your submission. If the command is available in another platform just move the page from `linux/` to the `common/` folder.

**Comment by gitsoft** [comment]
1. Moved markdown to common as suggested
2. Fixed trailing whitespace error
3. Signed CLA as gitsoft. No problems there.
4. Signed out and signed back in as Bjorn-QB to sign CLA (_I seem to have accidentally commited using that acount_). The CLA Page greated me as gitsoft even if I had changed account. Clearing history and cookies did not fix that issue.

Just delete my pull request if the CLA signature issue can't be solved on your end. :) I don't have time to troubleshoot the CLA page. Have a great day.

**Comment by blueskyson** [comment]
I faced the license issue caused by wrong config of my git. Close this and create a new PR is fine.

**Comment by navarroaxel** [comment]
@blueskyson we can ignore it, because the author of the merged commit will be the author of the PR and that user has signed the license.

**Comment by CleanMachine1** [comment]
Hi, I have opened #7876, this fixes this.

**Pull request closed without merging**
