### PR TITLE
  archey, arp-scan, as, aspell, at, 7z, 7za, 7zr: add chinese translations

### PR DESCRIPTION
**Pull request by HugueLiu**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform folder (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by HugueLiu** [comment]
@agnivade   I just don't fully understand what you meaning. I added 8 files , should I commit 8 times?

**Comment by HugueLiu** [comment]
And shouldn't I merge the latest updates?  If so, I will lose some contents that I committed before?

**Comment by agnivade** [comment]
> I just don't fully understand what you meaning. I added 8 files , should I commit 8 times?

Correct. That way each commit corresponds to a single page.

> And shouldn't I merge the latest updates? If so, I will lose some contents that I committed before?

No you should rebase the latest updates, not merge. See [this](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).

**Comment by HugueLiu** [comment]
Ok, I understand and I'll try to fix it. Should I reset to the position before the merge?

**Comment by HugueLiu** [comment]
My thought is as follows:
1. Reset to the point before the merge.
2. Rebase the latest updates.
3. Commit my changes one by one.
Is that right? I am worried about I will make some troubles.

**Comment by agnivade** [comment]
@waldyrious can help you with that.

**Comment by HugueLiu** [comment]
What if I close this PR and create a new branch and then send a PR once again?
I think it'll be easier.

**Comment by sbrl** [comment]
It's a shame that each page isn't in it's own commit, but I think it would be ok squashed.

**Comment by mebeim** [comment]
@HugueLiu no need to close and open a new PR! You can always push changes to this branch (`chinese`) on your fork and this PR will update automatically. If you have problems reordering your commits I can help you by telling you which commands to use.

**Comment by HugueLiu** [comment]
Thank you @mebeim, should I reset to the point before to the merge?

**Comment by mebeim** [comment]
Okay @HugueLiu, I'll start by saying that this should **not** be common practice since it's not really a clean way to work, but for this time, the simplest way to have one page per commit given the current situation is this one:

1. Checkout to your `chinese` branch:

        git checkout chinese

2. Start an interactive rebase to the first commit of the branch:

        git rebase --interactive 11f109b466cf35daefdde57a1ca2e0261f90555c

    This will open a text editor giving you the opportunity to edit the commits, you will see this:

        pick 71d3ff37 archey/arp-scan/as/aspell/at:add chinese translation
        pick b85b4f76 7z, 7za, 7zr: add chinese translations

3. In the text editor that just opened, change the `pick` to `edit` for both commits:

        edit 71d3ff37 archey/arp-scan/as/aspell/at:add chinese translation
        edit b85b4f76 7z, 7za, 7zr: add chinese translations

    And then save and close the editor.

4. Now you can edit the first commit. Remove all the files from the commit:

        git reset HEAD^1 pages.zh

5. Add the first file by amending the original commit:

        git add pages.zh/linux/archey.md
        git commit --amend -m 'archey: add Chinese translation.'

6. Now simply add and commit all the remaining files:

        git add pages.zh/linux/arp-scan.md
        git commit -m 'arp-scan: add Chinese translation.'

        git add pages.zh/linux/as.md
        git commit -m 'as: add Chinese translation.'

        git add pages.zh/linux/aspell.md
        git commit -m 'aspell: add Chinese translation.'

        git add pages.zh/linux/at.md
        git commit -m 'at: add Chinese translation.'

7. Continue the rebase to the next commit to edit:

        git rebase --continue

8. Do the same as before:

        git reset HEAD^1 pages.zh

        git add pages.zh/common/7z.md
        git commit --amend -m '7z: add Chinese translation.'

        git add pages.zh/common/7za.md
        git commit -m '7za: add Chinese translation.'

        git add pages.zh/common/7zr.md
        git commit -m '7zr: add Chinese translation.'

9. Continue the rebase to finalize it:

        git rebase --continue

10. Check if all is in order:

        git log

11. Now that everything is ok, just force push the branch:

        git push -f

**Comment by HugueLiu** [comment]
Thank you very much @mebeim. The tutorial is very detailed and clear and I have executed the commands as you said (except for  the last command), but there is still a merge, should I do something else about it? If not needed, I'll push it. Thank you again.

**Comment by mebeim** [comment]
@HugueLiu you need not to worry about that marge as far as I can tell. I cloned your repo and tested it myself. You should have something like this (output from `git log --graph --oneline`):

image

That's ready to push.

You can always create a new dummy branch and push that if you want to be 101% sure:

        git checkout -b `dummy`
        git push --set-upstream origin dummy
        # Now go on GitHub and manually check the branch.

        # Then delete it:
        git push -d dummy
        git branch -D dummy

**Comment by HugueLiu** [comment]
Thanks @mebeim, these parts  are the same as yours. But @agnivade said that I should rebase the lastest updates instead of merging them. So I think there is something that I need to do. @agnivade , need I do something else?

**Comment by agnivade** [comment]
Yes, there shouldn't be any merge commit in the branch. I will defer to @mebeim on the best approach.

**Comment by mebeim** [comment]
@HugueLiu well, yes, you can just rebase on our master, if you want.

1. If you don't have an `upstream` remote targeting `tldr-pages/tldr`, first add it:

        git remote add upstream https://github.com/tldr-pages/tldr/

2. Now checkout to your branch and rebase on `upstream/master`:

        git checkout chinese
        git fetch upstream master
        git rebase upstream/master

Now you should see your commits coming out of our `master` branch, like this:

image

Output from `git log --graph --oneline --decorate`.

**Comment by sbrl** [comment]
If anyone here is curious about git and how it works, [this might be of interest](https://learngitbranching.js.org/)

**Comment by mebeim** [comment]
@sbrl that is beautiful! I'll save it and link it to anyone asking me how git works. Pure gold. Thanks for the link 😎

**Comment by mebeim** [comment]
That looks perfect! Thank you for these translations @HugueLiu :smile:, merging this.

**Comment by sbrl** [comment]
No problem, @mebeim! It's great - I'm so glad I remembered it's name. I forgot about it for the longest time....

**Pull request merged**
