### PR TITLE
arp: add page

### PR DESCRIPTION
**Pull request by Misch-**
First time I've contributed to open source, starting small ;)

Not sure about putting the ip link command in since it isn't an arp command, but it's nice for flushing the table and I believe it's pretty standard. Windows and OSX seem to have different syntax for their arp command.

### CODE REVIEW

**Comment by ostera** [comment]
Hi! Very happy to hear this is your first contribution to open source! :smile:

We generally tend to make no reference to other commands within a single tldr-page, but we'll be happy to have an ip page if you made a separate pull request for it :)

Just make sure to ammend your commit and force-push your branch up to keep this pull request clean, and we'll merge this in as soon as we can :ok_hand:

**Comment by igorshubovych** [comment]
Yes, if `ip` command is moved out of it, then LGTM

**Comment by waldyrious** [comment]
> First time I've contributed to open source

> ammend your commit and force-push your branch up

Does not compute :( perhaps more beginner-friendly instructions/links are warranted?

**Comment by ostera** [comment]
@waldyrious haha, absolutely spot on.

Okay @Misch-, just in case you don't know how to update the PR, follow this simple steps:

1. Do your changes, save them. All pretty standard up to here.
2. Commit but don't just commit – remember to use the `--amend` flag. So this step becomes `git commit --amend`
3. Force push `git push origin <your-branch> --force`
4. ?
5. Profit

**Comment by rubenvereecken** [comment]
@Misch- if you don't mind I'm taking the liberty of merging your page _but_ removing the `ip` example. If you're up to I'd be happy to review that one separately :).

**Pull request merged**
