### PR TITLE
bat: refresh pt_BR translation

### PR DESCRIPTION
**Pull request by cncll**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**
`bat 0.18.3`

### CODE REVIEW

**Comment by navarroaxel** [comment]
Hi @cncll, welcome and thanks for your submission. But we only accept translations from the English page. Could you propose your changes into the English page too?

**Comment by cncll** [comment]
Hi @navarroaxel, thank you for your fast response!

The modifications I'm proposing are based on the English page. I only slightly changed the wording on the second and third examples to improve the quality of the translation, as a completelly direct translation would sound confusing in Portuguese.

Could you elaborate on the divergences? I'd be happy to make changes to the English page if needed.

**Review by navarroaxel — APPROVED** [review]

**Comment by navarroaxel** [comment]
@kbdharun please review this.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
