### PR TITLE
pages.*/*: remove double spaces

### PR DESCRIPTION
**Pull request by acuteenvy**

### CODE REVIEW

**Review by mebeim — APPROVED** [review]
Seems reasonable!

**Review by kant — APPROVED** [review]
spanish chapter: LGTM

**Review by spageektti — APPROVED** [review]

**Review by ikks — APPROVED** [review]
Pages.es are gtg. Thanks

**Review by renie — APPROVED** [review]
pt_BR LGTM

**Review by Zamoca42 — APPROVED** [review]

**Review by debghs — APPROVED** [review]
LGTM.

**Review by kbdharun — APPROVED** [review]

**Review by gutjuri — APPROVED** [review]

**Pull request merged**
