### PR TITLE
Add pandoc

### PR DESCRIPTION
**Pull request by adius**

### CODE REVIEW

**Comment by rubenvereecken** [comment]
Hey @adius, thanks for the submission?

I went and had little look at pandoc myself. Turns out that when using the `-o` option, it uses the target suffix to determine the output format (pdf, html,...). Do you think there's a way we could make that clearer? Not sure if it's actually necessary because your example is correct in itself. I just feel that if we could add info implicitly without making it more complicated, we should.

Maybe something like `pandoc -o {{file}}.pdf ...`? Hmm not happy with that one either.

**Comment by waldyrious** [comment]
I would add the note in the description of the command.

Also, I think it would be more intuitive if the input argument came before the output one, like so:

`pandoc {{input.md}} -o {{output.pdf}}`

**Comment by igorshubovych** [comment]
As the time gone and there no move on this task, I think it is better to merge it as is.
Any improvements and modifications can be added later.

@adius thank you for your submission!

**Comment by adius** [comment]
@igorshubovych wisely said 😉

**Comment by adius** [comment]
Btw: I think it's absolutely clear that the output format is inferred from the filename, but maybe that's just me…

**Pull request merged**
