### PR TITLE
Add link to R client

### PR DESCRIPTION
**Pull request by kirillseva**
[Link](https://github.com/kirillseva/tldrrr) to client repo, for convenience.

### CODE REVIEW

**Comment by igorshubovych** [comment]
Wow! That was fast.

Make sure you add caching in future by downloading the latest archive from 
http://tldr-pages.github.io/assets/tldr.zip

**Comment by igorshubovych** [comment]
LGTM

**Comment by waldyrious** [comment]
:smile: LGTM :+1:

**Comment by igorshubovych** [comment]
+1

**Comment by kirillseva** [comment]
@igorshubovych I don't want to add archive cache (like the cli tool from npm) for now because it would make it harder for users, they'll have to worry about cache invalidation. I added in-session memoization though. If, within an opened R session, you do `for (i in 1:10) { tldr('tar') }` you will only make one http request, because the result will be cached in RAM.

**Comment by igorshubovych** [comment]
Well this unfair to GitHub API. It has some limits. I will later give you link where brew faced similar issues. Regarding cache invalidation, you can do it automatically, let's say every month.

**Comment by igorshubovych** [comment]
@kirillseva 
https://gist.github.com/christopheranderton/8644743

**Pull request merged**
