### PR TITLE
docker: added rm command

### PR DESCRIPTION
**Pull request by jeeftor**
Added copy command to docker

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @jeeftor - since we are close to the max no. of examples, we have to be extra judicious in what we choose to add. In this case, I think adding the `rm` or `search` option is more likely to be used than `copy`. It also matches with the other commands already present like `start` and `stop`.

Let me know your thoughts.

**Comment by jeeftor** [comment]
So the way i operate with TLDR pages is that if i do something and it isn't there then i add it.  If you want to add the other commands go for it 👍 - but i dont actually use docker that frequently ... so I leave it up to you in this case :)

**Comment by agnivade** [comment]
> So the way i operate with TLDR pages is that if i do something and it isn't there then i add it.

That's absolutely perfect. But sometimes, what we use might not be the most appropriate example to add. The point here is that tldr being limited in scope, we always try to keep the most popular/practical examples from a newcomer's perspective. 

In that vein, I was saying that instead of adding `cp`, we should use `rm` or `search`, because those are the ones a newcomer will probably need before doing `cp`.

**Comment by agnivade** [comment]
@jeeftor - I swapped `cp` with `rm`. Let me know if that's alright with you.

**Comment by jeeftor** [comment]
All is good!

**Pull request merged**
