### PR TITLE
Added command for testing server configuration without affecting the …

### PR DESCRIPTION
**Pull request by joearcher**
…running server, invaluable for anyone new to using Nginx, when making configuration changes on a "live" server

### CODE REVIEW

**Comment by igorshubovych** [comment]
LGTM

**Comment by waldyrious** [comment]
LGTM :+1:

**Comment by waldyrious** [comment]
:ok_hand:

**Comment by igorshubovych** [comment]
Could you please rebase to leave only 13d0108 commit in this Pull Request.

For future it is better to use feature branches.

**Comment by joearcher** [comment]
Apologies, not sure how I fucked this up so badly.

**Comment by waldyrious** [comment]
@joearcher it's happening to a lot of PRs in the past couple days due to a spike in popularity of the project. Not your fault, just lots of contributions, so master's changing a lot :)

**Comment by ostera** [comment]
:+1: if rebased/squashed

**Comment by joearcher** [comment]
Sorry, I've tried rebasing from upstream master, it doesn't seem to be helping.

**Comment by joearcher** [comment]
Think I sorted it, sorry about that. Will feature branch for future changes.

**Comment by joearcher** [comment]
Please cancel this pull request, I'll feature branch and re request.

**Pull request closed without merging**
