### PR TITLE
pacman-*: add Polish translation, pacman-files: remove the example for pacman --query

### PR DESCRIPTION
**Pull request by acuteenvy**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by Magrid0 — APPROVED** [review]
Looks good to me, thanks for your contribution!

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution and welcome to tldr.

**Comment by kbdharun** [comment]
Great, so this PR adds Polish translation for all pacman commands?

**Comment by acuteenvy** [comment]
Yes, it does. I have a problem though. Inside the page for `pacman --files` there is an example for `pacman --query` ([here](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-files.md?plain=1#L29)). Should it be removed or should I translate that too?

**Comment by kbdharun** [comment]
> Yes, it does. I have a problem though. Inside the page for `pacman --files` there is an example for `pacman --query` ([here](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-files.md?plain=1#L29)). Should it be removed or should I translate that too?

I guess you can remove it.

**Comment by acuteenvy** [comment]
Should I remove it from the English page too?

**Comment by kbdharun** [comment]
> Should I remove it from the English page too?

Yes

**Comment by acuteenvy** [comment]
It's also [here](https://github.com/tldr-pages/tldr/blob/main/pages.de/linux/pacman-files.md?plain=1#L29) and [here](https://github.com/tldr-pages/tldr/blob/main/pages.ta/linux/pacman-files.md?plain=1#L29). Remove it everywhere?

**Comment by kbdharun** [comment]
> It's also [here](https://github.com/tldr-pages/tldr/blob/main/pages.de/linux/pacman-files.md?plain=1#L29) and [here](https://github.com/tldr-pages/tldr/blob/main/pages.ta/linux/pacman-files.md?plain=1#L29). Remove it everywhere?

Yes, we can remove it on both pages, you can either do it in this PR or in a new one.

**Comment by acuteenvy** [comment]
I removed it from every page.

**Review by Magrid0 — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

Note to maintainers: Rebase and merge this PR **don't squash and merge.**

**Comment by acuteenvy** [comment]
@kbdharun I added your edits from #10120 and #10121 to this translation.

**Review by pixelcmtd — APPROVED** [review]

**Pull request merged**
