### PR TITLE
German pages: Change 'neuste' to 'neueste'

### PR DESCRIPTION
**Pull request by FantasyCookie17**
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

See https://github.com/tldr-pages/tldr/pull/5839#discussion_r621266173. This PR updates only the occurrences of `neuste` that weren't already updated in the linked PR.

### CODE REVIEW

**Review by marchersimon — APPROVED** [review]

**Review by bl-ue — APPROVED** [review]
Just curious; what's the difference (besides `eu` → `eue`)?

**Comment by marchersimon** [comment]
It's just one of the cases where one and the same word has different notations, however `neuste` is [hardly used](https://trends.google.com/trends/explore?geo=DE&q=neueste,neuste).

**Comment by marchersimon** [comment]
@FantasyCookie17 `neuste` is also used in `apt` and `git-clone`.

**Comment by FantasyCookie17** [comment]
@marchersimon 
> This PR updates only the occurrences of `neuste` that weren't already updated in the linked PR (i.e. your PR).

@bl-ue What @marchersimon said. It both means "newest" or "latest".

**Comment by marchersimon** [comment]
> This PR updates only the occurrences of neuste that weren't already updated in the linked PR (i.e. your PR).

Completely forgot about that 😄

**Review by marchersimon — APPROVED** [review]

**Pull request merged**
