### PR TITLE
pip, pip-install: add Chinese translation

### PR DESCRIPTION
**Pull request by imleowoo**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by imleowoo** [comment]
> Hello! I've noticed something unusual when checking this PR:
> 
> * The page `pages.zh/common/pip-install.md` is outdated, based on number of commands.
> * The page `pages.zh/common/pip.md` is outdated, based on number of commands.
> 
> Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.



> Hello! I've noticed something unusual when checking this PR:
> 
> * The page `pages.zh/common/pip-install.md` is outdated, based on number of commands.
> * The page `pages.zh/common/pip.md` is outdated, based on number of commands.
> 
> Is this intended? If so, just ignore this comment. Otherwise, please double-check the commits.

**Comment by imleowoo** [comment]
Why is pip outdated? @tldr-bot 

Is it because Python2 uses pip, while Python3 uses pip3 ？

but in fact, the official default still uses `pip`

[pip User Guide](https://pip.pypa.io/en/stable/user_guide/)
[pypi examples](https://pypi.org/project/requests/)

image

**Comment by spageektti** [comment]
> Why is pip outdated? @tldr-bot 
> 
> Is it because Python2 uses pip, while Python3 uses pip3 ？
> 
> but in fact, the official default still uses `pip`
> 
> [pip User Guide](https://pip.pypa.io/en/stable/user_guide/)
> [pypi examples](https://pypi.org/project/requests/)
> 
> image
> 

@tldr-bot is a bot. You translation has less commands that the English page.

**Comment by imleowoo** [comment]
> > Why is pip outdated? @tldr-bot
> > Is it because Python2 uses pip, while Python3 uses pip3 ？
> > but in fact, the official default still uses `pip`
> > [pip User Guide](https://pip.pypa.io/en/stable/user_guide/)
> > [pypi examples](https://pypi.org/project/requests/)
> > image
> 
> @tldr-bot is a bot. You translations dont have the same number of examples as the English page.

Sorry, I didn't this important sentence. I fixed it.
> Translations of pages should be done based on the English (US) page in the pages directory. If the English pages don't exist for the command, it should be added first in a PR before creating a translation.

**Review by blueskyson — APPROVED** [review]

**Comment by spageektti** [comment]
Can you please update the page to match the [English one](https://github.com/tldr-pages/tldr/blob/main/pages/common/pip-install.md)?

**Comment by spageektti** [comment]
If you want to add examples to the page, you need to add them to the English page first.

**Comment by imleowoo** [comment]
> If you want to add examples to the page, you need to add them to the English page first.

Thank you for your advice, I have fixed it.

**Comment by imleowoo** [comment]
> Can you please update the page to match the [English one](https://github.com/tldr-pages/tldr/blob/main/pages/common/pip-install.md)?

Thank you for your advices, I have fixed it.

**Review by spageektti — APPROVED** [review]

**Pull request merged**
