### PR TITLE
bash: add --version

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by agnivade** [comment]
The added example looks good. I wanted to add

**Comment by agnivade** [comment]
The added example looks good. I just wanted to put a comment on L12(which github wasn't allowing) that we should enclose the `{{command}}` in quotes `"{{command}}"`.

For eg - for echo hello to work, we need `bash -c "echo hello"`. Of course, within the command, we need to double escape if needed. But I guess that is not important here.

**Comment by waldyrious** [comment]
Sure, I'll make that change.

**Comment by agnivade** [comment]
LGTM. :+1:

**Pull request merged**
