### PR TITLE
Add page for Linux's `mail` utility.

### PR DESCRIPTION
**Pull request by mikefowler**

### CODE REVIEW

**Comment by felixonmars** [comment]
The commit message says "ls" :P

**Comment by mikefowler** [comment]
Hah. Let me just start my brain and try that again.

**Comment by mikefowler** [comment]
:ok_hand:

**Comment by igorshubovych** [comment]
Check out #572

**Comment by igorshubovych** [comment]
As well as our recent discussion on Gitter https://gitter.im/tldr-pages/tldr

**Comment by mikefowler** [comment]
Gotcha, @igorshubovych. Feel free to close this.

**Pull request closed without merging**
