### PR TITLE
diff3: add page

### LINKED ISSUE #2310: page request: diff3
Add documentation for `diff3`.

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Closes #2310

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by sbrl** [comment]
@pxgamer: Oooh errr! I didn't realise that :P

Erm maybe we could merge the two?

**Comment by agnivade** [comment]
> Erm maybe we could merge the two?

How do you mean ? I don't think a non-admin can update another person's PR ? 

As an alternative, we can let one PR get merged, then rebase it on the latter and merge that. I see only one option extra in this PR. So shouldn't be an issue.

**Comment by sbrl** [comment]
Which should be first?

**Comment by agnivade** [comment]
Whoever finishes the review earlier. It shouldn't matter anyways since both changes are going to be there.

**Pull request merged**
