### PR TITLE
git-checkout: also works for remote branches

### PR DESCRIPTION
**Pull request by waldyrious**
Not sure if this clarifies or obscures the example. Opinions welcome.

### CODE REVIEW

**Comment by bobstrecansky** [comment]
Maybe change this to:
> Switch  to an existing or upstream branch

Thoughts?

**Comment by agnivade** [comment]
I prefer @bobstrecansky's suggestion.

**Comment by waldyrious** [comment]
Hmmm, not sure: an upstream branch already exists as well, just not locally. The distinction is not the existence, but the locality. How about this?

> Switch to an existing local or remote branch:

(Note that I'm using "remote" instead of "upstream" following the rationale described [here](https://github.com/tldr-pages/tldr/pull/1236#discussion_r96134742).

**Comment by agnivade** [comment]
Yea makes sense. Go ahead.

**Comment by waldyrious** [comment]
I'll just wait to see if @bobstrecansky has any thoughts about this :)

**Comment by bobstrecansky** [comment]
Sounds good to me!

**Pull request merged**
