### PR TITLE
nodenv: add German translation

### PR DESCRIPTION
**Pull request by schwarmco**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]
Hi @schwarmco, welcome and thanks for your submission. We accept multiple pages in one PR for translations. Only 1 page for PR when we are working over the main (English) page.

**Comment by schwarmco** [comment]
Hi @navarroaxel,
sorry for that - i've initially packed all commits in a branch and wanted to do a pr with all node-related pages (see https://github.com/schwarmco/tldr/tree/german-translation-node-utils) but then i've read about the PR title requirements and got thrown off.

If you agree with that, i'll close the multiple PRs and submit a bundled one with the changes you requested.

**Comment by navarroaxel** [comment]
@schwarmco No, the PRs are open and I reviewed them. Let's work on them :muscle:

**Review by sbrl — APPROVED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

**Comment by sbrl** [comment]
Merging early, since it's hacktoberfest season

**Pull request merged**
