### PR TITLE
Automate translator updates

### PR DESCRIPTION
**Pull request by Keating950**
Hi all,

Following up on #4020, here is a Python script that does two things:

1.  Update the last five users who have translated a given page when its English version changes, and
2.  Generates a markdown file of pages needing translation and puts it in the main repo.

Right now, it works by integrating with Travis. The basics of this method should work if you guys decided it would be better to host the list on tldr.sh, assuming you use some kind of template solution for it already. I looked into the possibility of updating a wiki page via the Github API, but it seems that there's no endpoint for that right now.

Let me know how I can help keep this ball rolling!

### CODE REVIEW

**Comment by agnivade** [comment]
This is great @Keating950. I think we would like to have tldr-bot do this. I have asked @mebeim to take a look since he has been looking at the translations part.

**Comment by zdroid** [comment]
cc @MasterOdin, who may be interested in reviewing the script

**Comment by zdroid** [comment]
This issue may make one unintended issue for this repository. Currently the repository's language is marked as `Shell`, which will almost certainly change to `Python` after this is merged. I guess it should go to https://github.com/tldr-pages/tldr-bot.

**Comment by Keating950** [comment]
Makes sense; I will open A PR there. On another note, I'm having trouble signing the CLA. I follow the link and click Agree and am taken back to GitHub as though it were successful, but it seems like the licence bot hadn't registered that because my git email didn't match my Github email. I tried  to fix this by rewriting my fork's history but it seems like I messed it up semi-severely -- probably best to start fresh with another PR anyway.

**Comment by zdroid** [comment]
You should make git commits with the email that you use on GitHub. Check GitHub help for that.

**Comment by Keating950** [comment]
Yup, slipped my mind that I changed my primary email. I reused some code from this repo to post comments, etc. so I'll need to refactor my script a bit, which is no issue. I'll open a PR over on the other repo once it's all ready.

**Comment by zdroid** [comment]
All you need to do in that case @Keating950 is to add your secondary email to your GitHub account. I've done the same when I had that issue.

**Pull request closed without merging**
