### PR TITLE
while: replace incorrect link

### PR DESCRIPTION
**Pull request by Managor**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by pixelcmtd — COMMENTED** [review]
`common` pages are supposed to cover the common ground (in this case POSIX) between all different implementations. For that reason we try to not link to GNU (or another specific implementation), and therefore I strongly disagree with this change.
Also, how do you create a menu with `while`? Am I missing something?

**Comment by Managor** [comment]
No, you're not missing anything. I copypasted from `select` and forgot to edit the text to fit `while`.

I was thinking that this should be moved to something else than `common` as the examples listed in the page did not match with the manual page linked in the original page.

**Comment by pixelcmtd** [comment]
> The manual page was for the Tcl programming language.

Ok that's pretty bad. I reckon that manned.org at some point changed what the default `while` points to, from the shell builtin to that Tcl thing. The best I can suggest is using https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_04_09

**Review by pixelcmtd — APPROVED** [review]

**Review by mfrw — APPROVED** [review]
LGTM :)
Thanks @Managor

**Pull request merged**
