### PR TITLE
rename github to GitHub

### PR DESCRIPTION
**Pull request by schneiderl**
this pr renames "github" to "GitHub" as it is the official name of the service.

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Really nice&mdash;but I'm sure I've done this before! 😄 🤷

**Comment by schneiderl** [comment]
@bl-ue Yes, I remember that. In fact, it was not that long ago haha. Perhaps those pages were added in the meantime.

**Comment by bl-ue** [comment]
I wonder if "GitLab" needs it done too...

**Comment by schneiderl** [comment]
@bl-ue just checked it. not necessary.

**Review by sbrl — APPROVED** [review]
Thanks, @schneiderl!

Consistency edits like these are great for improving the quality of tldr-pages. It's too small to be added to the contributing guidelines (otherwise they'd be too long and it'd be too much of a barrier to new contributors), but great as a mass-changes PR!

**Review by waldyrious — APPROVED** [review]
Nice one @schneiderl :)

**Pull request merged**
