### PR TITLE
xargs: add page

### PR DESCRIPTION
**Pull request by cole-brokamp**

### CODE REVIEW

**Comment by waldyrious** [comment]
See #165 and #450

**Comment by cole-brokamp** [comment]
Sorry about that! Didn't see it because it was listed in the linux folder when its actually a common command to linux and unix.  I've moved it to the right place and added two more examples.

**Comment by waldyrious** [comment]
Ok, thanks. I'd suggest waiting until #450 is merged and then updating this as needed. Meanwhile, you're welcome in the discussion at #450 :)

**Comment by igorshubovych** [comment]
These are more examples about `find`, not `xargs`. So they can be on `find`'s page, but should not be added here.

**Comment by aicioara** [comment]
@igorshubovych If this is a reject, let's close the PR and / or look into https://github.com/tldr-pages/tldr/pull/656 as well.

Thank you

**Comment by igorshubovych** [comment]
Does anybody else disagree with me? Opinions?
@waldyrious do you agree with me on that?

**Comment by waldyrious** [comment]
xargs will always require other commands to be properly explain, but yeah, we would probably want to use simpler commands like ls, echo, etc., if at all possible.

**Comment by igorshubovych** [comment]
@cole-brokamp 
Thanks for your contribution. At the moment we cannot merge this PR, because it is different variants of `find`, not `xargs`.

**Pull request closed without merging**
