### PR TITLE
e2undo: add page

### PR DESCRIPTION
**Pull request by navarroaxel**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For #4250

### CODE REVIEW

**Comment by navarroaxel** [comment]
Related to #4250

**Review by bl-ue — APPROVED** [review]
🚀

**Review by glenacota — COMMENTED** [review]
Besides the little change request, it looks great to me :)

**Review by sbrl — APPROVED** [review]
Thanks, @navarroaxel!

**Pull request merged**
