### PR TITLE
pages.it/*: update path placeholders and "directory" translations (#9031)

### PR DESCRIPTION
**Pull request by ffranchina**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

The aim of such pull request is to put order in the Italian translations of the path in the examples.
Most of the examples made use of a weird construction that is never used in Italian (_/percorso/a/file_), therefore it has been grammatically fixed everywhere with a combination of manual and automated work.

Additionally I have renamed every occurrence of _directory_ as _cartella_ with the attempt of bringing uniformity (in the repo they where both co-existing already).

If such PR is accepted, we will have a unique standard for Italian paths:
```
{{percorso/del/file}}
{{percorso/della/cartella}}
{{percorso/del/file_o_cartella}}
```
---

Reference for other mass renaming taks: I have used the command `find . -exec sed -i 's/a/del/g' {} \;`

### CODE REVIEW

**Comment by ffranchina** [comment]
@mebeim, as promised here is my PR for the mass rename of the path standard naming! :smile:

**Comment by kbdharun** [comment]
Wow, This is a massive PR 🚀 . Thanks for your contribution. Let's see what others think.

**Comment by kbdharun** [comment]
@ffranchina just a small suggestion can you update the paths in contributing-guidelines too?

**Comment by mebeim** [comment]
> can you update the paths in [contributing-guidelines](https://github.com/tldr-pages/tldr/tree/main/contributing-guides) too?

@kbdharun we don't seem to have a style guide for Italian pages, are you referring to some specific file mentioning Italian translations that I am missing?

**Comment by kbdharun** [comment]
> > can you update the paths in [contributing-guidelines](https://github.com/tldr-pages/tldr/tree/main/contributing-guides) too?
> 
> @kbdharun we don't seem to have a style guide for Italian pages, are you referring to some specific file mentioning Italian translations that I am missing?
> 

@mebeim seems like I made a typo instead of linking to common arguments, I linked it to contributing guidelines.

**Comment by ffranchina** [comment]
Done, thank you very much for your suggestion :)

**Comment by ffranchina** [comment]
@marchersimon for git now everything is fine but I see your point. Let me try to fix this with a --force push of a cleaned branch.

**Comment by marchersimon** [comment]
Now I hopefully managed to merge in all new commits.

**Review by marchersimon — APPROVED** [review]
Looks good.
Thanks @ffranchina

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

@mebeim Can you check this and merge this PR

**Comment by mebeim** [comment]
Thank you for the PR @ffranchina!

> Additionally I have renamed every occurrence of directory as cartella with the attempt of bringing uniformity

I had not initially looked at the changes when commenting above, but I noticed this now.

The term "directory" is the right one to use in Italian technical writing. In fact, since the initial translation support, I have tried to keep "directory" in Italian pages. Nonetheless some Italian translations might have slipped through without me reviewing them and therefore we ended up with some occurrences of "cartella" as well. Just like "folder" in English, "cartella" can cause confusion as it is used to indicate a graphical UI element (e.g. folders with icons in the file explorer) rather than a filesystem entity (i.e. a directory).

In fact, the term "directory" is also used for the Italian Wikipedia entry [Directory](https://it.wikipedia.org/wiki/Directory) and for all the Italian Linux manual pages (some common examples: [`ls`](https://manned.org/man.it/ls.1), [`dir`](https://manned.org/man.it/dir.1), [`mv`](https://manned.org/man.it/mv.1), [`mkdir`](https://manned.org/man.it/mkdir.1)).

Please, use `directory` instead of `cartella`. You can force-push the changes if that is simpler for you. The PR will be squashed when merging regardless.

**Comment by ffranchina** [comment]
Hello @mebeim, I see your point. Before running another mass rename, I would like to be sure of one thing: since the aim of this project is to document commands (that, due to your reasoning deal only with _directories_), we agree that we can safely replace _directory_ at every occurrence of _cartella/e_?

**Comment by mebeim** [comment]
> we agree that we can safely replace directory at every occurrence of cartella/e

@ffranchina I am not 100% sure of that honestly, maybe 90% sure :'). I will nonetheless check the changes. 140 files is still humanly doable.

**Comment by ffranchina** [comment]
Ok, the PR should be ready :)

**Review by mebeim — APPROVED** [review]
LGTM, just fixed a couple of minor things.

**Review by ffranchina — COMMENTED** [review]
I do not want to appear picky also because I've heard it may times in both the ways but, _repository_ is often used as male in Italian (also wikipedia does https://it.wikipedia.org/wiki/Repository).

Edit: talking about https://github.com/tldr-pages/tldr/pull/9031/commits/86b116ecfa3143b04334eb29a0204eb2b63836eb

**Review by kbdharun — APPROVED** [review]
Now, we need to fix the merge conflict and this PR is GTG I guess.

**Comment by kbdharun** [comment]
This is the first time I am using resolve conflict in GitHub web editor, I hope that I did it right 😅

**Comment by kbdharun** [comment]
> Oops, Seems like I didn't remove some parts.

Fixed it. Thanks, I learnt something new today 😄 .

@mebeim you can merge this PR if it's GTG.

**Pull request merged**
