### PR TITLE
!, archinstall: add Hindi translation

### PR DESCRIPTION
**Pull request by aditya955**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by aditya955** [comment]
Is it Okay if I add multiple translations in single commit?

**Comment by kbdharun** [comment]
> Is it Okay if I add multiple translations in single commit?

Yep

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution. Since the creation of your PR, [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md) has been updated, can you update the same here?

**Comment by aditya955** [comment]
> Thanks for your contribution. Since the creation of your PR, [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md) has been updated, can you update the same here?

[`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md) was last updated 2 weeks ago. I made PR 2 days ago. 
Btw I added 1 extra example (1st example: !!) which is not present in english version of [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md), so is there any issue with that? shall I remove it or add it in english version?

**Comment by kbdharun** [comment]
> [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md) was last updated 2 weeks ago. I made PR 2 days ago. Btw I added 1 extra example (1st example: !!) which is not present in english version of [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md), so is there any issue with that? shall I remove it or add it in english version?

In cases like this, I would suggest adding it to the English page, but the first example seems to be just removing `sudo` alone so we could use the existing example but add a note that the command can be executed without sudo too.

**Comment by aditya955** [comment]
> > [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md) was last updated 2 weeks ago. I made PR 2 days ago. Btw I added 1 extra example (1st example: !!) which is not present in english version of [`!.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/!.md), so is there any issue with that? shall I remove it or add it in english version?
> 
> In cases like this, I would suggest adding it to the English page, but the first example seems to be just removing `sudo` alone so we could use the existing example but add a note that the command can be executed without sudo too.

Okay then I will remove the first example.

**Comment by aditya955** [comment]
Removed first example!

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
