### PR TITLE
tldr: fix command description in Japanese translation

### PR DESCRIPTION
**Pull request by k1832**
Removed the unnecessary period because periods are not usually used in Japanese sentences.
In addition to this, the period, which is removed in this PR, is confusing when hyperlink doesn't work in the cli as it might be copied with the URL.

This might be a translation-related, so don't hesitate to close this PR if this should not be in PRs.

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by navarroaxel** [comment]
:thinking: your suggestion looks related to <https://github.com/tldr-pages/tldr/issues/6500>. Which client and terminal are you using?

**Comment by k1832** [comment]
I'm on macOS Big Sur (11.4) and using iTerm2.
But this is not about the hyperlink issue, but also about that period in the Japanese sentence being unnatural to me.

**Comment by k1832** [comment]
Maybe the title of PR is not appropriate...

**Comment by marchersimon** [comment]
This link was probably inserted with our [set-more-info-link.py](https://github.com/tldr-pages/tldr/blob/main/scripts/set-more-info-link.py) script. We didn't know about that rule in Japanese. But I'm sure it shouldn't be hard to fix it.

**Comment by marchersimon** [comment]
I found that a lot of Japanese pages use a full-width period at the end of the line (e.g. `pwd` or `sed`). Is this also wrong?

**Comment by sbrl** [comment]
Hmmm, there is a linter issue here because the linter currently requires a full stop at the end of description lines. To resolve this, I would recommend we make the linter language-aware. By doing so, it would enable / disable various linting rules depending on the language selected. I am aware however that this would be a significant undertaking to implement such a system.

**Comment by marchersimon** [comment]
@sbrl I thought the linter only lints English pages? 

@shu-pf what do you think about this? You've contributed some Japanese pages and used a `。` as period.

**Comment by k1832** [comment]
>@sbrl I thought the linter only lints English pages?

I think this is correct.
When I run `npm run lint-tldr-pages`, I got no error even after I removed the period from the Japanese page.
(I also made sure I got an error when I run it after I removed the period on the English page.)

**Comment by marchersimon** [comment]
@k1832 could you provide us a source that in official Japanese there is indeed no period at the end of a sentence? Because a lot of other Japanese contributors used the full-width period (`。`).

**Comment by sbrl** [comment]
@marchersimon that's correct, but it would be nice if it linted other languages to catch issues eventually as well :-)

**Comment by k1832** [comment]
@marchersimon 
Sorry for the confusion.

（First of all, I don't think this period is needed (even on the English page) because this looks like an equation.　`詳しくはこちら: {URL} -> 詳しくはこちら = {URL}`
But I believe that this is not the discussion we want to do here. So I just ignore it and try to explain why I wanted to remove the period in the first place.）

1. Periods in Japanese sentences are unnatural (to me)
In Japanese, periods (Now I'm talking about (half-width) periods, but not full-width periods. sorry for this confusion) can be used in some contexts, which include academic papers and maybe researchers' blogs? , but officially full-width periods are used.
2. A full-width period after a URL is still unnatural (to me)
A full-width period after the English word is weird to me.
If the sentence should end with a full-width period,  I would put it like this.
`詳しくはこちら（<https://tldr.sh>）をご覧ください。`

Sorry for not showing any source with this. Opinions for this PR are always welcome.
I would totally understand if this pull request is closed because of the lack of information.

**Comment by marchersimon** [comment]
Ok, so we should remove all periods after the More information links. But what about regular sentences (like the command description at the beginning)? Some pages have periods and some don't.

**Comment by k1832** [comment]
@marchersimon 
Thank you for your reply!
I believe that regular sentences (like [this one](https://github.com/tldr-pages/tldr/blob/e13e67b1711e4112cca0cc4d07521c0cf901290c/pages/windows/cd.md#L3) right?) should end with period.
Unless you see it as a header.

**Comment by sanopy** [comment]
I agree with removing all periods after links. And I also think that regular sentences should end with a full-width period (`。`).

**Review by marchersimon — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
