### PR TITLE
alias: add list all aliases

### PR DESCRIPTION
**Pull request by Aracki**
I have added a very useful command which will list all aliases defined.

### CODE REVIEW

**Comment by waldyrious** [comment]
> Just interested, does this do anything different to `alias -p`?

Actually, I don't have the `-p` option in my `alias` built-in command:

```
$ alias -p
alias: bad option: -p

$ man alias

BUILTIN(1)                BSD General Commands Manual               BUILTIN(1)
...
Commands marked ``No**'' under External do exist externally, but are implemented as scripts using a builtin command of the same name.

           Command       External    csh(1)    sh(1)
           ...           ...         ...       ...
           alias         No**        Yes       Yes
...
BSD                            February 23, 2005                           BSD
```

(For reference, I'm using zsh on macOS.)

**Comment by pxgamer** [comment]
I use zsh too (Ubuntu and MacOS), just I'm at work so on Windows.

**Comment by Aracki** [comment]
`alias -p` doesn't work on fish either.

**Comment by pxgamer** [comment]
Perhaps we should remove `alias -p` and just keep this one then. 🤔

However, I don't have a huge range of shells to test on.

**Comment by waldyrious** [comment]
I can test two more shells tonight at home. In the meantime, additional data from others would be nice.

**Comment by Aracki** [comment]
I suggest we remove `alias -p` and leave `alias` as a first example.

**Comment by sbrl** [comment]
It seems like `alias -p` is a bash-specific thing.

**Pull request merged**
