### PR TITLE
nodemon: change python example to general example

### PR DESCRIPTION
**Pull request by RedHeadphone**
- [ ] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**
2.0.13

### CODE REVIEW

**Comment by marchersimon** [comment]
Why is this a "fix"? You just converted the Python-specific example into a more general example right?

**Comment by RedHeadphone** [comment]
> Why is this a "fix"? You just converted the Python-specific example into a more general example right?

Yeah you are right I should have wrote better explaining commit.

**Comment by RedHeadphone** [comment]
> No problem. Since we have still room left, what do you think about leaving the Python example and adding the general example below it?

What would you suggest heading of this general example?

**Comment by marchersimon** [comment]
How about
```Markdown
- Run an arbitrary non-node script:

`nodemon --exec "{{command_to_run_script}} {{options}}" {{path/to/script}}`

- Run a Python script:

`nodemon --exec "{{python --verbose}}" {{path/to/file.py}}`
```

**Comment by RedHeadphone** [comment]
@marchersimon instead of `--verbose` how about `options`?

**Pull request merged**
