### PR TITLE
git-checkout*: add Ukrainian translation

### PR DESCRIPTION
**Pull request by burlakvo**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by CleanMachine1 — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by kbdharun** [comment]
I have a request can you add Ukrainian (pages.uk) terms to [common-arguments.md](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md) in a new PR as it would be helpful for reviewers when validating translations and it would also be as a reference for other translators.

**Comment by burlakvo** [comment]
@kbdharun yes, with pleasure.

**Comment by kbdharun** [comment]
> @kbdharun yes, with pleasure.

Thanks ❤️

**Pull request merged**
