### PR TITLE
ulimit: added to Linux section

### PR DESCRIPTION
**Pull request by Cvetomird91**
Added a page for the ulimit shell builtin for getting and setting various user and shell limits.

### CODE REVIEW

**Comment by waldyrious** [comment]
Would it be possible to use words in the example descriptions that match the letters of the options? That helps memorizing and undestanding the commands.

**Comment by Cvetomird91** [comment]
I have edited those descriptions accordingly and added some new options.

**Comment by waldyrious** [comment]
I think you swapped "soft" and "hard" in the descriptions relative to the corresponding commands :)

Also, I believe "per-user" (with a hyphen) is the correct form.

**Comment by waldyrious** [comment]
Btw, you may consider splitting `-Sn` and `-Hn` into `-S -n` and `-H -n` just to make it clear that they are separate options.

**Comment by Cvetomird91** [comment]
Thank you for your feedback. This has been taken care of.

**Comment by igorshubovych** [comment]
LGTM.
Actually all these commands work in OSX.

**Comment by waldyrious** [comment]
If that's the case, then this page should be in the common folder. Other than that, this looks good to go :+1:

**Comment by igorshubovych** [comment]
Thank you for contribution!

**Pull request merged**
