### PR TITLE
Update macOS references

### PR DESCRIPTION
**Pull request by danielbayley**
Update references to 'OS X' to 'macOS'.

### CODE REVIEW

**Comment by agnivade** [comment]
I'm not very sure, but aren't 'macos' and 'osx' the same ?

**Comment by sbrl** [comment]
@agnivade I think they are effectively. Apple have apparently rebranded from osx to macos, but I haven't yet met anyone who uses the new name - probably because apple devices aren't very common around my area :P

**Comment by danielbayley** [comment]
It was officially renamed a while ago now… this was just a precursor to my `open` update anyway.

**Comment by danielbayley** [comment]
@sbrl `macOS` 😄 I think their rationale was to bring it in line with the naming scheme for their other products (`iOS`, `watchOS`, `tvOS`…)

**Comment by agnivade** [comment]
Just a note that our platform folder is still named `osx`. And changing that might have consequences for various clients, so keeping it as is for now.

**Pull request merged**
