### PR TITLE
MAINTAINERS: add @glenacota

### LINKED ISSUE #4763: add contributor: @glenacota
Hi, @glenacota! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#4364, #4362, #2464, #2458, #2452, and #2440)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

### PR DESCRIPTION
**Pull request by navarroaxel**
- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

Close #4763

### CODE REVIEW

**Comment by bl-ue** [comment]
@navarroaxel has @glenacota accepted the invitation?  I think you should be able to see since you're part of the tldr pages org.

**Comment by navarroaxel** [comment]
@bl-ue I can't see (or I don't know how see) the collaborators list, I can only see the org members list.
But, his comments have the `Collaborator` tag, so @glenacota is a collaborator.

**Review by bl-ue — APPROVED** [review]

**Comment by bl-ue** [comment]
@navarroaxel I think you might have to be an org owner to view them, actually. 🤷

**Comment by bl-ue** [comment]
@glenacota since you're a collaborator, approve and merge this PR!

**Review by glenacota — APPROVED** [review]

**Pull request merged**
