### PR TITLE
screen: add kill from inside a screen example

### PR DESCRIPTION
**Pull request by digitalhabitat**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, thanks for the edit @digitalhabitat! Unfortunately, we have a limit of 8 examples per page. Is there an example that less commonly used that we could remove to bring us back under the limit?

Also, perhaps `- Kill the current screen session:` would be an alternative wording that would improve clarity a bit?

**Comment by digitalhabitat** [comment]
Hi @sbrl. I'm pretty new at using screen but once I discover this option I wished I knew it earlier. The original method I used was ```- Kill a detached screen:```  but I my experience I wanted to just kill the current session. I do like your alternative wording.

**Comment by sbrl** [comment]
@digitalhabitat I agree. How about we remove that one then to bring us under the limit then?

_(Also, @pxgamer / @agnivade?)_

**Comment by agnivade** [comment]
If I am counting it correctly, this example just takes it to 8. Not more than that.

Also, please move it one example up.

**Comment by pxgamer** [comment]
@agnivade, looks like you're right. 👍

**Comment by sbrl** [comment]
Oops! I can't count apparently then :P

**Pull request merged**
