### PR TITLE
*/halt: update link to `manned`

### PR DESCRIPTION
**Pull request by kbdharun**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by mebeim — APPROVED** [review]
Looks ok, but now I'm wondering... do we wanna link directly to the translated pages on manned? Or just keep the default links? Translated pages are in the correct language but sometimes have less (or not really up to date) information.

**Comment by kbdharun** [comment]
> Looks ok, but now I'm wondering... do we wanna link directly to the translated pages on manned? Or just keep the default links? Translated pages are in the correct language but sometimes have less (or not really up to date) information.

I am currently working on updating the style guide and focusing on the requested tasks from #10755. I will mention this too.

I think it is better to link to the English translation of the man page as most of the time, man page translations are outdated. Since we cover the important commands with translated pages I don't think it is necessary to link to outdated translations.

**Review by kant — COMMENTED** [review]
LGTM, @kbdharun @mfrw @mebeim @ry

**Review by mfrw — APPROVED** [review]
LGTM
Thank you @kbdharun

**Pull request merged**
