### PR TITLE
MAINTAINERS: add @gutjuri as org member

### LINKED ISSUE #11201: MAINTAINERS: add @gutjuri as org member
Hi, @gutjuri! After joining as a collaborator in the repository, you have been regularly performing [maintenance tasks](https://github.com/tldr-pages/tldr/pulls?q=reviewed-by:gutjuri).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our [Matrix chat room](https://matrix.to/#/#tldr-pages:matrix.org).
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

### PR DESCRIPTION
**Pull request by gutjuri**
closes #11201

Thanks!

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by kbdharun** [comment]
A minor suggestion, please set your membership to public in https://github.com/orgs/tldr-pages/people.

**Comment by kbdharun** [comment]
> A minor suggestion, please set your membership to public in https://github.com/orgs/tldr-pages/people.

Seems like @gutjuri's membership is still private. For non-members, your role would still be shown as collaborator.

Screenshot from 2023-10-24 22-31-50

**Comment by kbdharun** [comment]
> A minor suggestion, please set your membership to public in https://github.com/orgs/tldr-pages/people.

Seems like @gutjuri's membership is still private. For non-members, it will still show up as collaborator instead of member.

Screenshot from 2023-10-24 22-31-50

**Comment by gutjuri** [comment]
> > A minor suggestion, please set your membership to public in https://github.com/orgs/tldr-pages/people.
> 
> Seems like @gutjuri's membership is still private. For non-members, it will still show up as collaborator instead of member.
> 
> Screenshot from 2023-10-24 22-31-50

done, thanks for the reminder

**Pull request merged**
