### PR TITLE
use a more useful second example

### PR DESCRIPTION
**Pull request by waldyrious**
Grouping 3 related options that produce a more useful output. The descriptions are in the same order and use the same initials to allow understanding what each option does individually.

### CODE REVIEW

**Comment by rprieto** [comment]
Looks great to me, definitely a handy group!

I find the description a little confusing though (`Print the system (kernel) name, release and version (e.g. Linux, Darwin, SunOS, etc.)`). What about `Print the kernel name (Linux, Darwin...), release number, and version details`?

**Comment by waldyrious** [comment]
The goal of having "system" there is to make the origin of the option obvious. I'd rather remove "kernel" instead, since the examples actually make it obvious what that option returns, both for experienced and for new users.

**Comment by rprieto** [comment]
Sounds good to me :+1:

**Comment by waldyrious** [comment]
@rprieto done, check it out :)

**Comment by rprieto** [comment]
In fact sorry I reviewed the whole `tldr` page again, do you think it's worth having `-srv` when we already have `-a`?

Thinking about it again, I like having the `-n` to show just the network name (quite useful), and `-a` to show everything (pretty much `-srv` + network name + architecture).

**Comment by waldyrious** [comment]
Not sure what you're proposing. Both the `-n` and `-a` options were already present and weren't touched in this PR. I replaced `-s` with an example that's more useful in practice, without making the output too verbose like `-a` does.

**Comment by rprieto** [comment]
Sorry, I meant I hadn't noticed we already had `-a` in there, and I'm not sure what `-srv` brings (the `-v` flag makes it almost just as verbose, it just saves having `mycomputer.local` and `x86_64`).

Maybe `-sr` is a good compromise, since it's nice and concise (`Darwin 14.4.0`)?

**Comment by waldyrious** [comment]
I see the appeal of `-sr`. I included `-v` because I believe it fits with the information in `-sr`, namely it provides information on the software (OS) installed on the machine -- for instance, in my case it's the only indicator that the OS is Ubuntu, since `-o` returns `GNU/Linux`. `-n` is more of a specific configuration setting, and the remainder of -a (`-m`/`-i`/`-p`) provides information about the hardware (in fact maybe we could add `uname -mp`* as an extra example, which neatly completes the three major groups of information provided by uname)

\* the `-m` and `-p` seem [generally well supported](https://en.wikipedia.org/wiki/uname), while `-i` is an invalid option in some systems, most notably Mac OSX.

**Comment by rprieto** [comment]
That's a very good point, I really like the idea of separating software/hardware info! I'm sold on 3 examples to show the 3 groups (`n`, `srv`, `mp`). Up to you whether we should keep `a`, but to be fair I understand `uname` a lot better after your explanation, so keeping with 3 examples might be perfect.

**Comment by waldyrious** [comment]
Ok, took a stab at it. I think it makes more sense that way, too. Let me know what you think!

**Comment by rprieto** [comment]
Nice work, thanks for that. It looks really clean! :+1:

**Comment by waldyrious** [comment]
Thank you for the fruitful discussion :smile:

**Pull request merged**
