### PR TITLE
common-arguments: add Thai translation

### PR DESCRIPTION
**Pull request by kerlos**
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by kbdharun** [comment]
Thanks for your contribution. I will request reviews from native speakers.

- @MasterIceZ @nontw @pruekk @Aphrodicez @piromsurang  Can you review this PR? 
> Thanks in advance

**Review by MasterIceZ — COMMENTED** [review]
I think meaning of `directory` and `file` was swapped. 🤔

**Comment by kerlos** [comment]
> I think meaning of `directory` and `file` was swapped. 🤔

oops, fixed.

**Review by MasterIceZ — APPROVED** [review]
LGTM 👍🏻

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
