### PR TITLE
watch: add pt_BR translation

### PR DESCRIPTION
**Pull request by gugacavalieri**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]

**Comment by bl-ue** [comment]
We can add a more information link in a followup PR, no?

**Review by navarroaxel — APPROVED** [review]

**Comment by CleanMachine1** [comment]
Might waldyrious be able to help with this PR?
Or is Brazilian PT a little different?

**Comment by bl-ue** [comment]
It is different, but he could help all the same. I'm not sure about his availability though.  @schneiderl and @andrik are native pt_BR speakers, so it would be nice if they could...

**Comment by bl-ue** [comment]
Let's wait for a day or two more to get feedback, then let's merge.

**Comment by gugacavalieri** [comment]
Thanks @bl-ue @CleanMachine1! Let me know if you need any reviews for `pt_br` translations from now on. I would be glad to help :smile:

**Comment by CleanMachine1** [comment]
Thanks for your help :)

**Comment by bl-ue** [comment]
I sure will @gugacavalieri, thank you very much for the help!! ❤️

**Pull request merged**
