### PR TITLE
ping: add -a example

### PR DESCRIPTION
**Pull request by xxdavid**

### CODE REVIEW

**Comment by agnivade** [comment]
We should probably add the following caveat - "It can give beep only from terminal number 1 through 7 and gnome-terminal ( It will not work in console )."

Relevant - http://askubuntu.com/questions/15963/why-cant-i-hear-audible-pings

**Comment by waldyrious** [comment]
@agnivade I'm wondering if we could word the caveat in a more layman-friendly manner...

**Comment by xxdavid** [comment]
`ping -a` uses the standard `\a` character for the bell. It's commonly used (though I can only think of Vim now). I think that if someone's terminal doesn't support the bell, he/she is probably aware of it and won't expect `ping -a` to ring the bell. What do you think?

**Comment by agnivade** [comment]
@xxdavid - Not in my case. I wasn't aware that my terminal doesn't support the bell. If you look at the askubuntu question, it mentions that the "desktop effects" in compiz consumes the bell and therefore, no sound comes out. And also given the fact that it doesn't work in console, which is the major case for a lot of users, I feel this should be mentioned.

@waldyrious - Absolutely, I just copy-pasted the text here.

**Comment by agnivade** [comment]
Hi @xxdavid , any updates on this ?

**Comment by xxdavid** [comment]
What about `Ping host and ring the bell when a packet is received (if your terminal supports it)`?

**Comment by agnivade** [comment]
Sure, please update the PR and we'll see what others have to say.

**Comment by waldyrious** [comment]
You copied the "What about" 😄 please fix that. Other than that, LGTM! 👍

**Comment by waldyrious** [comment]
oops, clicked the wrong button, sorry.

**Comment by xxdavid** [comment]
Yay, sorry. 😄

**Comment by waldyrious** [comment]
@agnivade what do you think? (asking explicitly since lgtm seems to have erased my previous approval)

**Comment by agnivade** [comment]
:+1:

**Pull request merged**
