### PR TITLE
Add options to zip

### PR DESCRIPTION
**Pull request by xsb**
Adding options to add and remove files from a compressed zip file

### CODE REVIEW

**Comment by igorshubovych** [comment]
i checked in man that quotes are needed only if you use *. Maybe it is worth mentioning.

**Comment by xsb** [comment]
@igorshubovych thanks for noticing, I removed the unnecessary quotes

**Comment by igorshubovych** [comment]
Well, there 2 options:

1. Remove quotes
2. Write example with quotes, which might be even more helpful.

**Comment by xsb** [comment]
@igorshubovych even when working with multiple files, quotes are completely optional. For example this would work as expected (I just tested it):

```
zip -d myzipfile.zip unwanted_file_1.txt unwanted_file_1.txt
deleting: unwanted_file_1.txt
deleting: unwanted_file_2.txt
```

I removed the quotes from the example. I think it doesn't make sense to add a multi-file example because at the end it's the same behavior as the first example, which includes the `-r` for recursive.

**Comment by igorshubovych** [comment]
it is for * (asterisk)

**Comment by igorshubovych** [comment]
Also could you please squash commits?

**Comment by xsb** [comment]
@igorshubovych I just added quoted path with wildcard * and squashed all commits in one

**Comment by igorshubovych** [comment]
LGTM

**Comment by waldyrious** [comment]
Sorry to nitpick, but "an already generated zip file" and "a compressed zip file" may make it sound like they refer to different concepts and throw people off for a bit. Why not describe both as "and existing zip file"?

While you're at it, it'd be nice if you expanded the "&" in the first example into "and".

But if we're being too bothersome, I'm okay with merging this as-is and fixing later. Cheers!

**Comment by xsb** [comment]
Thanks for the ideas @waldyrious, I did all of them. I hope it looks good now :)

**Comment by waldyrious** [comment]
Looks great :+1:, but unfortunately due to the recent flurry of activity, the master branch has been quite active, so it needs to be merged to your zip branch (rebase or cherry-pick might be a better option). Sorry about that! Maybe @igorshubovych can do it and save you the trouble :)

**Comment by xsb** [comment]
@waldyrious I updated my branch to include latest changes on master

**Comment by igorshubovych** [comment]
Thank you, @xsb.

May the `--force` be with you!

**Pull request merged**
