### PR TITLE
[WIP] git* commands: add Spanish translation

### PR DESCRIPTION
**Pull request by ivanhercaz**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable). **Note**. This one will depend of each command, so I will mark it when I have all the commands translated.

This PR is a work in progress with the purpose to translate to Spanish all the `git*` commands. There are 49 untranslated commands if I am not wrong, so if you think I should translate just a batch of 10 or 20 commands, warn me to keep in mind and stop to work in this PR when I reach the recommended limit for a batch in the PR.

### CODE REVIEW

**Comment by zdroid** [comment]
You can consider making [a draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) in the future. :wink:

**Comment by ivanhercaz** [comment]
> You can consider making [a draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) in the future.

Ups! That's true. I will do it in the future. I wish I could turn this into a draft.

**Comment by zdroid** [comment]
No, this is good to stay.

**Comment by ivanhercaz** [comment]
Is it preferable to make a PR with a batch of 10 commands to make it easier to review?

CC. @zdroid @sbrl @agnivade @waldyrious @andrik

**Comment by zdroid** [comment]
Yes, it's good with as many commands as possible. :laughing:
Note: this should be merged without squashing (?)

**Comment by ivanhercaz** [comment]
> But you can stop here if you wish.

Hahaha, no, no, don't worry. I will continue with this translation, a bit each day. If the reviewers have not problems to review a lot of commits in the same PR, this is fine.

**Comment by sbrl** [comment]
Yeah, there's no limit to the number of translations in a PR. I've seen over 50(!) in a single batch before.

I guess ultimately it's a trade-off between the speed of merging and the quantity that is merged at once.

Mark it as ready for review when ready :-)

**Comment by ivanhercaz** [comment]
According to the argues of @mebeim in 3746#issuecomment-573306765 and 3746#issuecomment-573329046, with which I agree, I decided to remove the label `mass changes`of this PR.

**Comment by mebeim** [comment]
@ivanhercaz please do not use emojis in commit messages.

**Comment by ivanhercaz** [comment]
> @ivanhercaz please do not use emojis in commit messages.

@mebeim, until now nobody have warned me about the use of [gitmoji](https://gitmoji.carloscuesta.me/) in the commits I push to tldr-pages, so I hope you understand that I would like to receive more opinions about it from the rest of collaborators. Tonight I will open an issue about it to discuss it properly to avoid a mass of messages about this topic in this PR.

**Comment by mebeim** [comment]
@ivanhercaz for me it's pretty straightforward: emojis don't add anything useful in a commit message and are only rendered in a specific environment (that is, the GitHub website), thus also making it needlessly harder to read commit messages. Other than that, what you see as a globe here on GitHub, is really a 22 characters string which dramatically decreases the usable space of the first line of the commit message.

image

Feel free to open an Issue and reference this comment of mine if you want.

**Comment by zdroid** [comment]
I prefer putting the emojis at the end of the commit messages. That way they don't make the issue noted by @mebeim.

**Comment by ivanhercaz** [comment]
Until #3756 is resolved, I am going to use commit messages without emojis, to avoid the case of more disturbance in the history of this repository if they wouldn't accepted as a general rule for commit messages.

**Comment by ivanhercaz** [comment]
**Note for myself**. It is necessary to update the `git-add` page due to #3778.

**Comment by ivanhercaz** [comment]
I think all the translations has been made. I think it is possible that some of the files needs some change due the mass edits I did.

I also think that it should be reviewed by some Spanish speaker due the git terminology sometimes is a bit confusing in Spanish, so I am going to mention @ChrisADR, who maintains the [git-po for Spanish](https//github.com/ChrisADR/git-po): could you review the Spanish translations I added? I imagine you have a lot of work, but as you work with the translation of `git` to Spanish, I will very grateful with you. Thank you in advance! And please, don't feel commited.

**Comment by ivanhercaz** [comment]
> **Note for myself**. It is necessary to update the `git-add` page due to #3778.

Pushed the edit to `git-add` with the new example.

**Comment by ChrisADR** [comment]
Sorry for the delay, Spanish version sounds spanish enough to me, if something pops up later, I can update it without problems. Thanks!

**Comment by zdroid** [comment]
@ivanhercaz PRs can be converted into draft PRs now :wink:

https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

**Comment by ivanhercaz** [comment]
> @ivanhercaz PRs can be converted into draft PRs now 
> 
> https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

Thank for this notice @zdroid! I will keep this in mind the next time :heart:

**Pull request merged**
