### PR TITLE
Adding long format list sorted by reverse mod date

### PR DESCRIPTION
**Pull request by CBrowne**
This a pretty useful and common use of ls to display all files with the full details showing the last modified as the last file.

### CODE REVIEW

**Comment by CBrowne** [comment]
Does anything need changed for this to be pulled?

**Comment by waldyrious** [comment]
Hi @CBrowne, thanks for the contribution :) I'm just wondering, is the use case for this example common enough to warrant expanding the page to 6 examples and almost 30 lines? Note that we're discussing the implementation of a 5-example, 25-line limit (#686).

**Comment by CBrowne** [comment]
Ah @waldyrious I wasn't aware of the proposed limit. It's up to you guys! Thanks for making this tool, it is very handy :+1:

**Comment by rubenvereecken** [comment]
Keep this PR here for a bit as the discussion isn't finished yet.

**Comment by igorshubovych** [comment]
I personally don't like that you introduce to options here: `-t` and `-r`.
It is against guidelines.

**Comment by waldyrious** [comment]
@igorshubovych as I've said elsewhere, guidelines are just that: general hints that we can deviate from if justified. We shouldn't be applying them blindly as strict rules. In this case I would say that introducing two options may make sense if the example is common, we need compactness *and* both options are explained in the text using the first letter so that it's clear what they refer to (rather than just presenting a cryptic command that one has to memorize). The last criterion isn't applied here, but I'd say we first need to decide whether we want to expand the page in the first place. Hopefully the discussion at #686 is finalized soon.

**Comment by CBrowne** [comment]
Any update on this?

Thanks

**Comment by ostera** [comment]
I think it doesn't hurt and we are still not going over the 6-commands soft-limit. I'll merge for usefulness and maybe we can revisit if someone else proposes a new tldr for this page? Thanks @CBrowne for the contribution!

**Pull request merged**
