### PR TITLE
nmcli*: update pages

### PR DESCRIPTION
**Pull request by acuteenvy**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Comment by Managor** [comment]
Should the same treatment be given to the `git` page?

**Review by kbdharun — APPROVED** [review]

**Comment by kbdharun** [comment]
> Should the same treatment be given to the `git` page?

Probably yes

**Comment by kbdharun** [comment]
> No I mean that the main page shows the common sub commands

Oh. Yeah, we can reference other `nmcli` pages in the main page.

**Review by mfrw — APPROVED** [review]
LGTM :)
Thanks @Managor for your conntribution.

**Pull request merged**
