### PR TITLE
linux package managers: add link to ArchWiki Rosetta

### LINKED ISSUE #7637: Suggestion: Add link to ArchWiki's Rosetta page in pages for Linux package managers
When it comes to commonly used package managers like `apt`, `dnf`, `pacman`, etc, [Archwiki's Rosetta page](https://wiki.archlinux.org/title/Pacman/Rosetta) is an excellent middle ground between a tldr page and a full-on manpage. I think a link to it would be helpful for many Linux users looking up an unfamiliar package manager.

The justification is that most Linux users would have some experience with at least one package manager. So if they are on a different distro with a different package manager, the best way to help them could very well be to show them a translation table if the tldr page does not suffice.

Personally I had prior experience in `dnf` and `apt` prior to using `pacman` on Manjaro, so this Rosetta page became my goto-resource before reading any manpage. I feel like this is a relatable experience to many other Linux users too, whether they are distro-hopping, working on a server over SSH, or testing software compatibility. I think it would be nice if tldr simply informs its users of this resource via a link.

And finally as a disclaimer - I'm not financially associated with ArchLinux or Archwiki. I am promoting their Rosetta page simply because it's the best resource of its kind, in my opinion, as far as I know. Please don't hesitate to suggest an alternative if you think it's better.

### PR DESCRIPTION
**Pull request by cyqsimon**
Closes #7637.

Including all affected pages in the first line of the commit message made it too long, so I put the list in a new line. Hope you find this okay.

- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by CleanMachine1 — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]
The change LGTM thanks for your contribution. But I am not sure whether 4 lines of page descriptions are allowed (NOTE: Only a handful of pages have more than 3 descriptions, especially in `git` pages. If this is important we can make an exception or we can try to concatenate this with the above line which would make the descriptions cluttered, Let's see what others think).

**Review by blueskyson — APPROVED** [review]
I think this is a good idea though I don't really like 4-line decriptions.

**Review by CleanMachine1 — DISMISSED** [review]
Wait for other reviews.

**Review by EmilySeville7cfg — APPROVED** [review]
- No issues found, approved.
- Thanks for a contribution! ❤️

**Comment by EmilySeville7cfg** [comment]
> I think this is a good idea though I don't really like 4-line descriptions.

We can abandon them via our linter and style guide to keen all our pages concise.

**Comment by kbdharun** [comment]
> > I think this is a good idea though I don't really like 4-line descriptions.
> 
> We can abandon them via our linter and style guide to keen all our pages concise.

We shouldn't abandon them because some git pages require 4 lines of descriptions. We can restrict 4 line descriptions to a handful of pages whenever necessary.

**Comment by EmilySeville7cfg** [comment]
> We shouldn't abandon them because some git pages require 4 lines of descriptions. We can restrict 4 line descriptions to a handful of pages whenever necessary.

Then I suggest permit them everywhere to be consistent. Or we can hide some of lines via our clients by default and show when smth like `--long-description` option passed.

**Comment by EmilySeville7cfg** [comment]
Merging process must not be blocked just to wait reviewers (there is no such rule in our maintainers guide). If some PR must not be merged it must be marked as draft.

**Pull request merged**
