### PR TITLE
Add missing backticks in touch.md

### PR DESCRIPTION
**Pull request by hollingberry**
I wrote a little script in Ruby to check all the pages for missing backticks. Here's the output of that script running on 5f3e3aa, before the backticks were fixed.

```
Found 1 missing backtick in pages/common/git-branch.md:
    `git branch {{BRANCH-NAME}}

Found 2 missing backticks in pages/common/tmux.md:
    `tmux a -t {{name}}
    `tmux kill-session -t {{name}}

Found 3 missing backticks in pages/common/touch.md:
    - Create a new empty file(s) or change the times for existing file(s) to current time.`
    `touch -t 201412250801.59 {{filename}}
    `touch -t {{YYYYMMDDHHMM.SS}} {{filename}}

Okay, found 6 missing backticks in all.
```

### CODE REVIEW

**Comment by hollingberry** [comment]
I guess this just seems like overkill to me. Even if missing backticks have cropped up in the past, they're all (yay!) fixed now, and it shouldn't be that hard to monitor PRs for proper formatting.

I am rather pleased with how the script checks for missing backticks though :)

**Comment by hollingberry** [comment]
Let me know if you want one of the commits moved to a different PR or whatever

**Comment by rprieto** [comment]
Hi @hollingberry, I'm confused - do you want to keep the `Rakefile` or discard it?
Personally I think it doesn't hurt, we're not forcing anyone to run it, but it can be handy to run a check once in a while. Happy merge this is everyone else is happy.

**Comment by hollingberry** [comment]
I guess I'm in favor of discarding the Rakefile, just to keep the repo as clean and codeless as can be.

Also, a heads up, keeping the Rakefile is going to make Github identify the repo language as Ruby. As far as I know, all this means is that there'll be a maroon strip at the top of the page (see https://github.com/hollingberry/tldr), but it's worth keeping in mind.

Obviously you're free to keep it if you want :)

**Comment by rubenvereecken** [comment]
I know this has been around for ages but I feel this could be incorporated now. We now have a Makefile that runs a Ruby-script on pre-commit to rebuild the index.

If this could be rewritten as a little script instead of as a Rakefile (or is rake always included with Ruby?), we could definitely put it in the already-existing Makefile.

**Comment by hollingberry** [comment]
Aah give me a second, I amended the commits but the pull request is all messed up now. I’m going to close this PR and open a new one. One minute

**Comment by rubenvereecken** [comment]
Just so you know there's some black git magic if you want to reopen this PR instead of making a new one. You can start off clean, cherry-pick the commit you need or in your case just copy the file and then git force push (`git push -f`) to your remote on the right branch.

Or, you know, do a clean PR :). I'm interested in discussing the uses for the new make target either way.

**Comment by hollingberry** [comment]
Can't figure it out. See #277

**Pull request closed without merging**
