### PR TITLE
jobs: added the page

### PR DESCRIPTION
**Pull request by Cvetomird91**
Added a page for the BASH builtin for viewing information about processes spawned by the current shell and their state.

### CODE REVIEW

**Comment by igorshubovych** [comment]
As this does not work in Zsh, Fish and other popular shells, it makes sense to mention this in command description.

**Comment by Cvetomird91** [comment]
The description has been edited.

**Comment by igorshubovych** [comment]
LGTM if commits are squashed.

**Comment by Cvetomird91** [comment]
The merge commit appeared because I clicked on the "Merge branch" button here in the Travic CI section. The other commits have been squashed into "9e16549".

**Comment by Cvetomird91** [comment]
Closed because of troubles I had with merging.

**Pull request closed without merging**
