### PR TITLE
clear: add page

### PR DESCRIPTION
**Pull request by J053Fabi0**
clear: add page

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, @J053Fabi0! Is there any reason why this PR was closed?

**Comment by J053Fabi0** [comment]
@sbrl Because of the error. But I already open a new PR

**Comment by agnivade** [comment]
Pull requests can be updated by creating a new commit and pushing again. No need to open a new PR every time.

**Comment by J053Fabi0** [comment]
Oh, thanks to tell me 😅

**Pull request closed without merging**
