### PR TITLE
Sudo is not needed for npm install

### PR DESCRIPTION
**Pull request by eddiejaoude**
----

- [ ] ~~The page (if new), does not already exist in the repo.~~

- [ ] ~~The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.~~

- [ ] ~~The page has 8 or fewer examples.~~

- [ ] ~~The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited~~

- [ ] ~~The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines~~

### CODE REVIEW

**Comment by sbrl** [comment]
Not true. `sudo` is required on my system if I want to install a package globally. Indeed, it is not required to install locally, but it is (on my system at least) required to install globally.

**Comment by eddiejaoude** [comment]
> Not true. sudo is required on my system if I want to install a package globally. Indeed, it is not required to install locally, but it is (on my system at least) required to install globally.

Your system is not setup correctly! From the [npm docs](https://docs.npmjs.com/getting-started/installing-npm-packages-globally)

> To download packages globally, you simply use the command anpm install -g <package>a, e.g.:
> `npm install -g jshint`
> If you get an EACCES error, you should fix your permissions. You could also try using sudo, but this should be avoided:

> **You could also try using sudo, but this should be avoided:**

**Comment by sbrl** [comment]
Ok then! Thanks for the correction, @eddieantonio 😺

**Comment by eddiejaoude** [comment]
You are welcome @sbrl, I hope that helps 👍

**Comment by agnivade** [comment]
@sbrl - FYI - everywhere else the `npm install` is without sudo. In the node client repo, there is a section which mentions why root is not needed. Hence this was done to make everything uniform.

**Pull request merged**
