### PR TITLE
find: add example to find broken symbolic links

### PR DESCRIPTION
**Pull request by mukimov**

### CODE REVIEW

**Comment by agnivade** [comment]
@mukimov - Please fix the travis errors.

pages/common/find.md:38: TLDR103 Command example is missing its closing backtick

**Comment by mukimov** [comment]
@agnivade Thx fixed

**Comment by agnivade** [comment]
Hi @mukimov - thanks for your contribution. Unfortunately, this exceeds our max. no of examples(8) that we allow per page. Our primary aim, as the name tldr suggests, is to mention the most commonly used examples of a command and keep it within limits.

**Comment by waldyrious** [comment]
@mukimov, as @agnivade suggests, this addition exceeds our limit, but we can always replace one of the existing examples by this one, if you make a good case that it would be a reasonable tradeoff. Let us know what you think :)

**Comment by mukimov** [comment]
@waldyrious @agnivade Thank you both, but I can't find best reason why you should replace this command with existing. Will decline this PR.

**Comment by agnivade** [comment]
Thanks for your understanding @mukimov ! Appreciate it.

**Pull request closed without merging**
