### PR TITLE
nmtui.md: add page

### PR DESCRIPTION
**Pull request by haloboy777**
----

- [x] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by sbrl** [comment]
Hey - thanks for the new page, @haloboy777! Looks like you're having some issues with the linter. We've got the style we prefer documented over [here](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format), and a few good examples are the pages for `tar`, `eyeD3`, and `ln`. If you need any assistance, just ask :smiley_cat:

**Comment by agnivade** [comment]
ping @haloboy777 - please look into the syntax errors. And also have a look at some other tldr pages to see the general style that is followed.

**Comment by haloboy777** [comment]
sorry i've been busy.
I fixed my error.

**Comment by jsonbruce** [comment]
It seems like waiting for a long time.
How should we deal with this kind of situation? @agnivade @sbrl

**Comment by agnivade** [comment]
stale bot automatically closes issues like these. First it gives a waiting label if a PR is inactive for 15 days, then it closes it after 30 days of further inactivity. Now that you have commented on it, the cycle has been reset to 0 :laughing: 

I think I will take care of this PR myself.

**Comment by agnivade** [comment]
@jsonbruce - Please check

**Comment by sbrl** [comment]
Looks ok to me! Thanks, @haloboy777 and @agnivade :D

**Pull request merged**
