### PR TITLE
stty: fix typo

### PR DESCRIPTION
**Pull request by tomek-szczesny**
According to stty --help, parameter F must be capital (small is not recognized).
Some Asian translation appears to have the same error, but I didn't want to break encoding.

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by tomek-szczesny** [comment]
Pardon the polish extract from the command help, but this should be clear enough evidence. :)

```
mctom@Tomusiomat-ARM:~/notes$ stty --help
Składnia: stty [-F URZĄDZENIE] [--file=URZĄDZENIE] [USTAWIENIA]...
    albo: stty [-F URZĄDZENIE] [--file=URZĄDZENIE] [-a|--all]
    albo: stty [-F URZĄDZENIE] [--file=URZĄDZENIE] [-g|--save]
Wypisanie lub zmiana ustawień terminala.

Argumenty obowiązkowe dla opcji długich obowiązują również dla krótkich.
  -a, --all          wyświetlenie wszystkich aktualnych ustawień w postaci
                       czytelnej dla człowieka
  -g, --save         wyświetlenie wszystkich aktualnych ustawień w formacie
                       czytelnym dla stty
  -F, --file=URZĄDZENIE  otwarcie i używanie podanego URZĄDZENIA zamiast
                     standardowego wejścia
      --help     wyświetlenie tego opisu i zakończenie
      --version  wyświetlenie informacji o wersji i zakończenie
```

**Comment by bl-ue** [comment]
Hey @tomek-szczesny do you have "Allow edits my maintainers" (or something like that) turned on in this PR?  I'm having trouble pushing commits to the PR (to update the aforementions Asian pages)

**Comment by tomek-szczesny** [comment]
> Hey @tomek-szczesny do you have "Allow edits my maintainers" (or something like that) turned on in this PR? I'm having trouble pushing commits to the PR (to update the aforementions Asian pages)

Yep, edits by maintainers are allowed. The problem might be that I launched this PR from the fork in my repo.
I'll try to update this PR with the edit of "Asian" stty page, maybe I won't break it.

**Comment by tomek-szczesny** [comment]
I updated Chinese version of stty as well, the world didn't burst into flames.

**Comment by CleanMachine1** [comment]
I can't see why you can't push, also that git command you put (in the gitter) is pretty interesting, I've always worked on branches rather than PRs

**Comment by bl-ue** [comment]
@CleanMachine1 [that command](https://gitter.im/tldr-pages/tldr?at=60afbef4a10461235da1816c) that I ran (`git push upstream HEAD:refs/pull/6055/head`) _is_ cool, but I didn't come up with it myself.  
The official GitHub CLI, [`gh`](http://github.com/cli/cli), told me to try it after I ran `gh pr checkout 6055`, `git commit`, and `git push` (which didn't work :cry:).

**Comment by CleanMachine1** [comment]
I've never used the gh application, it seems overly junky, I'd rather use the web and use my mouse for it, and git for every thing I know how to since it has my gpg signing and other things

**Comment by tomek-szczesny** [comment]
Neither did I ever try github's official CLI. Not only do I find the idea redundant to git, I am also suspicious of tools that pop up right after Microsoft bought the platform.
@CleanMachine1, forgive me this, but I was sure you were a bot.. :D

**Comment by CleanMachine1** [comment]
Why did you think I was a bot?

**Review by CleanMachine1 — APPROVED** [review]

**Comment by tomek-szczesny** [comment]
> Why did you think I was a bot?

Must have something to do with your nick, and the fact that the first thing you did was adding a label to PR, something a bot could have done as well. ;)

**Comment by CleanMachine1** [comment]
I was busy but had a second to add a tag and my username is basic because I couldn't think of anything :)

**Comment by tomek-szczesny** [comment]
Same here, so I used that name that my mom used to call me. ;)

**Review by marchersimon — APPROVED** [review]
Thanks @tomek-szczesny

**Review by sbrl — APPROVED** [review]
Thanks, @tomek-szczesny! Great catch.

**Comment by sbrl** [comment]
Merging early, since this is a fairly trivial change.

**Pull request merged**
