### PR TITLE
fix `find` markdown format.

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by igorshubovych** [comment]
Why is it unnecessary?

-exec and -delete are different options

**Comment by felixonmars** [comment]
Actually I even find `-exec command {} +` very commonly used and wanted to add that as an example...

**Comment by appleboy** [comment]
@igorshubovych @felixonmars 

I update the markdown format. Please review again.

**Comment by appleboy** [comment]
The following screenshot was output by node version. Missing some content, so I correct markdown format.

screen shot 2015-12-28 at 5 47 11 pm

**Comment by igorshubovych** [comment]
It is a problem in tldr-node-client. Could you please report it?

**Comment by appleboy** [comment]
@igorshubovych OK. I can report to `tldr-node-client` but I think the correct format is single description and single command. Right?

**Comment by igorshubovych** [comment]
@appleboy 
That's right. Now I understood you've done.

Thank you for your contribution!

**Comment by appleboy** [comment]
@igorshubovych Thanks.

**Pull request merged**
