### PR TITLE
alias: add Hindi translation

### PR DESCRIPTION
**Pull request by 2KAbhishek**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Review by marchersimon — APPROVED** [review]
Syntax looks good, thanks

**Comment by marchersimon** [comment]
Just a quick question about Hindi punctuation: If Hindi uses `|`, why did you (and Hindi contributors before you) use `.` after the more info link?

I'm currently trying to fix Hindi pages in #6570. Could you maybe have a quick look at it? Thanks!

**Comment by 2KAbhishek** [comment]
> Just a quick question about Hindi punctuation: If Hindi uses `|`, why did you (and Hindi contributors before you) use `.` after the more info link?
> 
> I'm currently trying to fix Hindi pages in #6570. Could you maybe have a quick look at it? Thanks!

I'm not sure about other contributors (I think they assumed since most of the other hindi pages use '.' they used it too) I was suggested to use '.' in #6735 

But I do think that using '।' is a better option.

P.S - '।' is different from '|' :)

**Comment by marchersimon** [comment]
Great! @themayankjha also seems to agree here.

**Comment by themayankjha** [comment]
yes, totally agree '।' is a better option.

**Comment by 2KAbhishek** [comment]
I'm updating rest of my PRs to use '।'

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
