### PR TITLE
xmount: add page

### PR DESCRIPTION
**Pull request by Fake4d**

### CODE REVIEW

**Comment by navarroaxel** [comment]
@Fake4d You don't need to reopen a clean PR.

**Comment by Fake4d** [comment]
I dont now what to do - i cleared the mistakes and pulled it again. 
Is it possible to stay in the same PR? 

[https://github.com/tldr-pages/tldr/pull/6106](url)

**Comment by bl-ue** [comment]
It's okay @Fake4d let's forget it and work on the new PR :)

**Comment by Fake4d** [comment]
Sorry - really kind of newbie in this whole GitHub thing ;) but I will correct future commits in the same pr!

**Comment by bl-ue** [comment]
It's no problem at all.  Really 🙂

**Pull request closed without merging**
