### PR TITLE
mailx: Improve the readability of the descriptions

### PR DESCRIPTION
**Pull request by sbrl**
I noticed that the wording was a bit awkward on the mailx command page, so I improved it a bit.

### CODE REVIEW

**Comment by agnivade** [comment]
Hmm, I'm not so sure if it improves the wording. I understand that mail "body" is the right technical term for it. But, the word "contents" feels more approachable from a beginner's viewpoint. It might not be immediately apparent that the word "body" means the message inside the mail. Whereas, when I say "contents", it unambiguously refers to the message.

Let me know your thoughts.

**Comment by sbrl** [comment]
@agnivade Thinking about it, I can see why "content" would be better than "body" for new users - I can change it if you like. A web page has a body too though, and if you're looking something up in tldr, it's possible you'd already know about that. I don't know :P

The major wording issue that I intend to fix in this commit is the `Send mail with content which written in a file` though. It just sounds _awkward_.

**Comment by agnivade** [comment]
> The major wording issue that I intend to fix in this commit is the `Send mail with content which written in a file` though. It just sounds _awkward_.

Yea that's no issue. We can change it to "Send mail with content taken from a file".

Pinging @waldyrious / @jeeftor for their opinions on the body vs content thing.

**Comment by waldyrious** [comment]
I agree that "content" is more natural and approachable.

**Comment by waldyrious** [comment]
I've made some changes to the PR, please let me know if you're ok with them @sbrl :)

**Comment by sbrl** [comment]
@waldyrious Yep, LGTM! :+1:

**Comment by waldyrious** [comment]
Thanks :) @agnivade / @jeeftor I'll leave the review/merge to one of you since I made changes myself. Don't forget to use the rebase merging option!

**Pull request merged**
