### PR TITLE
rsync: edit example for use a different port for ssh

### PR DESCRIPTION
**Pull request by NickSmyr**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by sbrl — COMMENTED** [review]
Thanks for the edit, @NickSmyr! This looks ok in theory to me.

However, I'm somewhat concerned about over-complicating this page though by adding too many different things to the examples.

To this end, I'd love to hear the opinions of others here.

/cc @owenvoke, @mebeim, @navarroaxel?

**Comment by navarroaxel** [comment]
@sbrl I think the example is needed, but not at the top of the page when the user learn how to send or receive files - maybe in the example: `Transfer file over SSH and show global progress`.

**Comment by sbrl** [comment]
Hrm. The problem is that if we try and demonstrate too much in a single example, it overcomplicates it and makes it more overwhelming to read. I agree about the position in the page, but I'm unsure that adding it to the existing commands is the solution.

Let's wait to get some additional opinions on the matter.

**Comment by mebeim** [comment]
I agree with @sbrl that there is no need to overcomplicate examples. We are not trying to illustrate as much functionality as possible in 8 examples, we are just showing the most common and useful usages of the command.

**Comment by navarroaxel** [comment]
@mebeim I prefer the non-default port because is a most common use case over the `--info=progress2`, right?

**Comment by mebeim** [comment]
@navarroaxel now that's a good question. I don's use `rsync` that much, I have a feeling that you might be right, but I'm not sure.

**Comment by sbrl** [comment]
Hrm. What does `--info=progress2` do differently to not having the flag? I don't use `rsync` much either (I find it too complicated, so I avoid it where possible), so I'll defer to you on that one. I'm certainly up for replacing `--info-progress2` if a non-default port is more useful.

**Comment by navarroaxel** [comment]
Is similar to the example with `-P`. Looks like the `-P` is progress per file, and `--info=progress2` is global progress.
```bash
$  rsync -azzvhP catalina.vdi* lenovo:/home/anavarro
sending incremental file list
catalina.vdi.part1.rar
         56.79M   2%   10.52MB/s    0:03:04  ^C
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(701) [sender=v3.2.3]
$  rsync --info=progress2 catalina.vdi* lenovo:/home/anavarro
    105,046,752   1%   25.02MB/s    0:05:13  ^C
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(701) [sender=v3.2.3]
$  rsync -azzvhP --info=progress2 catalina.vdi* lenovo:/home/anavarro
sending incremental file list
catalina.vdi.part1.rar
         93.45M   1%   29.58MB/s    0:04:25  ^C
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(701) [sender=v3.2.3]
```

The `-P` is better and I heard more examples using it.

**Comment by sbrl** [comment]
Ah, I see. Wouldn't showing global progress be useful though to know when the `rsync` will complete?

**Comment by NickSmyr** [comment]
Perhaps i could move the new port fucntionality to the last example ? Isn't the default shell ssh anyway ? Sorry that this pr has sparked so much discussion for such a small thing

**Comment by sbrl** [comment]
No worries, @NickSmyr! `rsync` is just a particularly difficult page because there's so much functionality to show :P

It's not normally like this.

**Comment by einverne** [comment]
I kinda agree with @navarroaxel , a non-default port example is much important than the `--info=progress2` option.

**Comment by mebeim** [comment]
I think we can just let the first 7 examples unchanged, and edit the last one to this:

```
- Transfer file over SSH using a different port than the default and show global progress:

`rsync -e 'ssh -p {{port}}' --info=progress2 {{remote_host}}:{{path/to/remote_file}} {{path/to/local_file}}`
```

What do you guys think?

**Review by navarroaxel — APPROVED** [review]
LGTM, cc @mebeim

**Review by mebeim — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
Thanks, @NickSmyr!

**Pull request merged**
