### PR TITLE
*: shellcheck and fix typos

### PR DESCRIPTION
**Pull request by a1346054**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

CLA trivial, feel free to commit in your own name without attribution.

### CODE REVIEW

**Comment by CleanMachine1** [comment]
wow thanks for the work, surprised these hadn't been found before.

Unless you don't want to sign the CLA, it would be helpful for us for you to. It only takes a second :)

**Comment by a1346054** [comment]
I do not wish to go through the trouble of investigating a CLA for spelling fixes, which would be considered trivial in any licensing/relicensing situation. I do not ask for any recognition, commit it in your own name if you wish.

**Review by navarroaxel — APPROVED** [review]
Hi @a1346054, welcome and thanks for your submission. Could you please sign the license to pass the CLA check?

**Comment by CleanMachine1** [comment]
> I do not wish to go through the trouble of investigating a CLA for spelling fixes, which would be considered trivial in any licensing/relicensing situation. I do not ask for any recognition, commit it in your own name if you wish.

@navarroaxel

**Comment by sbrl** [comment]
Thanks for the changes, @a1346054! Very well, as you said:

> CLA trivial, feel free to commit in your own name without attribution.

....I will rebase this PR to be in my name.

**Review by sbrl — APPROVED** [review]
Thanks, @a1346054!

Note to whoever merged this: Please make sure to credit @a1346054's name in the commit message, since we've changed the commit authors here.

**Pull request merged**
