### PR TITLE
[[: add Chinese translation

### PR DESCRIPTION
**Pull request by LiLittleCat**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by LiLittleCat** [comment]
In the original `[[.md` file, there is an example:
>- Test if a given string conforms the specified glob/regex:
>`[[ ${{variable}} {{==|=~}} {{pattern}} ]]`

Should the `given string` be the `given variable`? 
I am not so sure about it, so I translated it as the `given variable`.
Let me know if there is any mistake, thanks.

**Review by EmilySeville7cfg — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
The [original page](https://github.com/tldr-pages/tldr/blob/main/pages/common/%5B%5B.md) contains several mistakes:
- `the specified` must be replaced with `a specific`
- `a given` must be replaced with a plain `a`

But they should be fixed later after this PR is merged.

**Comment by EmilySeville7cfg** [comment]
> Should the `given string` be the `given variable`?

Yes, it should. But according to the comment below without `given`.

**Review by kbdharun — APPROVED** [review]

**Comment by LiLittleCat** [comment]
> The [original page](https://github.com/tldr-pages/tldr/blob/main/pages/common/%5B%5B.md) contains several mistakes:
> 
> * `the specified` must be replaced with `a specific`
> * `a given` must be replaced with a plain `a`
> 
> But they should be fixed later after this PR is merged.

Should I correct the translated file in this PR or create a new PR after the correction of the original page？

**Review by blueskyson — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
> Should I correct the translated file in this PR or create a new PR after the correction of the original page？

It's better to split edits in several PRs. In this case I suggest you to create a separate PR for the original page's edit.

**Pull request merged**
