### PR TITLE
truss: add Hindi translation

### PR DESCRIPTION
**Pull request by pranavupadhyay123**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by sebastiaanspeck** [comment]
My bad! If I could force-push main, I could reword the commits if that's desirable.

**Comment by kbdharun** [comment]
> My bad! If I could force-push main, I could reword the commits if that's desirable.

I will fix both the ones. Force pushes are intentionally disabled for the main as it is a protected branch. If it is allowed when we do a force push on PRs we create (on other branches in the repo) it would get merged without us intending to do so.

When I need to do fixes I temporarily create an exclusion rule then revert the change, readd it.

**Comment by kbdharun** [comment]
Done, fixed it.

**Pull request merged**
