### PR TITLE
Added missing p7zip tools (7z and 7zr)

### PR DESCRIPTION
**Pull request by oxguy3**
There's already a tldr page for `7za`, the 7zip archiving tool from the p7zip package. But actually, the main executable from p7zip is `7z`. `7z` uses plugins to support lots of archive formats, while `7za` is a standalone version that only supports a limited set of archive formats. There's also `7zr`, which is another standalone version that exclusively supports the .7z formats. (I got all this info from [the ever-indispensible Arch Linux wiki](https://wiki.archlinux.org/index.php/p7zip#Differences_between_7z.2C_7za_and_7zr_binaries))

This PR adds a note to 7za.md explaining the relationship to `7z`, and also adds pages for `7z` and `7zr` (both pages are essentially copies of the original 7za.md page).

### CODE REVIEW

**Comment by waldyrious** [comment]
Would it make sense to use "archive" and "extract" (even if in parenthesis) to make it clearer what the `a` and `x` stand for?

**Comment by oxguy3** [comment]
Might not be a bad idea; I sorta just blindly copied the way 7za was written, but might as well make it better if we're modifying it. :smile:

**Comment by oxguy3** [comment]
Okay, I went ahead and changed the descriptions of the commands to archive and extract (7zip is capable of working with non-compressed archive formats like .tar files, so compress/decompress were actually misleading/incorrect terminology). I also went ahead and did a bunch of miscellaneous cleanup. In particular, the multipart archive example didn't seem particularly useful (I don't think I've ever created a multipart archive in my life), so I replaced it with the much more helpful list command.

**Comment by oxguy3** [comment]
I realized that there are a lot more archive formats available than the small list I copied from the man page, so I added "..." to the list of archive formats in the `-t` example, and then added the `7z i` command as an example of how to see the full list of available formats.

**Comment by waldyrious** [comment]
If you moved away from "compress"/"decompress", then shouldn't the tokens be changed as well?

**Comment by oxguy3** [comment]
Duhhh, yes, good catch; completely slipped my mind. Will fix that when I'm
at computer.

**Comment by igorshubovych** [comment]
@oxguy3 any updates?

**Comment by waldyrious** [comment]
Since the missing fix is quite simple and not problematic, we'll merge this and make the fix afterwards.

**Pull request merged**
