### PR TITLE
Add the nix-env to common

### PR DESCRIPTION
**Pull request by kiddkai**
Add `nix-env` command simple docs.

https://nixos.org/nix/

### CODE REVIEW

**Comment by waldyrious** [comment]
Great contribution, but I'm afraid the number of examples is too high. Can't they be reduced to the 3-5 most common tasks?

**Comment by lord63** [comment]
And the `pages/index.json` should be updated.

**Comment by kiddkai** [comment]
Cool will update it :+1: Thanks @waldyrious @lord63

**Comment by rubenvereecken** [comment]
Thanks @waldyrious and @lord63 for keeping an eye out. I'll be happily waiting for those updates :).

**Comment by igorshubovych** [comment]
@kiddkai 

Do you have any progress so far?

Can reduce the number of examples from 9 in your page to 5-6 recommended by Contributing Guideline? Or at least 7?

BTW, there is no need to update index.json. So you can just update the page.

**Comment by rubenvereecken** [comment]
I thought "let's just format this". Apparently the linter didn't catch trailing newlines yet, so thanks for that opportunity >.<.

**Comment by rubenvereecken** [comment]
It's probably just saying this isn't merged because I tried using a different approach to this sort of thing since I find myself doing this manually more and more often lately. Github is not so happy. Oh well.

:tada:

**Comment by waldyrious** [comment]
@rubenvereecken your last comment was a little confusing. For the record, this PR was merged but not through github's usual merging interface, hence the appearance that it was closed unmerged.

**Comment by rubenvereecken** [comment]
Oh no I merge through command line all the time. Lately, anyway. It's just that if I do it that way the way GitHub wants me to do it I end up creating two merge commits (instead of 1 through the interface). I opted to drop the first one this time round, just like the interface does. Apparently GitHub was looking for that one and didn't acknowledge the merge.

**Pull request closed without merging**
