### PR TITLE
sha*sum: add more information link

### PR DESCRIPTION
**Pull request by marchersimon**
For #5510

### CODE REVIEW

**Review by bl-ue — DISMISSED** [review]

**Comment by bl-ue** [comment]
@marchersimon please see @vladimyr's PR #5658 where he shorted the coreutils links.

**Comment by marchersimon** [comment]
I tried that, but that doesn't work here, since the url is sligthly different from the other pages.

**Comment by bl-ue** [comment]
Yeah, I just discovered that myself.  Well, never mind 😛

**Review by bl-ue — APPROVED** [review]

**Comment by bl-ue** [comment]
Though the linked page is tiny (this is all of the text content, Ctrl+A - Ctrl+C):
>Previous: sha1sum invocation, Up: Summarizing files   [Contents][Index]
>
>6.7 sha2 utilities: Print or check SHA-2 digests
>
>The commands sha224sum, sha256sum, sha384sum and sha512sum compute checksums of various lengths (respectively 224, 256, 384 and 512 bits), collectively known as the SHA-2 hashes. The usage and options of these commands are precisely the same as for md5sum and sha1sum. See [md5sum invocation](https://www.gnu.org/software/coreutils/manual/html_node/md5sum-invocation.html#md5sum-invocation).

...there's that link at the end which is pretty obvious IMO.  But if the others think, maybe we should change the links to all point to that md5sum link. 🤔

**Comment by marchersimon** [comment]
The problem I have with directly linking to the `md5sum` page, is that nowhere in the page is mentioned that those arguments also work for the `sha*sum` pages, which will probably confuse many and make it seem the link is wrong.

**Comment by bl-ue** [comment]
@navarroaxel, @glenacota, @yutyo Someone, can we get this merged?  I'd like to incorporate it into #5664 before that gets merged.

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
