### PR TITLE
MAINTAINERS: rework page to keep historical record

### PR DESCRIPTION
**Pull request by waldyrious**
See discussion starting [here](https://github.com/tldr-pages/tldr/issues/2989#issuecomment-490796319) for context and motivation.

### CODE REVIEW

**Comment by waldyrious** [comment]
In a later PR I intend to reconstruct the past history of role changes in order to full in the log for all sections. Any assistance in doing so is welcome!

**Comment by andrik** [comment]
@waldyrious what about a timeline?

I know markdown doesn't support it, but we can use an image to represent that.

**Comment by schneiderl** [comment]
@andrik I'm not really in favor of a image as it creates a bunch of maintenance need. 

The changes proposed in this PR are, IMHO, the way to go. As it documents the past while keeping the current points of contact highligted.

**Comment by waldyrious** [comment]
@andrik I'd much rather have the information in textual form (searchable, versionable, etc.) Not opposed to adding a timeline if there's a simple way to update it; otherwise, I agree with @schneiderl that it would be too burdensome to keep this page updated.

**Comment by waldyrious** [comment]
> If only there was a way to grey things out like lo-colour in the terminal.....

Well, we could use blockquote, but I tested and couldn't find a way to play nicely with the list formatting.

Option 1, list items inside blockquote:
- foo
- bar
> - baz
> - qux

Option 2, blockquote inside list items:
- foo
- bar
- > baz
- > qux

**Comment by waldyrious** [comment]
That said, we can look at some alternatives:

### Option 1: Bold and normal

This is the one currently implemented in this PR

- **Person One ([@personone]())**: [1 January 2001]() — present
- **Person Two ([@persontwo]())**: [2 February 2002]() — present
- Person Three ([@personthree]()): [3 March 2003]() — [13 March 2013]()
- Person Four ([@personfour]()): [4 April 2004]() — [14 March 2014]()

### Option 2: Blockquote without list

Person One ([@personone]()): [1 January 2001]() — present
Person Two ([@persontwo]()): [2 February 2002]() — present

> Person Three ([@personthree]()): [3 March 2003]() — [13 March 2013]()
> Person Four ([@personfour]()): [4 April 2004]() — [14 March 2014]()

### Option 3: Using the `<details>` element

- Person One ([@personone]()): [1 January 2001]() — present
- Person Two ([@persontwo]()): [2 February 2002]() — present

<details><summary>Past members</summary>

- Person Three ([@personthree]()): [3 March 2003]() — [13 March 2013]()
- Person Four ([@personfour]()): [4 April 2004]() — [14 March 2014]()
</details>

My opinion is that the first option is the simpler to implement and nicer-looking, but let me know what you guys think.

**Comment by schneiderl** [comment]
@waldyrious Agree with you.

**Comment by sbrl** [comment]
Hrm, I'm not sure about blockquote. The details looks good actually - I'm evenly split between bold and details.

**Comment by agnivade** [comment]
No blockquote please. I am also evenly split between bold and details.

**Comment by waldyrious** [comment]
@pxgamer, @andrik, what do you think?

**Comment by pxgamer** [comment]
I think option 1 (bold) seems the best. It also will work across pretty much all markdown editors and previewers, whereas `details` may not. Having `details` is also maybe a little less neat in the source. And the spacing between markdown and HTML elements can sometimes cause issues.

However, if people prefer using details, that's fine with me.

**Comment by mebeim** [comment]
I think option 1 is the best both for simplicity and compatibility.

**Comment by andrik** [comment]
Hi guys,

Great work @waldyrious 

I vote for number one too.

**Comment by waldyrious** [comment]
Great, so it looks like we have consensus. I'll go ahead and merge this to unblock @pxgamer's PR.

**Pull request merged**
