### PR TITLE
quick pages.ro translation using aws translate

### PR DESCRIPTION
**Pull request by cipy**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by CleanMachine1** [comment]
This isn't going to be very much fun to review.

1 Neptune year will be long enough to review.

**Comment by cipy** [comment]
this translation can be generated independently via `bash scripts/translate.sh` using the free tier in aws @CleanMachine1

**Comment by marchersimon** [comment]
Oh, wow. That's a quite unusual PR. I'm not sure if we can accept it tough, since we don't know about the quality of those translations.

**Comment by cipy** [comment]
well, I agree that aws translate is far from native (ro), bordering funny at times, but overall is maybe 75% accurate

**Comment by marchersimon** [comment]
The problem is just that people who have their system in `ro` will only get to see those pages, instead of the English fallback pages. And I don't think it's fun to read poorly translated documentation all the time.

**Comment by sbrl** [comment]
Does someone have a link to the part in the diff that contains the script `scripts/translate.sh` mentioned please? My (beefy) machine is struggling to render the diff in my browser, and it's also like a needle in a haystack

**Comment by marchersimon** [comment]
https://github.com/unPi-ro/tldr/blob/main/scripts/translate.sh

**Comment by cipy** [comment]
> The problem is just that people who have their system in `ro` will only get to see those pages, instead of the English fallback pages. And I don't think it's fun to read poorly translated documentation all the time.

I'd say most people will be in en/us if they understand the language, otherwise in `ro` at which point a similar question would be: will they copy & paste the text to G translate to understand it, or just bail? Plus man pages are still in `en` as a fallback

**Comment by marchersimon** [comment]
That's a really tough topic. We defenetly need some more opinions. @navarroaxel @SethFalco @waldyrious @owenvoke

**Comment by sbrl** [comment]
Thanks, @marchersimon!

A stylistic choice there would be to suggest using tabs (or 4 spaces) instead of 2 spaces to enhance readability.

The issue of translation quality is an interesting one.

On the 1 hand, some people may know `ro` (what language is that?) and not English, and the translation would be useful. On the other hand, they may know both English and `ro`, and hence the English one would be of better quality and be more useful.

The other consideration is whether the automated translation retains the specific technical meaning or not. We would need someone who speaks `ro` to look at this for us. Specifically, the `git` family of pages would be a great test for this.

**Comment by marchersimon** [comment]
Another problem I see with this is, that we currently have a lot of PRs to translate pages. If now every page has a translation, a lot of that would fall away. I think a great aspect of tldr pages is, that everything is user-created and reviewed by at least two other people.
(@sbrl `ro` is Romanian)

**Comment by SethFalco** [comment]
In my opinion, machine translations shouldn't be kept in projects without human review.

Machine translations are wonderful, but not when people don't know that they are. Especially if people end up wasting a tonne of time because small details or terminology didn't translate over correctly.

If tldr clients want to do machine translations, that could be a cool feature. How they implement or configured is up to the developer, but in the end that'd work. I feel this repository should only have high-quality human reviewed translations, however.

**Comment by sbrl** [comment]
To be clear, this is a great effort! Very cool. But it might be better served as a client-specific feature?

**Comment by cipy** [comment]
> > since we don't know about the quality of those translations.
> 
> Very valid.
> 
> > bordering funny at times, but overall is maybe 75% accurate
> 
> Anything below 100% (or 99% for the sake of human-error) isn't enough imo.

as everyone knows, automated translations can't match a good human translator in quality

case in point commit 96de11d3d9ef4a6c0e664b7466a18b6cc92effc2 where I had to retranslate it myself to reduce the line length (MD013)
also human translators introduce their own bias, as I distilled/cut further the line in order to get its shorter length.
overall it means the same as what I started with, but word for word is definitely not the same with `en` original

the glaring error I made in my translate.sh is that "- [a] rchive" like words are not properly translated, not because aws translate is that bad, but because I jumped ahead and ignored this case for now, as search [`a`] in the translated word might never be there. here's the only part where aws translate gets a bit funny. I doubts all commands have complex parameters like these, but maybe they are at least 15-25% of all

I'll ping this thread once I have a working solution for - [a] rchive cases and we should see how many of them are

I guess a good rule of thumb to validate a translation is to take one page at random, paste it as `ro` to `en` in G translate and see if the final meaning is similar to the one from `pages`, obviously some automated translators are bad at this 🙈

**Comment by cipy** [comment]
> To be clear, this is a great effort! Very cool. But it might be better served as a client-specific feature?

maybe prompting in `tldr` client: do you accept an automated translation for this language? before cloning would work 🥇

**Comment by cipy** [comment]
```
pages.ro git:(main) grep -rE '\[[a-z]\]' . | wc -l                                                  
      81
```

had a quick look at these, they'd need to be human interpreted, i.e. y in `s[y]mbols` can't be script matched to `s[i]mboluri`

81 (imperfect lines) out of 53089 total lines in this commit would be a 1.52% miss @SethFalco @sbrl

**Comment by marchersimon** [comment]
> maybe prompting in tldr client: do you accept an automated translation for this language? before cloning would work :1st_place_medal:

The big prroblem we have with new features is that we need to make sure all clients support it. For this we would have to keep a seperate list of what is translated and what not and the every client would have to parse that. This isn't going to happen. 

What we could do however is adding new pages, which are machine translated and proofread/corrected in multiple smaller PRs. This way we could ensure, that we don't have any "bad" pages. Also, for that many pages it would be great if there was a second person knowing the language to review those pages.

**Comment by cipy** [comment]
maybe @iuliandita?

**Comment by iuliandita** [comment]
I would be happy to help. I'm native in `ro` and dabble with `en`. I believe my `todoist` page was the first one in `pages.ro`. :D

And just to add my 2c. I wanted to say that most `ro` speakers have their devices in `en` anyway, however, I noticed a trend where more and more people, especially new(ish) to technology, use them in `ro` instead. Such as my parents, or my kids. When I first had contact with a computer, many years ago, nothing was available in `ro`, so I've been using `en-US` ever since. But today, especially large software publishers offer `ro` by default, so it might be worth to have more translated pages available.

I did look a bit through the AWS translation, and... it needs help :). If it were literature, I am sure it would have worked out a lot better, but in our case, with short sentences and variable names, the translations **must** be human proofread (and I can help with that).

We could also try the [DeepL API](https://www.deepl.com/docs-api)? I tested it on the `2to3` page, and I believe the translation is better. Not sure how much we can automate it, though...

```md
# 2to3

> Automated Python 2 to 3 code conversion.
> More information: <https://docs.python.org/3/library/2to3.html>.

- Display the changes that would be performed without performing them (dry-run):

`2to3 {{path/to/file.py}}`

- Convert a Python 2 file to Python 3:

`2to3 --write {{path/to/file.py}}`

- Convert specific Python 2 language features to Python 3:

`2to3 --write {{path/to/file.py}} --fix={{raw_input}} --fix={{print}}`

- Convert all Python 2 language features except the specified ones to Python 3:

`2to3 --write {{path/to/file.py}} --nofix={{has_key}} --nofix={{isinstance}}`

- Display a list of all available language features that can be converted from Python 2 to Python 3:

`2to3 --list-fixes`

- Convert all Python 2 files in a directory to Python 3:

`2to3 --output-dir={{path/to/python3_directory}} --write-unchanged-files --nobackups {{path/to/python2_directory}}`

- Run 2to3 with multiple threads:

`2to3 --processes={{4}} --output-dir={{path/to/python3_directory}} --write --nobackups --no-diff {{path/to/python2_directory}}`
```

AWS:
```md
# 2to3

> Conversie automată Python 2 la 3 cod.
> Mai multe informaţii: <https://docs.python.org/3/library/2to3.html>

- Afișați modificările care ar fi efectuate fără a le efectua (uscat-run):

`2to3 {{path/to/file.py}}`

- Conversia unui fișier Python 2 în Python 3:

`2to3 --write {{path/to/file.py}}`

- Conversia specifice Python 2 caracteristici lingvistice la Python 3:

`2to3 --write {{path/to/file.py}} --fix={{raw_input}} --fix={{print}}`

- Convertiți toate caracteristicile lingvistice Python 2, cu excepția celor specificate în Python 3:

`2to3 --write {{path/to/file.py}} --nofix={{has_key}} --nofix={{isinstance}}`

- Afișează o listă cu toate caracteristicile lingvistice disponibile care pot fi convertite de la Python 2 la Python 3:

`2to3 --list-fixes`

- Convertiți toate fișierele Python 2 într-un director la Python 3:

`2to3 --output-dir={{path/to/python3_directory}} --write-unchanged-files --nobackups {{path/to/python2_directory}}`

- Rulați 2to3 cu mai multe fire:

`2to3 --processes={{4}} --output-dir={{path/to/python3_directory}} --write --nobackups --no-diff {{path/to/python2_directory}}`
```

DeepL
```md
# 2to3

> Conversia automată a codului Python 2 în 3.
> Mai multe informații: <https://docs.python.org/3/library/2to3.html>.

- Afișați modificările care ar fi efectuate fără a le efectua (dry-run):

`2to3 {{path/to/file.py}}``

- Conversia unui fișier Python 2 în Python 3:

`2to3 --write {{path/to/file.py}}``

- Conversia unor caracteristici specifice ale limbajului Python 2 în Python 3:

`2to3 --write {{path/to/file.py}} --fix={{{raw_input}} --fix={{{print}}``

- Convertește toate caracteristicile limbajului Python 2, cu excepția celor specificate, în Python 3:

`2to3 --write {{path/to/file.py}} --nofix={{{has_key}} --nofix={{isinstance}}`

- Afișează o listă cu toate caracteristicile de limbaj disponibile care pot fi convertite din Python 2 în Python 3:

`2to3 --list-fixes`

- Convertește toate fișierele Python 2 dintr-un director în Python 3:

`2to3 --output-dir={{{path/to/python3_directory}}} --write-unchanged-files --nobackups {{path/to/python2_directory}}``

- Rulați 2to3 cu mai multe fire de execuție:

`2to3 --processes={{4}}} --output-dir={{path/to/python3_directory}} --write --nobackups --no-diff {{path/to/python2_directory}}``


Translated with www.DeepL.com/Translator (free version)
```

**Comment by cipy** [comment]
indeed, DeepL gives a much cleaner translation
but it's also ~30 EUR to retranslate everything🎖️

**Comment by iuliandita** [comment]
> but it's also ~30 EUR to retranslate everythingmedal_military

It is free for up to 500k chars per month. I did not expect tldr/pages to be 3 times that, shoot...

**Comment by cipy** [comment]
common and linux directories are 1.3 Million chars, hence you'd need 3x deepL quota to run it once with no mistakes 💯

**Comment by marchersimon** [comment]
Maybe we can somehow trick it with multiple accounts. But otherwise, it wouldn't be a problem at all if we do a third of the pages each month.  But please don't make too huge PRs, maybe 20 pages per PR. And thanks a lot @cipy and @iuliandita.

**Comment by marchersimon** [comment]
@cipy, would doing smaller PRs with DeepL be okay for you? Because in this case, I think we can close this PR.

**Comment by cipy** [comment]
I guess it could be done at some point 🔹

**Comment by cipy** [comment]
I'm looking now at translations coming from DeepL and they're on the same level of fsck as aws translate

yes, as a native if someone cherry picks some of aws translated lines and some of deepl line, the result is better

but at least for Romanian, deepl is not much for 20 EUR vs all for free in aws translate /cc @iuliandita

**Pull request closed without merging**
