### PR TITLE
README: Fix description of C client

### PR DESCRIPTION
**Pull request by sbrl**
Ref https://github.com/tldr-pages/tldr-cpp-client/issues/20

### CODE REVIEW

**Comment by zdroid** [comment]
Once the repository gets renamed, we should also change the link to it. What do you think about doing both in this PR?

**Comment by sbrl** [comment]
Not sure about that @zdroid. It sounded complicated to do the repo rename - we should do that in a separate PR.

**Comment by zdroid** [comment]
It's not really complicated at all. There are no conflicts with any other repositories, so GitHub will make a repository redirect without any problem.

**Comment by sbrl** [comment]
@zdroid: https://github.com/tldr-pages/tldr-cpp-client/issues/20#issuecomment-246769596

**Comment by agnivade** [comment]
Let's merge this for now.

**Pull request merged**
