### PR TITLE
J

### PR DESCRIPTION
**Pull request by Aracki**
I have added [j](https://github.com/wting/autojump) (copy of `autojump`) and links to each other.

### CODE REVIEW

**Comment by Aracki** [comment]
@sbrl Here I made another PR about `autojump`. Can you please take a look?

**Comment by mebeim** [comment]
I'm not sure about this PR:

- `j` is not a command itself. It's just a shortcut for `autojump`, and as a consequence the examples are also duplicated.
- `autojump` has more than one shortcut, if we create a page for one of them, does that also mean we should create a page for each of the others? Wouldn't really make much sense IMHO.
- The description of `autojump` taking up four lines doesn't look that pretty. I wouldn't suggest that addition.

**Comment by sbrl** [comment]
Ah, good points @mebeim. Not actually having used `autojump` before, I thought that `j` was a command that autojump provides.

**Comment by Aracki** [comment]
OK no problem, I will close it.

**Comment by mebeim** [comment]
@sbrl `j` is indeed a command provided by `autojump`.

**Comment by sbrl** [comment]
@mebeim If it's a command provided by `autojump` an  not an alias, should it not have it's own page?

**Comment by mebeim** [comment]
@sbrl sorry for the misunderstanding, I meant to say that `j` is a command provided by `autojump` as a short alias to itself. So yes, basically an alias.

**Pull request closed without merging**
