### PR TITLE
alien, abbr: add German translation

### PR DESCRIPTION
**Pull request by Mastercuber**
- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by navarroaxel** [comment]
@Mastercuber could you please sign the license to pass the CLA check?

**Comment by Mastercuber** [comment]
I already sign the license..

**Comment by navarroaxel** [comment]
@Mastercuber You should amend your commit using:

```bash
git commit --amend --author 'Your name <user@example.com>'
git push --force
```

And the name and email must match your GitHub account.

**Comment by Mastercuber** [comment]
Ok, I appended the author and force pushed

**Comment by navarroaxel** [comment]
@Mastercuber but you should do that for both commits.

**Comment by Mastercuber** [comment]
Looks better. Next time I know that.

**Review by pixelcmtd — APPROVED** [review]
LGTM.

**Pull request merged**
