### PR TITLE
fc: add page

### PR DESCRIPTION
**Pull request by alex0112**
----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, @alex0112! It looks like you've got a bunch of extra commits against other pages there. Are those intentional?

**Comment by alex0112** [comment]
@sbrl They are not!  I will get that fixed.

**Comment by alex0112** [comment]
Fixing in another PR

**Comment by alex0112** [comment]
See #2608 for an update.

**Pull request closed without merging**
