### PR TITLE
git-merge-file: add page

### PR DESCRIPTION
**Pull request by MQ-06**
- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by spageektti** [comment]
Hi. Thanks for your contribution. Have you seen CONTRIBUTING.md and the style guide?

**Review by spageektti — CHANGES_REQUESTED** [review]
You copied/written a man page, which is not what tldr-pages is about.

**Comment by MQ-06** [comment]
@spageektti let me review the mistakes and get back to you!

**Comment by spageektti** [comment]
Hi @MQ-06 , any updates?

**Pull request closed without merging**
