### PR TITLE
  xargs: insert piped arguments at random position

### PR DESCRIPTION
**Pull request by aicioara**
Waiting on https://github.com/tldr-pages/tldr/pull/615 and https://github.com/tldr-pages/tldr/pull/450 no problem.

### CODE REVIEW

**Comment by aicioara** [comment]
Ping? 

Tickets should probably be prioritized based on readiness as opposed to date of arrival. This is disappointing.

**Comment by waldyrious** [comment]
@aicioara apologies for the poor feedback. We're a very small team of volunteer maintainers, and our free time is erratic; we've been dealing with the recent flurry of PRs as well as we can, and are tackling the backlog and gradually addressing the dozens of daily notifications across several repositories, in an attempt to get it down to levels that we can manage more reasonably. Thanks for pinging -- I would assess this page but I've never used xargs myself so I'll have to leave it to others.

**Comment by aicioara** [comment]
Ping

**Comment by ostera** [comment]
@aicioara sorry for the delay and thanks for the contribution :) Merged and fixed up the formatting and conflicts.

**Comment by aicioara** [comment]
Thank you very much!

**Pull request merged**
