### PR TITLE
multiple pages: add korean translation

### PR DESCRIPTION
**Pull request by lch7167**
- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by lch7167** [comment]
@einverne i want to more translation and put the common folder.

**Comment by Proscream** [comment]
this friend, me, and two are a team. we're working together, but directory was set incorrectly. i leave PR "https://github.com/tldr-pages/tldr/pull/3533" but no more mentions. Do you want this friend PR again?

**Comment by einverne** [comment]
@Proscream  Thank you for pointing out the directory problem. #3533 has just been merge. It looks good to me. @lch7167 If you work together, just follow the directory structures as other translation directory.

**Comment by sbrl** [comment]
Merging, because although I don't know the language it looks ok to me, and @Proscream says that they are translating with a friend - so I assume that this has been peer-reviewed by someone who knows the language.

In addition, I don't think we've got anyone with merging rights who knows Korean yet :-)

**Pull request merged**
