### PR TITLE
xar: add page

### PR DESCRIPTION
**Pull request by johan456789**
----

- [ ] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by johan456789** [comment]
I've fixed the errors you mentioned, but I'm not familiar with github and also this command should not be in common folder. Please help me move this file to linux and mac folders, and push again. Thanks!

**Comment by agnivade** [comment]
Just create duplicate copies of the file in linux and mac folders and push again. Let us know if you face any issues.

**Comment by sbrl** [comment]
Hey,  @johan456789! What's up? It looks like you're having some issues. Why close this pull request?

Let us know if you need any help :smiley_cat:

**Comment by johan456789** [comment]
Don't know how to edit. I created new pull requests instead😂

**Comment by sbrl** [comment]
Ah, ok! If you've used git before, you can just push new commits to the branch created in your fork. If not, then have you obtained the _GitHub Desktop App_ yet? It should make the process much easier.

**Pull request closed without merging**
