### PR TITLE
gpgconf: add page

### PR DESCRIPTION
**Pull request by th0ughtcrime**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** GnuPG 2.2.39

### CODE REVIEW

**Comment by CleanMachine1** [comment]
closes #7739

**Review by Nico385412 — APPROVED** [review]
LGTM

**Review by owenvoke — APPROVED** [review]
Nice!

**Review by kbdharun — APPROVED** [review]

**Comment by kbdharun** [comment]
LGTM, Thanks for your contribution.

**Pull request merged**
