### PR TITLE
cp: add Japanese translation

### PR DESCRIPTION
**Pull request by shu-pf**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by marchersimon** [comment]
@shu-pf if you force-pushed because of a messy git history - that's not a problem. We squash and marge the PR anyways. Force-pushing makes the reviewing process a little harder.

**Review by marchersimon — APPROVED** [review]
Thanks @shu-pf

**Comment by shu-pf** [comment]
> @shu-pf if you force-pushed because of a messy git history - that's not a problem. We squash and marge the PR anyways. Force-pushing makes the reviewing process a little harder. 

I understand. I'll try to do it without the force next time.
Thank you!

**Review by navarroaxel — COMMENTED** [review]
Thanks @shu-pf, remember that you can translate several pages in 1 PR.

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
