### PR TITLE
lpmove: update pt_BR translation

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
This PR again proves that we exclude too many checks for too many languages. This issue should've been catched in the previous PR itself.

Apart from that, the description in the beginning isn't translated at all.. @vitorhcl

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
Yeah, this seemed to have missing our oversight. We can update the page descriptions to pt_BR too here.

**Comment by vitorhcl** [comment]
Oh, I'm so sorry! I'll be more careful from now on.

When i have time I'll translate the missing CUPS pages.

**Comment by kbdharun** [comment]
@vitorhcl No problem, if possible can you add a suggestion for the untranslated first line here.

**Comment by isaacvicente** [comment]
Also guys, I'm sorry I didn't pay enough attention and left this slip off in my reviews.

**Review by vitorhcl — APPROVED** [review]

**Review by isaacvicente — APPROVED** [review]

**Pull request merged**
