### PR TITLE
alias: add Portuguese translation

### PR DESCRIPTION
**Pull request by FilipaDurao**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Review by sbrl — CHANGES_REQUESTED** [review]
Don't speak the language, but the syntax looks fine to me!

Thanks, @FilipaDurao :slightly_smiling_face:

**Review by schneiderl — APPROVED** [review]
I'm not a pt_PT speaker as a pt_BR native speaker I would say it looks all good.

**Comment by schneiderl** [comment]
@sbrl perhaps you meant to approve here? 
Your message seems positive but you requested changed.

**Review by sbrl — APPROVED** [review]
Lol oops, I did mean to approve! I hit the wrong button there :sweat_smile:

**Pull request merged**
