### PR TITLE
leave: add page

### PR DESCRIPTION
**Pull request by m4grio**
----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by m4grio** [comment]
Hi, @sbrl. It reminds you just by feeding `'Time to leave'` to the terminal 5 minutes before, at the time and every minute thereafter until you logout or manually kill the process/es – its intention is to remind you when to leave.

I normally use it to set quick reminders like for example when I'm playing a game but I need to wait certain amount of time to do something further.

The synopsis is `leave [[+]hhmm]`, where `hh` is the time in hours and `mm` the time in minutes – one nedds to set the exact time of the day to be reminded, unless the argument is preceded by `+`, which means the reminder will be triggered in `hh` hours and `mm` minutes from now.

I actually struggled to decide whether should I clarify that in the arguments with the options currently available in the `tldr` lexis and came up with the current proposal, leaving further clarification to the `man` page – which is, by the way, pretty clear and easy to understand.

Happy to discuss any further change. Couple of options:
- More examples – clarify through examples how the argument is assembled.
- Detailed explanation on the `hh`, `+`, and `mm` usage in the first example.
- Different wording.

**Comment by sbrl** [comment]
Ah, cool! Looking at it, perhaps we could put the last example 2nd? I think that should make it more obvious.

**Comment by m4grio** [comment]
I think it would be rather confusing that way.

This is the rational behind why I decided to put the examples in the order of my proposal:
1. The synopsis of remind-me-at-x command.
2. An example of remind-me-at-x command.
3. The synopsis of remind-me-in-x command.
4. An example of remind-me-in-x command.

Maybe the issue is not the *order* but the *clarity* of the descriptions – shall we try to reword it? A bit of help would help me a lot.

**Comment by m4grio** [comment]
Haha no worries.

**Comment by agnivade** [comment]
Hi @m4grio - we usually keep the language indirect and from a 3rd person perspective. So we try to avoid mentioning 'you'.

Can you update the PR to change the tone so that 'you' is not mentioned ?

**Comment by agnivade** [comment]
@m4grio made some slight changes of my own. Let me know if they look okay to you.

**Pull request merged**
