### PR TITLE
Sftp

### PR DESCRIPTION
**Pull request by smevawala**
Added an example for pulling folders.

### CODE REVIEW

**Comment by waldyrious** [comment]
This page is getting rather large. We usually recommend 5-6 examples, and this change bumps the page to 7. Perhaps we could remove one of the existing examples in order to add this one? Remember, we only aim to list the most common usages, not provide an exhaustive usage reference.

**Comment by smevawala** [comment]
True, maybe I could delete 'ls' and 'lls' and replace that with '?' which loads a list of sftp commands?  I feel as thought the recursive flag is less intuitively explained in that list.

**Comment by waldyrious** [comment]
I don't regularly use sftp myself, so I'll let others comment on your proposal. Pinging @igorshubovych @ostera @rubenvereecken @rprieto @felixonmars

**Comment by igorshubovych** [comment]
It is still 7 examples. I think it is useful and common. LGTM.

**Comment by felixonmars** [comment]
:+1:

**Pull request merged**
