### PR TITLE
powershell: add Italian translation

### PR DESCRIPTION
**Pull request by Magrid0**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by blueskyson — APPROVED** [review]

**Comment by mebeim** [comment]
Hmm, I'm kind of confused here. Seems to me like this page is out of sync with the current English version ([see `pages/common/powershell.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/powershell.md)). Just a few things I noticed at a glance:

- The description is slightly different.
- Translation of some commands is very different from the original English wording.
- `powershell -NoProfile` is documented in the English page, but not here.

Secondly, I believe the word `Text` in the command `powershell -OutputFormat {{Text|XML}}` should be left *as is* even in Italian, as that is a specific command line option accepted as is by Powershell.

Finally, the page seems to be in the wrong OS directory, it should be under `common`, not `windows`.

---

Could you please address the above and update the translation based on the current English version of the page? Thank you @Magrid0! Let me know if there is any issue, I can also apply the needed changes if you want, the bulk of the translation work seems done.

**Review by mebeim — CHANGES_REQUESTED** [review]
Hmm, I'm kind of confused here. Seems to me like this page is out of sync with the current English version ([see `pages/common/powershell.md`](https://github.com/tldr-pages/tldr/blob/main/pages/common/powershell.md)). Just a few things I noticed at a glance:

- The description is slightly different.
- Translation of some commands is very different from the original English wording.
- `powershell -NoProfile` is documented in the English page, but not here.

Secondly, I believe the word `Text` in the command `powershell -OutputFormat {{Text|XML}}` should be left *as is* even in Italian, as that is a specific command line option accepted as is by Powershell.

Finally, the page seems to be in the wrong OS directory, it should be under `common`, not `windows`.

---

Could you please address the above and update the translation based on the current English version of the page? Thank you @Magrid0! Let me know if there is any issue, I can also apply the needed changes if you want, the bulk of the translation work seems done.

**Comment by Magrid0** [comment]
> Could you please address the above and update the translation based on the current English version of the page? 

I think I'll redo it from the start, also sorry, I must've confused the two folder.

**Comment by Magrid0** [comment]
> Thanks @Magrid0. I've applied some minor changes in the wording, good to go!

thanks

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
