### PR TITLE
nm: adjust "demangle" example and sync content across linux/osx

### PR DESCRIPTION
**Pull request by waldyrious**
See #538 and #1709 for context.

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by waldyrious** [comment]
Looks like macOS's `nm` binary has a `-demangle` option that allows us to avoid piping to a separate command. Maybe this is a recent addition? It seems to not have been the case in the past, judging by the conversation in #538.

In any case, I tested this in a macOS machine to make sure the output is the same. Here are my results:

#### Without demangling

`nm /usr/local/Cellar/ilmbase/2.3.0/share/ilmbase/Half/.libs/half.o`

<details>

```
000000000000060c s GCC_except_table8
0000000000000650 s GCC_except_table9
                 U __Unwind_Resume
00000000000002ab T __Z9printBitsPc4half
00000000000002f2 T __Z9printBitsPcf
00000000000001c0 T __Z9printBitsRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE4half
0000000000000235 T __Z9printBitsRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEEf
0000000000040670 S __ZN4half5_eLutE
000000000000002a T __ZN4half7convertEi
0000000000000670 S __ZN4half8_toFloatE
0000000000000000 T __ZN4half8overflowEv
                 U __ZNKSt3__16locale9use_facetERNS0_2idE
                 U __ZNKSt3__18ios_base6getlocEv
                 U __ZNSt3__113basic_istreamIcNS_11char_traitsIcEEErsERf
                 U __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_
                 U __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev
                 U __ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEElsEf
000000000000048c T __ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_
000000000000033a T __ZNSt3__124__put_character_sequenceIcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_m
                 U __ZNSt3__15ctypeIcE2idE
                 U __ZNSt3__16localeD1Ev
                 U __ZNSt3__18ios_base33__set_badbit_and_consider_rethrowEv
                 U __ZNSt3__18ios_base5clearEj
                 U __ZSt9terminatev
                 U __ZdlPv
000000000000011a T __ZlsRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE4half
                 U __Znwm
0000000000000141 T __ZrsRNSt3__113basic_istreamIcNS_11char_traitsIcEEEER4half
0000000000000600 T ___clang_call_terminate
                 U ___cxa_begin_catch
                 U ___cxa_end_catch
                 U ___gxx_personality_v0
                 U _memset
```
</details>

#### Using the `-demangling` option:

`nm -demangle /usr/local/Cellar/ilmbase/2.3.0/share/ilmbase/Half/.libs/half.o`:

<details>

```
000000000000060c s GCC_except_table8
0000000000000650 s GCC_except_table9
                 U __Unwind_Resume
00000000000002ab T printBits(char*, half)
00000000000002f2 T printBits(char*, float)
00000000000001c0 T printBits(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, half)
0000000000000235 T printBits(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float)
0000000000040670 S half::_eLut
000000000000002a T half::convert(int)
0000000000000670 S half::_toFloat
0000000000000000 T half::overflow()
                 U std::__1::locale::use_facet(std::__1::locale::id&) const
                 U std::__1::ios_base::getloc() const
                 U std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(float&)
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(float)
000000000000048c T std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char)
000000000000033a T std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long)
                 U std::__1::ctype<char>::id
                 U std::__1::locale::~locale()
                 U std::__1::ios_base::__set_badbit_and_consider_rethrow()
                 U std::__1::ios_base::clear(unsigned int)
                 U std::terminate()
                 U operator delete(void*)
000000000000011a T operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, half)
                 U operator new(unsigned long)
0000000000000141 T operator>>(std::__1::basic_istream<char, std::__1::char_traits<char> >&, half&)
0000000000000600 T ___clang_call_terminate
                 U ___cxa_begin_catch
                 U ___cxa_end_catch
                 U ___gxx_personality_v0
                 U _memset
```
</details>

#### Using the `c++filt` command:

`nm /usr/local/Cellar/ilmbase/2.3.0/share/ilmbase/Half/.libs/half.o | c++filt`

<details>

```
000000000000060c short GCC_except_table8
0000000000000650 short GCC_except_table9
                 U __Unwind_Resume
00000000000002ab T printBits(char*, half)
00000000000002f2 T printBits(char*, float)
00000000000001c0 T printBits(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, half)
0000000000000235 T printBits(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, float)
0000000000040670 S half::_eLut
000000000000002a T half::convert(int)
0000000000000670 S half::_toFloat
0000000000000000 T half::overflow()
                 U std::__1::locale::use_facet(std::__1::locale::id&) const
                 U std::__1::ios_base::getloc() const
                 U std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(float&)
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()
                 U std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(float)
000000000000048c T std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char)
000000000000033a T std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long)
                 U std::__1::ctype<char>::id
                 U std::__1::locale::~locale()
                 U std::__1::ios_base::__set_badbit_and_consider_rethrow()
                 U std::__1::ios_base::clear(unsigned int)
                 U std::terminate()
                 U operator delete(void*)
000000000000011a T operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, half)
                 U operator new(unsigned long)
0000000000000141 T operator>>(std::__1::basic_istream<char, std::__1::char_traits<char> >&, half&)
0000000000000600 T ___clang_call_terminate
                 U ___cxa_begin_catch
                 U ___cxa_end_catch
                 U ___gxx_personality_v0
                 U _memset
```
</details>

The only [difference](https://www.diffchecker.com/GurZrpT9) is the `s` prefix provided by `-demangle` vs. the `short` prefix used by `c++filt`, which seems acceptable to me.

However, this is a single example that may fail to capture a representative sample of behavior changes between these two alternatives. Pinging @ry and @eddieantonio (the authors of the aforementioned PRs) for additional input.

**Comment by mebeim** [comment]
LGTM @waldyrious, wanna wait some time to see if original authors respond?

**Comment by ry** [comment]
LGTM - I’m glad to learn about nm -demangle

**Comment by agnivade** [comment]
Oh hi @ry, didn't know you were a contributor here. Nice.

With his blessings, I am going to merge this.

**Comment by agnivade** [comment]
Oh hi @ry, didn't know you were a contributor here. Nice.

With his blessings, I am going to merge this.

**Pull request merged**
