### PR TITLE
python: fix typo

### PR DESCRIPTION
**Pull request by chuanconggao**

### CODE REVIEW

**Comment by waldyrious** [comment]
:+1:

**Comment by felixonmars** [comment]
AFAIK -O does little "optimizations" besides skipping asserts. I don't see it as a really useful use case that belongs here.

**Comment by chuanconggao** [comment]
Skipping asserts is quite important for certain scripts, as that could take significant amount of time.

**Comment by igorshubovych** [comment]
[Contriubuting Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines):

2nd. When in doubt, keep new command-line users in mind. Err on the side of clarity rather than terseness.

I think `-o` is for advanced users.

**Comment by igorshubovych** [comment]
@chuanconggao can you please split this PR into 2 parts: fixing typo and `-O`. The reason I am asking for this: typo can be merged without any discussions.

**Comment by igorshubovych** [comment]
Thank you!

**Pull request merged**
