### PR TITLE
tmux inside tmux

### PR DESCRIPTION
**Pull request by venoel**
----

- [x] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by agnivade** [comment]
I have the same question as @sbrl. @venoel - Is this something that you use very commonly ? Or you just added this option because it is possible to do it ?

**Comment by venoel** [comment]
I have the same answer as for @sbrl. :)

For example. I start tmux locally, log in to the remote server and start tmux in remote console.

At the same time I do not insist. It is just proposal (first time in github). I like tmux and I excited of your project.

**Comment by agnivade** [comment]
Why not just type `tmux` in the remote console ? Does that not work ?

**Comment by venoel** [comment]
It works. But then you need control remote tmux, isn't it? You can achieve it by `Ctrl + B, Ctrl + B, c` for create another windows in remote tmux, for examle.

**Comment by venoel** [comment]
It works. But then you need control remote tmux, isn't it? You can achieve it by `Ctrl + B, Ctrl + B, c` for create another windows in remote tmux, for examle.

**Comment by agnivade** [comment]
I think this falls into the category of advanced usage. It would have been okay if the no. of examples would have been 5, but since this stretches it all the way to our max 8, I am reluctant to add this.

**Pull request closed without merging**
