### PR TITLE
systemd-socket-activate:  add page

### PR DESCRIPTION
**Pull request by SAYUK09**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by Magrid0 — CHANGES_REQUESTED** [review]
Hi, thanks for contributing to this project, but unfortunately we can't accept this pull request, we advise to take a look to the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) and update the file.

**Comment by SAYUK09** [comment]
> Hi, thanks for contributing to this project, but unfortunately we can't accept this pull request, we advise to take a look to the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) and update the file.

Thanks for letting know @Magrid0 

I have made the changes. Please take a look now.

**Comment by SAYUK09** [comment]
Hey @Magrid0. 
I have fixed the check errors. All the test have passed.
Maybe you can take a look now.

Thanks for being patient with me.

**Review by Magrid0 — APPROVED** [review]
Looks good to me, thanks for your contribution!

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution. I have some suggestions for this page.

Note: We highlight placeholders using `{{}}` which are highlighted in a different color/style by our clients.

Also, updated the link to point to the man page.

**Comment by SAYUK09** [comment]
> Thanks for your contribution. I have some suggestions for this page.
> 
> Note: We highlight placeholders using `{{}}`, which shows the placeholders in a different color/style on our clients.
> 
> Also, updated the link to point to the man page.

Understood, I'll keep in mind next time.

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
