### PR TITLE
pg_dumpall: update page

### PR DESCRIPTION
**Pull request by kovacs-andras**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

Hi!

I found an example in `pg_dumpall` which is invalid. Also tried to make the flags similar to `pg_dump`.
Should I do it the other way arount and modify the existing "single-letter options" to the long ones for both `pg_dump` and `pg_dumpall` (as it's mentioned in [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines) 3.)?

Thanks!
Andras

### CODE REVIEW

**Review by spageektti — APPROVED** [review]
Hi.Thanks for your contribution. LGTM. Please sign the CLA.

**Comment by spageektti** [comment]
> Should I do it the other way arount and modify the existing "single-letter options" to the long ones for both `pg_dump` and `pg_dumpall` (as it's mentioned in [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines) 3.)?

We can add both long and short using {{-s|--long}} syntax.

**Comment by spageektti** [comment]
@kovacs-andras can you please sign the CLA?

**Comment by kovacs-andras** [comment]
Sorry for the late response!
Thank you! I'll follow your approach with the flags in the future.

**Pull request merged**
