### PR TITLE
last: added the command in common section

### PR DESCRIPTION
**Pull request by Cvetomird91**
A command to check the last logged in users.

### CODE REVIEW

**Comment by waldyrious** [comment]
The only example provided seems a bit at odds with that the main purpose of the command is. Could you provide a more typical example before that?

Also, please capitalize the descriptions (sentence case).

**Comment by Cvetomird91** [comment]
I have added more examples and capitalized the description.

**Comment by waldyrious** [comment]
Much nicer, thanks! As for capitalization, I meant that the first letter of each example should be uppercase, but [looking again at the contributing guide](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format), it looks like I misremembered, so this looks :+1: to me as-is.

**Comment by Cvetomird91** [comment]
Thank you for your feedback.

**Comment by igorshubovych** [comment]
Thank you, @Cvetomird91 !

**Pull request merged**
