### PR TITLE
git-help: fix location

### PR DESCRIPTION
**Pull request by fejx**
I just noticed the `git-help.md` file is in the wrong folder structure.

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by fejx** [comment]
I am confused, [git-help:10](https://github.com/tldr-pages/tldr/blob/master/common/pages/git-help.md#L10) *does* end with a colon, is the checkstyle broken or am I overlooking something obvious?

**Comment by fejx** [comment]
Trailing whitespaces are the root of all evil 😆

**Comment by zdroid** [comment]
That's why `.editorconfig` is present :laughing:. But not all editors come with support for it pre-installed.

**Comment by sbrl** [comment]
Oops, my bad @fejx - great catch, thanks :heart:

**Pull request merged**
