### PR TITLE
hd.md: add brazilian portuguese translation

### PR DESCRIPTION
**Pull request by schneiderl**

### CODE REVIEW

**Comment by mebeim** [comment]
I'd change the commit message to `hd: add ...`, but that can be done when merging. Thanks @schneiderl :)

**Comment by andrik** [comment]
Hi @schneiderl 

I suggested a minor change, what do you think?

**Comment by sbrl** [comment]
If it's a minor change, then it may be ok to just do it & merge @andrik.

**Comment by andrik** [comment]
> If it's a minor change, then it may be ok to just do it & merge @andrik.

**Comment by andrik** [comment]
Hi guys @sbrl @mebeim 

I closed this PR by mistake and the option to reopen is disabled. Could any of you reopen, please?

**Comment by schneiderl** [comment]
Oh, I haven't seen this somehow haha. 
Sorry about not answering for so long. 
@andrik as soon as we get this reopened, I will apply the suggested changes.

**Comment by mebeim** [comment]
Can't reopen because "The repository that submitted this pull request has been deleted." guess you'll have to open another one @schneiderl, sorry :\

**Comment by andrik** [comment]
I didn't read the message, sorry about that.

**Comment by schneiderl** [comment]
@mebeim oh yes, I've deleted it some days ago. But that's okay, I will create a new one.

**Pull request closed without merging**
