### PR TITLE
atom, clear, convert, df: sync French translations with English pages

### PR DESCRIPTION
**Pull request by nicokosi**
Fix a few `fr` warnings from https://lukwebsforge.github.io/tldri18n/.

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
This type of translation PR is one of my favorite! 🧡

**Review by marchersimon — APPROVED** [review]

**Comment by bl-ue** [comment]
@nicokosi FYI—I just corrected the spaces before the colons to the French thin unbreakable ones.  See #5152 for details.

**Comment by bl-ue** [comment]
@nicokosi can you update your fork?  It's a bit out-of-date.  Here's how:
```bash
# switch to the master branch
git checkout master

# only do this step if you don't already the upstream remote (check with `git remote -v`)
git remote add upstream https://github.com/tldr-pages/tldr.git

# download the latest commits from the main repo into a temporary place
git fetch upstream master

# sync the latest commits into your fork's local master branch, in their correct order
git rebase upstream/master

# push everying up to your fork
git push
```

**Comment by bl-ue** [comment]
Also @nicokosi, will you please join our [Gitter channel](https://gitter.im/tldr-pages/tldr)? You can just login using your GitHub account.  I'd like to say something to you ;)

**Pull request merged**
