### PR TITLE
mke2fs: replace ext3 duplicaded for new ext4

### PR DESCRIPTION
**Pull request by jopefd**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by jopefd** [comment]
Sorry, I created `mke2fs-fix` branch from `commandsNandString` branch. Should I fix it for only include my commit `mke2fs: replace ext3 duplicaded for new ext4`? If yes, how can I do it?

**Comment by bl-ue** [comment]
I'll fix those for you ;)

**Comment by jopefd** [comment]
Thanks :)

**Review by bl-ue — APPROVED** [review]
Good catch, @jopefd!

**Review by CleanMachine1 — APPROVED** [review]

**Comment by jopefd** [comment]
Can I close the this PR now?

**Comment by CleanMachine1** [comment]
Why?

**Review by navarroaxel — APPROVED** [review]

**Comment by jopefd** [comment]
> Why?

Sorry, I think that PR's are closed at the end. (I'm new to contributing) 😅

**Comment by CleanMachine1** [comment]
If a PR is closed, its not merged into the base branch.

If a PR is merged then the branch you applied the commits to (base branch) are merged together

**Comment by bl-ue** [comment]
Yep, that's right.  @jopefd no problem 👍🏻

**Pull request merged**
