### PR TITLE
basename: update French translation

### PR DESCRIPTION
**Pull request by patricedenis**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

Please consider merging this pull request.
Also, can someone explain me how can I add the "translation" label to the pull request in order to sort it better?

### CODE REVIEW

**Comment by navarroaxel** [comment]
Hey @patricedenis you can translate several pages in 1 PR, and also please add the more info link to the main (English) page too. Thanks!

**Comment by patricedenis** [comment]
ok I did not saw how to do that but I think I just found.
You commit several commits into one branch and after that you can do a PR for the whole?
Also, is it possible to create a branch with a specific name directly into the Web GUI?

**Review by navarroaxel — APPROVED** [review]

**Comment by patricedenis** [comment]
Ok I did try to merge all my commits into just one PR to update basename

**Comment by bl-ue** [comment]
@patricedenis

>You commit several commits into one branch and after that you can do a PR for the whole?

Yes, that's exactly right 👍🏻 

>Also, is it possible to create a branch with a specific name directly into the Web GUI?

Yes, I believe you can, when you create the PR.

**Comment by patricedenis** [comment]
@bl-ue and @navarroaxel thank you both for your feedbacks

**Comment by bl-ue** [comment]
>Also, can someone explain me how can I add the "translation" label to the pull request in order to sort it better?

@patricedenis only repository collaborators and organization members can add/remove issue/PR labels.  Seeing "translation" in the PR title thought makes it very easy to identify it as a translation and so it's not much work to label, but thank you for the offer!

I'm not sure if GitHub supports PR templates like it does issue templates.  If it did, we could create PR templates for translations, page edits, new commands, etc., and have labels automatically added when a user creates a PR.  With issue templates, you can configure which labels should automatically be applied when a user opened an issue 🤔 

I'll merge this now, seems like it slipped out of my notice.

**Review by bl-ue — APPROVED** [review]
These sort of cleanup PRs are priceless.  IMO, they take skill and a real desire to improve the project. Thank you @patricedenis!

**Comment by patricedenis** [comment]
thank you

**Pull request merged**
