### PR TITLE
invoke-webrequest, iwr, curl, wget: add Indonesian translation

### PR DESCRIPTION
**Pull request by reinhart1010**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

This is a continuation of #8306 with fixes to mistakes spotted by @marchersimon

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
The changes LGTM, Thanks for your contribution.

> Should we update the original pages highlighting the -o option for older clients?

**Comment by reinhart1010** [comment]
> Should we update the original pages highlighting the -o option for older clients?

Our original Node.js client uses `--os` instead of `--platform`, and the issue hasn't been fixed for years. See tldr-pages/tldr-node-client#336 for details.

**Comment by kbdharun** [comment]
> > Should we update the original pages highlighting the -o option for older clients?
> 
> Our original Node.js client uses `--os` instead of `--platform`, and the issue hasn't been fixed for years. See [tldr-pages/tldr-node-client#336](https://github.com/tldr-pages/tldr-node-client/issues/336) for details.

Yeah, I noticed it too, My question was should we update the English pages too for these commands.

**Comment by reinhart1010** [comment]
Oh I thought I've done that on #8177 before

**Comment by reinhart1010** [comment]
Edit: It's under #8297 which is still an open PR

**Review by navarroaxel — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
