### PR TITLE
git-diff: Adds comparison of file on current branch to other branch

### PR DESCRIPTION
**Pull request by deiga**
----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by deiga** [comment]
@agnivade It does, but it's a more succinct syntax in comparing files from the current branch

**Comment by deiga** [comment]
And it allows you to compare files which are named differently

**Comment by agnivade** [comment]
Can we change the example to compare two different files and thereby avoid the [] ? The use of [] is a bit confusing.

**Comment by deiga** [comment]
In that case I'd rather make 2 examples, since my purpose of adding was the easy comparison of current branch file to other branch

**Comment by agnivade** [comment]
Unfortunately, we cannot make it 2 examples because that would exceed the max quota that we have of 8 examples. 

You can choose the one you think is the most important and practical one and we can go with that.

**Comment by deiga** [comment]
Why do you think that `[]` is confusing? It's a common practice in manpages to denote optional params etc.

**Comment by agnivade** [comment]
It is because of the description. You mention compare a single file from current branch to other branch, so the natural thought process is that the required input is the file, and the other branch. But then there is another file within []. So, that makes the user think what is that about. It takes some time to realize that the same command can be used to compare a different file too.

Here in tldr, we frequently do not use the man page syntax and focus on more practical and real-world examples. While using optional parameters are succinct, they only increase the cognitive load for a user. Therefore, my suggestion to use just one method.

Please note that we do not aim to cover all possible syntaxes. That is what the man page is for. We want to focus on 8 (and if possible less than that) most practical and real-world examples.

Let me know your thoughts.

**Comment by deiga** [comment]
@agnivade I went with the "compare 2 different files"

**Comment by deiga** [comment]
@sbrl jup :)

**Pull request merged**
