### PR TITLE
pipenv: add lock command with --requirements flag

### PR DESCRIPTION
**Pull request by mspear**
----

- [X] The page has 8 or fewer examples.

- [X] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [X] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by agnivade** [comment]
@mspear - I don't have much experience with `pipenv`. Do you believe this command is necessary for day-to-day usage of the command ?

**Comment by mspear** [comment]
I think so. As pipenv is an external tool and not a standard (yet) many projects and services still look for the classic requirements.txt file. This is one of my most googled commands in order to generate the that file so I thought it was pretty useful.

**Comment by agnivade** [comment]
The email used in the commit does not match with the user. Hence the issue.

**Comment by mspear** [comment]
Yep, I bet I know the problem. Did this on my work computer so my email was set to my work email instead of my personal github. Would you like me to submit a pull request with the correct email or see if I can update this one?

**Comment by mspear** [comment]
Got it. I just edited my email to the correct one in the repository. We should be good to go 👍

**Pull request merged**
