### PR TITLE
rails-db: add more information link

### PR DESCRIPTION
**Pull request by Gitleptune**
Documentation for command line usage

### CODE REVIEW

**Comment by CleanMachine1** [comment]
Could you please not spam PRs, especially trivial changes.

This is the sort of thing that fits a `mass changes` tag

**Review by CleanMachine1 — APPROVED** [review]

**Review by navarroaxel — APPROVED** [review]

**Comment by Gitleptune** [comment]
> Could you please not spam PRs, especially trivial changes.
@CleanMachine1 

Oh sorry, it's just that #5510 says that:

> Note: This should be done with a separate PR for each page

and that's why I did them in many separate ones, I'd prefer to make a bunch with one PR too.

**Comment by sbrl** [comment]
@Gitleptune no worries! Any number of PRs is great :D

Generally speaking we try to put related changes in a single PR. For example, iff someone translated 10 pages to French, they could open 1 single big PR for all 10. Similarly, if you want to add lots of more information links, they can all go in a single PR (1 commit per page changed).

The exception here and the reason it's documented as such is when one is adding new pages or making substantial changes to an existing page.

Great spot though, we should definitely update that to improve clarity.

**Comment by Gitleptune** [comment]
Oh okay, so if i were to add 10 links I should do them in a single pr that is like:
```
title: mass change: add more information links

commit 1: item1: add more information link
commit 2: item2: add more information link
...
```
?

**Comment by CleanMachine1** [comment]
> Note: This should be done with a separate PR for each page

I am very sorry for that. I didn't know about that line and TBH was getting a little annoyed from the notification spam I was getting.
Regardless of the PR count, your contributions are still wanted. And that line should probably be edited


and title would be more like

page_name, page_name: add more information link

however if it is bulk of words starting with `a`  for example then `a*: add more information link is acceptable

**Comment by Gitleptune** [comment]
No worries, I didn't realise it sent you notifications, sorry. I'll probably go with the second approach then 👍, thanks for clarifying.

**Comment by CleanMachine1** [comment]
Well I am automatically subscribed to every PR and issue. Overall, sorry for the bit of the obtuse comment I made, I worded it in a rude way.

Thanks for the contributions!

**Pull request merged**
