### PR TITLE
calc: update Spanish translation

### PR DESCRIPTION
**Pull request by kant**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

@kant While we are at this, can you update the page to match with the [English page](https://github.com/tldr-pages/tldr/blob/main/pages/common/calc.md) too? (Thanks in advance)

**Comment by kbdharun** [comment]
@kant Any updates on this? (if possible, can you update your other PRs to match with the English page too)

**Comment by kant** [comment]
> @kant Any updates on this? (if possible, can you update your other PRs to match with the English page too)

Done @kbdharun

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
