### PR TITLE
change signal explanation

### PR DESCRIPTION
**Pull request by lanzhiwang**
add common kill signal

### CODE REVIEW

**Comment by igorshubovych** [comment]
I like it. But I think it deserve a place at the bottom of the page, not at the top.

**Comment by markusthoemmes** [comment]
I'ld suggest adding some explanation for CTRL-C (interrupt, program can handle SIGINT) and CTRL-D (signaling end of file)

**Comment by waldyrious** [comment]
@markusthoemmes :+1:

**Comment by rubenvereecken** [comment]
Alright we'll have to figure something out here because the page has simply become too long.

**Comment by ostera** [comment]
I don't think we have to explain signals. It's good enough to show how to send a custom signal, but it's definitely out of the scope to explain what signals are, which ones are available, and what do they do. I'd rather close and only add `kill -{{signal_number}} {{process_id}}` instead.

**Comment by waldyrious** [comment]
@ostera I agree, but it would be nice to provide a reference to e.g. the man page of this (or another) command that explains signals; what do you think?

**Pull request closed without merging**
