### PR TITLE
docker-ps: add Indonesian translation

### PR DESCRIPTION
**Pull request by fadhlanhrts**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

### CODE REVIEW

**Comment by marchersimon** [comment]
@reinhart1010 could you please help out here? (if you want to)

**Review by reinhart1010 — CHANGES_REQUESTED** [review]

**Comment by reinhart1010** [comment]
Hey @fadhlanhrts I have left some notes to review about this. In short,

- Variables such as `{{path/to/file}}` can and should be translated, too
- I think it's better to use `kontainer` rather than `container`. for this, despite I'm disagree with replacing `image` with `citra` in this case

**Comment by navarroaxel** [comment]
@reinhart1010 do you want to contribute with this translation on your own PR?

**Comment by reinhart1010** [comment]
Sure I'll check later

**Pull request closed without merging**
