### PR TITLE
hexdump: add page

### PR DESCRIPTION
**Pull request by tzhenghao**

### CODE REVIEW

**Comment by tzhenghao** [comment]
Hey @pxgamer, good question. I believe it's installable on Windows, but I'm not sure where this should live. Should I still slot it under `linux` directory? btw, this command is readily available on MacOS.

**Comment by tzhenghao** [comment]
Another option is to put it under both `/linux` and `/osx` directories. I'm looking at another command like `htop` being slotted under `/linux`, but it works the same on MacOS. However, this markdown file isn't in the `/osx` directory.

**Comment by agnivade** [comment]
Yes, let's go with both directories. Please ensure that the command usage is correct by testing on macOS :)

**Comment by pxgamer** [comment]
Sounds good to me. :+1:

**Comment by tzhenghao** [comment]
Hi @agnivade @pxgamer, I've made the appropriate changes and tested that it works on both Linux an MacOS. Please have a look when you get the chance. Thanks!

**Pull request merged**
