### PR TITLE
gcc: add -c option

### PR DESCRIPTION
**Pull request by liuderchi**
writing `Makefile` often involves `-c` option to create object files from source code.

### CODE REVIEW

**Comment by liuderchi** [comment]
I just came up with another explanation: Compile source code into object file without linking.

**Comment by ostera** [comment]
@liuderchi can you check your git config? make sure your name and email are properly set so your commit will be attributed to your github user.

Otherwise looks good to me!

**Comment by liuderchi** [comment]
I did set my git config WRONG. Thanks for the notice.

1. Should I send another Pull Request to fix it? (turn this PR off?)
2. I want to discuss about the final description:

`- Compile source code without linking:`
or
`- Compile source code into object file without linking:`

which one is better?

**Comment by waldyrious** [comment]
For future reference, this PR was followed-up by #897 (by the same author).

**Pull request closed without merging**
