### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by rajivrnair**
Added commonly used docker commands to:
- list containers
- remove containers
- remove container images

### CODE REVIEW

**Comment by igorshubovych** [comment]
Please remove index.json from commit.

**Comment by igorshubovych** [comment]
We tend to have 5-6 the most common examples. You have 10. Let's think if we can make it shorter.

I used Docker a little bit, but I think the following examples would be used less then others:
`docker ps --filter status={{status}}`
`docker ps -q`
`docker stop $(docker ps --filter status=running -q)`

Also I would try to simplify the following complicated commands:
`docker rm $(docker ps -a -q)`
`docker rmi $(docker images -q)`

With something like this:
`docker rm {{container}}`
`docker rmi {{container_image}}`

**Comment by markusthoemmes** [comment]
Having worked quite a bit with docker, i tend to agree that the three commands mentioned by @igorshubovych are not quite common.

I also agree that simplifying the rm commands seems like a good idea, although I'ld say that both of the "complicated" ones are common use cases, as they clean up docker entirely. So, keeping tldr as what it is it would make sense to keep those two in (much like common `tar` usecases).

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

**Comment by rajivrnair** [comment]
@igorshubovych & @markusthoemmes . Understood. Thanks for the review.
I've removed the uncommon commands and reverted index.json.

As @markusthoemmes said, I think the `docker rm` and the `docker rmi` commands are fairly common when you hit the "Why isn't this working!!??" wall :)
I've added simplified versions of these commands but retained the original ones. Please let me know if this is ok.

**Comment by waldyrious** [comment]
I must say that 9 examples is still a bit excessive by tldr standards. Is there any way this could be shortened further?

**Comment by igorshubovych** [comment]
@rajivrnair,

Also could you
1) remove index.json from commits at all?
2) squash the commits.

You can use rebase for it.

**Comment by rajivrnair** [comment]
Shall I just remove the `docker rm` and `docker rmi` commands and add them as a separate file? Like the git-xxx commands.

**Comment by rajivrnair** [comment]
I've kept it simple for now - just commands to list and stop/start containers. I can add more commands to a new file if needed.

**Comment by igorshubovych** [comment]
Well being honest, I would break a rule for this command.
5-6 examples rule works good for typical Unix command which usually does one thing and does it good. Docker team made docker a super-command which does pretty everything. But I propose to merge your page as is, because it is already helpful. Later we (maybe you) can polish it even more, either adding new examples to this page or creating new subpages (checkout `tldr git-add`, `tldr git-clone`).

Thank you for your work! 👏

**Pull request merged**
