### PR TITLE
git-rename-tag: add page

### PR DESCRIPTION
**Pull request by CleanMachine1**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable). 

For #5137 

See #5950 for what I based this on

### CODE REVIEW

**Comment by bl-ue** [comment]
Why did you close this PR @CleanMachine1?

**Comment by CleanMachine1** [comment]
Since I wanted to see if I would get a perfect PR without the mess.
Sorry if it was against etiquette.

**Comment by bl-ue** [comment]
No, no problem.

**Comment by sbrl** [comment]
Tip: You can run the linter locally :-)

https://www.npmjs.com/package/tldr-lint

**Pull request closed without merging**
