### PR TITLE
uptime: Fill out some more options

### PR DESCRIPTION
**Pull request by sbrl**
....I suspect that this belongs in `linux/` too. Thoughts?

----

- [ ] The page (if new), does not already exist in the repo.

- [ ] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [ ] The page has 8 or fewer examples.

- [ ] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [ ] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by agnivade** [comment]
Yea, the platform thing is tricky. People try these commands from different systems. We need a comprehensive solution. The simplest way would be for the client to look into other folders and mention that the same page exists for a different platform.

**Comment by sbrl** [comment]
Indeed. Do we have a spec for 'official' clients or something? If we did, then we could include it in there.

Alternatively there's the symbolic link solution - which [has issues on Windows](https://github.com/git-for-windows/git/wiki/Symbolic-Links). It's that age old question in #1966 and #787 again....

**Comment by agnivade** [comment]
We have https://github.com/tldr-pages/tldr/issues/1065 which is not yet closed. It is more up @waldyrious' alley.

**Comment by sbrl** [comment]
Indeed, @agnivade

**Pull request merged**
