### PR TITLE
Added common/phpunit.md page and examples.

### PR DESCRIPTION
**Pull request by mario-deluna**
Added phpunit examples. 

Doc: 
https://phpunit.de/manual/current/en/textui.html

I hope this is the right place to put it. 

Thanks for this amazing tool!

### CODE REVIEW

**Comment by igorshubovych** [comment]
Overall LGTM.

But I would change 1st example to something like
~~~Markdown
`phpunit {{path/to/TestFile.php}}`
~~~

Again this is debatable, because tests is probably used in 99% of cases.

What do you think?

**Comment by waldyrious** [comment]
I agree with @igorshubovych. Also, [this phpunit intro page](https://www.mediawiki.org/wiki/Manual:PHP_unit_testing/Getting_started) I made for a while ago, in the context of MediaWiki development, may have some usable stuff (but that may be added in a new PR).

**Comment by ostera** [comment]
:+1:

**Comment by ostera** [comment]
@mario-deluna, please rebase from master instead of merging master back into the branch. Also squash your commits into a single one. Then we can merge this :)

**Comment by mario-deluna** [comment]
Ok, great I do that 👍

**Pull request closed without merging**
