### PR TITLE
vue: add page

### PR DESCRIPTION
**Pull request by gldraphael**

### CODE REVIEW

**Comment by waldyrious** [comment]
Thanks for the PR @gldraphael, looks great! I've left only a minor comment inline, please take a look.

**Comment by agnivade** [comment]
Nice, vue seems to be really picking up pace ! LGTM from me after fixing @waldyrious' comment.

**Comment by gldraphael** [comment]
@waldyrious done!
@agnivade yes it is :D

**Comment by waldyrious** [comment]
@gldraphael please remove the `/` as well, if you don't mind 😄

**Comment by gldraphael** [comment]
@waldyrious so should it be `{{path/to/template}}` or `{{path/to/template_folder}}`?

**Comment by ostera** [comment]
LGTM -- ha! the first `tldr.jsx` was written with vue :P

**Comment by waldyrious** [comment]
If it's a folder rather than a file, then `{{path/to/template_folder}}` would be preferred :)

**Comment by waldyrious** [comment]
LGTM!

**Pull request merged**
