### PR TITLE
fdroidcl: add page

### PR DESCRIPTION
**Pull request by Rudloff**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey, @Rudloff! Thanks for the new page. Perhaps you could sign the CLA please? Then we can get to reviewing.

Note that the email address you committed with has to be associated with your GitHub account for it to register.

**Comment by agnivade** [comment]
@mvdan - Any comments on this ? :smiley:  Would you like something changed ?

**Comment by mvdan** [comment]
I guess I'd also show `search` to find apps, and `install` to actually install them on a device. But yeah, LGTM :)

**Comment by agnivade** [comment]
@Rudloff, since we have space for more, would you like to make those changes ?

**Pull request merged**
