### PR TITLE
composer: add page

### PR DESCRIPTION
**Pull request by waldyrious**
Take two on #975, which has gotten stale.

### CODE REVIEW

**Comment by sbrl** [comment]
Ah, sorry I haven't gotten around to dealing with this. As you mentioned in #975, yeah, `origin` on my local fork points to `sbrl/tldr` (my fork) and not `tldr-pages/tldr`, since I like to be able to push to `origin`. `tldr-pages/tldr` is usually something like `upstream`. I should have caught on to that :P

**Comment by waldyrious** [comment]
@sbrl thanks for confirming :) if you do try it out eventually, let us know if you run into anything unexpected.

**Comment by agnivade** [comment]
@waldyrious - can you shed some light on this comment of mine ? https://github.com/tldr-pages/tldr/pull/975#discussion_r80179711

**Comment by waldyrious** [comment]
Quoting here for convenience:
> `- Create a new project from a given version of an existing package:`
>> @agnivade: what does it mean when you say create a project "from" a package ?

I never used composer myself, but I can only imagine that it means creating a new copy of a project; maybe it's useful for forking an existing project, or for enabling users to create their own templates for new projects? I'm not entirely sure.

In any case, since we need to wait for @brpaz to sign the CLA before merging this PR, hopefully he can clarify this as well.

**Comment by agnivade** [comment]
@waldyrious - Looks like @brpaz is inactive. Shall we close this ?

**Comment by sbrl** [comment]
I could continue the work here on a separate PR, if you like - once I've dealt with #1307. What needs doing?

**Comment by agnivade** [comment]
@brpaz needs to sign the CLA before this can be merged. So it does not matter if you do any work or not, unless he signs it, it cannot be merged.

@waldyrious - correct me if I am wrong.

**Comment by sbrl** [comment]
@agnivade Awww, nuts! I forgot about that. Ah ok, I could write a completely new one then (once I've finished `zramctl` in #1307), since I've forgotteen what this one contains :P

**Comment by jeeftor** [comment]
@sbrl - so do you want to close this PR if you are writing a new one?

**Comment by sbrl** [comment]
@jeeftor: Sure, but as I say I'd like to finish #1307 first before starting work here :smiley:

**Comment by waldyrious** [comment]
@sbrl now that #1307 is wrapped up, feel free to send a PR for composer at your leisure :) Since the contents of this PR can't be used for derivative content, I'll close it and open a new issue to track this cleanly.

**Comment by sbrl** [comment]
For interested parties, I've now created #1329.

**Pull request closed without merging**
