### PR TITLE
sleep: add page

### PR DESCRIPTION
**Pull request by dawidd6**
Added sleep page

### CODE REVIEW

**Comment by oxguy3** [comment]
LGTM!

I will note though, the minutes and hours commands only work with the [GNU coreutils version](http://www.gnu.org/software/coreutils/sleep). The [POSIX spec for sleep](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sleep.html) only requires that the sleep command support an integer number of seconds, and from [the looks of OS X man pages](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sleep.1.html), I think OS X's version only support the POSIX bare minimum. Thus, might be a good idea to have an osx version of this page in addition to the common version.

**Comment by igorshubovych** [comment]
Thanks you!

**Comment by oxguy3** [comment]
Uhh, could someone with contribution privileges please fix this? Build of master branch is failing b/c of errors in this PR (would have helped if Travis CI didn't just arbitrarily ignore this PR and not show build status on it...)

**Comment by igorshubovych** [comment]
Fixed.

**Pull request merged**
