### PR TITLE
aspell: fix the example, enclose `aspell` in backticks

### PR DESCRIPTION
**Pull request by trolzen**
The `list` command in the last example shouldn't be a token. 
The `aspell` should be enclosed in backticks, since it's a command.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

### CODE REVIEW

**Review by marchersimon — APPROVED** [review]
Thanks @trolzen

**Comment by marchersimon** [comment]
> @marchersimon Done. There was a conflict in German translation, I hope I resolved it correctly (I'm not a German speaker).

I'm not sure what conflict you mean. You didn't change anything except the curly brackets and the backticks.

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by trolzen** [comment]
@marchersimon
> I'm not sure what conflict you mean. You didn't change anything except the curly brackets and the backticks.

I'm talking about this change by other committer: https://github.com/tldr-pages/tldr/commit/5e797cefa47245f36f24879b2d9f5bfc62f6674f#diff-c8156c471133cc08b65ad59cc47d42bd6471e937d3440ec1f3c50ab1a05a8ce1

which was resolved in this extra commit: [Merge branch 'main' into aspell](https://github.com/tldr-pages/tldr/pull/9131/commits/1164c0f78b112e4cf93eb632216c72266babefaf)

**Pull request merged**
