### PR TITLE
Solve Travis error

### PR DESCRIPTION
**Pull request by zdroid**
Somehow a LF endline was missing in `ls.md` file from #3396. I'm not sure how it passed the Travis test.

P.S.
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected. At least 2 approving reviews are required by reviewers with write access.
To github.com:tldr-pages/tldr.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:tldr-pages/tldr.git'
```
I read that for merging you need 2 approvals, but it seems pushing any change requires it aswell.

### CODE REVIEW

**Comment by pxgamer** [comment]
Hmm. It looks like that PR was merged even though [Travis had failed](https://travis-ci.org/tldr-pages/tldr/builds/621272924). 🤔

**Comment by sbrl** [comment]
Yes, #3396 was merged because I believe @andrik was going to open a new PR to fix it.

@zdroid: That looks like it's because you're trying to push to master.  Try pushing to  a neww branch and opening a PR instead :P

**Comment by zdroid** [comment]
@sbrl that's exactly what I did, but I thought I could push things directly into master. :P

**Comment by agnivade** [comment]
Nope you can't :)

**Comment by sbrl** [comment]
It's for transparency. Generally we try to avoid committing directly to master - using pull requests instead.

**Pull request merged**
