### PR TITLE
Migrate to Bun 🥟

### PR DESCRIPTION
**Pull request by okineadev**

### CODE REVIEW

**Comment by spageektti** [comment]
But why?

**Comment by okineadev** [comment]
> But why?

Reforms

**Review by kbdharun — CHANGES_REQUESTED** [review]
Hi, thanks for the proposed changes. Unfortunately, I have to decline it (would love to hear more insights from our other maintainers), Bun is a relatively new programming language that is still in active development and isn't fully compatible with NodeJS yet. All of our current tooling is built for NodeJS so changing it would mean new and existing contributors need to relearn some of the changing syntax b/w NodeJS and Bun if they need to fix/update a feature. Also, it isn't given the features would work exactly the same across environments without extensive testing.

Bun atm while having good documentation is nowhere near NodeJS docs which is well documented both officially and on other sites.

We aren't an early adopter of platforms/programming languages, we wait a few years for it to become stable and widely used before adopting it. For instance, this is why we don't have a platform dedicated for something like SerenityOS (https://github.com/tldr-pages/tldr/issues/5500).

**Comment by okineadev** [comment]
> Hi, thanks for the proposed changes. Unfortunately, I have to decline it (would love to hear more insights from our other maintainers), Bun is a relatively new programming language that is still in active development and isn't fully compatible with NodeJS yet. All of our current tooling is built for NodeJS so changing it would mean new and existing contributors need to relearn some of the changing syntax b/w NodeJS and Bun if they need to fix/update a feature. Also, it isn't given the features would work exactly the same across environments without extensive testing.
> 
> Bun atm while having good documentation is nowhere near NodeJS docs which is well documented both officially and on other sites.
> 
> Btw, we aren't an early adopter of platforms/programming languages, we wait a few years for it to become stable and widely used before adopting it. For instance, this is why we don't have a platform dedicated for something like SerenityOS (#5500).

Bun is just a **runtime**, not a programming language. New contributors don't have to learn anything new, just install **Bun** and that's it.

When migrating to Bun - nothing will change

**Comment by kbdharun** [comment]
> Bun is just a runtime, not a programming language. New contributors don't have to learn anything new, just install Bun and that's it.

> When migrating to Bun - nothing will change

Fine, I am not a Bun user myself, so will wait for others views and take part in the conversation later.

**Comment by acuteenvy** [comment]
Unless you really do have some rationale, I'm also against this. Changes for the sake of changes are never good. Node.js is working just fine, why should we migrate to Bun? If we break something, we'll have to dedicate time to fixing issues that wouldn't otherwise have existed.

If you think this is worth it, please explain why.

**Comment by okineadev** [comment]
In addition, the transition to Bun is not critical for this project because there are no complex tasks here, only linters and builders, if the project was entirely based on JS and had some side effects when using Bun - then yes, it would be necessary to postpone the migration to Bun until all the bugs are fixed

And if the project is not based entirely on JS, then I honestly do not see the point in delaying the transition to a faster runtime (Bun)

**Comment by spageektti** [comment]
| bun | npm | winner |
| ----- | ------ | ---- |
| We have to change something | We do not have to do anything | npm |
| May be faster | Speed is OK | bun? |
| May break something | Just works | npm |
| users have to install bun | High chance that user already have npm installed | npm |
| I didn't know it exists | popular tool | npm |

**Comment by okineadev** [comment]
Well, according to the unanimous decision of several participants, I think it is worth canceling this PR

Thanks @spageektti for the sensible explanation.

**Comment by sbrl** [comment]
For reference, a comparison of the two is available here: https://www.builder.io/blog/bun-vs-node-js

....not to say that I support moving, but in this case I think it's probably better to stick with Node.js as bun appears to have a slightly different API? And, as @spageektti notes `node`/`npm` will likely already be installed.

**Pull request closed without merging**
