### PR TITLE
tftp: add page

### PR DESCRIPTION
**Pull request by johandegn**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known): tftp-hpa 5.2**

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution. I have a question shouldn't the last four commands have `tftp` at the start too or are they independent commands?

**Comment by johandegn** [comment]
Ah, yes, good question. They are the tftp commands you would use through the tftp client when connected to the server (maybe the examples descriptions could make it clearer). So they are not strictly speaking examples of how to use the tftp command itself, but rather how to use it after connecting.
I'm actually not sure if they should be included for that reason, but i looked around and some other pages, eg. _ftp_ and _telnet_, and they all include such examples. I think it makes sense, since just connecting the client and not actually doing anything would not be of much use. To actually use the client you would need to know these commands. But let me know what you think?

**Comment by blueskyson** [comment]
Is there any special indicator in front of tftp client command, e.g. the colon of `:wq<Enter>` of `vim`.

**Comment by johandegn** [comment]
Yes, the prompt starts with `tftp> `, indicating it expects tftp commands (like $ in a shell). But it is not something you have to write yourself, like you have to write `:` before typing a command in vim. I can add  `tftp> ` in front of the examples, but then the page is not consistent with the ftp page which has the `ftp> ` prompt (though that page could be adjusted). Since tftp is just a simple version of ftp, i think it makes sense to keep them consistent. It might also be confusing if a user thinks they need to write the prompt themselves. 

Alternatively (or maybe under all circumstances) i could adjust the descriptions to be more elaborate like: _Download file from server from the tftp client prompt_.

**Review by blueskyson — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
