### PR TITLE
added readlink

### PR DESCRIPTION
**Pull request by Cvetomird91**
Added readlink for getting symlink info.

I also added the -f option for getting the absolute path to a file, which proved to me to be very useful in 
shell scripting.

### CODE REVIEW

**Comment by igorshubovych** [comment]
-f option is not available in OSX.

**Comment by Cvetomird91** [comment]
I moved the page to the Linux section.

**Comment by igorshubovych** [comment]
Well, `readlink` is available on OSX. The 1st example works correctly. But it does not have `-f` option.

**Comment by Cvetomird91** [comment]
I have a FreeBSD box, I will test it there. Excuse me, but I don't have a Mac OS X instance at my disposal.

**Comment by igorshubovych** [comment]
NP. That's why I am telling you.

Well, I think you can move it to common anyway. And I (or somebody else) can just add the one to osx folder. It is available on OSX anyway, if you install coreutils.

Sorry, can you please revert your last commit back? It is ok, if it is in common.

**Comment by Cvetomird91** [comment]
The page has been moved to the common section and I just squashed the commits.

**Comment by ostera** [comment]
Thanks @Cvetomird91!

**Pull request merged**
