### PR TITLE
.

### PR DESCRIPTION
**Pull request by ultrox**
.

### CODE REVIEW

**Comment by waldyrious** [comment]
Hi @ultrox! Thanks for the contribution. Could you let us know why you closed the PR? Is there anything we could to to help?

**Comment by ultrox** [comment]
Hey :), 
Well, I'm not sure you would find it useful, and also I didn't make good comments, so didn't want to waste your time. I'll reopen it.

**Comment by waldyrious** [comment]
No problem :) for starters, please sign the CLA, and also reduce all the pages to the max of 8 (ideally less) examples. Currently the find.md and npm.md exceed the limit. Also, note that the git.md page is only for the plain git command -- there are dedicated pages for the subcommands, e.g. git-commit.md, so you can remove the subcommand examples from the git.md page (you may want to move the examples to the subcommands' pages).

**Comment by ultrox** [comment]
Better?

**Comment by agnivade** [comment]
Hey @ultrox - please take a look at @waldyrious' comments.

In particular -
> and also reduce all the pages to the max of 8 (ideally less) examples. Currently the find.md and npm.md exceed the limit.

and

> Also, note that the git.md page is only for the plain git command -- there are dedicated pages for the subcommands, e.g. git-commit.md, so you can remove the subcommand examples from the git.md page

**Comment by ultrox** [comment]
Oh, now I understand, you guys want max 8 example per document. Well, I personally find that not very helpful, I misunderstood instructions. 

I'll use my repo instead.

**Comment by waldyrious** [comment]
Yeah, we can see how getting rid of most of the examples you added would defeat the purpose for your needs. We're thankful that you took the time to submit a contribution regardless :)

**Pull request closed without merging**
