### PR TITLE
Pin down the dependencies to their exact version

### PR DESCRIPTION
**Pull request by agnivade**
- And keep tldr-lint on a greater than mode

As discussed in #1095

### CODE REVIEW

**Comment by waldyrious** [comment]
LGTM 👍 per previous discussion in #1095.

**Comment by zdroid** [comment]
Why write `=x.y.z` when it's [basically needless](https://docs.npmjs.com/files/package.json#dependencies)? `x.y.z` is enough to define you want an exact version. :wink:

Anyway, LGTM. :shipit:

**Comment by agnivade** [comment]
That's true actually. I hadn't read up properly on semver. Will send an update.

**Comment by agnivade** [comment]
LGTM

**Pull request merged**
