### PR TITLE
webstorm: add page

### PR DESCRIPTION
**Pull request by navarroaxel**
- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 2022.1

### CODE REVIEW

**Comment by navarroaxel** [comment]
All the JetBains IDEs are based on IntelliJ IDEA. Should we move this to `idea.md` and create alias pages?

**Review by CleanMachine1 — APPROVED** [review]

**Comment by CleanMachine1** [comment]
> All the JetBains IDEs are based on IntelliJ IDEA. Should we move this to `idea.md` and create alias pages?

I don't quite understand what you mean, move webstorm to a page called idea.md?

**Comment by navarroaxel** [comment]
> I don't quite understand what you mean, move webstorm to a page called idea.md?

@CleanMachine1 The JetBrains IDE's are based on IntelliJ IDEA, and all of them supports these examples. Perhaps we should use alias pages for `pycharm`, `rubymine`, etc.

**Review by einverne — APPROVED** [review]
Looks good.

**Pull request merged**
