### PR TITLE
swift: update documentation link

### PR DESCRIPTION
**Pull request by nelsonfigueroa**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

### CODE REVIEW

**Review by spageektti — CHANGES_REQUESTED** [review]
We are removing www from links, not adding (#13633).

**Comment by nelsonfigueroa** [comment]
My reasoning was that it's better to have the direct URL to documentation rather than a URL that redirects, as redirects may not be in place forever. I will leave it up to the maintainers though.

**Comment by spageektti** [comment]
> My reasoning was that it's better to have the direct URL to documentation rather than a URL that redirects, as redirects may not be in place forever. I will leave it up to the maintainers though.

I agree with you for other redirects, but I can't agree that it matters for this kind of redirect.

**Comment by nelsonfigueroa** [comment]
Fair enough, closing this.

**Pull request closed without merging**
