### PR TITLE
README: add JetBrains IDEs plugin

### PR DESCRIPTION
**Pull request by AlexPl292**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Review by navarroaxel — APPROVED** [review]

**Review by marchersimon — APPROVED** [review]
Amazing 😅

**Review by marchersimon — CHANGES_REQUESTED** [review]
Whoops, just saw that we keep this list in alphabetical order. @AlexPl292 please put this between `Java client` and `Keypirinha Plugin`.

**Comment by AlexPl292** [comment]
Didn't know that, thank you. Updated :)

**Review by marchersimon — APPROVED** [review]
Thanks @AlexPl292

**Pull request merged**
