### PR TITLE
Add Rust client to README.md

### PR DESCRIPTION
**Pull request by rilut**
I wrote a client in Rust and would love for it to be included in the Readme. Thanks :smile:

### CODE REVIEW

**Comment by igorshubovych** [comment]
While trying to compile with:
- Rust 1.5.0
- OSX El Capitan

```
Build failed, waiting for other jobs to finish...
failed to compile `tldr v0.1.2`, intermediate artifacts can be found at `/Users/igor/Projects/tldr-pages.github.io/target-install`

Caused by:
  failed to run custom build command for `openssl v0.7.4`
Process didn't exit successfully: `/Users/igor/Projects/tldr-pages.github.io/target-install/release/build/openssl-bade188098f75a08/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("x86_64-apple-darwin")
debug=false opt-level=3
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = Some("-Qunused-arguments")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-Qunused-arguments" "-m64" "-fPIC" "-o" "/Users/igor/Projects/tldr-pages.github.io/target-install/release/build/openssl-bade188098f75a08/out/src/c_helpers.o" "-c" "src/c_helpers.c"
ExitStatus(Code(1))


command did not execute successfully, got: exit code: 1



--- stderr
src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
thread '<main>' panicked at 'explicit panic', /Users/igor/.cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.21/src/lib.rs:772
```

**Comment by rilut** [comment]
I have no OSX. Can you help me verify whether this fixes the openssl issue on El Capitan?

    $ brew install openssl
    $ brew link --force openssl

If that works, I'll add those to my readme.

**Comment by igorshubovych** [comment]
It did not help.

This is what I have:
```
$ brew install openssl
Warning: openssl-1.0.2e already installed
```

And build fails while installing:
```
Compiling openssl v0.7.4
```

**Comment by rilut** [comment]
@igorshubovych force link didn't working? Ok, how about?

   export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include 
   export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include

Thanks.

**Comment by bahrunnur** [comment]
Hi @igorshubovych ,

You should try all the things in: https://github.com/sfackler/rust-openssl/issues/255

For me, the compile succeeded when I set this:
```
export C_INCLUDE_PATH=/usr/local/Cellar/openssl/1.0.2d_1/include/
```

**Comment by rilut** [comment]
@bahrunnur Cool! Is C_INCLUDE_PATH all you need?

No need for OPENSSL_INCLUDE_DIR or DEP_OPENSSL_INCLUDE?

**Comment by rilut** [comment]
The Readme is updated at https://github.com/rilut/rust-tldr/blob/master/README.md

**Comment by igorshubovych** [comment]
Thank you it works!

**Comment by rilut** [comment]
Thank you @igorshubovych and @bahrunnur! :+1:😹:+1:

**Pull request merged**
