### PR TITLE
add virtualenv page

### PR DESCRIPTION
**Pull request by sonph**
Examples include creating, sourcing and deactivating a virtual environment.

### CODE REVIEW

**Comment by ostera** [comment]
I wanted to make annotations on the diffs, but I feel it's better to address things at the PR level.

It feels you're writing this PR aimed at someone who knows what a `venv` is. Most people might, and likely will, not know. A slightly different approach could be better. Since virtualenv is mostly used within projects, why not refer to `venv` as `path/to/project` ? That makes much more sense for a first time reader and still gives an experienced virtualenv-er the knowledge they need without sacrificing too much terseness.

Just a thought, I've seen this pattern in a bunch of PR's and I think it should be addressed rather soon.

**Comment by waldyrious** [comment]
I agree with @ostera, the suggested change improves beginner-friendliness without sacrificing conciseness neither making it harder for experts.

**Comment by felixonmars** [comment]
I think `path/to/project` is a bit misleading, since he may not want to put the venv right inside his project (which introduces dirs like bin, include, lib). `path/to/venv` may be better :)

**Comment by sonph** [comment]
Personally I think `/path/to/env` works better.

> It feels you're writing this PR aimed at someone who knows what a `venv` is. Most people might, and likely will, not know.

Correct me if I'm wrong, but if someone looks for the `virtualenv` TLDR page then he/she should already know what a virtual env is and how it works, right?

**Comment by ostera** [comment]
@sonph if they did then good for them, but if you were starting out and I sent you a link to it you'll probably ask me what that `venv` is. Either way, as long as it's clear that it's a path it's fine by me.

**Comment by sonph** [comment]
Ok changed to `path/to/venv` to indicate that it's a path.

**Comment by ostera** [comment]
Thanks @sonph!

**Pull request merged**
