### PR TITLE
Ability to comment on PR failure

### LINKED ISSUE #1066: Post and update a Checklist with the errors to be fixed on each PR
As per https://github.com/tldr-pages/tldr/issues/980

While most people are happy with checking travis logs, it's a step less for us to just look for a message like the one below when a Travis build has failed, and make sure it's been all checked.

> Hi! We found some errors in your pages. Please attend to them soon so we can take a look at your page!
> - [ ] pages/linux/strace.md:21: TLDR005 Example descriptions should end in a colon
> - [ ] pages/linux/strace.md:21: TLDR006 Command name and description should be separated by an empty line

### PR DESCRIPTION
**Pull request by agnivade**
Closes #1066

### CODE REVIEW

**Comment by zdroid** [comment]
You can use `[ci skip]` tag in commit message if it isn't about testing functionality. :wink:

**Comment by agnivade** [comment]
@waldyrious / @sbrl - Please approve :smile:

**Comment by sbrl** [comment]
What does this do, @agnivade?

**Comment by agnivade** [comment]
This sets up travis to send the PR details to the tldr-bot on failure.

**Comment by agnivade** [comment]
@sbrl - I assume you do not have any objections to merging this.

**Comment by sbrl** [comment]
@agnivade Nope! I was just curious, that's all ;-)

**Pull request merged**
