### PR TITLE
Update rsync.md

### PR DESCRIPTION
**Pull request by quarcu**
Added rsync over SSH

### CODE REVIEW

**Comment by waldyrious** [comment]
I think each example should introduce only one or two new options. I believe the goal of tldr is not to provide quick copy-paste templates, but to expose newcomers to a friendly interface to gain intuition about how each command works, and forgetful experts to a quick reminder that similarly allows them to reason out and rebuild their mental model of the command's behavior.

More concretely, my point is: with only the -r option shown before, one's left to wonder which of the -a, -z or -e relate to the SSH, so that should be clarified or simplified. Also, the use of -r could be relinquished to simplify this example further, since the one above it demonstrates it already.

**Comment by rprieto** [comment]
Thanks for the PR! Agreed with @waldyrious, I don't really mind that the example has both `-e SSH` and `--progress` (it's pretty clear what they do), but the `-azr` could add to the confusion. Maybe we can leave these out?

Otherwise :+1:

**Comment by quarcu** [comment]
Well, I simply provided this example as it is commonly used to transfer via SSH. 
Probably the additional explanation for each might help but that might lengthen the list above the point of usefulness - your call guys, I will adapt.

**Comment by quarcu** [comment]
Ok gents, please review.

**Comment by waldyrious** [comment]
:+1: LGTM

**Comment by rubenvereecken** [comment]
The new page looks clean to me, I know for myself that I'll need it in the future. I do feel like we're missing out on the `az` bit now, since @quarcu said those options are commonly used.

I'll merge it as it is but if you ever feel inclined to document the other options, feel free to submit a new PR. Thanks for the work.

**Pull request merged**
