### PR TITLE
zip: make it more evident where the x comes from

### PR DESCRIPTION
**Pull request by waldyrious**
c.f. #782

### CODE REVIEW

**Comment by agnivade** [comment]
Can we add the labels for the other flags too ? Like 'recursive' for `-r` and change "Remove" to "Delete" for `-d`.

**Comment by waldyrious** [comment]
Yes, I thought about that. I'll work on this later today.

**Comment by waldyrious** [comment]
@agnivade PTAL

**Comment by agnivade** [comment]
perfect.

**Comment by waldyrious** [comment]
The travis failure is because of the []. We need to edit the linter to allow this.

**Pull request merged**
