### PR TITLE
pkill: add page

### PR DESCRIPTION
**Pull request by kmoe**
There is already an example of `pkill` on the `pgrep` page but I assume we want users to be able to look things up directly wherever possible. For that reason I have created a standalone page for `pkill` with an additional example.

### CODE REVIEW

**Comment by igorshubovych** [comment]
And there should not be `pkill` example in `pgrep` page

**Comment by waldyrious** [comment]
:+1: for `pkill -9 {{process_name}}`

**Comment by kmoe** [comment]
Amended. I can remove the `pkill` example from `pgrep` in this PR as well if you like, or open another one?

**Comment by igorshubovych** [comment]
No, I guess, this is good to go now. Thanks! LGTM.

Please open new one on `pgrep`

**Comment by waldyrious** [comment]
LGTM as well, thanks for the contribution!

**Pull request merged**
