### PR TITLE
uname -a

### PR DESCRIPTION
**Pull request by igorshubovych**

### CODE REVIEW

**Comment by waldyrious** [comment]
Just to be sure, have you seen the discussion in #285?

**Comment by igorshubovych** [comment]
Interesting discussion. No, I haven't seen it earlier.

I still think we should include `-a`. My friend who works as a system administrator and I always use just `uname -a`. This example is the only one mentioned on [Wikipedia page](https://en.wikipedia.org/wiki/Uname) and many other pages about `uname`, just google for them. I think it is the most common use of `uname`.

**Comment by waldyrious** [comment]
Fair enough, I do agree that the `-a` is more memorable. @rprieto, care to comment?

**Comment by felixonmars** [comment]
I would +1 to include `-a`, too.

**Pull request merged**
