### PR TITLE
envoy: add page

### PR DESCRIPTION
**Pull request by pxgamer**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by pxgamer** [comment]
@agnivade, ah. I hadn't heard of that before. Naming projects is so crowded these days. _sigh_

**Comment by Aracki** [comment]
I agree with @agnivade, but what do we do in such cases?

**Comment by agnivade** [comment]
We likely need to come up with a modified pages architecture and an index format which can handle this. I don't know what exactly that should be. Needs some thought.

**Comment by mebeim** [comment]
@sbrl well, there still isn't... but I would argue that creating a "disambiguation" page would be the most simple option. Anyway we'll see what to do when this happens.

**Comment by sbrl** [comment]
Ah, that's a good idea - I hadn't even thought of that! Maybe something like this?

```markdown
# envoy

> Disambiguation page.

- Show information about envoy, the PHP command:

`tldr envoy_php`

- Show information about envoy, the proxy:

`tldr enoy_proxy`
```

**Comment by mebeim** [comment]
@sbrl yep, exactly what I was thinking about :slightly_smiling_face:

**Comment by agnivade** [comment]
PR looks good. Merging.

**Comment by Aracki** [comment]
Thats a good practice for such cases @sbrl thanks 👍

**Pull request merged**
