### PR TITLE
contribute two trick about git

### PR DESCRIPTION
**Pull request by charlestang**
contribute two trick about git,
git-pull with --rebase is a good habit
git-clone with --depth will save your time

### CODE REVIEW

**Comment by igorshubovych** [comment]
I do not like rebase example. It is not for for novice. Honestly, it is rather a trick, not a common use. It breaks rule 2 of [Contributing Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md): When in doubt, keep new command-line users in mind.

However I like "git clone --depth" example. I think it is quite a common and useful case.

Also can you please:
* fixup 7169c16 commit by rebasing
* remove index file from it, there is no need to do it

**Comment by rprieto** [comment]
That's interesting: I was about to say the opposite. I use rebase on a daily basis to keep branches clean, but not once have I ever used "--depth". Maybe let's leave this open for other comments?

**Comment by igorshubovych** [comment]
Ok. We may leave both.

FYI, I used git clone --depth in tldr's build.sh:
https://github.com/tldr-pages/tldr/blob/master/scripts/build.sh

**Comment by charlestang** [comment]
@igorshubovych Thank you for reviewing my code. I've removed the index file from my commits.

Actually, it's hard for people to decide when to use rebase, 'pull' may be a mostly right scenario, but still sometimes dangerous(e.g. like after some local branches merge operations).

If you don't approve --rebase argument when git-pull, I'm OK with that.

**Comment by igorshubovych** [comment]
@charlestang 

Now, after @rprieto explanation I think you might be right. It is just in my practice I rarely use it. So I am good to have --rebase merged.

**Comment by igorshubovych** [comment]
Thank you for contribution! Keep up the good work!

**Pull request merged**
