### PR TITLE
Fix another much needed command for imagemagick.

### PR DESCRIPTION
**Pull request by 85pando**
I think the resize to pixels command is also important.

### CODE REVIEW

**Comment by igorshubovych** [comment]
I tried to rephrase it a little bit to make it short and to move the key information (aspect ration) go first:

~~~Markdown
- Scale an image keeping the original aspect ratio to a maximum dimension of 640x480

+`convert {{image.png}} -resize 640x480 {{image2.png}}`
~~~

What do you think?

**Comment by 85pando** [comment]
As long as the command gets in, I am fine with improvements. 👍

**Comment by igorshubovych** [comment]
Is my description correct? (Remember, i do not use it, so i am not sure if i right or not)

**Comment by 85pando** [comment]
Yep, totally cool!

**Comment by igorshubovych** [comment]
Could you then fix your commit and I will merge it?

**Comment by 85pando** [comment]
done

**Comment by igorshubovych** [comment]
@85pando 

there is a little mess with commits. could you please fix it? we should have a single commit in PR. let me know if you have issues with it, in this case I will try to manually merge it.

**Comment by 85pando** [comment]
You mean like so?

**Comment by igorshubovych** [comment]
Should be single commit:
http://take.ms/2JXZG

**Comment by 85pando** [comment]
I think I messed something up with my repo, but I think it should be as requested now ☺

**Comment by igorshubovych** [comment]
Thank you.
LGTM!

**Pull request merged**
