### PR TITLE
brew cask: add page

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
`brew cask` is for binary packages, while `brew` normally builds packages from source (the Homebrew project prefers the latter whenever possible)

**Comment by agnivade** [comment]
Oh, so its like `pip install` and `apt-get install`

**Comment by waldyrious** [comment]
yes :)

**Comment by agnivade** [comment]
@waldyrious - Anything blocking this from merging ?

**Comment by waldyrious** [comment]
Nope, I was just waiting to see if another maintainer would do it (so that one of the two approvals wouldn't have to be the author's), but since there's been no objections for over a week, I guess we can just go ahead and merge.

**Pull request merged**
