### PR TITLE
create ffmpeg.md add-pages

### PR DESCRIPTION
**Pull request by sarav-egnaroinc**
created page for ffmpeg

----

- [x] The page (if new), does not already exist in the repo.

- [x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x] The page has 8 or fewer examples.

- [x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by pxgamer** [comment]
@sarav-egnaroinc, it looks like this is already in `common`.
Is the Linux version different to the other version?
https://github.com/tldr-pages/tldr/blob/master/pages/common/ffmpeg.md

**Comment by agnivade** [comment]
I believe ffmpeg is same in all platforms.

**Comment by pxgamer** [comment]
I thought so @agnivade 👍

**Comment by sarav-egnaroinc** [comment]
Yes, Sorry I didn't check. I will remove the request.

**Pull request closed without merging**
