### PR TITLE
lvs: add

### PR DESCRIPTION
**Pull request by sahilister**
- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey there, @sahilister! You can always push to the same branch you've opened this PR on to update the PR - no need to open a new PR for every edit you make to it :-)

Is there anything else we can help with? If so, please do let us know :-)

**Comment by sahilister** [comment]
Thanks for reaching out @sbrl , really appreciate it!

I saw #4188 not passing the CI check. I felt maybe that's because of GitHub GUI's 2 spaced default indent and this [mentioning](https://github.com/tldr-pages/tldr/blob/master/.markdownlintrc) 4 as default lint (had a somewhat similar issue with my first #4156)

Thought i could help so was checking before commenting (it wasn't due to indent).

**Comment by sahilister** [comment]
and I'll soon make the PR for `lvs` command soon.

**Comment by sbrl** [comment]
Ah, I see! Thanks for clarifying - I look forward to that PR  :-)

If there's anything else in  the mean time we can help with, don't hesitate to let us know.

**Pull request closed without merging**
