### PR TITLE
git-rename-tag: add page #6092

### PR DESCRIPTION
**Pull request by CleanMachine1**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable). 

For #5137 

See #5950 for what I based this on

### CODE REVIEW

**Comment by CleanMachine1** [comment]
If no commits/changes are made can this be rebased since it is only 1 commit?

**Review by marchersimon — APPROVED** [review]
Looks good. Why do you want it to be rebased. As far as I know it doesn't make any difference if there is only one commit.

**Comment by CleanMachine1** [comment]
Yes but this is acceptable to rebase

**Comment by bl-ue** [comment]
It's perfectly fine for it to be rebased; however, since it's not necessary and we normally squash I'd prefer to squash.  The added benefit (which is my primary motive) is that squashing causes the PR number to be in the commit message, which is very helpful for navigating. Rebasing causes the commit to go directly to the `main` branch unmodified (except that the the merger is attributed as "committer").

**Review by bl-ue — APPROVED** [review]

**Comment by CleanMachine1** [comment]
Only because this is one commit.

I'll leave the PR in the title

**Comment by bl-ue** [comment]
No problem — it doesn't matter that much.

**Pull request merged**
