### PR TITLE
ssh-copy-id: add page

### PR DESCRIPTION
**Pull request by forsigner**
Add ssh-copy-id support.

### CODE REVIEW

**Comment by igorshubovych** [comment]
https://github.com/tldr-pages/tldr/blob/master/pages/linux/ssh-copy-id.md

**Comment by forsigner** [comment]
But there is no Mac support

**Comment by igorshubovych** [comment]
Because it is not available on OSX.
You can install it on OSX though in brew.

**Comment by waldyrious** [comment]
@forsigner feel free to improve the linux page with the parts of your proposal that you feel are better, though :)

**Comment by forsigner** [comment]
@waldyrious  the page of ssh-copy-id.md in linux is nice,  but I think it should be moved from linux to common.

**Comment by ostera** [comment]
This is a duplicate! It's about the same as the linux one. Closing.

**Pull request closed without merging**
