### PR TITLE
julia: switch example from parallel to threaded

### PR DESCRIPTION
**Pull request by sjkelly**
Switch example startup from parallel mode (-p) to multithreaded mode (-t) to align with the latest practices, which should lead to better performance.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):** all

### CODE REVIEW

**Comment by fazlearefin** [comment]
@sjkelly Welcome to the TLDR project and thank you for your contribution! Please accept the license/cla.

Could you please provide official links for the latest practice of favoring multi-threaded mode over parallel?

**Comment by sjkelly** [comment]
> Could you please provide official links for the latest practice of favoring multi-threaded mode over parallel?

When this page was written, parallel would have still likely been the most common way to run Julia in the wild (starting N seperate julia runtime processed). Since v1.3 in 2019, more efficient mulithreading on a single julia process was introduced behind the `-t` flag. 
https://julialang.org/blog/2019/07/multithreading/

**Review by kbdharun — APPROVED** [review]
LGTM, Welcome to tldr and thanks for your contribution.

**Review by gutjuri — APPROVED** [review]
Thanks!

**Review by CleanMachine1 — APPROVED** [review]

**Pull request merged**
