### PR TITLE
toilet: edit page

### PR DESCRIPTION
**Pull request by nath1as**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by pxgamer** [comment]
Is this not the same as #3364? :thinking_face:

**Comment by nath1as** [comment]
> ~Is this not the same as #3364~? thinking
> 
> No worries. Got confused. +1

my bad, forgot to change the pr title

**Comment by mebeim** [comment]
@pxgamer something going on with the automated checks. I think you can use your super powers to merge this.

**Comment by pxgamer** [comment]
Yeah, I had to merge master back into the PR branch as it had a conflict. 👍 All good now.

**Pull request merged**
