### PR TITLE
translation-templates/*: add Bengali translation

### PR DESCRIPTION
**Pull request by HVbajoria**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Comment by HVbajoria** [comment]
Hello @kbdharun,
As mentioned in the previous pull request I have made the changes. 
Could you please also add hacktoberfest-accepted label for this contribution? 
Thank you

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by Magrid0 — APPROVED** [review]
Looks good to me, thanks for your contribution!

**Comment by HVbajoria** [comment]
Hello @kbdharun,
By the way I would like to be part of your organisation. Could you help me with the steps?
Thank you

**Comment by kbdharun** [comment]
> Hello @kbdharun, By the way I would like to be part of your organisation. Could you help me with the steps? Thank you

Thanks for expressing your interest in joining the organization @HVbajoria. We strive to have new contributors and maintainers for tldr. I would suggest you check out the [Community roles file](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) to get to know about the process and the various tiers.

As you might have observed we don't have a native speaker reviewing Bengali PRs so it would be indeed nice to have one (as Bengali translations/pages have been lagging a bit when compared to other languages [some are outdated, but most of the times many pages aren't translated at all]).

I would suggest you keep creating PRs (even after reaching the minimum threshold specified in the file), I will create an issue to formally add you as a collaborator (maintainer) to this repo (next month), if the conditions are satisfied.

**Pull request merged**
