### PR TITLE
ip-link: add page

### PR DESCRIPTION
**Pull request by aherst**
- [x ] The page (if new), does not already exist in the repo.
- [x ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Hey there! Any reason you closed this PR? We'd love to help if you've having issues.

**Comment by aherst** [comment]
I screwed up my repository. I couldn't find any way to delete the pull request and given my limited git knowledge it was easier for me to re-fork and do the pull request again. Any advice as to how to do this better in the future is always appreciated.

**Comment by navarroaxel** [comment]
@aherst depens how you have the remotes configured in your working directory, is your fork the `origin`?, but you should remove your branch locally and push force a new one.
```
# copy your page in another dir, you could use `git cherry-pick instead`
git checkout main # you should sync your local branch main with the tldr-pages/main.
git fetch upstream main # fetch new commits from upstream
# if you have diverged you need to use
git reset HEAD~100 --hard # before the sync operation (merge --ff).
git merge --ff upstream/main # update your local branch with news from tldr-pages/main.
git push <your_remote> main
git branch -D ip-link
git checkout -b ip-link # create a new branch from a clean main
git cherry-pick 66b9308 # the branch is deleted but the commit is still in the Git DB.
git push <your_remote> ip-link --set-upstream --force # replace the branch with this new one in the fork.
```

:grimacing:

**Comment by aherst** [comment]
Thanks @navarroaxel! I'll have to spend some time thinking about you suggestions to figure out what's going on.

With regard to this pull requrest, I ended up creating a new pull request for the submission. Unless I've made a mess of things and need to do some cleanup, I'm happy to forget about this pull request and move on to my next page.

**Comment by sbrl** [comment]
No worries! Yeah, we can absolutely forget about this PR. I was just wondering if you needed any help :-)

To update a PR you can always push additional commits to the branch you've opened the PR with.

**Pull request closed without merging**
