### PR TITLE
autofsd, biomesyncd, biometrickitd, cloudd, coredatad, ctkd, deleted, InternetSharing, dhcp6d, hidd, systemsoundserverd, wps, webinspectord, watchdogd, watchlistd, symptomsd: add page

### PR DESCRIPTION
**Pull request by pixelcmtd**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage, if possible.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the commands being documented (if known):** macOS 13 Beta

### CODE REVIEW

**Comment by kbdharun** [comment]
Wow, This is a huge PR. I will review it after a couple of hours.

**Review by blueskyson — APPROVED** [review]
LGTM

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by kbdharun** [comment]
I have a doubt regarding the man pages. Is the current links fine or is there this commands present in manned?

> From what I remember Mac commands weren't present in manned.

**Comment by blueskyson** [comment]
@kbdharun Yes, it's fine. Many osx commands don't appear on manned.org so some pages use manpagez.com or ss64.com.

**Comment by kbdharun** [comment]
> @kbdharun Yes, it's fine. Many osx commands don't appear on manned.org so some pages use manpagez.com or ss64.com.

Noted thanks

**Comment by pixelcmtd** [comment]
@kbdharun I'm not sure if I understand all of your questions correctly, but I'll try to answer: One big problem with manned is that, AFAIK, it doesn't include any macOS man pages. So we use other sites like ss64 and manpagez, which have horribly outdated, but usable macOS pages. For `biomesyncd` and `coredatad`, the first thing I found was an active project from @keith (huge probs man), so I just included that. For `systemsoundserverd` I found nothing online.

Online man pages, especially for macOS, are annoying enough that I already had the idea of suggesting we make our own site a few months ago. Even if don't do this (too much hassle, not enough infrastructure, …), we should at least make a decision on which man page viewers to use for `osx` pages.

**Comment by kbdharun** [comment]
> @kbdharun I'm not sure if I understand all of your questions correctly, but I'll try to answer: One big problem with manned is that, AFAIK, it doesn't include any macOS man pages. So we use other sites like ss64 and manpagez, which have horribly outdated, but usable macOS pages. For `biomesyncd` and `coredatad`, the first thing I found was an active project from @keith (huge probs man), so I just included that. For `systemsoundserverd` I found nothing online.
> 
> Online man pages, especially for macOS, are annoying enough that I already had the idea of suggesting we make our own site a few months ago. Even if don't do this (too much hassle, not enough infrastructure, …), we should at least make a decision on which man page viewers to use for `osx` pages.

Agreed, Thanks for the insightful reply.

**Pull request merged**
