### PR TITLE
ufw: use manned as more information link

### PR DESCRIPTION
**Pull request by navarroaxel**
- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Related discussion: https://github.com/tldr-pages/tldr/pull/6170#discussion_r658667001

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]

**Comment by CleanMachine1** [comment]
Why?

the ubuntu page is way better than a man page. It provides examples, modification and what it does feature-wise.

Manned is for last resorts when there is nothing else, correct?

**Comment by CleanMachine1** [comment]
https://github.com/tldr-pages/tldr/pull/6170#discussion_r658709669

Nevermind, I see its use. I hadn't looked at the other PR.

I can't tell which is better however I am willing to have either

**Comment by navarroaxel** [comment]
I believe that a link to a wiki page is better than the same `man page` that the user has in the CLI, but this was the decision that we made in #5510 :man_shrugging:

**Review by CleanMachine1 — APPROVED** [review]

**Comment by sbrl** [comment]
Yeah, generally we only go for a man page if there's nothing else that's appropriate, though it's really a case-by-case thing.

**Comment by sbrl** [comment]
Believe it or not, UFW is actually Ubuntu-specific as best I can tell - at least it started that way. To that end, the Ubuntu wiki page is more informative here.

**Comment by CleanMachine1** [comment]
UFW was made for ubuntu to my knowledge however seems to adopted from uncomplicated nature.

**Comment by marchersimon** [comment]
> @CleanMachine1 I believe that a link to a wiki page is better than the same `man page` that the user has in the CLI, but this was the decision that we made in #5510 man_shrugging

@navarroaxel as far as I can remember we only made a decision for which man page side we should use as default. We always preferred Wikis or Homepages over man pages.

**Pull request closed without merging**
