### PR TITLE
afl-fuzz

### PR DESCRIPTION
**Pull request by d33tah**
In this example I show how to prepare a fuzzable binary and fuzz it.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
While this file has certainly taught me something interesting I wouldn't otherwise know, it doesn't really adhere to the tldr spirit. I see how it shows a whole `afl-fuzz` workflow, but this isn't really what tldr aims to achieve. Rather, tldr is there as a really quick reference because you can't remember exactly how to invoke a tool. In that respect, the third example is what we're looking for, the fourth is irrelevant and the first two near a border case because they're really part of how `afl-fuzz` works. Still, they bloat the file while people might just be looking for a quick way to fire up `afl-fuzz`.

I know it feels bare, but I suggest you keep this file limited to only `afl-fuzz` commands. Even then, aim at the tldr structure of using something like

`AFL_EXIT_WHEN_DONE=1 afl-fuzz -i {{input_files}} -o {{output_directory}} -- {{executable}}`
instead of
`AFL_EXIT_WHEN_DONE=1 afl-fuzz -i input_cases -o output_directory -- ./hello`

We're currently working to refine guidelines on how to name those 'variables', but that's a start.

**Comment by d33tah** [comment]
@rubenvereecken: I removed the final example and added parameters. Is it passable now?

**Comment by waldyrious** [comment]
While I love the concept of afl-fuzz, I'm really torn on this one, in that the examples aren't really independent, but the whole page is a sequential manual for preparing an input for afl-fuzz and then actually run it.

I am not sure how we can address that. Could these two minimal examples perhaps be added to the [README](http://lcamtuf.coredump.cx/afl/README.txt), the [Quick start guide](http://lcamtuf.coredump.cx/afl/QuickStartGuide.txt) or even the [Wikipedia page for the tool](https://en.wikipedia.org/wiki/American_fuzzy_lop_(fuzzer)) (although the latter option [may be questionable](https://en.wikipedia.org/wiki/WP:NOTHOWTO)), and then linked to from this page?

**Comment by d33tah** [comment]
@waldyrious reference: https://groups.google.com/d/msg/afl-users/YrZk5ri4nnA/H0FIJBM6BwAJ

**Comment by waldyrious** [comment]
Yeah, that's definitely something that should be provided in the quick start guide IMO :) but for tldr it kinda deviates from the goal / format (collections of independent usage examples of the command in question, not a getting started guide). Do you know if the project is receptive to contributions in this form (i.e. adding this info to the gettign started guide)?

**Comment by rubenvereecken** [comment]
Closing for now, sorry lads.

**Pull request closed without merging**
