### PR TITLE
multiple pages: normalize "more information" labels

### PR DESCRIPTION
**Pull request by bl-ue**
This PR normalizes the "more information" labels in the all translations of all pages.

I picked each label based on the most common one in the `pages.*` folder. Usually there are 1% or 2% are strange labels and 95%+ are the same, e.g. for German:
```
Mehr Information:                = 2
Mehr Informationen:              = 59
Mehr informationen:              = 2
Weitere Informationen zu Cradle: = 1
Weitere Informationen:           = 21
Weitere informationen:           = 1
```

Labels decided on:

- German (`de`): `Mehr Informationen:`

### CODE REVIEW

**Comment by bl-ue** [comment]
@waldyrious @mebeim looks good so far?

**Review by mebeim — APPROVED** [review]
@bl-ue I don't speak German, but it seems reasonable to convert everything to the most common phrasing 👍

**Review by schneiderl — APPROVED** [review]

**Review by owenvoke — APPROVED** [review]
Whoa! That's a lot of pages. Brilliant work @bl-ue.

Let's make sure to rebase this when merging to keep the commit history. 👍🏻

**Review by schneiderl — APPROVED** [review]

**Comment by bl-ue** [comment]
@schneiderl this was supposed to be rebased...

(@owenvoke wrote:)
>Whoa! That's a lot of pages. Brilliant work @bl-ue.
>
>Let's make sure to rebase this when merging to keep the commit history. 👍🏻

**Comment by bl-ue** [comment]
But it doesn't really matter. Only 11 commits :)

**Comment by sbrl** [comment]
Those commit messages look fine to be rebased and not squashed, @bl-ue :-)

**Comment by waldyrious** [comment]
@sbrl that's precisely what he's saying :) @owenvoke had proposed to do a rebase merge, but when @schneiderl merged the PR, he used a squash merge instead.

**Comment by schneiderl** [comment]
I'm sorry about that 🦖

**Comment by bl-ue** [comment]
No worries @schneiderl! :D

**Pull request merged**
