### PR TITLE
style-guides, common-arguments: remove trailing spaces

### PR DESCRIPTION
**Pull request by adamatan**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Removed trailing spaces from some internal documentation files. A matter of style, does not affect any command.

### CODE REVIEW

**Review by mfrw — APPROVED** [review]
Thank you for your contribution @adamatan.
LGTM

**Comment by adamatan** [comment]
My pleasure!

**Review by marchersimon — CHANGES_REQUESTED** [review]
@adamatan those spaces are there on purpose. Markdown uses two trailing spaces for a newline. (I know it's ugly, but that's just the way it is.)

**Comment by adamatan** [comment]
Oh my. Thanks.

**Comment by marchersimon** [comment]
Anyways, thanks for the effort.

**Pull request closed without merging**
