### PR TITLE
less: show line numbers

### PR DESCRIPTION
**Pull request by OranShuster**
----

- [X] The page has 8 or fewer examples.

- [X] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited.

- [X] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines.

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @OranShuster, thanks for the contribution.

Unfortunately, we have a hard limit of 8 for the no. of examples that we allow in a page. This was written explicitly in the PR template. Not sure why you have ticked the box even when the limit was exceeded. The reason is to challenge ourselves to provide the most useful set of examples in a short space. For a complete documentation, there is always the man page.

The existing options are pretty much useful as is. I don't see anything that warrants to be removed.

**Comment by OranShuster** [comment]
@agnivade I actually counted and i got 8 examples (including my own). i might need to recheck my counting skills

**Comment by agnivade** [comment]
Hey @OranShuster - sorry if I came off as rude. That was not my intention. I just wanted to point out that we have a hard limit of 8 which we do not cross.

Regarding your PR, these are the examples you have - 

`less {{source_file}}`
`less --LINE-NUMBERS {{source_file}}`
`<Space> (down), b (up)`
`G (end), g (start)`
`/{{something}}`
`?{{something}}`
`F`
`v`
`q`

Which comes to 9.

**Comment by OranShuster** [comment]
Didn't think you were rude at all, it's all good!

**Pull request closed without merging**
