### PR TITLE
tldr: changed -u to --update

### PR DESCRIPTION
**Pull request by feliscatusmeows**
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by CleanMachine1** [comment]
I'm pretty sure the haskell client version in the apt repo doesn't have --update and rather only -u

**Comment by CleanMachine1** [comment]
Its the other way round. I approve.

**Review by CleanMachine1 — APPROVED** [review]

**Review by mfrw — APPROVED** [review]

**Review by navarroaxel — CHANGES_REQUESTED** [review]
If we read the https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#arguments it says:

> Clients MAY choose to only implement the short version of an option, ignoring the long form

We can find this https://github.com/tldr-pages/tldr/pull/5965/files#r632621019

**Comment by CleanMachine1** [comment]
How did I sign it

**Comment by marchersimon** [comment]
@feliscatusmeows thanks for your help, but unfortunately, as @ navarroaxel pointed out, we can't change the options here.

**Pull request closed without merging**
