### PR TITLE
pages.pt*: fix verb tenses

### PR DESCRIPTION
**Pull request by vitorhcl**
- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Eu busquei e substitui vários verbos pelo regex "^- [A-Za-z]+r". Ainda existem vários verbos ainda no infinitivo, a maioria no português brasileiro.

### CODE REVIEW

**Comment by gutjuri** [comment]
Wow, that's a lot of changes :O Was this some sort of automatic change? Or did you review each one manually?

**Comment by kbdharun** [comment]
> I searched and replaced several verbs with the regex "^- [A-Za-z]+r". There are still several verbs still in the infinitive, most of them in Brazilian Portuguese.

@gutjuri It indeed seems to be an automated change by replacing it using regex. We recently added this rule to the style guide under Portuguese Portuguese-specific rules section. So we need to carefully go through the changes. Also, we must wait for @isaacvicente's suggestions too.

We can ignore the outdated pages in this PR for now (and update it later) as this PR is already big enough.

**Comment by vitorhcl** [comment]
Yeah, it was an automated change, it indeed needs a careful revision.

**Comment by isaacvicente** [comment]
I'm figuring out a way to review +600 files LOL. In my research, the Github CLI seems great, but it only shows the diff. I wish something like `vimdiff` to compare the two files and change something, so that I can make my review.
At a glance I saw that the first verb of the files are correct, but sometimes there are more verbs to the sentence, and these verbs need to be changed as well.

Do you guys know how accomplish this? @vitorhcl @kbdharun @sebastiaanspeck

**Comment by kbdharun** [comment]
> I'm figuring out a way to review +600 files LOL. In my research, the Github CLI seems great, but it only shows the diff. I wish something like `vimdiff` to compare the two files and change something, so that I can make my review.
> At a glance I saw that the first verb of the files are correct, but sometimes there are more verbs in the sentence, and these verbs need to be changed as well.
> 
> Do you guys know how to accomplish this?

VSCode with the official GitHub pull requests extension is useful for these cases. I use it in large PRs to mark/unmark pages as reviewed so that I can keep a track of them efficiently.

**Comment by isaacvicente** [comment]
> > I'm figuring out a way to review +600 files LOL. In my research, the Github CLI seems great, but it only shows the diff. I wish something like `vimdiff` to compare the two files and change something, so that I can make my review.
> > At a glance I saw that the first verb of the files are correct, but sometimes there are more verbs in the sentence, and these verbs need to be changed as well.
> > Do you guys know how to accomplish this?
> 
> VSCode with the official GitHub pull requests extension is useful for these cases. I use it in large PRs to mark/unmark pages as reviewed so that I can keep a track of them efficiently. It also supports adding review suggestions locally and making a review.

Thanks! I ended up using `vim` for that. I cloned Vitor's fork and checkout to the PR branch. I configured `git` to use `vimdiff` instead of the default diff tool. I'm gonna check out the "VSCode" way (maybe will be easier).

**Comment by isaacvicente** [comment]
As this review will take me some time to do, I will do it later. I'm a bit busy these days. I think in the weekend I'll have time to carefully review everything.

**Comment by vitorhcl** [comment]
I fixed the verb tenses of all verbs in command descriptions, including the ones in the middle of the sentences :tada:

Now we gonna have to review the changes :sweat_smile:

**Review by gutjuri — APPROVED** [review]

**Review by kbdharun — APPROVED** [review]

**Review by isaacvicente — APPROVED** [review]
Olá, @vitorhcl! Modifiquei apenas alguns arquivos.
Um imenso obrigado pela sua contribuição :)
Irá fazer uma grande diferença a ajudará a manter uma boa consistência. :tada: :partying_face: 

Na próxima vez, só modifica os arquivos em `linux`, `common`, `osx`, etc, beleza?
Assim podemos organizar melhor o workflow (além de dar menos trabalho pra quem faz o review :sweat_smile:)

LGTM :rocket:

**Pull request merged**
