### PR TITLE
Page astyle

### PR DESCRIPTION
**Pull request by lamar-frankie**
----

- [ x] The page (if new), does not already exist in the repo.

- [ x] The page (if new), has been added to the correct platform folder:  
      `common/` if it's common to all platforms, `linux/` if it's Linux-specific, and so on.

- [x ] The page has 8 or fewer examples.

- [ x] The PR is appropriately titled:  
      `<command name>: add page` for new pages, or `<command name>: <description of changes>` for pages being edited

- [ x] The page follows the [contributing](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) guidelines 

Close page request: astyle #1218

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @lamar-frankie , looks like you had some git issues. Let me know if you need some help. :smiley:

**Comment by lamar-frankie** [comment]
I had two commit messages that we're not formatted correctly. So, I did a squash and merged them with a commit that was properly formatted. However my build is still failing. Travis says is giving me an error saying thw build is failing because the description does not end in a period, but my description does end in a period.

**Comment by lamar-frankie** [comment]
Any help would be useful. Thank you.

**Comment by agnivade** [comment]
> Travis says is giving me an error saying thw build is failing because the description does not end in a period, but my description does end in a period.

It's a common issue. Your description ends with a trailing space, not a period. I would recommend setting your editor to trim all trailing whitespace on save.

**Pull request closed without merging**
