### PR TITLE
Started tldr for emacs

### PR DESCRIPTION
**Pull request by shybovycha**

### CODE REVIEW

**Comment by ostera** [comment]
:+1: for a start. Would be nice to see some more commands!

**Comment by shybovycha** [comment]
As with VIM, more cool things are behind keyboard shortcuts and in-app commands :simple_smile:

**Comment by waldyrious** [comment]
Note that there's already #474 so we should probably coordinate both PRs. /cc @sethwoodworth

**Comment by sethwoodworth** [comment]
@shybovycha I like your description better, so I rebased my PR on this one.

**Pull request merged**
