### PR TITLE
equery: add page

### PR DESCRIPTION
**Pull request by fuerbringer**
Messed up the last PR :cry: Anyways, this one has better and more consistent descriptions.

### CODE REVIEW

**Comment by waldyrious** [comment]
Looks great! Just one question: what are overlays?

**Comment by fuerbringer** [comment]
Gentoo overlays are additional repositories and packages not directly provided by the Gentoo developers. Once a package from an overlay is installed, it appears as an installed package just like any other applications from the main portage tree. It's somewhat comparable to the Arch User Repository (AUR).

**Comment by waldyrious** [comment]
Ah, understood. Would it be clearer to say "Search for installed packages in the Portage tree and in overlays", then? If so, I'll merge and make the change directly, to save you the trouble :)

**Comment by waldyrious** [comment]
Thanks :+1:

**Pull request merged**
