### PR TITLE
style guide: update wording of the page link

### PR DESCRIPTION
**Pull request by pxgamer**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by pxgamer** [comment]
I think that's what we ended up with. Correct me if I'm wrong though...

**Comment by mebeim** [comment]
@pxgamer I'm not that much up to date about the topic, but I remember seeing the majority of people agree on `More information`, so I think it's ok (?)

**Comment by schneiderl** [comment]
I think that ```More Information``` is the best option in this case. 

Let's just wait for others.

**Comment by mebeim** [comment]
While I agree that other words might be more suitable to more precisely describe the linked resource, there's two reasons why I'd say `More information` is the way to go:

1. It's generic, so we don't have to define which link corresponds to which keyword. It is not that simple to draw the line between terms like `Documentation`, `Reference`, `Manual`, and so on. It can get confusing both for the users and the contributors.
2. It's still as easy to understand as any other keyword, and gets the job done without needing to think much about it: "you want more information? Then go here <link>". We don't really need to precisely describe each link.

**Comment by sbrl** [comment]
@mebeim Very true. Here I think it's very much my high-functioning Autism speaking: "but it needs to be _precise_!". Let's go ahead with this change.

**Pull request merged**
