### PR TITLE
mas: add page

### PR DESCRIPTION
**Pull request by Aracki**
I have added [mas](https://github.com/mas-cli/mas) - a CLI tool for the Mac App Store.

### CODE REVIEW

**Comment by pxgamer** [comment]
Hmm. Looks like this is the same command as [`brew-mas`](https://github.com/tldr-pages/tldr/blob/bbd3c4cbca2dd3fc9c2e09cd6fbf1912b41e1f6a/pages/osx/brew-mas.md) but I guess the page name is incorrect.

Wondering if we should keep this and remove the other, or rename the other and close this. 🤔

**Comment by andrik** [comment]
I think the description made by @Aracki is unbiased

Maybe editing the existing page by adding new examples and updating the description would be better.

What do you think @Aracki ?

**Comment by Aracki** [comment]
1. I think the title should be `mas` instead of `brew-mas`. 
2. The title description is better without adjectives like 'simple'.
3. `mas install app_name app_identifier` example is incorrect. `install` command is taking only one integer argument which is app ID(s) to install or how they call it `product_identifier`.

**Comment by sbrl** [comment]
Yeah, I like yours better @Aracki.

Pages should always bear the name of the command executed. Does `brew-mas` work in the terminal? If so, then it can probably stay.

If not, then it needs renaming & editing I think

**Comment by Aracki** [comment]
@sbrl `brew-mas` doesn't work. Maybe it's and old alias for that specific tool.

**Comment by Aracki** [comment]
This is moved here #3032

**Pull request closed without merging**
