### PR TITLE
Enhancements to the PDF script.

### PR DESCRIPTION
**Pull request by SuperSonicHub1**
Some simple changes to the PDF script to make the code a bit nicer to read and the CLI a bit nicer to use.
### `.gitignore`
* Ignore `.vscode` and my virtual environment which I used to test my changes.
### `scripts/pdf/render.py`
* Converted the top comment to a multi-line string.
* Replaced `i` with `enumerate`.
* Gave the `ArgumentParser` a name and description.
* Added `basic` as a color choice and made it the default.
* Added `color` as a long flag.
* Removed no longer used variables and `if` statement.
### `scripts/pdf/README.md`
* Updated command line usage to:
  * Reflect changes made to the CLI.
  * Demonstrate recommended use of pip.
* Made some grammar changes.
* Added more useful alt text to the images.

### CODE REVIEW

**Review by sbrl — COMMENTED** [review]
Thanks, @SuperSonicHub1! We've already got #4993 open against the PDF script though, so once that's merged would it be possible for you to rebase this PR to merge in the changes at all?

**Comment by SuperSonicHub1** [comment]
> Thanks, @SuperSonicHub1! We've already got #4993 open against the PDF script though, so once that's merged would it be possible for you to rebase this PR to merge in the changes at all?

No problem! Just make sure to reply here once that happens so I can make the necessary changes.

**Comment by sbrl** [comment]
#4993 is merged now, @SuperSonicHub1 :slightly_smiling_face:

**Comment by SuperSonicHub1** [comment]
Should have a revamped patch by tomorrow!

**Comment by SuperSonicHub1** [comment]
@sbrl Sorry I took so long, but I've finally resolved our commits.

**Review by sbrl — COMMENTED** [review]
Thanks, @SuperSonicHub1!

I notice though that when I run your version of the script that there are 2138 pages in the `windows` platform, and none in any of the other platforms. I seem to remember this wasn't the case when I ran the script when I implemented the "Generated on {{datetime}}" feature.

Could you take a look into that at all please?

**Comment by SuperSonicHub1** [comment]
@sbrl Just realized that I made an indentation error! Happens in Python. Pushing a patch now.

**Comment by SuperSonicHub1** [comment]
@sbrl Don't know if you're aware already, but I've fixed the issue you referred to.

**Comment by SuperSonicHub1** [comment]
@sbrl I hope I'm not annoying you right now, but I really want to get this pull request over with.

**Comment by waldyrious** [comment]
@SuperSonicHub1 just FYI, you can reach out in the [Gitter chat](https://gitter.im/tldr-pages/tldr) as an additional venue for feedback/discussion. @sbrl has been around in the chat in the past few days, so he's not completely offline, but he's probably busy with other stuff and hasn't had the chance to respond here yet. Apologies for the delay, but don't worry, the PR will be merged as soon as he (or another maintainer with the expertise to review the code) is able to take another look. Thanks for the patience! 😄

**Comment by SuperSonicHub1** [comment]
@waldyrious Oh, no problem!

**Review by owenvoke — APPROVED** [review]

**Review by sbrl — APPROVED** [review]
@waldyrious: *she :-)

@SuperSonicHub: So sorry that I haven't gotten around to merging this! I've been having a much needed break over Christmas (the last one I took was August), so PRs kinda slipped my kind lol

This looks great - merging now :-)

**Comment by sbrl** [comment]
Merged!

For future reference, this is one of the extremely rare moments that a merge commit was needed. This branch had conflicts with the master branch, which I had to resolve and then merge manually.

**Comment by SuperSonicHub1** [comment]
Great! Thanks for all the help!

**Comment by waldyrious** [comment]
> @waldyrious: *she :-)

Oh wow! Can't believe I never realized that all this time :)

> For future reference, this is one of the extremely rare moments that a merge commit was needed. This branch had conflicts with the master branch, which I had to resolve and then merge manually.

Um, not a big deal, but just FYI, I'm pretty sure that the branch could be rebased on top of the latest master (with the conflicts merged during that process), and force-pushed. That would allow a fast-forward merge without a merge commit.

**Comment by sbrl** [comment]
Oh oops! I'll try that next time.

**Pull request merged**
