### PR TITLE
age: replace `unencrypted` with `decrypted`

### PR DESCRIPTION
**Pull request by CleanMachine1**
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

Really small PR.
Feel free to close if it is incorrect

### CODE REVIEW

**Comment by marchersimon** [comment]
I'm not sure if `unencrypted` and `decrypted` are exactly the same. `decrypted` kind of implies that it has been encrypted before.

**Comment by bl-ue** [comment]
@CleanMachine1 I'm not sure about this one, because `decrypted` implies "it used to be encrypted", while "unencrypted" means that it has never been encrypted.  While both technically indicate the same end state, they imply different meaning.  I think `unencrypted` is better.

**Comment by CleanMachine1** [comment]
Yes, thats precisely why I mentioned, "feel free to close if incorrect"

**Comment by CleanMachine1** [comment]
Closing since I also agree it makes not a lot of sense

**Pull request closed without merging**
