### PR TITLE
Using new travis token

### PR DESCRIPTION
**Pull request by agnivade**
Used my token here.

Travis seems to be down. Will test it once it's up.

### CODE REVIEW

**Comment by agnivade** [comment]
xref #1878

**Comment by waldyrious** [comment]
Are you planning to remove the other token?

Also, don't forget the documentation :) from https://github.com/tldr-pages/tldr/issues/1878#issuecomment-356573527:

> we definitely should add a comment to that file noting the token on .travis.yml, and the comment on `.travis.yml` should mention the `upload_assets()` function on this file.

**Comment by agnivade** [comment]
First I wanted to verify that this thing works. :) Will update the documentation once its working.

Yes, there can only be one token at a time.

**Comment by waldyrious** [comment]
Cool. Btw, looks like Travis is working well again, so I've restarted the build. Let's wait and see!

**Comment by agnivade** [comment]
You would only be able to test it once you merge with master. Yes, now it works !

**Comment by waldyrious** [comment]
Right, forgot about that detail :P

**Pull request merged**
