### PR TITLE
odps-inst: add page

### PR DESCRIPTION
**Pull request by onesuper**
similar to https://github.com/tldr-pages/tldr/pull/881

### CODE REVIEW

**Comment by waldyrious** [comment]
Is "logview" a technical term? Or could it be replaced by "log output" or something like that? Also, when is it printed -- after the instance is terminated, or while it's running?

**Comment by onesuper** [comment]
@waldyrious 
Em...logview, which is a url link pointing to the log output (webpage) of an instance, is an term in odps.
I will double-quote it.

**Comment by waldyrious** [comment]
It's ok not to mention it, but if the printing happened after the termination (please confirm), that would make sense as to what the wait command does... without that information, all we know is that it waits for the termination... and then what? It would sound like a no-op.

**Comment by onesuper** [comment]
@waldyrious 
The 'wait' command will block the user input. An url to 'logview' will print. And some progress  information will be printed in the console, like:

```
> wait instance123456;
> logview: http://hostname:port/...
> 10%
> 20%
...
```

The user will retain the control of console until the instance is terminated.

**Comment by waldyrious** [comment]
How about this, then?

`Wait on the termination of an instance, printing log and progress information until then:`

**Comment by onesuper** [comment]
I have changed the description. Thanks!

**Comment by waldyrious** [comment]
LGTM

**Comment by felixonmars** [comment]
:+1: Thanks

**Pull request merged**
