### PR TITLE
added kill detached screen command

### PR DESCRIPTION
**Pull request by snollygolly**
I use this command a lot, and would love to have it listed.  Really useful for killing hung sessions.

### CODE REVIEW

**Comment by waldyrious** [comment]
:+1:

**Comment by felixonmars** [comment]
:shipit:

**Comment by igorshubovych** [comment]
Sorry guys. Press Merge too early according to our new rules. Just unintentionally pressed big button on my phone.

**Comment by waldyrious** [comment]
It's ok @igorshubovych , I think we should open an exception on the 2-day rule while the peak in contributions subsists, in order to prevent a backlog to form.

**Pull request merged**
