### PR TITLE
chore: fix use doublequotes and $(..) notation in deploy script

### PR DESCRIPTION
**Pull request by mstruebing**
see: https://github.com/koalaman/shellcheck/wiki/SC2006 and https://github.com/koalaman/shellcheck/wiki/SC2086

### CODE REVIEW

**Comment by agnivade** [comment]
Did you actually run `shellcheck` and these were the only errors ? If not, we should fix any others too.

**Comment by mstruebing** [comment]
There was only one left: `$encrypted_973441be79af_key` is used but not defined but I assume this comes somewhere magically, maybe from travis.

**Comment by agnivade** [comment]
Yes.

**Comment by waldyrious** [comment]
Thanks @mstruebing. Maintenance cleanup like this is often overlooked and considered somewhat unglamorous, but truly pays off in the long run.

**Comment by sbrl** [comment]
Great, thanks! I wonder if it passes shellcheck now?

**Comment by pxgamer** [comment]
@sbrl, looks like it passes except for the Travis variable that @mstruebing mentioned (which is fine). 👍
```
Line 23:
  openssl aes-256-cbc -K "$encrypted_973441be79af_key" -iv "$encrypted_973441be79af_iv" -in ./scripts/id_ed25519_tldr_asset_upload.enc -out id_ed25519 -d
                          ^-- SC2154: encrypted_973441be79af_key is referenced but not assigned.
>>                                                          ^-- SC2154: encrypted_973441be79af_iv is referenced but not assigned.
```

**Comment by sbrl** [comment]
Ah, awesome! I should have read it more closely :P

**Pull request merged**
