### PR TITLE
quotacheck: add page

### PR DESCRIPTION
**Pull request by pearcem0**

### CODE REVIEW

**Comment by waldyrious** [comment]
This page can't be in common as-is:

```
$ quotacheck --all
quotacheck: illegal option -- -
usage:	quotacheck -a [-guv]
	quotacheck [-guv] filesys ...
```

**Comment by pearcem0** [comment]
I see, thanks for that. Sorry for the inconvenience.

**Comment by waldyrious** [comment]
Not a problem @pearcem0 :) thank *you* for taking the time to contribute.

**Comment by pearcem0** [comment]
Closing this and adding a new pr in the correct place.

**Comment by waldyrious** [comment]
For future reference, the new PR is #1002.

**Pull request closed without merging**
