### PR TITLE
sha*sum: add link

### PR DESCRIPTION
**Pull request by marchersimon**
For #5510
I already moved the pages to `pages.sh`, I hope this won't conflict with #5664.

### CODE REVIEW

**Comment by marchersimon** [comment]
I didn't update my master branch before making the changes. How can I resolve this?

**Comment by marchersimon** [comment]
I deleted the branch and made a new one with the same name. Can I somehow reopen this PR or is this not possible?

**Comment by bl-ue** [comment]
>I didn't update my master branch before making the changes. How can I resolve this?

Next time, just run:
```bash
git checkout master         # switch to master in case you're not already
git fetch upstream master   # pull latest changes down to a temporary hidden branch called FETCH_HEAD
git rebase upstream/master  # update your local master with the main remote master (uses pulled content in FETCH_HEAD)
git checkout shasum-link    # switch back to your feature branch
git rebase master           # rebase the changes from your local master onto your current branch.  Note: rebase is important here, it adds all of the commits from the specified branch into your branch BEFORE any commits that you made in this branch
git puch --force            # push, overwriting existing state on remote branch
```

>I deleted the branch and made a new one with the same name. Can I somehow reopen this PR or is this not possible?

I don't think it's possible.  Just open a new PR.

**Comment by bl-ue** [comment]
>I already moved the pages to pages.sh, I hope this won't conflict with #5664.

I'm not sure if it will or not, I actually want to say that it _will_ but I really don't know.

Instead, just keep them in `pages.hbs` and modify and commit them there, and then when your PR gets merged I'll update that PR with the new changes from `master` 👍🏻

**Comment by marchersimon** [comment]
Okay, thanks

**Pull request closed without merging**
