### PR TITLE
Avoid the responsibility of global settings

### PR DESCRIPTION
**Pull request by kotp**
We should only ignore files that may concern this project, not folks editors and operating systems.  Added reminder text in the `.gitignore` file itself.

### CODE REVIEW

**Comment by kotp** [comment]
`.gem` may need to be in there, I am unsure.

**Comment by rprieto** [comment]
While I agree with the theory, I find that it doesn't hurt much, and prevents people who haven't setup their `~/.gitignore` properly from checking-in the files we know are likely to exist.

Happy to get more feedback from other contributors.

**Comment by kotp** [comment]
Then it should be complete.  If you are going to ignore certain subsets of, let's say, the vim swap file patterns, we should cover all of them.  Not just one of them.  Or the emacs swap file patterns as well, and we may as well do RubyMine and Sublime as well.  It is a murky place to be.

Better yet, perhaps, ignore the .gitignore file itself, in the project and let uses use it or not, without it being something that gets tracked.

If it is decided to be complete, github has some good gitignore files in its repository of gitignore files.

**Comment by rprieto** [comment]
> ignore the .gitignore file itself

How would that work? I don't want to fall into arguing over fake extreme cases. Of course adding every editor in the world is not practical, nor is the intention. But having `.DS_Store` doesn't hurt much, since we have a lot of contributors on OSX, and they might have forgotten to ignore these files.

That being said, again I agree with the initial intention, so if the other contributors agree I'm happy to merge this.

**Comment by rubenvereecken** [comment]
I've got mixed feelings about this. I've taken the comfortable relaxed route with all too many repositories, adding some sane default ignores to a project's .gitignore just because it's practical. Still, I'm happy to revise that suboptimal habit and pick up some git best practice.

The concern lies more with one-time contributors (which are as in most repositories the main part) who are often even very new to git but decide to chip in because of the low entry cost of tldr. They'd have to add files selectively or even set up the local ignore, the latter is certainly too much of a hassle for most.

So, let's go with it for now because I like doing things 'right' but I suggest we revert back if we get too big a portion of commits containing unneeded files.

**Comment by rprieto** [comment]
> So, let's go with it for now because I like doing things 'right' but I suggest we revert back if we get too big a portion of commits containing unneeded files.

Agreed :+1: Let's just keep `/.gem` in there I think, given it will be created by `bundle install`.

**Comment by kotp** [comment]
Having some instructional information in the .gitignore itself is probably the most practical route.  It reminds that project things go in there, not tooling preferences.  So they will pause and consider the change.

`git update-index --assume-unchanged .gitconfig` is the closest thing to having local changes and untracking them.  Not a great fit for this repository, as it is additional work and buys little advantage, and is IMO the wrong thing to do here.

If this is pretty much a perfect "first time committer" type repository, having the explanatory text in the `.gitignore` with a reference to further information is not a bad thing.  It is the maintainers giving back to their contributors long term knowledge.

**Comment by rubenvereecken** [comment]
I came across `git update-index --assume-unchanged` before, but why untrack the gitconfig instead of the changed files themselves? I'm asking because I feel like this is a learning opportunity.

It's looking good for me now, I'll wait until @rprieto has found a moment to check in.

**Comment by kotp** [comment]
@rubenvereecken If I untrack the .gitignore file itself because I add some custom entries there, I can ignore only things that I may use, perhaps a custom test reporter.  For the purpose illustrated in this discussion, it is definitely not worth the hassle.

But then, individually, I have to remember to stash my changes, undo that change, and then do it again and then unstash my changes, and make the appropriate changes. 

In some of my projects, I have a custom setting, and could use this, but I prefer to ignore the _real_ configuration file, provide a config.ext.sample file that is under version control as a template, with instructions to copy that file to the actual file name.  Less work, and helps to ensure confidential information doesn't accidentally get included, without the additional overhead of the `assume-unchanged` and `no-assume-unchanged` flags.

For the context of this project, perhaps ignoring the changes generated by the git commit hook temporarily while making some exploratory changes might be a use of this flag.  Restoring it when it is appropriate for those changes to be committed.

**Comment by rprieto** [comment]
Thanks for updating with `.gem` back in, and in general for the contribution!

**Pull request merged**
