### PR TITLE
MAINTAINERS.md: update @pxgamer status

### LINKED ISSUE #2989: Add @pxgamer as an organisation owner
Hi, @pxgamer! You've been an active tldr-pages org member for over 6 months.
Thanks for sticking around this far and helping out!
According to [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
Before performing such role transitions, make sure to review the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

### PR DESCRIPTION
**Pull request by pxgamer**
Closes #2989

### CODE REVIEW

**Comment by pxgamer** [comment]
See https://github.com/tldr-pages/tldr/issues/2989#issuecomment-490796319 for some more details on the wording.

**Comment by waldyrious** [comment]
Let's wait for #3006 to be merged before merging this one, as discussed in #2989.

**Comment by sbrl** [comment]
Ah, I see! Nevermind my comment in the other PR then - I see this PR will add @pxgamer back for historical reference :+1:

**Comment by pxgamer** [comment]
@waldyrious, I was just working on rebasing master into my branch 😂

Thanks for the merge!

**Comment by waldyrious** [comment]
Sorry for wasting your time @pxgamer 😅. I wanted to try the web-based conflict resolution interface, which I hadn't tried before.

**Comment by pxgamer** [comment]
No waste of time at all. 👍

**Pull request merged**
