### PR TITLE
nginx:add stop,quit,reopen,reload

### PR DESCRIPTION
**Pull request by WALL-E**
Send a signal to the Nginx master process, stop,quit,reopen,reload.

### CODE REVIEW

**Comment by waldyrious** [comment]
Do you think you could shorten the page to have 5-6 examples?

**Comment by notpeter** [comment]
Is sending signals to nginx using `nginx -s` a common use? Don't most people just send signals directly or use init scripts?

**Comment by ostera** [comment]
@notpeter, @waldyrious, as a heavy nginx user I've never had the need to directly use -s for anything other than the very very sporadic testing of a configuration reload.

I've merged and left that sample since is the most useful, the rest can be achieved by using the service scripts. Changes here: https://github.com/tldr-pages/tldr/commit/b7bca90124e8a3938452659fffa8c75fbe7b38b7

**Comment by notpeter** [comment]
Looks great!

**Pull request merged**
