### PR TITLE
youtube-dl: add download playlist example

### PR DESCRIPTION
**Pull request by tminei**
Adding download playlist as mp3.

### CODE REVIEW

**Comment by tminei** [comment]
> There are already 8 examples, so one has to go. Which one is less informative than yours?
Hello, i think this example less useful, because there is already an example of quality choice

Download the best quality audio and video and merge them:
```
youtube-dl -f bestvideo+bestaudio {{url}}
```

**Comment by zdroid** [comment]
I'd rather remove list formats or list subtitles examples. Those are not really needed for most use cases.

**Comment by tminei** [comment]
> 
> 
> I think they used to be useful, but with the other great examples on this page I think the list formats might be ok to be removed.

Yeah, I guess so. I think you need to add the --all key to tldr to see the extended version of the manual with all the examples, and without that key to show 8 main examples, because 8 examples are quite small, and watching man is not always convenient, because of the curved style of its pages.

**Comment by tminei** [comment]
I prefer to listen to YouTube music from the playlist, but I don't always have stable Internet and I would like to save the playlist to my device in mp3 format. I think that most Internet users don't have a high-speed connection, and for many of them my manual will be useful.

**Comment by zdroid** [comment]
@sbrl So, which one to remove, list subtitles or list formats? I'd say list subtitles.

**Comment by tminei** [comment]
> which one to remove, list subtitles or list formats? I'd say list subtitles.

I think formats are more important than subtitles.

**Comment by zdroid** [comment]
I applied those changes @tminei. @sbrl you may wanna review this now

**Pull request merged**
