### PR TITLE
repo-add: add barebones example

### PR DESCRIPTION
**Pull request by Managor**
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Review by vitorhcl — COMMENTED** [review]
It looks like the package argument is required, isn't it? It's enclosed within angled brackets in the man page
> repo-add [options] <path-to-db> <package> [<package> ...]

**Comment by Managor** [comment]
> It looks like the package argument is required, isn't it? It's enclosed within angled brackets in the man page

Whatever the man page says, practical experience overrides it. I made an empty repo just yesterday.

**Review by vitorhcl — APPROVED** [review]

**Comment by kbdharun** [comment]
> It looks like the package argument is required, isn't it? It's enclosed within angled brackets in the man page
> 
> > repo-add [options] <path-to-db> <package> [<package> ...]

This entry is located in the synopsis so it is generally a summary of the available/required options and arguments and not the actual representation of all command examples. They are generally formatted this way.

image

**Pull request merged**
