### PR TITLE
k6: add js compatibility mode and response bodies

### PR DESCRIPTION
**Pull request by simskij**
- Add commands for
    - discarding response bodies, and
    - running scripts in the base javascript compatibility mode.
- Update the tool description.

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by navarroaxel** [comment]
Oh @simskij, looks like you should rebase with `master` or `reset --hard` some commits and `push --force` a new commit in the same branch.

**Comment by simskij** [comment]
@navarroaxel a rebase seems to have solved it 👍

**Comment by simskij** [comment]
Fixed, thanks for pointing that out! 🙏

**Review by sbrl — APPROVED** [review]
Thanks, @simskij! :D

**Review by navarroaxel — APPROVED** [review]

**Pull request merged**
