### PR TITLE
logcat: add page

### PR DESCRIPTION
**Pull request by Rudloff**
- [x] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

This is an Android-only tool, so I assumed `linux` was the correct directory?

### CODE REVIEW

**Comment by sbrl** [comment]
Do you mean to say that it is a command only available on Linux for interacting with Android devices, or that it only runs on Android devices? If it's the latter, then we *may* need a new platform folder.

**Comment by Rudloff** [comment]
This command is only available on Android devices.
(It can be called from a computer connected to the device with `adb logcat` though.)

**Comment by sbrl** [comment]
Ah, I see @Rudloff. In that case, I think we might need to tweak this a bit. I'd suggest that it is indeed on Linux that it's used most often. In that case, we should treat this as a sub-page of `adb` - just like `git merge` is a sub-page of git. This would mean that we'd need to do the following:

 - Rename the page to `adb-logcat.md`
 - Prefix all instances of `logcat` with `adb ` in the page itself

If the opposite is true (i.e. it's used on Android directly more often), then we may need to create a new platform folder.

What do you think?

**Comment by Rudloff** [comment]
Hum, I guess it is more often used with adb.

**Comment by agnivade** [comment]
Yeah, let's do what @sbrl said.

**Pull request merged**
