### PR TITLE
solo: add page

### PR DESCRIPTION
**Pull request by sbrl**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by pxgamer** [comment]
Hi @sbrl, do you have a Solo key? 😄

**Comment by sbrl** [comment]
@pxgamer I do! However did you guess :P

It arrived a few days ago after I backed the Kickstarter last year. It's apparently the first open-source hardware security key - and it's pretty cool :D

**Comment by pxgamer** [comment]
It looks really neat, was having a look at their website and wondered how they are. 👍

**Comment by sbrl** [comment]
Yeah!

> and wondered how they are

They are what :question:  If you're after the source code, it's [here](https://github.com/solokeys/solo). I believe they've got hardware designs in another repo in their org too.

**Comment by pxgamer** [comment]
Sorry, I didn't make myself very clear. I meant like, if they are any good. :+1:

**Comment by sbrl** [comment]
Ah, I see @pxgamer! I haven't had my pair very long, but they seem great so far. Much easier than typing in a 6 digit code for 2FA all the time.

Support is patchy amongst websites at the moment, but it seems to be picking up steam quickly.

Example issues I've run into include having to spoof my user agent string on GitHub while I added my keys (it's fine without after this step).

**Comment by pxgamer** [comment]
Thanks for the reply :+1: Will have to take a look.

**Pull request merged**
