### PR TITLE
git-remote: mention how to add a new URL

### PR DESCRIPTION
**Pull request by waldyrious**
- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by sbrl** [comment]
Great addition, @waldyrious! If you add a new url whilst keeping the existing one, does it pick one at random or something?

**Comment by pxgamer** [comment]
@sbrl, I'm pretty sure it allows you to push to multiple repositories at once. 👍

**Comment by waldyrious** [comment]
> If you add a new url whilst keeping the existing one, does it pick one at random or something?

To be honest I don't recall exactly what algorithm git uses to pick the remote URL to act on. It could prefer git-protocol URLs to https ones, or use the oldest one first, etc. I had this change lying around but it's been a while since I actually used this feature, so I'm not sure. Maybe if I figure it out I'll add a comment here for future reference :)

**Comment by sbrl** [comment]
Ah, that's very interesting! I didn't know that git could do that.

**Pull request merged**
