### PR TITLE
rsync: add French translation

### PR DESCRIPTION
**Pull request by FloLangenfeld**
- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

### CODE REVIEW

**Comment by antoine-amara** [comment]
It is a good translation, I made some suggestions to try to improve it.

**Comment by FloLangenfeld** [comment]
Looks better, indeed. Thanks @antoine-amara

**Comment by zdroid** [comment]
@FloLangenfeld Here @antoine-amara only suggested those changes, but you have to commit them yourself. I applied all of them this time. Thanks for the contribution!

**Comment by FloLangenfeld** [comment]
@zdroid Thanks (new githuber spotted...)

**Pull request merged**
