### PR TITLE
Curl-Consuming-REST-APIs Page Added (formatting corrected)

### PR DESCRIPTION
**Pull request by a-r-1**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by seenukarthi** [comment]
Isn't curl covered by tldr/pages/common/curl.md?

**Comment by a-r-1** [comment]
> Isn't curl covered by tldr/pages/common/curl.md?

Hi, @seenukarthi , the curl.md page doesn't cover the commands and syntax for consuming REST API's, which is one of, if not _the_ most popular use for Curl.

Thanks.

**Review by sbrl — COMMENTED** [review]
Hey there, @a-r-1! Thanks for the contribution.

Unfortunately, we already have a page for `curl`, as has already been mentioned here.

However, I can see where you're coming from. The examples you detail here seem quite specific to a specific REST API (although I can't tell which one).

While examples like these are valuable, they might be a better fit for a personal cheat sheet and not tldr pages, as they are specific to a single or a collection of REST APIs. For example, not all REST APIs have a `userId` GET parameter, or use an `Authorization` header. Hence the existing `curl` page tries to be a neutral as possible while describing useful functionality.

**Comment by a-r-1** [comment]
Hi, yeah I can see how the page I submitted is confusing - the topic seemed a bit esoteric to write a page about at the time.

I'll close this PR, and I'll maybe have a go at another topic.... Thanks for the feedback!

**Comment by sbrl** [comment]
Thanks for understanding, @a-r-1. We hope to see you back in the future :heart:

**Pull request closed without merging**
