### PR TITLE
ksvgtopng5: add more information link

### PR DESCRIPTION
**Pull request by navarroaxel**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #5510

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
I'm not sure what others would say about linking to a `.cpp` file, but I, for one, think it's quite a good source of extra information for the user! :)

**Comment by marchersimon** [comment]
How about [http://manpages.org/ksvgtopng](http://manpages.org/ksvgtopng)? (Unfortunately there's no `https` version)

**Comment by bl-ue** [comment]
That page doesn't seem to give more information than this tldr page does though, besides just feeling a bit odd.

**Comment by marchersimon** [comment]
Yeah, that's right. In that case, I'd actually prefer [https://invent.kde.org/plasma/kde-cli-tools/-/tree/master/ksvgtopng](https://invent.kde.org/plasma/kde-cli-tools/-/tree/master/ksvgtopng), since it gives an overview of the project, instead of jumping directly into the source code.

**Review by sbrl — APPROVED** [review]
Hrm, a difficult one.

<http://manpages.org/ksvgtopng> suggests that Debian has a man page for it, but when you check <https://manpages.debian.org/> it claims it can't find one.

I think linking to the .cpp file is the best trade-off here. Linking to the directory it is in adds an extra click for the user, because said directory doesn't contain a README.

**Review by marchersimon — APPROVED** [review]

**Pull request merged**
