### PR TITLE
git-release: update

### PR DESCRIPTION
**Pull request by CleanMachine1**
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

### CODE REVIEW

**Comment by bl-ue** [comment]
I'd also word the first line of the page description thus:
```
> Create a Git tag for a release.
```

**Review by SethFalco — APPROVED** [review]
I think this is better! \\(^-^)/

**Review by bl-ue — APPROVED** [review]
So do I — thank you @CleanMachine1! :)

**Comment by CleanMachine1** [comment]
I can't see how any one else is going to add anything to this. The entire PR was long to fix a suggestion I didn't make.

**Pull request merged**
